### ISSUE TITLE
drop supporting Node.js 4

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#10052]
Node.js 4 became more legacy and outdated. It's in maintenance mode since April 2017, which will end in April 2018.

It will give our codebase and us a breath of fresh air. There are a bunch of awesome stuff starting Node.js 6, which are missing in Node.js 4  : 
+ default function parameters
+ rest parameters
+ spread operator
+ destructuring
+ no need for `'use strict'` to use let, const.
+ ...

since this will be a breaking change, when can we make this change?

**Comment by not-an-aardvark** [comment]
I think there was general consensus at the [last TSC meeting](https://github.com/eslint/tsc-meetings/blob/db3c0010144ba403a95daf3611af24ee271b3c78/notes/2018/2018-03-01.md#planning-for-500-release) that we should drop support for Node 4 in our next major release. We will probably start doing prereleases for it sometime in the next few weeks.

**Comment by realityking** [comment]
You might want to consider requiring Node.js 6.5. It has a newer V8 version and a better coverage of ES2015 features, mostly around edge cases.

**Comment by not-an-aardvark** [comment]
I'll move [this TSC agenda item](https://github.com/eslint/tsc-meetings/issues/81#issuecomment-377360664) to this issue.

**TSC Summary**: We need to decide which versions of Node we will support in the next major release.
**TSC Questions**:

* Should we explicitly drop support for Node 7?
* Should we support anything above a particular version of Node 6 (e.g. >=6.9.4), or any version of Node 6 at all (i.e. >=6.0.0)?

**Comment by alberto** [comment]
Do we plan to enforce this somehow? I remember when we initially released eslint 3.0 it didn't include any node4-only feature in the critical path and caused some confusion when we added it later on, so I think it would be better if we did it right away

**Comment by not-an-aardvark** [comment]
According to the [npm docs](https://docs.npmjs.com/files/package.json#engines), if we update the `engines` field in `package.json`, npm will produce a warning if the user has an outdated version of Node.

If we want to do more than that, I can think of a few options:

* Add a runtime check in `bin/eslint.js` to check the Node version and print a warning if the version is too low
* Add some Node 6 syntax on the critical path somewhere

The former could be nice for UI, but it would require us to keep `bin/eslint.js` parseable indefinitely on old versions of Node. I can definitely think of some places on the critical path where Node 6 syntax would be nice, so we could do that anyway.

**Comment by platinumazure** [comment]
@alberto Agreed. I think we could potentially leverage a package like [check-node-version](https://github.com/parshap/check-node-version) in order to avoid having to really maintain that logic ourselves.

**Comment by not-an-aardvark** [comment]
I'm not strongly opposed to it, but I'm a bit averse to the "runtime check" option because it would hurt performance, and this can be detected statically (the user should have already seen a warning message from npm).

It seems like there are two potential issues here:

* The user might be confused about why ESLint is suddenly broken after upgrading to ESLint 5.
* The user might upgrade to ESLint 5.0.0 and have it work initially when using Node 4, but then have it break when (e.g.) ESLint 5.0.1 is released and uses Node 6 syntax somewhere.

It seems like the npm `engines` check already handles the first problem. If I'm understanding correctly, the issue with the ESLint 3.0 release was along the lines of the second problem. It seems like we could avoid this by making sure we use destructuring right from the start.

**Comment by not-an-aardvark** [comment]
https://github.com/eslint/eslint/issues/10052#issuecomment-377381218 has a :+1: from a majority of TSC members, so I'm going to update #10074 to change the supported versions to `^6.14.0`, `^8.11.0`, and `>=9.10.0`, and remove this issue from the TSC agenda.

**Comment by platinumazure** [comment]
Personally I think this should wait a bit longer for merge, since neither @ilyavolodin nor @nzakas have seen this discussion yet and they have been key drivers of our past policy in this area. The last thing we want to do is merge with a later :-1: from them. (Of course, the rest of the TSC should get a chance to see this as well.)

**Comment by not-an-aardvark** [comment]
Ok, I'll re-add it to the TSC agenda and mark the corresponding PR as `evaluating`.

**Comment by realityking** [comment]
While eslint probably isn‘t used too often on AWS lambda, it might be nice to continue to support it. The newest Node.js version supported by AWS Lambda is 6.10.3.

**Comment by not-an-aardvark** [comment]
@realityking Thanks for that info. My gut reaction is that AWS Lambda should update to a version of Node without known security vulnerabilities, but I realize this isn't something that users have control over. How often do they generally update?

**Comment by realityking** [comment]
@not-an-aardvark I guess the best way to sum it up is “never“. For Node 4 they’re still on 4.3.2.

I’m hoping for Node 8 to be added soon but who knows what Amazon’s plans are.

**Comment by not-an-aardvark** [comment]
For what it's worth, Node 8.10 was [added a few days ago](https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/)

**Comment by not-an-aardvark** [comment]
In [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/4604d91e9e0c546b9bf336ed24dc9a7998a17010/notes/2018/2018-04-12.md#drop-supporting-nodejs-4), the TSC decided that we will support Node `^6.14.0 || ^8.10.0 || >=9.10.0` in ESLint 5.0. (We decided to support Node 8.10 rather than starting support at Node 8.11 so that ESLint can be used on AWS Lambda.)
