### ISSUE TITLE
Replace babel-code-frame with @babel/code-frame

### ISSUE THREAD

**Issue by hulkish** [eslint/eslint#10080]
Please replace `babel-code-frame` with `@babel/code-frame` & enable `highlightCode` option.

**Comment by not-an-aardvark** [comment]
Moving the discussion from https://github.com/eslint/eslint/pull/10079 to here:

The `highlightCode` option was intentionally disabled based on https://github.com/eslint/eslint/pull/7437#pullrequestreview-5370538 for performance reasons. (This could have a performance impact when doing a linting run with a large number of errors, because the formatter would have to do syntax highlighting on a large number of different files.) Unless the performance has improved since the `codeframe` formatter was added, I personally don't think it's worth enabling this option.

I don't object to replacing `babel-code-frame` with `@babel/code-frame`, but I'm hesitant because it appears to be in beta (the current version number is `^7.0.0-beta.40`). Would it be better to wait until it's stable instead?

**Comment by hulkish** [comment]
@not-an-aardvark Fair enough, put this on backburner until stable 7.0.0 release?

**Comment by not-an-aardvark** [comment]
Ok, I'll close this for now. Feel free to open a new PR when `@babel/code-frame` is stable. (It won't be necessary to create an issue for that, since it wouldn't have any user-facing effects.)
