### ISSUE TITLE
[Feature request] Lint only certain lines in a file

### ISSUE THREAD

**Issue by tomkel** [eslint/eslint#10116]
My motivation for this feature request is that the same that [precise-commits](https://github.com/nrwl/precise-commits) addresses. I want to be able to `--fix` only the lines that I've changed in a source file. `precise-commits` lays out some of the drawbacks of applying `--fix` on a particularly large file:

>-  Increases the complexity and review time burden of PRs on senior team members.
>-  Potentially increases the amount of time it takes to complete a PR in the first place.
>-  Can block concurrent work on the same codebase and/or result in nasty merge conflicts with outstanding feature branches.

> If I make a change on line 10 of a 4000 line file, I shouldn't be forced to reformat all 4000s lines (thus making me the last git user to update all of them) as part of my PR.
> I should just need to reformat line 10.

This may already be possible by splicing changes and passing them to eslint's `--stdin`. Either way, consider this request a conversation starter.

**Comment by platinumazure** [comment]
I'm not sure this is really necessary, because this problem is eliminated with a small workflow change: Don't stage a file for commit until `eslint --fix` passes with no autofixing.

Similarly, if you have files that have a bunch of formatting problems (and so wouldn't pass linting), you could use a tool like `eslint-nibble` to enable only some rules at a time.

So basically, I can't imagine a scenario where it would be required to tolerate a non-linting file, until one line is changed, then suddenly the whole file must pass linting. Seems there should be other ways around this.

Am I missing something?

**Comment by not-an-aardvark** [comment]
I've had a related use case in the past where I wanted to gradually enable ESLint on a large codebase, but running `eslint --fix` on the whole codebase (or even fixing problems one rule at a time) was undesirable because it would mess up the git history and cause a lot of merge conflicts. In that case, it would have been useful to have a general heuristic of "Only report problems that weren't present before this change, or problems that appear on a line that has been changed." As a result of following this heuristic, the codebase would gradually become more consistent as lines are changed, without interfering with git history.

I'm not sure what the best way to enforce that heuristic is (whether it's something that should be handled in ESLint core or elsewhere), but hopefully that explains a potential use case.

**Comment by tomkel** [comment]
Yes, my use case is similar to @not-an-aardvark, where trying to insert eslint into the dev workflow produces hundreds of errors and warnings. Lit up like a christmas tree. For our organization it is better to just fix as we go along to preserve git history and lighten PR load rather than fix everything at once. Alas, manually fixing every lint error is a pain, so I was hoping to make my life easier by only `--fix`ing parts of a file that I am working on.

**Comment by betaorbust** [comment]
We would also like this feature, as we'd like to enforce folks fixing/modifying their own changes while not making them fix the entire file. 
This use case for us is in a large team, with incoming new lint rules, and large files that the engineer might not have all the context on. We don't want to block their PRs or pushes because everything isn't perfect, but we'd like to ensure that new/modified code is within our current styles.

**Comment by ilyavolodin** [comment]
It feels like this should be solvable either through another wrapper tool, and usage of Node API, passing only modified code into stdin or creating a simple processor that would remove all unchanged code before passing it into ESLint. Processor is probably the least complex path.

**Comment by kaicataldo** [comment]
@ilyavolodin I agree with you, though I would be concerned about a number of rules possible breaking code then, given that it doesn't have any more context than the snippet provided.
