### ISSUE TITLE
 Update: allow custom styleguide when init

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#10132]
## Question
For many organizations, they use their own shareable eslint config (eg:`eslint-config-ali` for us). But `eslint --init` seems not very helpful for the users -- it only support `Google`, `Airbnb` and `Standard` style guide. It's a pretty large burden on users to add a config(and its peer dependencies).

## Proposed solution
allow users to type a shareable config.
```bash
$ eslint --init

? Which style guide do you want to follow?
  Google
  Airbnb
  Standard
❯ type a shareable config

$ eslint-config-ali

? What format do you want your config file to be in? JavaScript

Checking peerDependencies of eslint-config-ali@latest
Installing eslint-config-ali@latest, eslint-plugin-xxx...
```

**Comment by not-an-aardvark** [comment]
Personally, I don't think we should add this, for a few reasons:

* In general, it's unreliable to automatically install the `peerDependencies` of an arbitrary package. (The behavior was intentionally removed from npm because it caused a lot of problems, such as https://github.com/npm/npm/issues/5080.)
* I don't think this is the intended use case for `eslint --init`. It's usually intended for users who aren't sure how to configure ESLint, but if someone already knows how to use a given shareable config then they can follow the instructions in the readme for that config.

I agree that the current UX for installing shareable configs is not ideal due to the `peerDependency` requirement, but I think we should evaluate other ways to address that problem instead.

**Comment by Aladdin-ADD** [comment]
agreed!  I didn't realize `eslint --init` is for new users. but we could reevaluate it if someday we move the cli to another repo (like`eslint-cli`).
Thanks for the suggestions anyway! 🤩@platinumazure
