### ISSUE TITLE
[meta] "To use eslint-plugin-rulesdir, you must load it beforehand and set the `RULES_DIR` property on the module to a string." error in VSCode

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#10229]
When I work on ESLint repository, VSCode's ESLint seems to throw "To use eslint-plugin-rulesdir, you must load it beforehand and set the `RULES_DIR` property on the module to a string."

![image](https://user-images.githubusercontent.com/1937871/38830244-9d5714c0-41f6-11e8-9e98-85fac575de05.png)

Repro step:

1. delete `node_modules`
2. `npm i`
3. `npm i -f --no-save eslint`
4. `code .` then open eslint's log in `output` tab.

:thinking: It's very weird. That `loadFromDisk` function in the stacktrace has read `.eslintrc.js` that set `RULES_DIR` property....

On Windows 7, VSCode 1.22.2, vscode-eslint 1.4.8

**Comment by not-an-aardvark** [comment]
Is it possible that there are two different versions of `eslint-plugin-rulesdir` installed? If `node_modules/eslint-plugin-rulesdir` and `node_modules/eslint/node_modules/eslint-plugin-rulesdir` both exist, then this error would probably occur because `.eslintrc.js` would set a property on the wrong module.

**Comment by mysticatea** [comment]
```
~\dev\eslint [issue9990]> npm ls eslint-plugin-rulesdir
eslint@5.0.0-alpha.1 C:\Users\t-nagashima.MSS\dev\eslint
`-- eslint-plugin-rulesdir@0.1.0
```

Thank you for the suggestion. One version seems to exist.

**Comment by mysticatea** [comment]
Oh, I'm sorry. I find two diffrent versions. Thank you.
