### ISSUE TITLE
Feature Request: Speed up repeat ESLint runs via an `eslint server` command

### ISSUE THREAD

**Issue by cvoege** [eslint/eslint#10233]
**Tell us about your environment**
Ubuntu 16.04 

* **ESLint Version:**
4.18.1

* **Node Version:**
8.6.0

* **npm Version:**
5.3.0

**What did you do?**
Ran eslint on a large code base. Ran it again after making a few changes.

**What happened?**
Eslint took nearly 30 seconds to complete both times.

**What did you expect to happen?**
I expected ESLint to take 30 seconds the first time, but the second time should have taken less than a second since eslint should have only re-evaluated the files I changed.

**Proposed Solution**

My proposed solution is an `eslint server` or `eslint --persist` command. This command would run eslint and start a daemonized server running in the background. This server would watch for file changes in your repo and keep track of which files have changed since the last time eslint was run. Next time the user runs eslint only the files that changed would need to be reevaluated. If the ruleset or eslintignore has changed, the entire folder will simply be rerun as normal. If a file has not been changed since the last running of the command, the errors reported in the last running for that file will be reported again without the trouble of having to parse the file.

Facebook's `flow` library does this, and it makes it much easier to iterate. I'm planning on writing a server like this on my own because slow eslint runs are starting to slow my team down. Thus I'm making this issue to ask if the authors of eslint this would accept a pull that introduced the command i just mentioned to eslint. If not, I'll write it as a separate library. Though it seems like it would be nicer if it was built in. If this command was built in, then in the future we could further optimize this process by caching things like parsed ASTs into RAM, further speeding things up. But that's just an idea for the future and in my opinion a decent justification to build this command into the main eslint.

Hopefully I can contribute this soon. Thanks for your time!

**Comment by not-an-aardvark** [comment]
Hi, thanks for the feature request. Have you looked at [`eslint_d`](https://github.com/mantoni/eslint_d.js)? It seems to do a lot of the things that you're describing.

The last time something like this was proposed in https://github.com/eslint/eslint/issues/8109, the team seemed to generally favor having functionality like this in libraries rather than in ESLint core. I'm not sure I understand how it would be beneficial to include this in core -- you mentioned that we could cache ASTs, but it seems to me that the cache wouldn't be very useful because we would need to invalidate it any time a file changes, which is generally when we would need to lint the file anyway.

**Comment by ilyavolodin** [comment]
The functionality that you are requesting already exists in ESLint. You can run ESLint with `--cache` flag, which will cache the results of the first run and reuse them on all consecutive runs. This is different from @not-an-aardvark suggestion, because ESLint will not be running in the background all the time, so there's still start-up time overhead, but it will only validate changed files, so consecutive runs will be much faster.

**Comment by cvoege** [comment]
I think the combination of eslint_d and --cache are definitely enough to make this project unnecessary. Thanks for the response guys! I'll close the issue now.
