### ISSUE TITLE
Make sort-keys rule fixable

### ISSUE THREAD

**Issue by lipis** [eslint/eslint#10324]
Yes there is a https://github.com/eslint/eslint/issues/7714 but it's locked.. Can we at least unlock it so people could vote for it? I'm sure there are plenty of people that would like to have it, since it exists as a rule..

I don't see a valid point not fixing this rule fixable.

**Comment by platinumazure** [comment]
The main reason why we don't want to add an autofix here is because we don't want autofix to change runtime behavior. If you use (e.g.) `Object.keys()`, then autofix will change runtime behavior.

As a result, I'm still :-1: to this.

You're welcome to create a custom rule which implements autofix if you like. You could even use [eslint-rule-composer](https://github.com/not-an-aardvark/eslint-rule-composer) to leverage the core rule in your custom rule, so that any updates to this rule become available in the custom rule.

**Comment by platinumazure** [comment]
> But if the rule is there.. what's the difference if the eslint will fix it or not. Isn't that up to the users to decide? It's off by default anyway.

Unfortunately, there is currently no way to set autofix on or off per rule-- either all fixable rules have fixes applied, or not. Partially due to this and partially due to pain users have experience in the past around autofix breaking code, we have taken a conservative approach to autofixing and (for the most part) only autofix when there is no change of runtime behavior.

> I believe that whatever could be fixed with auto fix should be eventually implemented.. Isn't that part of the whole idea? Let machines do it for you.. :)

When an autofix occurs that changes runtime behavior, it is (generally speaking) *very hard* to debug. It can be hard to detect that the change even occurred in the file in the first place, and then there's the fact that the code experiencing a problem might be far away from the code that was changed to cause a problem. (For this rule, consider how an object might be created and exported in foo.js, and then bar.js calls a function to get the object and then iterates over the object's keys. The autofix would occur in foo.js but the issue would occur in bar.js.

------

Again, there's nothing stopping you from writing a custom rule that does this, as long as you (and the other users of that rule) are willing to accept the risks. So if we ultimately choose not to accept the proposal, this does not need to block you.

**Comment by lipis** [comment]
Yes I understand it all and I didn't mean to have the autofix per rule. 

In practice I'm not sure if anyone that writes an object should iterate them and rely on the original insertion order (I didn't even know that in some cases the [order remains](https://stackoverflow.com/a/5525820/8418)). That's why we have arrays :)

My point was that if someone will set this rule, they would like to have their keys sorted (unless `eslint-disable`...) instead of seeing the errors all the time. If that breaks the code it's not ESLint's fault, but the operator's :)

I guess we can close that issue (again) and thanks for letting me know that I can do it myself.. I didn't know how this open source thing works :P

**Comment by not-an-aardvark** [comment]
Closing this issue since it seems like the consensus is to not add it to ESLint core.

Thanks for opening it anyway -- it's often good to have a second look at issues even if they've been closed before.
