### ISSUE TITLE
Entire node highlighted because of endLine, endColumn inference

### ISSUE THREAD

**Issue by bsuh** [eslint/eslint#10424]
**The version of ESLint you are using.**
v4.12.1

**The problem you want to solve.**
Entire node highlighted with https://github.com/Microsoft/vscode-eslint
https://github.com/Microsoft/vscode-eslint/issues/370
https://github.com/Microsoft/vscode-eslint/pull/463#issuecomment-393101936

**Your take on the correct solution to problem.**
Add an option to disable endLine, endColumn inference or an option to reduce the reported range to the first token within the reported node
https://github.com/eslint/eslint/pull/8234

**Comment by not-an-aardvark** [comment]
Hi, thanks for the proposal.

In https://github.com/eslint/eslint/issues/8004, it was decided that ESLint should report large ranges if a node with a large range is reported by a rule, and allow integrations to display a smaller report if desired. The reasoning is that different integrations will have different needs with regard to report ranges (for example, an integration that posts comments on GitHub might want to know the entire reported range, whereas an editor integration might only want to highlight a subset of a reported range). ESLint doesn't really have any more information than editor integrations do about what report range is appropriate. (It only has the AST node provided by a rule, which is used to generate the original large report range).

As a result, I don't think it would be advantageous to add an option to limit `endLine`/`endColumn` behavior, because almost anything ESLint did as a result of that option could also be done by an integration, and an integration would have a better idea of what type of report range is appropriate for its users.
