### ISSUE TITLE
Rule/Plugin about tilde and caret in package.json

### ISSUE THREAD

**Issue by kaanozcan** [eslint/eslint#10439]
Hello Everyone,

I've been looking for ways to restrict the usage of tilde and caret in package.json of our project, no luck yet. Do you know any way to accomplish that, rule or plugin?

Thanks.

**Comment by platinumazure** [comment]
Could you please provide more detail? Is this about dependency management, or something else?

**Comment by kaanozcan** [comment]
Hello @platinumazure ,

This is about dependency management. Basically I want to allow this in package.json

```javascript
{
  "dependencies": {
    "x": "1.2.3"
  }
}
```
  
and fail our eslint step if it encounters anything like this:
```javascript
{
  "dependencies": {
    "x": "~1.2.3",
    "y": "^1.2.3"
  }
}
```

Thanks.

**Comment by nzakas** [comment]
It sounds like you're asking if ESLint can lint your `package.json` file. The answer is no, ESLint is only able to lint JavaScript files.

As this is a question rather than an action item, I'm closing the issue. If you still need help, please send a message to our [mailing list](https://groups.google.com/group/eslint) or [chatroom](https://gitter.im/eslint/eslint). Thanks!
