### ISSUE TITLE
Validate object literals

### ISSUE THREAD

**Issue by BridgeAR** [eslint/eslint#10550]
**Please describe what the rule should do:**

I propose to add a new object literal validation. In case the properties on an object are not dynamically manipulated in any way and the object is also not exported it would be possible to validate all accesses to properties of that object. That way it would be possible to check if the static property accesses are all valid. Besides that it would also be possible to validate for unused properties in case property access is only static and the object is never exported.
__[Update]__: There are a couple further things that would have to be though about like referencing the same object with a different variable name and then accessing the properties / setting them and passing the object to a function or using destructuring. The rule could therefore not warn about a lot of things but I believe this could a) be maybe improved later on and b) would still provide benefit for all possible cases. __[/Update]__

**What category of rule is this? (place an "X" next to just one item)**

[ ] Enforces code style
[x] Warns about a potential error
[ ] Suggests an alternate way of doing something
[ ] Other (please specify:)

**Provide code examples that this rule will warn about:**

```js
const kConstants = {
  a: true,
  b: false,
  errorOnNotAccessed: 'yes please' // Should error
}
Object.defineProperty(kConstants, 'c', {
  value: 'works'
}

// ... application code ...
function doThings(bar) {
  const randomAccess = kConstants[bar]
  const abc = kConstants.c
  const accessError = kConstants.d // Should error
  // ...
}

// Object is not exported
module.exports = { doThings }
```

**Why should this rule be included in ESLint (instead of a plugin)?**

It could provide early feedback when users access non existing properties on an object.

**Comment by ljharb** [comment]
The implication in the OP is that if the object is passed to any function (outside the file, at least) you’d be unable to validate it.

**Comment by not-an-aardvark** [comment]
Personally, I think it would be better to use a dedicated type checker such as TypeScript for this, because it would be able to do a much better job than ESLint and catch many more errors. Only being able to catch errors in a very small subset of cases (when there is no aliasing, and the object isn't passed to any functions that could modify it, and the object is never passed outside of the file) makes me think that this rule wouldn't be very useful.

**Comment by not-an-aardvark** [comment]
To add to my previous comment, why is an object being used here rather than a variable? It seems like instead of using an object like `kConstants` and accessing the `a` property, you could simply use a variable like `constantA`, and then you would be able to statically detect typos in names with `no-undef` since JavaScript variables are statically resolvable.

It's true that objects are sometimes more flexible than variables (e.g. since they can be dynamically created). But it seems to me that the cases where the additional flexibility is useful are the same cases where this rule wouldn't be able to validate your code, since it wouldn't be able to track dynamically-created object properties. So if the rule would only be useful for the cases where object properties are used as a replacement for variables, then I think a better solution would be to just use variables.

**Comment by BridgeAR** [comment]
I updated my code example to reflect my use case (random access from outside). I believe that pattern is not that uncommon but I do not have any numbers at hand.

I agree that TypeScript is probably more potential in this case. But there are lots of applications that do not use TypeScript at all and IMHO it would be a shame if eslint would not warn about mistakes that it could warn about (even if the cases are not as frequent).
