### ISSUE TITLE
Add an option to not throw an error on an unmatched pattern

### ISSUE THREAD

**Issue by yvele** [eslint/eslint#10587]
**The version of ESLint you are using.**

```
ESLint: 5.1.0.
```

**The problem you want to solve.**

Since breaking behaviour change 8b7c6eaed39e8506dba1aa6e57b1d0e2fdc351c3 #7390 #10143 bundled in ESLint 5, a fatal error is thrown if any file pattern return no files.

My company is using a generic ESLint configuration/runner for all our projects, and we are pretty happy with that:

```bash
eslint \
  --ext .js --ext .jsx --ext .mjs \
  -- src test "packages/*/src" "package/*/test"
```

The problem is that not ALL of our projects matches the same patterns, and we got this error since we upgraded to `eslint@5`

```
No files matching the pattern "test" were found.
Please check for typing mistakes in the pattern.
```

We don't want to implement custom code to check for pattern existence before appending them to eslint CLI parameters (and we where really happy with eslint@4 behaviour on this particular case).

NOTE: This issue is a bit related to https://github.com/eslint/eslint/issues/9977

**Your take on the correct solution to problem.**

Add a CLI option (exactly like [how proposed here](https://github.com/eslint/eslint/issues/9977#issuecomment-402269256)) not to throw errors on unmatched patterns.

Something like `--no-error-on-missing-files` or `--no-error-on-unmatched-pattern`

**Comment by kaicataldo** [comment]
This seems reasonable to me as long as long as the default behavior remains unchanged. Let's see what others say.

**Comment by platinumazure** [comment]
Agreed, it would be better to opt-in to this so that by default we are helping users avoid typos in their patterns.

**Comment by wei** [comment]
Related: #10530 #10556 

It is showing the same error when `--ignore-path` is used. 
Something like `--ignore-path .gitignore` as seen in the [docs](https://eslint.org/docs/user-guide/configuring#using-an-alternate-file) now breaks, which is quite frustrating. `.gitignore` could include folders like `build/` or `coverage/` that might not exist when linting. 😃

**Comment by not-an-aardvark** [comment]
I don't think an error is thrown nonexistent paths in `.gitignore`. Are you sure that's creating an error?

**Comment by isnifer** [comment]
Any update on this?

**Comment by not-an-aardvark** [comment]
@isnifer Thanks for explaining your use case. I'm a bit confused -- if you don't have any `app` code, couldn't you simply remove the path to `app/` from your script that lints all projects?

**Comment by isnifer** [comment]
@not-an-aardvark no, I have a code. But `app` and `web` are independent projects that use both `shared` and `api`. I don't use different configs and linter commands. I have the only config, the only lint command, and many projects.
```
.eslintrc
.eslintignore
packages/
package.json
lerna.json
...etc
```

Actually, I have found a solution for this:
```
# my v4 command to lint js
"lint": "eslint -c .eslintrc.js 'packages/api/**/*.js' 'packages/app/src/**/*.js' 'packages/app/__tests__/**/*.js' 'packages/app/scripts/**/*.js' 'packages/shared/**/*.js' 'packages/web/src/**/*.js' 'packages/web/__tests__/**/*.js' --cache"

# my v5 command to lint js
"lint": "eslint -c .eslintrc.js 'packages/**/*.js' --cache",
```
It works little bit longer when cold start, but then there is no problem.

**Comment by isnifer** [comment]
@not-an-aardvark 
```
> eslint -c .eslintrc.js 'packages/api/**/*.js' 'packages/app/src/**/*.js' 'packages/app/__tests__/**/*.js' 'packages/app/scripts/**/*.js' 'packages/shared/**/*.js' 'packages/web/src/**/*.js' 'packages/web/__tests__/**/*.js' 'packages/lol/__tests__/**/*.js' --cache || true


Oops! Something went wrong! :(

ESLint: 5.2.0.
No files matching the pattern "packages/lol/__tests__/**/*.js" were found.
Please check for typing mistakes in the pattern.
```
Because I don't need my RN `app` code inside docker for `web`

**Comment by not-an-aardvark** [comment]
So to make sure I understand, you want to use the same lint script in multiple environments, but in certain environments some of the files are absent?

**Comment by isnifer** [comment]
@not-an-aardvark correct. And I did it before v5.

**Comment by brunoscopelliti** [comment]
I've just upgraded to latest eslint@5.*, and this check is causing troubles to me as well.

I usually use eslint as: `eslint app/** --ext .js`.
Then in the *.eslintignore* file I exclude the undesired directory (eg. app/dist)...

In this case I get the following error:

```
No files matching the pattern "app/dist" were found.
Please check for typing mistakes in the pattern.
```

IMHO eslint shouldn't trigger the error for folders which are explicitly ignored. What do you think about this?

**Comment by brunoscopelliti** [comment]
Sorry for the double post.

I've also tried to run eslint as `eslint app/folder1/** app/folder2/** app/file1 --ext .js`.

That's not optimal cause if I add a folder, or file I've to update the build script as well, but I need a workaround for now.

However the above causes troubles as well, because I've some folders (eg. in app/folder2) which don't contain javascript file, but only json (eg. app/folder2/data/foo.json).

So I would really need a way to opt-out from this stricter check.

**Comment by not-an-aardvark** [comment]
Hi @brunoscopelliti, have you tried quoting the globs like `eslint "app/**" --ext .js`? It's possible that your shell is expanding the globs to a list of files before passing the files to ESLint, and the expanded list of files includes some folders that don't contain any lintable files.

**Comment by brunoscopelliti** [comment]
Hi @not-an-aardvark, I didn't know that was possible; quoting the globs worked for me. Thank you for the help.

**Comment by lucasrossini** [comment]
I've created a bash script as a workaround for this issue:

```bash
#!/bin/bash

GLOB_PATTERN=${1:-"."}
OUTPUT="$(script --quiet --return --command "eslint "${GLOB_PATTERN}"")"
EXIT_CODE=${?}

if [[ "${EXIT_CODE}" == "2" ]]; then
  exit 0
fi

echo "${OUTPUT}"
exit "${EXIT_CODE}"
```

Just call it passing the desired pattern as an argument.
Hope it helps!

**Comment by revelt** [comment]
I think this issue was closed prematurely. Many people (including me) want to be able to save time and share ESLint scripts across different projects (with sometimes non-existing paths in the glob).

It could be easily solved by adding a new CLI flag to skip glob entries that result in no paths.

If somebody from admin team are still reading this, please consider reopening this issue.

**Comment by alubbe** [comment]
I'd like to second that. We're working on legacy code which is close to impossible to refactor to our eslint rules, so we use `git log` to generate a list of changed files that eslint should run on. But sometimes this will included deleted files, breaking our workflow. Adding an option to just keep going would be extremely helpful.

**Comment by nathanredblur** [comment]
Anyone has some workaround for this issue. I'm migrating from js to typescript and eslint not support `as` operator then I disable to lint `ts` files but doing this brake the linting of the rest of `js` files. :(

**Comment by revelt** [comment]
@nathanredblur I ended up using a bit convoluted set of ignores on top of `--fix`, here's my npm `script`:

```
...
"lint": "./node_modules/.bin/eslint \"**/*.js\" --fix --ignore-pattern \"dist/*\" --ignore-pattern \"rollup.config.js\"",
...
```

Every time something breaks in my universal eslint script above, I add that path to every script on every package from the set. Thinking about your case, you could maybe add `--ignore-pattern \"**/*.ts\"`?

**Comment by rgranger** [comment]
I just tried to upgrade to eslint@5 and i ran into the same issue.

I have a "starter-kit" project with all the backbone code that I then fork to create other projects.

I have an eslint command that is trigged by the ci to lint my sources files, as well as my test files.
The starter-kit project doesn't have any test files since it has nothing to test, but i don't think the linting script should fail because of it...

Here are the scripts

```json
{
  "eslint:source": "eslint . --ignore-pattern=*.spec.js --ext=.jsx --ext=.js",
  "eslint:test": "eslint . -c=.eslintrc.test --ext=.spec.jsx --ext=.spec.js",
  "eslint": "npm run eslint:source && npm run eslint:test"
}
```

And the Error

```No files matching the pattern "." were found.```

Thanks for fixing this, or at least provide an option to not fail on empty test suites.
Otherwise I have a add a dummy empty test file in the starter-kit project, which is lame.

**Comment by RoSk0** [comment]
This definitely should be re-opened and fixed. Just faced with this strange behaviour on version v5.15.0. tested with Node 6 & 8.

Eslint should **NOT** fail if it can't find some files from a pattern.

**Comment by thecodejunkie** [comment]
Tooling should exit silently if it doesn't apply to any files.

**Comment by heldrida** [comment]
Please, reopen this issue as we should not get an error if eslint can't find files from a pattern.

**Comment by ezpuzz** [comment]
`eslint . --ext .graphql` with a custom extension I would assume it would exit silently if no files were found matching that extension in my project.  I do plan to eventually add some `.graphql` files to this project but my CI tooling runs all lint tasks.

**Comment by platinumazure** [comment]
I'll reopen this. We need to at least evaluate this as a TSC for sure.

**Comment by platinumazure** [comment]
**TSC Summary:**

In ESLint 5.0.0, we started throwing errors when nonexistent directories or files, or glob patterns that don't match any files, were passed to ESLint. The assumption was that users would want to know when a file wasn't being linted as it could be due to a misspelling. However, this has caused unforeseen side-effects for some tooling, where the intention is to create lint scripts that will lint certain files as they are created in a new project.

Numerous members of the community are asking that we add a CLI option to enable the old behavior on an opt-in basis. Example option names: `--no-error-on-missing-files`, `--no-error-on-unmatched-pattern`

**TSC Question**:

Should we invite contributions for a new CLI option to suppress errors when lint target files/directories are not found, or globs match no patterns?

**Comment by btmills** [comment]
I don't know what my schedule will be this afternoon, so in case I don't make it to the TSC meeting, I left a :+1: on the TSC summary above. It seems like the new default behavior works for most users, but the use cases described here justify an opt-out.

If you'll allow me to bike-shed a bit, I have a slight preference for option names like unmatched glob or unmatched pattern, since "missing files" sounds ambiguous to me. Having a long option name shouldn't be an issue since the use case here is a write-once shared script, and users wouldn't be typing it on every invocation.

**Comment by platinumazure** [comment]
Per discussion in the [2019/04/11 TSC meeting](https://github.com/eslint/tsc-meetings/blob/master/notes/2019/2019-04-11.md), this is now accepted. (Apologies for not following up here.)

**Comment by ozaytsev86** [comment]
Hi guys, just in case is useful, I'm in the same issue as you but with a bit different approach. 
Used command: `git diff --name-only --relative develop... src/ | grep -E \"\\.(js|jsx)$\" | xargs eslint -f node_modules/eslint-friendly-formatter --color`
What is doing, `git diff` to check for changed files between my branch and develop in this case in src/ folder then pass it through grep to only get .js and .jsx files then let's say normalize them and finally run eslint.

Is working fine but when there is at least one removed file is throwing an error:
`ESLint: 5.15.1.
No files matching the pattern "web/src/pathToTheFile/FileName.jsx" were found.
Please check for typing mistakes in the pattern.`

**Comment by platinumazure** [comment]
@ozaytsev86 In your case, you might be able to use `--diff-filter=d` to remove the deleted paths from consideration and avoid the problem.

**Comment by ozaytsev86** [comment]
thanks a lot @platinumazure , I checked again git diff documentation and exactly is saying if u use mayus arguments is to include and minus to exclude. Now it's working as a charm. :)

**Comment by Nikecow** [comment]
I would like this too as some of my projects dont have certain files. I make lots of projects a day so its hard to constantly adjust the command.

**Comment by xahon** [comment]
A solution is to create all needed files by patterns in separated directory
It's too silly

**Comment by GiancarlosIO** [comment]
I ended using :disappointed: 
```
"npx eslint ./crehana/frontdev/jsx/**/*.js ./crehana/frontdev/jsx/**/*.ts ./crehana/frontdev/jsx/**/*.tsx --ignore-pattern /node_modules/",
```

**Comment by rhyek** [comment]
I'm working with a monorepo and just wasted 3 hours with this dumb error.

**Comment by kaicataldo** [comment]
This proposal has been accepted. PRs welcome!

**Comment by ncraley** [comment]
I'm gonna take a look at this over the weekend and see if it's something I can tackle
