### ISSUE TITLE
try to remove some deprecated/unmaintained deps

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#10684]
To some extend, deprecated deps mean unhealthy. While I'm not seeing depth=1 deprecated deps in eslint, but
 + a) some seems unmaintained, e.g. levn; 
 + b) some depth>1 deps seems deprecated. (filing an issue in these repos might be a good idea)
![image](https://user-images.githubusercontent.com/13050025/43289971-28867e2a-915f-11e8-9159-272106fec004.png)
https://travis-ci.org/eslint/eslint/jobs/408555040#L430

I think it make sense to upgrade/remove these deps. a few thoughts on this(and want to get help from the community ✋ ):

+ find out deprecated/unmaintained deps.
+ if still maintained, upgrade to latest.
+ if not maintained, find a high-quality alternate.
+ if can't find a qualified alternate, write own.
+ or keep it. ◑﹏◐

refs: 
+ https://www.nczonline.net/blog/2015/12/why-im-not-using-your-open-source-project/
+ http://npm-introspect.z3d.tech/?packages=eslint

**Comment by mysticatea** [comment]
About `levn`, I don't think we should change it because it's a part of our public API (it parses CLI arguments and `/*eslint ...*/` directives).

About deprecated indirect dependencies, those seem to come from `beefy`, `karma`, and `sinon`.

<details>

```
> npm ls leftpad formatio nodemailer wrench uws mailcomposer socks node-uuid buildmail
eslint@5.2.0 C:\Users\starc\Documents\GitHub\eslint
+-- beefy@2.1.8
| `-- leftpad@0.0.0
+-- karma@2.0.5
| +-- log4js@2.11.0
| | +-- loggly@1.1.1
| | | `-- request@2.75.0
| | |   `-- node-uuid@1.4.8
| | +-- mailgun-js@0.18.1
| | | `-- proxy-agent@3.0.1
| | |   +-- pac-proxy-agent@2.0.2
| | |   | `-- socks-proxy-agent@3.0.1
| | |   |   `-- socks@1.1.10
| | |   `-- socks-proxy-agent@4.0.1
| | |     `-- socks@2.2.1
| | `-- nodemailer@2.7.2
| |   +-- mailcomposer@4.0.1
| |   | `-- buildmail@4.0.1
| |   `-- socks@1.1.9
| `-- socket.io@2.0.4
|   `-- engine.io@3.1.5
|     `-- uws@9.14.0
`-- sinon@3.3.0
  +-- build@0.1.4
  | `-- wrench@1.3.9
  `-- formatio@1.2.0
```

</details><br>

- I'm not sure what does `beefy` do. Can we remove it?
- We are using the latest `karma`, but most deprecated dependencies come from `karma`. Probably we have to find an alternative for `karma` and [phantomjs](https://github.com/ariya/phantomjs). Maybe [puppeteer](https://github.com/GoogleChrome/puppeteer) and ...? As a side note, we should consider drop the support of IE11 for our online demo since we cannot test for ES5 environment if we switch `phantomjs`.
- We are using very old `sinon`. Upgrading may solve it.

**Comment by mysticatea** [comment]
Should we open an issue on the `levn` repo at first? Because that repo has no issue in a long time, it means they have not needed to change their code.
