### ISSUE TITLE
Add fixer for no-useless-escape

### ISSUE THREAD

**Issue by pantosha** [eslint/eslint#10700]
**What rule do you want to change?**
no-useless-escape
**Does this change cause the rule to produce more or fewer warnings?**
No
**How will the change be implemented? (New option, new default behavior, etc.)?**
Add fixer
**Please provide some example code that this change will affect:**

```js
{
    code: "var foo = '\\`foo\\`';",
    errors: [
        { line: 1, column: 12, message: "Unnecessary escape character: \\`.", type: "Literal" },
        { line: 1, column: 17, message: "Unnecessary escape character: \\`.", type: "Literal" }
    ],
    output: "var foo = '`foo`';"
},
```

**What does the rule currently do for this code?**
Rule looks for useless escapes

**What will the rule do after it's changed?**
Rule will look for and fix useless escapes.

**Comment by not-an-aardvark** [comment]
Hi, thanks for creating an issue.

It may be worth noting that this has been proposed a couple times in the past, in https://github.com/eslint/eslint/pull/7188 and https://github.com/eslint/eslint/pull/7379. In both cases, we decided not to add a fixer because the `no-useless-escape` rule is often highlighting a mistake in the user's code, where they really meant to make the code do something else. Autofixing the rule would often prevent the user from seeing the error, which would prevent them from noticing a potential bug.

**Comment by pantosha** [comment]
Thank you for explanation. It sounds sad. I implemented this fixer to improve large code base in automatic way. Most likely, I'm not the only one. So it'll be nice to have optional fixers.
