### ISSUE TITLE
Add an optional --console-format flag so that you can save to file / log different errors

### ISSUE THREAD

**Issue by BenRuns** [eslint/eslint#10707]
**eslint 4.17.0**

**Humans may want to read an output in a different format than computers would like to consume**

**Add a --console-format  flag that specifies what is sent to the terminal**

I use eslint in jenkins and would prefer to have logs output be in a human readable format like stylish. For the output file, I want it to be  saved in junit to be consumed by jenkins.  Currently am using a hack using ClIEngine but would prefer to have be built into the CLI

**Comment by not-an-aardvark** [comment]
Hi, thanks for creating an issue.

I'm not strongly opposed to this, but my gut reaction is that this seems like sort of a narrow use case, and might not be worth adding an option for.

Have you considered using the [`CLIEngine`](https://eslint.org/docs/developer-guide/nodejs-api#cliengine) API for linting, rather than running ESLint directly from the command line? With that API, you could do whatever you wanted with the linting results, such as simultaneously outputting them to a file and printing them to stdout.

**Comment by BenPatterson2** [comment]
That's what I'm doing now. But I opened the PR/issue because I don't like the idea of having a different command for linting on Jenkins vs how my devs use eslint locally.  I also don't want to force anyone to use the my CliEngine based script locally if only because losing the flexibility of the existing Cli.

**Comment by BenRuns** [comment]
Sorry, logged into the wrong account. 

Seems this request has come up previously per https://github.com/eslint/eslint/issues/8185, I'm not really sure how often it comes up but I think this would convenience more than just my team considering that Jenkins is still pretty widely used.

**Comment by maxnordlund** [comment]
I also would like this, to output JUnit for GitLab CI and stylish to the log. That way you can see progress but also allow GitLab in this case to understand what happens.

**Comment by dimrozakis** [comment]
I would also like to see this implemented, I'd kindly ask to reopen this issue.

I'm using `eslint` with Gitlab CI and would like to be able to simultaneously:
1. Have a nice human readable output sent to stdout so that it can be inspected by developers.
2. Store a `junit-xml` artifact for processing with different tools.

**Comment by BenRuns** [comment]
Would be happy to work on the PR/Issue https://github.com/eslint/eslint/pull/10708 if there is some maintainer support to add the feature.

**Comment by platinumazure** [comment]
Personally, I'm still not sure I see a net benefit, compared to the small but nonzero cost of maintaining yet another CLI option (and the small but nonzero confusion this could potentially add to users who don't need the option but see it in `--help`, the small but nonzero time we need to spend as a team answering questions about it, etc.), when it seems it should be pretty easy to use the Node.js API to get the raw results and then invoke multiple formatters (one for console output, one or more for file outputs). So I'm mildly opposed to adding this flag.

If we didn't have the Node.js API and had no way around this issue, I would be more in favor of adding a CLI option.

**Comment by G-Rath** [comment]
I'm in the exact same boat using CircleCI - it will only use `junit` output files for it's insights, which means we're 100% reliant on their output (which isn't always great).

Hence, I'd love to be able to see the same output in the console in CircleCI, as I (and the other devs) do when running locally, w/o the overhead of having to learn & setup a whole other "thing" (what at a glance seems to be another JS file? which since I'm using TypeScript, becomes a whole new mess, as I assume eslint would require me to compile it into JS).

Personally, I don't think having a `--console-format` or `--ci` option would be too confusing.

**Comment by BenPatterson2** [comment]
Here is what I use in ci as a workaround.  I'd rather have a cli option but getting both formats isn't too difficult without it.
```
'use strict';

/* eslint-disable no-console */
/* eslint-disable require-jsdoc */
const fs = require('fs');
const { CLIEngine } = require('eslint');

const cli = new CLIEngine({
  ignorePath: 'repo/.eslintignore',
  configFile: 'repo/.eslintrc.js',
});

const report = cli.executeOnFiles(['repo/**/*.js']);

const consoleFormatter = cli.getFormatter();
const junitFormatter = cli.getFormatter('junit');

console.log(consoleFormatter(report.results));

fs.writeFileSync('./repo/lint-results.xml', junitFormatter(CLIEngine.getErrorResults(report.results)));

if (report.errorCount) {
  throw new Error('Linter Failed');
}

```

**Comment by G-Rath** [comment]
While a nice workaround, (and not bashing on you) I'd like to point out that this is just that - a workaround.

My primary problem w/ it is that is requires duplication of configuration, since you have to provide options such as `ignorePath`, `configFile` & the globs.

You could attempt to resolve some of this by parsing where it currently exists, but that'd be a mess: for me I'd have to require my `package.json`, and try to parse all the globs from `scripts.lint: "eslint \"**/*.ts\" <other globs & settings>"`.

Either Way, it's somewhat brittle as it requires you to have somewhat extraneous knowledge about the inner workings of eslint.

As a further example; the fact that you have to pass the `configFile` property makes me rather paranoid, as I don't know if that'll mean `eslint` will just use that `configFile` for every file it lints (compared to when I run it via `eslint`, where it will fall upwards until it finds an `.eslintrc` config file).

This is all stuff I don't want to know - and that quite frankly I'd want to implement tests for; case & point: yesterday I found out eslint has only been linting a handful of my files on CI due to me not escaping my globs (i.e "eslint \*\*/\*.ts" lints all files on Windows, but not on Linux - needed to be "eslint \"\*\*/\*.ts\""). - That's not eslints fault, but it was something I didn't know until I happened to glance at the uploaded artifacts while testing some changes I was making to my CI.

----

In saying all this, to me the problem could be "eliminated" by just switching to taking multiple formatters, like `jest` does (`jest --ci --reporters=default --reporters-jest-junit` gives you both the default output, and the `jest-junit` reporter output, which is a file).

While that'd have a bit of a higher initial non-zero cost in terms of users being confused & such, far as I can tell it nips this & all future issues of "I want x & y" in the bud by allowing an arbitrary number of formatters to do their thing.

I don't think it'd result in any real "formatter collision" bugs, since it'd literally be something like the above code, where you just call each formatter with the value of `report.results`.

I think I saw an open issue for this around somewhere, but eh it's a of course a bit bigger than the original scope of this issue 😉 

> and the small but nonzero confusion this could potentially add to users who don't need the option but see it in --help, the small but nonzero time we need to spend as a team answering questions about it, etc

I give you permission to have an issue template called "Anything about --console-format", and make its contents "@G-Rath promised he'll deal w/ & fix everything relating to this flag" in big block letters 😜

But seriously I get that - it's a valid worry. Would you be at all open to making it a semi-secret flag, on the argument that the people using it would have found it in context of what it's used for, and thus should be least confused? (i.e they'd have found it from issues like this one, where we had these long discussions), or is there anything else we as a community could do to try and help make this less of a worry for you guys if it was to be implemented?

**Comment by BenPatterson2** [comment]
I think the issue isn't the implementation.( I did as much in https://github.com/eslint/eslint/pull/10708/files) it's the maintenance of it down the road.

**Comment by G-Rath** [comment]
@BenPatterson2 ah awesome! That at least means we could explore using [`patch-package`](https://www.npmjs.com/package/patch-package) as a middle ground.

> it's the maintenance of it down the road.

Totally understandable, but also somewhat unavoidable in the long run - that's the nature of evolving products.

But I'm totally willing to pitch in, hence my question: is there anything we the community can do to help either reduce the maintenance cost of this feature, or reduce the surrounding maintenance cost to allow room for this feature? (Said knowing I'm pretty writing a blank check w/ which you could ask for the world 😂)
