### ISSUE TITLE
set cache defaults to true

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#10712]
**The version of ESLint you are using.** 
master/5.2.0

Caching is a common way to speed linting up. But now the cache defaults to false, so few people use this feature. I'm seeing a rationality to defaults to true. Is there a previous discussion on this?

**Comment by mysticatea** [comment]
Thank you for this issue.

I don't think that we should enable it by default.
Because the cache leads wrong results with some plugin rules such as `eslint-plugin-import`, `eslint-plugin-node`, `eslint-plugin-eslint-comments`, `eslint-plugin-flow-errors`, etc... The error of those rules can depend on other than the file, but the cache feature skips linting if the file is not modified.
