### ISSUE TITLE
eslint-recommended changes in eslint v6.0.0

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#10768]
Similar to previous release, new rules can be added to `eslint:recommended`(https://github.com/eslint/eslint#semantic-versioning-policy)

some candidates:
+ require-unicode-regexp
+ no-misleading-character-class
+ no-async-promise-executor
+ require-atomic-updates

+ reconsider rules like `eval`, `no-implied-eval`, `no-new-func`. (https://github.com/eslint/eslint/issues/9406#issuecomment-335983858)

+ ~~`no-console`~~

+ `no-mixed-spaces-and-tabs`: enable smart-tabs options. 

+ `no-shadow-restricted-names`

+ ``no-prototype-builtins``

+ https://github.com/eslint/eslint/issues/11279 (not accepted/implemented yet)

+ `no-useless-catch`

+ `no-with`

**Comment by platinumazure** [comment]
I like all of the new candidates in the original post.

I would like to remove the following from `eslint:recommended`:

* no-console

I would like to reconsider the following:

* no-mixed-spaces-and-tabs: It would be ideal (IMO) if smart-tabs option were enabled in recommended. I would also be okay with removing this from recommended.

**Comment by not-an-aardvark** [comment]
In [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/3e40976a2ebb9481405d4c3a358bc3191ecd234a/notes/2019/2019-02-28.md#fix-no-var-fixed-to-incorrect-code-fixes-11441), the TSC decided to accept this change with specific rules to be decided on this issue.

**Comment by not-an-aardvark** [comment]
It seems like we need a full proposal to decide on. I'll propose the following:

---

Add the following rules to `eslint:recommended`:

* `no-misleading-character-class`
* `no-async-promise-executor`
* `require-atomic-updates`
* `no-shadow-restricted-names`
* `no-useless-catch`
* `no-with`
* `no-prototype-builtins`

Remove the following rule:

* `no-console`

**Comment by nzakas** [comment]
I'm :+1: with everything except for `no-prototype-builtins`. I've always felt that rule was addressing an extreme edge case that most devs won't ever encounter and don't feel like we should be forcing it on our users.

**Comment by not-an-aardvark** [comment]
Personally, I'm convinced that `no-prototype-builtins` is worth adding. I suspect a majority of `hasOwnProperty` usages are buggy even if no one has discovered the bug yet, due to the possibility that `hasOwnProperty` can be shadowed in user-provided objects. (`hasOwnProperty` is only useful for objects where set of keys isn't precisely known, and that's precisely the case where one of the keys could shadow `Object.prototype`.)

To me, this is a case where developers can either (a) use a terse notation that is occasionally subtlely wrong, or (b) use a more verbose notation that doesn't have those problems. So my opinion is that always doing (b) is an easy choice, and enforcing against it is important for developers who might not be aware of the subtle bug.

**Comment by btmills** [comment]
I'm :+1: to all, though I won't argue too hard for `no-prototype-builtins` if there's not consensus around it. @not-an-aardvark makes a strong argument in my opinion because of the limited scope where `hasOwnProperty` is used. The two mitigating factors that would make me okay with not including it are that first, since it's a called function and not something that could be coerced to a boolean, it's less likely to result in a security vulnerability and more likely just a crash; and second, the use case for using an object as a map is going away now that we have built-in `Map`s.

**Comment by not-an-aardvark** [comment]
Adding this to the TSC agenda because we haven't reached a consensus on the issue.

**TSC Summary**: We need to finalize a decision for which rules to add to `eslint:recommended` in v6.

**TSC Question**: What rules should be added?

**Comment by platinumazure** [comment]
We've discussed in the [2019/04/11 TSC meeting](https://github.com/eslint/tsc-meetings/blob/master/notes/2019/2019-04-11.md).

Resolution: We will modify eslint:recommended as follows:

* Add no-misleading-character-class
* Add no-async-promise-executor
* Add require-atomic-updates
* Add no-shadow-restricted-names
* Add no-useless-catch
* Add no-with
* Remove no-console

And we will discuss no-prototype-builtins in the next TSC meeting on 4/25. (Goal is to have a final decision on that rule with that meeting.)

**Comment by not-an-aardvark** [comment]
In the [last TSC meeting](https://github.com/eslint/tsc-meetings/blob/3977017e01062f5b0ef58fed74f17b826a233cb2/notes/2019/2019-04-25.md#adding-no-prototype-builtins-to-eslintrecommended), the TSC decided to add `no-prototype-builtins` to `eslint:recommended` in addition to the changes discussed in https://github.com/eslint/eslint/issues/10768#issuecomment-486803164.
