### ISSUE TITLE
Linting by Resolving Functions from Multiple Scripts in HTML

### ISSUE THREAD

**Issue by hellofolks** [eslint/eslint#10774]
In  `index.html`:

```
<script src="scriptA.js"></script>
<script src="scriptB.js"></script>

<!-- and other scripts -->
```

In  `scriptA.js`:

```
function foo() {

}

// and many other functions
```

In  `scriptB.js`:

```
foo();

// and calling many others from scriptA
```

While editing the  `scriptB.js`  **eslint**  gives  `'foo' is not defined`  _error_. And in  `scriptA.js` it gives `never used` _error_. There should be a solution for these errors rather than specifying globals in files. Think that you have 50 global functions in `scriptA.js` and defining all of them as globals is burden. 

**ESLint** can check `name.html` file **with a new parameter** and can understand scripts' order and resolve them without any problem. Or it can just check `index.html` next to `.eslintrc` without a parameter. Regards.

**Comment by hellofolks** [comment]
ESLint is being waited for adding html script resolving feature. Thanks.

**Comment by ilyavolodin** [comment]
ESLint works only on one file at a time currently, so there's no way to share those globals. ESLint is also an ECMAScript linter, it doesn't know anything about html, and probably never will.

**Comment by hellofolks** [comment]
@ilyavolodin Yes ESLint is ECMAScript linter but this ECMAScript mostly runs in a html file. And people are adding their `ECMAScript`s into `html` files.
Just for `.html` files with a simple `--html index.html` parameter **ESLint can check** `.js` files order and lint as they are one under the other I think.
Thanks.

**Comment by ilyavolodin** [comment]
As I mentioned, ESLint works on one file at a time. So it currently can't share variables between files. In order to enable this, we would need to make some major changes. This possibility has been discussed before, but there're no concrete plans to do that right now.
There're no plans to make ESLint ever parse HTML files. Statement that ECMAScript mostly runs in html file is very misleading. I, for example, haven't written a pure HTML file in about 10 years. Between server-side languages, templates, aggregation techniques, transpilers and Node, I would venture to say that writing pure HTML files that include JS and can be easily parsed is probably a very very small minority of use-cases.

**Comment by platinumazure** [comment]
I think it might be worthwhile for a plugin (e.g., eslint-plugin-html) to consider exploring this. I don't think ESLint core should do this, for the reasons @ilyavolodin has stated [here](https://github.com/eslint/eslint/issues/10774#issuecomment-415037903).

**Comment by hellofolks** [comment]
@ilyavolodin I understood that ESLint works on one file at a time But with very simple parsing of just script tags in html ESLint can behave these multiple scripts as one script on another. And can easily lint this one file and give the output.
Whatever we are not talking here the requirements could people need with this tool, we are mostly talking about fixedness and trying to give it reasons.
Regards.
