### ISSUE TITLE
sourceType: 'infer'

### ISSUE THREAD

**Issue by kuraga** [eslint/eslint#10911]
Good day!

There are two options for `sourceType` configuration option: `'script'` and `'module'`. But what about `'infer'`?

AFAIK NodeJS [infers](https://nodejs.org/api/esm.html#esm_enabling) this based on extension. Let's implement it?

Thanks.

**Comment by platinumazure** [comment]
Hi @kuraga, thanks for the issue.

If you're using a recent version of ESLint, you could use [glob-based configuration overrides](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) to achieve this. You could create an override for `**/*.js` which uses `sourceType: "script"`, and one for `**/*.mjs` which uses `sourceType: "module"`.

Personally, I'm not seeing strong value in incorporating this into ESLint core, as many users do use ES6 modules within `.js` files so this would be a breaking change for them. And with the glob-based config override feature, you can achieve this pretty easily as it is :smile: But maybe other team members feel differently.

**Comment by ilyavolodin** [comment]
Agree with @platinumazure I'm also not seeing a whole lot of benefit implementing this.

**Comment by kuraga** [comment]
Well the only benefit is following (unfinished?) standard - ESM. We don't throw an error on incorrect code (ESM in .js files). Think not 'infer' but 'as standard'. (Well, agree, unfinished.)

**Comment by not-an-aardvark** [comment]
In the future, I think it would be a good idea to determine the default source type based on the file extension, while still allowing the user to override it if necessary for compatibility. If there is a standardized location to get information about a file's source type (e.g. the file extension), then this would reduce configuration complexity for many users because they could specify a source type in one place and have all tools use it, rather than needing to configure the source type in each tool separately. (Also see: https://github.com/eslint/eslint/issues/9592)

However, the `.mjs` extension in Node is still very experimental, and the final mechanism for determining a file's source type is up in the air, with strong opinions on both sides. I don't think we should implement source type detection until Node stabilizes the interface.

**Comment by kuraga** [comment]
Ok, thanks! I just wanted to show it's not about comfort but following ESM.
