### ISSUE TITLE
Change proposal: Allow exceptions for require-jsdoc

### ISSUE THREAD

**Issue by leinelissen** [eslint/eslint#10910]
Hey guys,

I want to start adopting require-jsdoc for internal use at the company I'm working with. The problem is that it either flags any function or none at all; meaning that even oft-repeated functions need a docblock. To be more specific, we'd like to opt-out of the rule if the function has a certain name, ie. `mapStateToProps` or `render`. We believe this will enforce a pattern of creating thoughtful comments, without having to create a docblock for recurring pieces of code.

I am perfectly willing to do a pull request for this one, if it all sounds good to you.

**What rule do you want to change?**
require-jsdoc

**Does this change cause the rule to produce more or fewer warnings?**
Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option

**Please provide some example code that this change will affect:**

Config 
```
"require-jsdoc": ["error", {
    "require": {
        "FunctionDeclaration": true,
        "MethodDefinition": false,
        "ClassDeclaration": false,
        "ArrowFunctionExpression": false,
        "FunctionExpression": false
    },
    "exceptions": [
      "mapDispatchToProps"
    ]
}]
```

Code:
```js
function mapDispatchToProps() {
  return {};
}

function otherFunctionName () {
  return {};
}
```

**What does the rule currently do for this code?**
Throws errors for both `mapDispatchToProps` and `otherFunctionName`.

**What will the rule do after it's changed?**
Only throw an error for `otherFunctionName`.

**Comment by leinelissen** [comment]
@ibbignerd Makes perfect sense to me!

**Comment by kaicataldo** [comment]
This seems reasonable to me, though I think `exceptions` might make more sense than `exceptMethods` since this rule also checks function declarations and expressions.

**Comment by leinelissen** [comment]
@kaicataldo I'll change it then!

**Comment by nzakas** [comment]
Thanks for the suggestion. As of yesterday, we have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. All JSDoc features are now deprecated and we won't be fixing bugs or making any further improvements to those features.

We are recommending that people transition over to use the [`eslint-plugin-jsdoc`](https://github.com/gajus/eslint-plugin-jsdoc) plugin instead of the built-in rules in ESLint.

Thanks for understanding and we apologize for any inconvenience.
