### ISSUE TITLE
no-useless-return and no-empty conflict

### ISSUE THREAD

**Issue by LJNeon** [eslint/eslint#10944]
**Tell us about your environment**

* **ESLint Version:** 5.6.1
* **Node Version:** 10.11.0
* **npm Version:** 6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**
My configuration is insanely elaborate covering most of the rules in depth, for an easy to verify example [use this](https://eslint.org/demo/#eyJ0ZXh0IjoiZnVuY3Rpb24gZnVuYyhib29sLCBudW0pIHtcclxuXHRpZihib29sKSB7XHJcblx0XHRyZXR1cm47XHJcblx0fWVsc2UgaWYobnVtID09PSA1KSB7XHJcblx0XHRjb25zb2xlLmxvZyhcInlheVwiKTtcclxuXHR9ZWxzZSBpZihudW0gPiAwKSB7XHJcblx0XHRjb25zb2xlLmxvZyhcInJpcFwiKTtcclxuXHR9XHJcbn1cclxuZnVuYyhmYWxzZSk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo5LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHktY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1lbXB0eS1wYXR0ZXJuIjoyLCJuby1lbXB0eSI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1peGVkLXNwYWNlcy1hbmQtdGFicyI6Miwibm8tbmV3LXN5bWJvbCI6Miwibm8tb2JqLWNhbGxzIjoyLCJuby1vY3RhbCI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zcGFyc2UtYXJyYXlzIjoyLCJuby10aGlzLWJlZm9yZS1zdXBlciI6Miwibm8tdW5kZWYiOjIsIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjoyLCJuby11bnJlYWNoYWJsZSI6Miwibm8tdW5zYWZlLWZpbmFsbHkiOjIsIm5vLXVuc2FmZS1uZWdhdGlvbiI6Miwibm8tdW51c2VkLWxhYmVscyI6Miwibm8tdW51c2VkLXZhcnMiOjIsIm5vLXVzZWxlc3MtZXNjYXBlIjoyLCJyZXF1aXJlLXlpZWxkIjoyLCJ1c2UtaXNuYW4iOjIsInZhbGlkLXR5cGVvZiI6Miwibm8tdXNlbGVzcy1yZXR1cm4iOjJ9LCJlbnYiOnsibm9kZSI6dHJ1ZX19fQ==)

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
See the demo for a live example of source code that causes this issue, try clearing line 3.

```bash
eslint . --ext .js
```

**What did you expect to happen?**
One of the two wouldn't error, in order to avoid conflict which each other. Even `--fix` conflicts with these rules.
**What actually happened? Please include the actual, raw output from ESLint.**
without `--fix`
```
../src/utility/LibraryHandler.js
  65:11  error  Unnecessary return statement  no-useless-return
```
with `--fix`
```
../src/utility/LibraryHandler.js
  64:46  error  Empty block statement  no-empty
```

**Comment by platinumazure** [comment]
Hi @LJNeon, thanks for the issue.

The `no-empty` rule ignores empty blocks with a comment. Will that work for your use case?

**Comment by LJNeon** [comment]
That doesn't sound like a real fix, I'd probably put a comment mocking eslint if that's the only solution \:P

**Comment by not-an-aardvark** [comment]
@LJNeon The reasoning for adding a comment is that it can help explain to readers of your code why the block is empty, when it might otherwise appear that it was a mistake. For example, you could write something like this:

```js
function func(bool, num) {
	if(bool) {
		// do nothing
	} else if(num === 5) {
		console.log("yay");
	} else if(num > 0) {
		console.log("rip");
	}
}
```

In other words, adding a comment to the block is less of a workaround to appease the linter, and more of a mechanism for making sure your code is readable. Using `return;` in this case isn't ideal because it could cause unexpected results if you need to add additional statements after the `if`/`else` statement (namely, those statements will be skipped).

**Comment by LJNeon** [comment]
> it could cause unexpected results if you need to add additional statements after the `if`/`else` statement (namely, those statements will be skipped).

So... it could do what it's supposed to? That doesn't seem very unexpected to me. But yea I guess a comment is more readable than just returning, but then code after the if..else statement would be executed when it shouldn't be.

**Comment by not-an-aardvark** [comment]
To clarify, if code after the `if`/`else` statement isn't supposed to be executed, then using `return` is fine (and `no-useless-return` won't report an error if there are additional statements).

Even if there aren't additional statements after the `if`/`else`, if the first case is conceptually supposed to be an "early exit" it might be clearer to write it this way:

```js
function func(bool, num) {
	if(bool) {
		return;
	}

        if(num === 5) {
		console.log("yay");
	} else if(num > 0) {
		console.log("rip");
	}
}
```

If the first case isn't conceptually an "early exit" and `return` is being used as a placeholder for "do nothing", then it seems clearer to actually do nothing (perhaps with a comment clarifying this choice), otherwise the use of `return` could be misleading to people reading/modifying the code in the future.
