### ISSUE TITLE
It's 2018, but async functions is syntax error

### ISSUE THREAD

**Issue by trusktr** [eslint/eslint#10978]
I know, I have to set `ecmaVersion: 2018`.

But perhaps this should be automatically set to the year we are in? Seems like that would probably be a better default for most people. Those people who really need older syntax can use the `ecmaVersion` option.

**Comment by not-an-aardvark** [comment]
Hi, thanks for the proposal.

I don't think defaulting the `ecmaVersion` option to the current year would be a good idea, for a few reasons:

* Users typically target specific browsers, and many users need to support browsers that aren't fully up-to-date. Also, sometimes browsers haven't fully implemented a spec even though the spec has a date with the current year.
* Changing the default `ecmaVersion` option is a breaking change, since users might not want to allow new syntax if they're targeting old platforms). Having the behavior of ESLint change depending on the date when it's run seems like it could be fairly confusing.

**Comment by nzakas** [comment]
We've discussed related things before:
https://github.com/eslint/eslint/issues/8290
https://github.com/eslint/eslint/issues/7528

And as I mentioned in #8290, what you're really asking for is to have `ecmaVersion: 2018` be the value we use when it's not specified in a config. Given that we automatically set this value when using `--init`, and the majority of ESLint users will be using it on an existing project, there isn't really a positive upside to this change whereas the negative downside is big (for users who don't have `ecmaVersion` set in their config files already).
