### ISSUE TITLE
Allow use node version >8

### ISSUE THREAD

**Issue by tp4k** [eslint/eslint#10981]
**The version of ESLint you are using.**
5.7.0
**The problem you want to solve.**
I want to use node eslint on node 8
**Your take on the correct solution to problem.**
Change node version to something like `"node": "^6.14.0 || >=8"`

I've seen https://github.com/eslint/eslint/issues/10052#issuecomment-377381218 but not support version because it have security reasons is very strange. All features are supported, and I don't think people care much about security during build stage. Now I have to install with `--ignore-engines` and everything works fine

**Comment by sharmilajesupaul** [comment]
@kaicataldo not OP, but we're using node v8.9.1 and are running into this issue since the allowed engines explicitly lists node `^8.10.0`.

**Comment by kaicataldo** [comment]
Ah, I see! `^8.10.0` was the latest version of Node v8 when we released ESLint v5, and this value hasn't changed since the 5.0.0-alpha.1 release. [Here's the reasoning](https://github.com/eslint/eslint/issues/10052#issuecomment-377381218) behind our decision to support the latest minor version of each major Node version.

**Comment by tp4k** [comment]
Sorry for my english. I've seen this comment. Eslint works fine on node>=8. So there is no reason to force users use node ^8.10. Security reasons doesn't matter much during build stage. Choosing version because it was last when you released new major is strange. 

> Earlier versions of Node 6 (as well as 8, 9, and the latest version of Node 7) have known security vulnerabilities. As a result, I think most users will be using the latest version on their release line (e.g. 6.14.0), or they should be able to upgrade without too much difficulty

So the only reason for node 8 is security, which is not eslint problem.

**Comment by Aladdin-ADD** [comment]
could you clarify the reason not upgrade node to `^8.10.0`(have better security)? If so, I would recommend to stay `eslint@4.19.1` before you can upgrade.

**Comment by ljharb** [comment]
Staying on eslint 4 loses out on much more security benefits than upgrading to the latest node 8 does - many of the security vulnerabilities don’t apply whatsoever to users, depending on their usage patterns, but eslint can prevent many classes of bugs at build time.

In other words, for many use cases, using eslint 5 on node 0.10 is much more secure than using eslint 4 on node 10.

**Comment by not-an-aardvark** [comment]
To clarify, our reasoning for supporting `^8.10.0` rather than `^8.0.0` is due to the fact that Node 8.10 has more features than Node 8.0, and ESLint might use those features in the future. The decision isn't directly motivated by security concerns.

We think most users who use `8.x` are probably using `^8.10` anyway for security reasons. This isn't about whether there are security vulnerabilities during the build step while running ESLint -- it's just that most users will probably have upgraded in general due to security concerns in other applications.

**Comment by ljharb** [comment]
In sirbnb’s case we’re stuck on node v8.9.1, because it is very costly and takes a lot of time to upgrade, the security concerns don’t affect our use cases, and we use babel, so new features never really motivate upgrading.

**Comment by ljharb** [comment]
What features that you might want are in 8.10 that aren’t in 8.9 or 8.8, for example?

**Comment by ljharb** [comment]
I agree that it's arbitrary and you have to draw it somewhere, but:
> I think it's reasonable for ESLint to not support it either.

I don't think node's choice of platform support need have any bearing on a given library's.

As I've said, we don't *need* any of the security updates, because none of the vulnerabilities apply to us, and since upgrading has a significant cost, eslint becomes the sole reason we might have to incur that cost.

**Comment by tp4k** [comment]
Security is not the reason on build stage. Package works fine on node 8. Security should be the concern of user (unless there is a security breach in package itself). Node version should be chosen based on needed features, performance, but not because it was last during major release.
The only thing you get with strict node `^8.10.0` is forcing users to install with `--ignore-engines` which seems completely pointless.

**Comment by ljharb** [comment]
To be fair, only yarn requires that, since npm correctly treats “engines” as advisory, but it’d still be nice to avoid the warning.

**Comment by not-an-aardvark** [comment]
@ljharb I understand your issue. My concern is that since we both agree that the exact point to draw the support line is largely arbitrary, I'm not sure it would be a good idea for us to change the support based on the version of Node used by one particular user/company. If we did that for everyone, then it would defeat the point of having a minimum supported version. I'd be interested to here what other team members think about this. (In https://github.com/eslint/eslint/issues/10052#issuecomment-380947327, we actually did reduce the minimum supported version to the version used by AWS Lambda, but that's a scenario where users wouldn't have any ability to upgrade their Node version.)

@tp4k To reiterate what I said in https://github.com/eslint/eslint/issues/10981#issuecomment-430298296, our Node version decision was based on the availability of features, not security. Although the package currently works fine on Node 8.0.0, in the future we might decide to use features that were introduced afterwards, and we don't want that to be a breaking change.

**Comment by ljharb** [comment]
@not-an-aardvark fair. Can you list what features are in 8.10 but not 8.9 that you’d want to use?

**Comment by patrickmcelwee** [comment]
I agree that ESLint should be as permissive as possible when it comes to Node versions. Currently, ESLint is putting itself in an odd position as the enforcer of upgrades to Node point release versions.

We have an application starter kit, for enterprise environments, with a goal of supporting Node 8.6+ (we specifically want to use the spread operator). We do not control all the environments in which generated applications will run, and Node point version upgrades can be a major undertaking in some enterprise environments. We are setting `engine-strict` to true so that we can throw an early error if the user does not have Node >= 8.6 or npm >= 5.7 (which we need for other reasons).

Like other projects, we have many npm dependencies, but ESLint is the only one which specifies a point release higher than 8.6 and thus forces us to require 8.10+ if we use `engine-strict` and ESLint (which we love!). The strictness with regard to Node point releases isn't in keeping with the npm ecosystem - and I think it should require specific reasons to justify.

**Comment by not-an-aardvark** [comment]
**TSC Summary**: We currently support only versions of Node 6 after 6.12.0, and only versions of Node 8 after 8.10.0. We do this to allow ESLint to use some newer Node features. (For example, we recently switched to using `assert.fail` with a single argument in `RuleTester` to avoid a deprecation warning in Node v11, and the new pattern is only supported in Node 6.14.0 and above.) However, some of our users are on older Node versions like Node 8.9 or 8.6, and unnecessarily upgrading to a later version of Node would be undesirable/expensive for them.

**TSC Question**: Should we expand our Node version support to older versions on the 8.x/6.x lines? If so, which versions?

**Comment by ljharb** [comment]
@not-an-aardvark it would be appreciated, if the status quo is retained, to get a concrete answer to https://github.com/eslint/eslint/issues/10981#issuecomment-431110502

**Comment by platinumazure** [comment]
> (For example, we recently switched to using `assert.fail` with a single argument in `RuleTester` to avoid a deprecation warning in Node v11, and the new pattern is only supported in Node 6.14.0 and above.)

If we're only supporting 6.12+ but this pattern is only supported in 6.14+, it seems that we've put in a breaking change. Do we need to revert that change and eat the deprecation warning?

**Comment by not-an-aardvark** [comment]
Sorry, I switched around the two numbers -- we [support 6.14+](https://github.com/eslint/eslint/blob/3d88b388aaa90f6053971b6073809e481f1ff457/package.json#L126) and the feature was [introduced in 6.12.0](https://github.com/nodejs/node/blob/d8924a0160b395025648f15b2a812596c2f19d3d/doc/changelogs/CHANGELOG_V6.md#2017-11-07-version-6120-boron-lts-mylesborins), so there wasn't a breaking change. I'll edit my comment.

**Comment by platinumazure** [comment]
@not-an-aardvark Thanks for clarifying!

**Comment by kaicataldo** [comment]
**TSC Resolution:** The TSC wasn't able to come to a consensus in the time allotted for today's meeting and will open up a new issue to discuss how ESLint will handle Node.js version support going forward.

**Comment by not-an-aardvark** [comment]
Created an issue at https://github.com/eslint/eslint/issues/11022.

**Comment by ljharb** [comment]
It'd still be good to reopen this one - #11022 is about a policy decision; this one is about a specific package.json change.

**Comment by not-an-aardvark** [comment]
They're the same issue given that the package.json change is just the implementation of the policy decision.

**Comment by ljharb** [comment]
Fair enough.

**Comment by nzakas** [comment]
Reopening to maintain a place for public comment on this topic while we figure out how to move forward.

**Comment by ljharb** [comment]
In response to https://github.com/eslint/eslint/issues/11022#issuecomment-462844169:
> as a carrot to encourage users to upgrade Node.js to the latest LTS.

It’s not a carrot for upgrading (no such carrot is ever needed, everyone upgrades whenever they can) but rather a stick that keeps us on an older eslint. airbnb is stuck on eslint 4 because we’re on node 8.9.

When we’re able to upgrade node will have zero to do with eslint or other tools’ support, and entirely to do with having the people available to do the upgrade. im also not aware of any syntax in 8.10 thats not in 8.9 (or if there’s any new APIs in 8.10 eslint is using, but it doesn’t appear so), so im not clear on why you couldn't lower the threshold a single minor version.

**Comment by patrickmcelwee** [comment]
ditto, but I'd extend the argument down to 8.6. https://node.green/ doesn't show any syntax support differences down to that version.

**Comment by kaicataldo** [comment]
Has this been resolved by [this discussion](https://github.com/eslint/eslint/issues/11022#issuecomment-473200771)?

**Comment by nzakas** [comment]
I believe so. I think our policy seems pretty well-defined now. If no one else disagrees, then I'd say it's time to close this.

**Comment by kaicataldo** [comment]
Sounds good! Closing this now.
