### ISSUE TITLE
`valid-jsdoc`: Report use of undefined (or project-restricted) types and unused types

### ISSUE THREAD

**Issue by brettz9** [eslint/eslint#11048]
**The version of ESLint you are using.**

5.8.0

**The problem you want to solve.**

Our project members may end up mistyping or mistakenly adding types which aren't defined in our library (or which are overly broad).

**Your take on the correct solution to problem.**

It would be great to have imported (or required) files be processed for `@typedef`, `@interface`, and all tags setting up names, to determine whether a type is defined anywhere in the application or not.

I'd also like the option to glob-include additional files/directories (e.g., we have a `typedefs.js` file which only consists of JSDoc comments for some generic types or external types used across our project) along with an option to glob-ignore certain folders/files.

Of course basic types like "string" and "boolean" would be expected by default though it'd be nice to be able to turn these off selectively as well, except within designated files--e.g., our project is currently insisting on avoiding "number" in favor of "Float" and "Integer", "object" in favor of "PlainObject", avoiding "*" in favor of "Any", etc., except in our `typedefs.js` file so as to better foster precision)

It'd also be helpful to find any types which were unused despite being declared.

**Are you willing to submit a pull request to implement this change?**

Not at this time.

**Comment by nzakas** [comment]
Thanks for the suggestion. As of yesterday, we have decided to officially [end-of-life JSDoc support](https://eslint.org/blog/2018/11/jsdoc-end-of-life) in ESLint. All JSDoc features are now deprecated and we won't be fixing bugs or making any further improvements to those features.

We are recommending that people transition over to use the [`eslint-plugin-jsdoc`](https://github.com/gajus/eslint-plugin-jsdoc) plugin instead of the built-in rules in ESLint.

Thanks for understanding and we apologize for any inconvenience.
