### ISSUE TITLE
Tests failing on current master

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#11062]
see https://ci.appveyor.com/project/nzakas/eslint/builds/20097976

**Comment by nzakas** [comment]
Confirmed. This is blocking PRs right now.

**Comment by not-an-aardvark** [comment]
Based on the test failures this might have been caused by the recent release of [`flat-cache`](https://github.com/royriojas/flat-cache). However, I probably won't have time to look into it in more detail today.

**Comment by nzakas** [comment]
I'll try to take a look in the few minutes of remaining energy I have.

**Comment by nzakas** [comment]
Related: #11052

**Comment by nzakas** [comment]
It looks like the contents of `.eslintcache` is now an array instead of an object, and all of the tests are failing because they are expecting the cache file to contain an object with keys that are the filenames.

I'm not sure that this has actually changed the functionality of `CLIEngine`, because we are reading from and writing to the cache using the API, whereas in the tests we are reading the cache file directly.

However, if the cache file format has changed, that will cause a problem for people who have an existing cache file and then upgrade or reinstall ESLint.

@royriojas any thoughts?

**Comment by royriojas** [comment]
hi @nzakas,

I recently released a new version of the `flat-cache` as a patch, which is in time used by `file-entry-cache`, but the unit tests passed in both `flat-cache` and `file-entry-cache` that's why I believe it was safe. 

The newer `flat-cache` is now using `flatted` as it was changed in this PR. https://github.com/royriojas/flat-cache/pull/23

Will take some time to review if that might be interpreting differently the cache

**Comment by royriojas** [comment]
I've reverted the upgrade of `circular-json` to `flatted` :( 

Will add a test for the eslint case before attempting to upgrade again

**Comment by nzakas** [comment]
Thanks @royriojas looks like we are in the clear now.

**Comment by Aladdin-ADD** [comment]
closing, as the issue has been fixed.
