### ISSUE TITLE
prefer-object-spread should discuss spec availability

### ISSUE THREAD

**Issue by vapier** [eslint/eslint#11136]
the [prefer-spread](https://eslint.org/docs/rules/prefer-spread) page helpfully discusses the fact that it's new to ES2015, but there is no such info on the [prefer-object-spread](https://eslint.org/docs/rules/prefer-object-spread) page which makes it read like people should be able to readily use it.

unfortunately, it's new to [ES2018](https://github.com/tc39/proposal-object-rest-spread), and even then, going by the [MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals), Edge & Safari don't yet support it.

**Comment by ljharb** [comment]
These days, most people are using Babel, so browser support is irrelevant.

It'd still be useful to make the docs clearer, tho!

**Comment by ilyavolodin** [comment]
@ljharb That's a very generic statement and one, that I believe is totally false. There's a huge number of legacy sites that are still supported that do not use Babel, so browser support is very much relevant. It's better to say that in your experience it's irrelevant.

**Comment by ilyavolodin** [comment]
> i should have qualified; irrelevant for those users
That's also a very broad statement. Most of the site have a matrix of supported browsers. If they do not transpile their code, they have to write code that will run natively in those browsers, which includes understanding of which features are supported and which are not.
If you work for a modern company and heavily involved in Open Source, it's really easy to think that everyone is writing modern WebApps and using Babel, Webpack, ESLint and other popular tools. But in reality, that covers a rather small percentage of JS developers. I know, because I work with those developers every day.

**Comment by nzakas** [comment]
👍 At a minimum, this should be mentioned in "When Not to Use It".
