### ISSUE TITLE
Add exceptions to no-unexpected-multiline rule

### ISSUE THREAD

**Issue by Mouvedia** [eslint/eslint#11197]
**What rule do you want to change?**

https://eslint.org/docs/rules/no-unexpected-multiline

**Does this change cause the rule to produce more or fewer warnings?**

fewer depending on an option

**How will the change be implemented? (New option, new default behavior, etc.)?**

probably like that:

```
"no-unexpected-multiline": [2, {"exceptions": [ /* … */ ]}]
```
**Please provide some example code that this change will affect:**

```js
promise.then(foo)
       .then(bar)
       ['catch'](qux);
```

**What does the rule currently do for this code?**

> Unexpected newline between object and [ of property access.
 
**What will the rule do after it's changed?**

Id like to add 2 optional exceptions for promises:

- `['catch']`
- `['finally']`

motivation: IE doesn't like `.finally` and `.catch`

**Are you willing to submit a pull request to implement this change?**

No.

**Comment by not-an-aardvark** [comment]
Hi, thanks for creating an issue. Sorry about the delayed response.

Personally, I don't think it would be worth adding this option to ESLint core. The `no-unexpected-multiline` rule is suggesting that you avoid using a linebreak here because it has the potential to be confusing -- it's not disallowing the use of computed properties in general. So it doesn't seem like it would make sense in general to have exceptions for specific computed properties when the rule isn't primarily aimed at computed properties. We wouldn't be able to add individual options for every user's preference, so instead we generally only add an option to a rule if it would be useful for a fairly large percentage of our users, and in other cases we suggest that people [create a custom rule](https://eslint.org/docs/developer-guide/working-with-rules) instead. Personally, I'm not convinced this option would meet the bar for adding to ESLint core, although I wouldn't object to adding it if another team member thinks it's worthwhile.

**Comment by Mouvedia** [comment]
@not-an-aardvark it could be specific as well:
```
{ "allowPromiseMethods": "true" }

// or

{ "ignorePromiseMethods": "true" }
```
would permit
```
promise['then'](foo)
       ['catch'](qux)
       ['finally'](bar);

**Comment by Mouvedia** [comment]
...
