### ISSUE TITLE
Remove autoconfig from --init

### ISSUE THREAD

**Issue by btmills** [eslint/eslint#11235]
The autoconfig portion of #11105 is being moved into this new issue after discussion in today's TSC meeting. The rest of this description was originally written by @nzakas in #11105:

**The problem you want to solve.**

The `--init` behavior has remained pretty consistent since it was first launched. At that point, we didn't know what options people wanted and the number of rules was very small. It seems like the current questions don't make sense for how ESLint is used today. For example, forcing people to pick a style guide doesn't make sense for everyone and sends a message that ESLint is used primarily for styling. I'd like to update the behavior of `--init` to better reflect current users expectations and usage.

**Your take on the correct solution to problem.**

**Remove autoconfig option.** I'm not sure how people feel about this, but I'm skeptical that this option is used all that much thanks to the popularity of shareable configs. I'm in favor of removing it if others agree but have no problem leaving it in if people feel it's still helpful. 

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by nzakas** [comment]
I'm also in favor of removing it. I see very little discussion of autoconfig anywhere I look (issues, Twitter, StackOverflow) and I'm not sure it's working 100% correctly at this point (see https://github.com/eslint/eslint/issues/11099).

Autoconfig was originally created because we felt that most people would want to create a style guide that most closely matches what they already have, but in reality, it seems like most people take an existing style guide and tweak it to match what they want.
