### ISSUE TITLE
Eslint keeps requiring overridden parsers when extending config 

### ISSUE THREAD

**Issue by kirill-konshin** [eslint/eslint#11240]
I am using `plugin:typescript/recommended` (`eslint-plugin-typescript`) on top of `react-app` (`eslint-config-react-app`) and as I can see from `eslint --print-config` the `parser` field is overwritten from `babel-eslint` to correct `/Users/dis/Sites/apple-music/node_modules/eslint-plugin-typescript/parser.js`, but for some reason ESLint still tries to resolve the unneeded parser, which is not even in final config.

I'm kinda okay to still install the useless parser, but it is a bit annoying.

**Tell us about your environment**

* **ESLint Version:** 5.8.0

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
  "extends": [
    "eslint:recommended",
    "react-app",
    "plugin:typescript/recommended",
    "plugin:import/recommended",
    "plugin:jsx-a11y/recommended",
    "plugin:prettier/recommended"
  ],
  "rules": {
    "no-console": "off",
    "prettier/prettier": "error"
  },
  "env": {
    "browser": true,
    "mocha": true,
    "node": true
  },
  "settings": {
    "import/resolver": {
      "node": {
        "extensions": [
          ".js",
          ".jsx",
          ".ts",
          ".tsx"
        ]
      }
    }
  }
}
```

</details>

```bash
eslint --fix src/**/*.ts src/**/*.tsx
```

**What actually happened? Please include the actual, raw output from ESLint.**

```
Error: Cannot find module 'babel-eslint'
Referenced from: /Users/dis/Sites/apple-music/.eslintrc
    at ModuleResolver.resolve (/Users/dis/Sites/apple-music/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at loadFromDisk (/Users/dis/Sites/apple-music/node_modules/eslint/lib/config/config-file.js:514:42)
    at load (/Users/dis/Sites/apple-music/node_modules/eslint/lib/config/config-file.js:564:20)
    at configExtends.reduceRight (/Users/dis/Sites/apple-music/node_modules/eslint/lib/config/config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/dis/Sites/apple-music/node_modules/eslint/lib/config/config-file.js:408:26)
    at loadFromDisk (/Users/dis/Sites/apple-music/node_modules/eslint/lib/config/config-file.js:528:22)
    at load (/Users/dis/Sites/apple-music/node_modules/eslint/lib/config/config-file.js:564:20)
    at configExtends.reduceRight (/Users/dis/Sites/apple-music/node_modules/eslint/lib/config/config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
```

**Are you willing to submit a pull request to fix this bug?**

I could if I would know how to fix this...

**Comment by Aghassi** [comment]
I'm wondering if this is related to this change https://github.com/eslint/eslint/commit/258b6541f61dc3a9ae64e200680766a11c3dd316

That seems to be the only thing that is related to requiring modules.

**Comment by kirill-konshin** [comment]
Superficially it looks like ESLint tries to actually require everything as soon as extends step was taken, not when config is fully finalized.

**Comment by not-an-aardvark** [comment]
> Superficially it looks like ESLint tries to actually require everything as soon as extends step was taken, not when config is fully finalized.

This is correct. As far as I know, ESLint has been doing this for awhile (i.e. it's not a recent change).

That said, I am a bit confused because I would have expected that the shareable config you're using would include the parser as a dependency, which would avoid the need for you to install unnecessary parsers manually.

**Comment by kirill-konshin** [comment]
This config is a part of `create-react-app` package, and it seems that this is a normal practice not to include lots of things in eslint setups, this one has everything listed as peer: https://github.com/facebook/create-react-app/blob/master/packages/eslint-config-react-app/package.json#L13, another example of quirk: `eslint-plugin-prettier` does not include `eslint-config-prettier` (I should probably file a bug for that).

**Comment by kirill-konshin** [comment]
I also suspect they do it this way (not adding `babel-eslint` to `dependencies`) in order to not end up having multiple instances of it, so that end-users will take responsibility to install it. Also they don't add any of the plugins they use, for the same reason, I think.

**Comment by not-an-aardvark** [comment]
To clarify, if something is a `peerDependency` of a package, then you always need to install it in order to use that package. This applies to ESLint configs and also everything else.

It's true that ESLint could probably avoid loading unneeded parsers as a performance optimization, but that is an implementation detail and isn't defined behavior. If a package is missing its required `dependencies` or `peerDependencies`, there are no guarantees about whether it will work.

**Comment by kirill-konshin** [comment]
Agree. If it's listed, it should be installed.

**Comment by nzakas** [comment]
It seems like this might be an unintended consequence of this change:
https://github.com/bradzacher/eslint-plugin-typescript/commit/2087aac3e5f371b4d65e8edfa622a38a8c0bb806

cc @bradzacher

**Comment by bradzacher** [comment]
My understanding of the intended use case of peer deps is that you are specifying parent deps, ie my package is run by these packages. 

The use of peer dependencies by CRA to attempt to merge or make packages optional seems like an "abuse" (for lack of a better term) of the non-automatic install quality of them...

That said, it's intentional for us to set the parser to our parser. The question here is that if you're extending a config that sets a parser, then overriding it in the base config, does it still bug out?

```JSON
{
  "extends: ["react-app"],
  "parser": "eslint-plugin-typescript/parser"
} 
```

**Comment by kirill-konshin** [comment]
In order to clarify: this ticket is not about peer deps, it's about ESLint who still requires a parser that does not appear in resulting configuration.

The use case is that I override a config that has one parser with another config that has another parser, I am not assigning parser myself, and the first parser is still required.

**Comment by aladdin-add** [comment]
I was able to repro it, and it seems a bug to me -- `babel-eslint` is not used at all.

**Comment by kirill-konshin** [comment]
Hmm, that's weird. It's clearly a bug that ESLint requires unused things, but now it's closed... what to do?
