### ISSUE TITLE
 error  Parsing error: Unexpected character '.' in scss files

### ISSUE THREAD

**Issue by phani17c** [eslint/eslint#11291]
ESLint version: "5.12.0",
Node: "8.0.0"
parser: babel-eslint: "8.2.1"

.scss file 

.some-class {
line-height: 1.5;
}

ESlint error:
 1:1  error  Parsing error: Unexpected token
.some-class {
^
line-height: 1.5;
}

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report. I would recommend not trying to run ESLint on scss files, because ESLint only supports JavaScript code by default.

For additional questions about how to use ESLint, please asking in our [Gitter channel](https://gitter.im/eslint/eslint) instead -- the issue tracker is generally intended for bug reports or feature requests, rather than support.

**Comment by phani17c** [comment]
Okay thanks for answering @not-an-aardvark
