### ISSUE TITLE
Allow the user to specify custom environments

### ISSUE THREAD

**Issue by jauco** [eslint/eslint#1130]
### The problem I want to solve:
Currently I have a hackish way of calling eslint because my test files require a slightly different eslintrc than my normal js files. I could put my test files in a seperate directory, but besides the fact that I don't like that, I can image more groups of files that require a slightly different eslintrc such as files that need to run on IE6 (requiring eslint rules that prevent a comma at the end of a hashmap) vs. files that are only for nodejs. I don't think that requiring different directories is always the best solution.

### My take on the solution to problem.
My first take was to simply allow you to specify eslint overrides depending on the file name. (so you can have `some.test.js` and `some.crossplatform.js`) While this is a quick fix it was pointed out to me that this adds too much complexity to the configuration system. So perhaps we could make the environments configurable?

- I'm currently on master
- I'm willing to implement this myself

### discussion points
 - [x] whether to store the property in the .eslintrc or in a seperate file. (.eslintrc)
 - [ ] the name of the property in the .eslintrc
 - [ ] how to deal with naming collisions between the custom environment
 - [x] how to deal with two environments specifying a different severity. ([simply let the environment that is included latest win](#issuecomment-50901055))

**Comment by matz3** [comment]
Is there any progress here?

It would be great if plugins could provide custom environments that define not only rules but also globals e.g. for (testing) frameworks that are not supported out of the box.

**Comment by nzakas** [comment]
No progress, but PRs are gratefully accepted.

**Comment by eric-isakson** [comment]
Moving this conversation from #2509 at the request of Nicholas... 

What I attempted in #2509 was to namespace the environment definitions using the plugin name and load them early enough that they can be referenced in other configurations. Based on where I added the logic in lib/config.js any environment added via a plugin will be treated exactly as an environment from conf/environments.js with the exception that the environment name will be prefixed with the plugin name. This allows all the normal mechanics of turning them on/off in the env block of the config files or via eslint-env comments.

It appears to me that in the earlier commentary on this issue, the original request to put these directly in .eslintrc was closed out and the decision to make this a plugin feature only was stated. Did I not understand that correctly? https://github.com/eslint/eslint/issues/1130#issuecomment-51491446 If we want support for this directly in .eslintrc I would suggest we use some kind of reserved name like "env" which would preclude anyone from ever creating eslint-plugin-env plugin that contributes environments and then process them after plugin environments from the same config and adding that prefix. IMO, we should just do this with plugins though since a single "env" namespace has lots of potential for name collision issues when multiple configs are loaded and merged. Thoughts?

It also appears that precedence for rule overrides would be based on config load order, so that issue is resolved but... if two environments are actived in the same config, which one takes precedence? That is an existing issue that probably just doesn't occur because the only environment contributing rules currently is the node one. The env property of the config is processed using an Object and iterating over its keys rather than an array, so the order is non-deterministic and not based on the order they are defined as mentioned earlier (probably need to open an issue for this if it was not intended to work this way but I don't see a backward compatible fix):

https://github.com/eslint/eslint/blob/master/lib/config.js#L245
http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order
http://yaml.org/spec/1.2/spec.html#id2765608

Are there any other issues with this proposal that should be addressed? Other thoughts or opinions about the direction this should take? I'd much prefer an accepted fix than a private fork, so I'm motivated to provide a fix for this.

**Comment by nzakas** [comment]
The big issue is how to include environments in plugins that might reference both native rules and rules in that same or another plugin. This is the problem we have been unable to solve. 

One of the things we did in plugins is that nowhere in the plugin do you need to reference the plugin name, so rules are referred to without a prefix. This is important for maintainability. So given that constraint, how can we create an environment that can disambiguate native ESLint rules and rules from this plugin?

**Comment by ilyavolodin** [comment]
@nzakas Given that --reset change is going to land in 1.0.0 and all of the built-in environments will stop supporting environment specific rules, do we want plugins to allow for environment specific rules? It sounds a bit strange to allow third-party plugins to do something that we disallow our own code to do.

**Comment by eric-isakson** [comment]
Just read over #2100 and I don't see the issue ilyavolodin. How will reset as default make plugin.rulesConfig or env definitions not support rules? It seems to me that it will only affect the default rules that are applied when reset is not specified and there is no baseConfig:

https://github.com/eslint/eslint/blob/master/lib/config.js#L302

Am I missing some other issues where rules will no longer be specified in environments?

As to rule name prefixes, I think there are a few good options with differing tradeoffs. For native rules and rules from other plugins, use the bare rule name for native and the plugin qualified name for the other plugin. Referring to other plugins from a plugin has its own set of issues like can a plugin depend on another plugin or do you just document that your plugin has that dependency...you can express a peerDependency in your plugin package.json but you need the consumer to reference both in their .eslintrc if the plugin cannot declare the dependency chaining plugins or environments recursively may be worth consideration but carries other baggage, so on to the options:

1. prefix this plugin's rule names in the environment with a */ and replace with the plugin name before adding to envirionments object. As suggested and discussed starting at https://github.com/eslint/eslint/pull/2024#discussion_r26438578 IMO, this is the best we can do if we don't want to require the plugin name.
2. require the plugin author to qualify their rule names with their plugin name like they would any other plugin's rules.
3. if a rule is defined with the given name in the plugin, use the bare name to prefix the rule with the plugin name. The problem with this one is you can't tell if the rule configuration in the environment is for the plugin rule or the native rule if there is a name collision between the plugin rule and the native rule with the same name. Given that you would need a way to differentiate these and you may as well have gone with option 1 or 2 at that point.

IMO, 2 is the way to go but 1 meets Nicholas' objective of not using the plugin name as a prefix.

**Comment by eric-isakson** [comment]
https://github.com/eric-isakson/eslint/commit/eec12e7a78a2fa3c8d94bf8110766d73e8988e7d has an implementation that supports */rulename if you want to see it in action.

**Comment by nzakas** [comment]
@eric-isakson we already rejected the `*/rule` approach.

@ilyavolodin that's a very good point I hadn't thought of. Maybe shareable configs already solve the problem we thought custom environments were solving?

**Comment by ilyavolodin** [comment]
Shareable configs do allow you to enable rules, but they do not allow for quick on/off switches in comments. I'm not sure that's a show stopper, but it would probably be nice to have for consistency. In any case, I still think it would be strange to allow third-party environments to enable/disable rules, and not allow our core environments to do so.
P.S. @eric-isakson --reset also resets environment specific rules, so once it becomes standard, environments will lose ability to turn rules on/off.

**Comment by eric-isakson** [comment]
@nzakas I know you rejected "*/rule" but you also do not want "plugin/rule" and if you just say "rule" you can't tell the difference between a plugin rule and a "native" rule if they use the same rule name. As much as we don't like */rule or plugin/rule, I don't see any other option, do you?

perhaps the point is moot if the reset proposal is a done thing. Once reset is the default in 1.0.0, the only way an environment can contribute rules is if an /*eslint-env envname*/ comment is used (which still appies environment rules even when reset is on). IMO, it is a loss that environments will no longer be able to contribute rules via .eslintrc but I see the value gained by reset as noted in that issue. I suspect this will not be a happy thing for many eslint users that are not aware of the reasoning behind this change, so IMO broad communication on this breaking change is important and that is probably true for any other 1.0.0 breaking changes. Is there anywhere those are being recorded right now outside of github issues? I recall a roadmap way back but don't see that now on the site.

It looks to me like shareable configs will solve the problem I'm trying to address which is to provide a way for my teams to easily adopt our corporate standards. I will pursue that route and keep watching for other ways I can contribute to this community. Love the tool :)

**Comment by nzakas** [comment]
@ilyavolodin that's true. I think the larger question is if there's a need to quickly toggle things on and off in this manner. I'm not seeing that as a need right now, are you?

**Comment by ilyavolodin** [comment]
No, don't see a real need for that right now. Just listing all possibilities for consideration. I think with shareable configs we will cover most of the needs for custom environments. This issue can probably be closed now.

**Comment by nzakas** [comment]
Agreed. We will keep an eye out for such cases in the future.
