### ISSUE TITLE
Auto fix conflict (implicit-arrow-linebreak and max-len)

### ISSUE THREAD

**Issue by jabacchetta** [eslint/eslint#11408]
**Tell us about your environment**

* **ESLint Version:**
5.3.0
* **Node Version:**
10.10.0
* **npm Version:**
6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
"eslintConfig": {
  "parser": "babel-eslint",
  "rules": {
    "max-len": ["error", 100],
    "implicit-arrow-linebreak": ["error", "beside"]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const someIncrediblyRidiculousSuperLongFnName = (foo, bar) =>
  someOtherIncrediblyRidiculousSuperLongFnName(foo, bar);
```

```bash
eslint --fix
```

**What did you expect to happen?**
```js
const someIncrediblyRidiculousSuperLongFnName = (foo, bar) => (
  someOtherIncrediblyRidiculousSuperLongFnName(foo, bar)
);
```

**What actually happened? Please include the actual, raw output from ESLint.**
```js
// FIXME: Fixed implicit-arrow-linebreak, but broke max-len
const someIncrediblyRidiculousSuperLongFnName = (foo, bar) => someOtherIncrediblyRidiculousSuperLongFnName(foo, bar);
```

**Are you willing to submit a pull request to fix this bug?**
Not in the near future, but would be willing to eventually.

**Comment by g-plane** [comment]
Hi @jabacchetta , thanks for this issue. I can reproduce this bug.

**Comment by not-an-aardvark** [comment]
This doesn't seem like a bug to me. The autofixers for some rules can generally create linter problems for other rules.

**Comment by g-plane** [comment]
Can we change the autofixer to create parens and linebreaks like @jabacchetta mentioned?

**Comment by g-plane** [comment]
Of course I know each rule shouldn't concern other rule, but this is really confusing in UX.

**Comment by not-an-aardvark** [comment]
It seems like the user would sometimes want everything to be on the same line. Since the `implicit-arrow-linebreak` rule can't read the config for `max-len`, it seems difficult to make an informed decision in that rule. I suppose we could set an arbitrary hardcoded limit in `implicit-arrow-linebreak`.

**Comment by g-plane** [comment]
Any details?

**Comment by not-an-aardvark** [comment]
For example, in the `implicit-arrow-linebreak` rule we could decide to add `(` and a linebreak if the length of the line before the arrow function body is at least 50 characters, and otherwise we would just stick with the current behavior.

Personally, I'm not sure this is worthwhile, but it would be one way to sometimes address the confusing UX.

**Comment by not-an-aardvark** [comment]
Relabeling as an "enhancement" because it's expected that autofixers for some rules can sometimes create linter problems for other rules.

**Comment by DZuz14** [comment]
Was looking for this tonight. C'mon eslint bot, show us and them sweet arrow functions some love.
