### ISSUE TITLE
Insert semicolons automatically when running fixers (to prevent generating invalid code with ASI failures)

### ISSUE THREAD

**Issue by futpib** [eslint/eslint#11481]
**The version of ESLint you are using.**
5.14.1 (but the exact version seems irrelavant)

**The problem you want to solve.**
Built-in and third-party rule fixers have to duplicate automatic semicolon insertion logic to generate correct replacements. Built-in [`curly` rule has it](https://github.com/eslint/eslint/blob/5018378131fd5190bbccca902c0cf4276ee1581a/lib/rules/curly.js#L156-L208), [`semi` does too](https://github.com/eslint/eslint/blob/5018378131fd5190bbccca902c0cf4276ee1581a/lib/rules/semi.js#L204-L216), `eslint-plugin-unicorn` has an issue sindresorhus/eslint-plugin-unicorn#254 about it.

**Your take on the correct solution to problem.**
When eslint applies fixes, it could check if a fix would result in ASI failure and insert semicolons when required. Rule authors would not be required to handle this.

**Are you willing to submit a pull request to implement this change?**
Probably, yes.

**Comment by fisker** [comment]
sounds great

**Comment by not-an-aardvark** [comment]
Hi, thanks for creating an issue.

Unfortunately, I'm not sure this is feasible. Rules can output any text at all as part of an autofixer, and ESLint has no way to determine what semantics the rule intended. It seems like it would cause problems if a rule intentionally omitted a semicolon (in order to have two pieces of text be part of the same statement), and ESLint added a semicolon to the text, incorrectly believing that the rule made a mistake.

In the long term I think it would be nice to have an AST-based autofixing API along the lines of how babel plugins work, which would make it easier to write autofixers without dealing with lots of special cases. In the meantime, though, I think we're stuck with having rules check for ASI on their own.
