### ISSUE TITLE
Provide users with a way to customize how changes to files are detected for caching purposes

### ISSUE THREAD

**Issue by montmanu** [eslint/eslint#11490]
**The version of ESLint you are using.**

5.12.1

**The problem you want to solve.**

We are currently unable to realize the benefits of eslint's result caching within our CI environment due to a combination of limitations related to file attribute preservation with common CI tooling and the current `stat` -based change detection implementation within eslint.

**Your take on the correct solution to problem.**

Add a `--cache-strategy` (working title) CLI option to enable customization of the `useChecksum` argument to [`file-entry-cache#create`](https://github.com/royriojas/file-entry-cache#createcachename-directory-usechecksum).

(see #11487)

**Are you willing to submit a pull request to implement this change?**

(see #11487 😉)

**Comment by hulkish** [comment]
+1 would like to use this also

**Comment by not-an-aardvark** [comment]
Hi, thanks for creating an issue.

Could you clarify the workflow that you would expect to use with caching in CI? Is the idea that you would include a cache file in source control, which would affect the behavior of linting in CI? I'm not sure I fully understand the desired use case.

As I mentioned on https://github.com/eslint/eslint/pull/11487#issuecomment-470739742, my main concern with adding a CLI flag is that by adding an option like this we would be making the details of our cache behavior part of the public API, which could make it more difficult to change or improve how caching works in the future without breaking users' more-specific expectations.

If we do decide to add a flag for this, if nothing else I think we should make the possible values for `--cache-strategy` a bit broader -- for example, `--cache-strategy=file-mtime` and `--cache-strategy=file-contents`. (The values of `stat` and `md5` in https://github.com/eslint/eslint/pull/11487 seem unnecessarily specific to implementation details. For example, if we decided for some reason to switch to a different hash function instead of `md5`, the user-visible behavior would still be the same, so I don't think making the user provide a value of `md5` is a good idea.)

**Comment by hulkish** [comment]
@not-an-aardvark how about https://github.com/royriojas/file-entry-cache/pull/14

**Comment by montmanu** [comment]
@not-an-aardvark We cache certain build artifacts to remote storage locations (e.g., s3, gcs, etc).. Prior to running any CI tasks, we update the local state by restoring the previously cached artifacts. 

In our case, we cache / restore the eslint result cache file.. when the eslint result cache is used, our lint task completes in ~4s. When the eslint result cache is not used, our lint task completes in ~4:15s (we're working on a largish project).

When relying on `mtime` to detect changes to files, the eslint result cache never actually resulted in a cache hit because the items checked out by git on disk always appeared newer than what was stored in the eslint result cache from the previous build (even if a file had not actually changed). Switching to the `useChecksum` approach resolved this by comparing checksums of a file's contents (which do not change unless the file itself had changed).

**Comment by montmanu** [comment]
If https://github.com/royriojas/file-entry-cache/pull/14 is merged, we'd be happy to use that approach instead. We're really not married to any particular implementation as long as we have a way to customize that `useChecksum` argument..

**Comment by nzakas** [comment]
If the request here is "have ESLint use a different checksum for its caches", then this should be implemented in ESLint (if at all). We shouldn't let transitive dependencies define ESLint behavior on its own because there's no guarantee that the dependencies we use now will be the same ones we use in the future, and tracing down implicit features is tricky.

As this is a request for an significant enhancement, we would need a design to consider and it would fall under our RFC policy. You can read more about creating an RFC here:
https://github.com/eslint/rfcs/

**Comment by montmanu** [comment]
@nzakas Thanks for the insight. I will review that policy. 

To clarify, the request here is less about using a _different_ checksum than it is about supporting the use of a checksum at all (instead of the file's `mtime` which is the default) .. currently, the underlying dep supports using an md5 checksum (the `useChecksum` argument to [`fileEntryCache#create`](https://github.com/royriojas/file-entry-cache#createcachename-directory-usechecksum)) for detecting changes, but eslint does not use that feature and does not provide an API to enable its use. So the request here is to provide that API (while leaving the current / default implementation unchanged).
