### ISSUE TITLE
`object-shorthand` with `ignoreConstructors` option wrongly identifies '_foo' as a constructor name

### ISSUE THREAD

**Issue by overlookmotel** [eslint/eslint#11595]
**Tell us about your environment**

* **ESLint Version:** v5.16.0
* **Node Version:** v10.15.3
* **npm Version:** v6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
	env: {
		node: true
	},
	parserOptions: {
		sourceType: 'script'
	},
	extends: [
		'airbnb-base',
		'plugin:eslint-comments/recommended'
	],
	rules: {
		// Alterations of airbnb rules
		'max-len': ['error', {
			code: 105,
			tabWidth: 4,
			ignoreStrings: true,
			ignoreTemplateLiterals: true,
			ignoreRegExpLiterals: true,
			ignoreUrls: true
		}],
		indent: ['error', 'tab'],
		'no-tabs': ['error', {allowIndentationTabs: true}],
		'comma-dangle': ['error', 'never'],
		'object-curly-spacing': ['error', 'never'],
		'one-var': ['off'],
		'no-plusplus': ['off'],
		'no-restricted-syntax': ['off'],
		'no-param-reassign': ['off'],
		'no-use-before-define': ['error', {functions: false}],
		'object-curly-newline': ['error', {multiline: true, consistent: true}],
		'one-var-declaration-per-line': ['error', 'initializations'],
		'prefer-destructuring': ['error',
			{
				VariableDeclarator: {array: false, object: true},
				AssignmentExpression: {array: false, object: false}
			},
			{enforceForRenamedProperties: false}
		],
		'no-invalid-this': ['error'],
		'no-underscore-dangle': ['off'],
		'space-before-function-paren': ['error', {
			anonymous: 'never',
			named: 'never',
			asyncArrow: 'always'
		}],
		'func-names': ['off'],
		'object-shorthand': ['error', 'always', {
			avoidQuotes: true,
			ignoreConstructors: true,
			avoidExplicitReturnArrows: true
		}],

		// eslint-comments rules
		'eslint-comments/no-unused-disable': ['error'],
		'eslint-comments/disable-enable-pair': ['error', {allowWholeFile: true}]
	}
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
const o = {
  _foo: function() {
    // Foo foo!
  }
};
```

```bash
eslint lib/** --ext .js
```

**What did you expect to happen?**

Expected `object-shorthand` rule to flag a violation of the rule. I am using `ignoreConstructors: true` option but `_foo` is not a constructor.

**What actually happened? Please include the actual, raw output from ESLint.**

No output. The rule is not triggered.

**Are you willing to submit a pull request to fix this bug?**

Yes.

However, I'm not completely sure what correct behavior is. What characters can a constructor name begin with?

The current check for if an identifier is a "constructor" [here](https://github.com/eslint/eslint/blob/master/lib/rules/object-shorthand.js#L125) is:

```js
function isConstructor(name) {
  const firstChar = name.charAt(0);
  return firstChar === firstChar.toUpperCase();
}
```

So `'_foo'` is identified as a constructor. So is `'$foo'`.

From ECMAScript spec [here](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-identifier-names), it looks like `'_'` and `'$'` are the only non-letter characters which are legal as the start of identifiers, so the only chars which will cause this issue.

In which case, an additional line would solve it:

```js
if (firstChar === '_' || firstChar === '$') return false;
```

But would `_Foo` be considered a constructor name or not? `$Foo`?

And are there any other unicode chars which should be similarly be considered not valid as first char of constructor names?

Certainly method names starting with `_` are quite common cases, so it'd be good to solve that case at least.

**Comment by overlookmotel** [comment]
I have submitted PR https://github.com/eslint/eslint/pull/11596 to fix the common cases of `'_'` and `'$'`.

**Comment by btmills** [comment]
Ha, nice catch on this fun edge case @overlookmotel! I was able to verify this in the demo ([`ignoreConstructors: false` has an error](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IG9iamVjdC1zaG9ydGhhbmQ6IFtcImVycm9yXCIsIFwiYWx3YXlzXCIsIHsgXCJpZ25vcmVDb25zdHJ1Y3RvcnNcIjogZmFsc2UgfV0gKi9cblxuY29uc3QgbyA9IHtcbiAgX2ZvbzogZnVuY3Rpb24oKSB7XG4gICAgLy8gRm9vIGZvbyFcbiAgfVxufTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=), yet [`ignoreConstructors: true` doesn't](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IG9iamVjdC1zaG9ydGhhbmQ6IFtcImVycm9yXCIsIFwiYWx3YXlzXCIsIHsgXCJpZ25vcmVDb25zdHJ1Y3RvcnNcIjogdHJ1ZSB9XSAqL1xuXG5jb25zdCBvID0ge1xuICBfZm9vOiBmdW5jdGlvbigpIHtcbiAgICAvLyBGb28gZm9vIVxuICB9XG59OyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6Niwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==)).

If we were to fix this behavior, we'd be assuming that no constructor can start with `_` or `$` because identifiers starting with those characters would always error. Is that a safe assumption?

**Comment by overlookmotel** [comment]
@btmills When you say "would always error" do you mean the code would be invalid Javascript? Or that ESLint would error on this rule?

It's valid Javascript. This don't cause an error on NodeJS v10:

```js
function _Foo() {}
const foo = new _Foo();
```

Having thought about it more, I think `_Foo` should be considered a constructor name. If I wanted to declare a constructor and mark it as "private", I'd call it `_Foo`. But this would be very very uncommon case.

However, if you're happy with PR #11596, could you possibly merge that in the meantime as it solves the most common case and shouldn't have negative effects elsewhere?

**Comment by btmills** [comment]
Good question, I can clarify that a bit if I expand on your example ([demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IG9iamVjdC1zaG9ydGhhbmQ6IFtcImVycm9yXCIsIFwiYWx3YXlzXCIsIHsgXCJpZ25vcmVDb25zdHJ1Y3RvcnNcIjogdHJ1ZSB9XSAqL1xuXG5jb25zdCBvYmogPSB7XG4gICAgLy8gU2hvdWxkIGhhdmUgYW4gb2JqZWN0LXNob3J0aGFuZCBlcnJvclxuICAgIF9wcml2YXRlTWV0aG9kOiBmdW5jdGlvbigpIHtcbiAgICAgICAgLy8gRG8gc3R1ZmZcbiAgICB9LFxuICAgIC8vIFNob3VsZCBub3QgaGF2ZSBhbiBvYmplY3Qtc2hvcnRoYW5kIGVycm9yXG4gICAgX1ByaXZhdGVDb25zdHJ1Y3RvcjogZnVuY3Rpb24oKSB7XG4gICAgICAgIC8vIFJldHVybiBhIG5ldyBpbnN0YW5jZVxuICAgIH1cbn07Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)):

```js
/* eslint object-shorthand: ["error", "always", { "ignoreConstructors": true }] */

const obj = {
    // Should have an object-shorthand error
    _privateMethod: function() {
        // Do stuff
    },
    // Should not have an object-shorthand error
    _PrivateConstructor: function() {
        // Return a new instance
    }
};
```

This is a bit contrived, but the issue I see is that if we change the constructor-detection logic to be `firstChar !== "_" && firstChar !== "$" && firstChar === firstChar.toUpperCase()`, then `_PrivateConstructor` wouldn't be detected, and the error from `object-shorthand` would be a false positive.

Now that I typed out an example, what if instead of looking at `name.charAt(0)`, should we instead do the first non-`/[_$]/` character? People could theoretically then run into the same issue you encountered with a name like `_8Name`, but that seems way less common than an identifier with just a `_` or `$` prefix.

**Comment by overlookmotel** [comment]
Thanks for swift reply. So are you saying that you think all the following should be treated as constructors names:

```
Foo
_Foo
$Foo
__Foo
___Foo
$__Foo
_8Foo
$8Foo
__123Foo
```

and these not:

```
foo
_foo
$foo
__foo
_8foo
$8foo
_123foo
_
__
$
$$
```

If, so something like this would do it:

```js
const CTOR_PREFIX_REGEX = /[^_$0-9]/;

function isConstructor(name) {
  const match = CTOR_PREFIX_REGEX.exec(name);
  if (!match) return false; // In case name is e.g. `_`, `$$`, `_8`
  const firstChar = name.charAt( match.index );
  return firstChar === firstChar.toUpperCase();
}
```

**Comment by platinumazure** [comment]
I can get behind an option that looks for, basically, the first letter in the identifier name and checks that it's capitalized. :+1:

**Comment by overlookmotel** [comment]
OK, I've amended PR #11596 accordingly.
