### ISSUE TITLE
Autofix for no-unused-vars "caughtErrors: all"

### ISSUE THREAD

**Issue by saschanaz** [eslint/eslint#11640]
**The version of ESLint you are using.** 5.16

**The problem you want to solve.**

We currently have to manually fix `caughtErrors: all` errors even when we give `"ecmaVersion": 2019`.

**Your take on the correct solution to problem.**

 ESLint could automatically fix this by removing catch bindings.

**Are you willing to submit a pull request to implement this change?**

Yes if I learn how to implement an autofix.

This is basically #10434 but based on the existing rule.

**Comment by g-plane** [comment]
Hi @saschanaz , thanks for this issue.

The rule `no-unused-vars` isn't intended to provide autofix. So we won't implement autofix for this rule.

**Comment by saschanaz** [comment]
@g-plane I can understand why the rule currently does not autofix (as removing general variable may cause some side effect), but maybe this specific case can be autofixed. Can you elaborate more?

**Comment by not-an-aardvark** [comment]
We generally only autofix a rule when we're sure of what the user intended to do. With `no-unused-vars`, sometimes an unused variable indicates that the user has a bug in their code because they meant to use the variable. So if we "fix" the problem by deleting the variable, we might end up just concealing the bug because the problem will no longer be brought to the user's attention.

**Comment by arcanis** [comment]
Could that be enabled via an explicit option of the rule?
