### ISSUE TITLE
"semi-spacing" rule doesn't work after "while"

### ISSUE THREAD

**Issue by vitaly-t** [eslint/eslint#11721]
**Tell us about your environment**

* **ESLint Version:**
5.16.0
* **Node Version:**
10.15.3
* **npm Version:**
6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "env": {
    "es6": true,
    "node": true,
    "jasmine": true
  },
  "extends": "eslint:recommended",
  "parserOptions": {
  },
  "rules": {
    "semi-spacing": "error"
    "prefer-arrow-callback": "error",
    "no-else-return": "error",
    "no-multi-spaces": "error",
    "no-whitespace-before-property": "error",
    "camelcase": "error",
    "new-cap": "error",
    "no-console": "error",
    "comma-dangle": "error",
    "no-var": "error",
    "no-shadow": "error",
    "object-shorthand": [
      "error",
      "properties"
    ],
    "indent": [
      "error",
      4,
      {
        "SwitchCase": 1
      }
    ],
    "quotes": [
      "error",
      "single"
    ],
    "semi": [
      "error",
      "always"
    ]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
while (/*condition*/) ;
```

```bash
./node_modules/.bin/eslint ./lib
```

**What did you expect to happen?**

To error about the space between the end of `while` condition and `;`, because of the `"semi-spacing": "error"` rule. This issue is specific to one-line (or empty) while statements.

**What actually happened? Please include the actual, raw output from ESLint.**

It passes.

**Are you willing to submit a pull request to fix this bug?**

Maybe.

**Comment by mysticatea** [comment]
Thank you for your report.

However, I think that this is expected behavior because the `while` statement and the empty statement (`;`) are different statements. The `semi-spacing` checks two spaces:

- `before` ... between a statement and the `;` of the statement.
- `after` ... between a statement and the `;` of the previous sibling statement.

**Comment by vitaly-t** [comment]
>  the `while` statement and the empty statement (`;`) are different statements.

I don't follow you. The `;` closes the `while` statement, indicating that no `{}` follows. That is a single block, not two separate ones.

**Comment by mysticatea** [comment]
- `while (true) ;` ... The body of the `while` statement is an empty statement.
- `while (true) {}` ... The body of the `while` statement is a block statement.

The former's semicolon is the empty statement's, but not the `while` statement's. It's the reason that the latter case doesn't have semicolon.

**Comment by vitaly-t** [comment]
> ... but not the while statement's

Of what statement then? `;` terminates the `while` statement's logic.

**Comment by mysticatea** [comment]
The body of the `while` statement. It's an empty statement. 

`if (true) ; else ;` is a similar case.

**Comment by platinumazure** [comment]
I really think we should be considering this rule in terms of tokens, not statements. `semi-spacing` should look at all semicolon tokens and ensuring there is (or is not) a space between the semicolon and the previous and next tokens, regardless of statement boundaries.

**Comment by vitaly-t** [comment]
@mysticatea 
I do not see any analogy. You are showing some useless code examples, I logged it for how people write code:

**Example:**

```js
// find the end of string:
while(text[++c] !== '\n');

// c = index of the symbol;
```

**Comment by mysticatea** [comment]
@platinumazure I don't think so. Different semantics should have different appearances to distinguish what you do. At least, I think it requires a space before the `;`. Though, configurable is nice.

@vitaly-t  `while(text[++c] !== '\n');` means "repeats en empty statement while until a line break." - The body of the `while` statement is an empty statement. See the language spec: https://tc39.github.io/ecma262/#sec-iteration-statements

**Comment by mysticatea** [comment]
How about an option: `{ danglingEmptyStatement: { before: boolean, after: boolean } }`?

It affects to:

- `for (a) ;`
- `while (a) ;`
- `do ; while (a)`
- `if (a) ;`
- `if (a) ; else ;`
- `with (a) ;`
- `LABEL: ;`

**Comment by platinumazure** [comment]
I just think a token-based approach would work best because it would be intuitive to users and would be parallel to rules like `comma-spacing`. We should design rules to keep the most common case simple, and less common customizations can be done with extra rule options.

In my opinion, having the rule not work at all for `while (condition);` is bad, but requiring that users use a new option just because that semicolon is associated with an extra empty statement is not a useful distinction for most users. Instead, we should have the rule work on those semicolons by default. If users say they want different behavior for empty statements, only then should we add an option for that customization.

**Comment by mysticatea** [comment]
I agree that it's reasonable if `semi-spacing` rule checks empty statements as well, with the same preference as others by default. But it's a breaking change.

**Comment by platinumazure** [comment]
@mysticatea That's debatable- it depends on if the lack of enforcement is considered a bug. I think it is, but you and others might disagree. As you know, if this is a bug, we can accept a fix as semver-minor.

**Comment by mysticatea** [comment]
From my curiosity, I'd like to ask:

I guess that we can agree that the following space is needed.

```js
while (a) foo();
//       ^ this space
```

Because that space separates the head and the body of the `while` statement.

This is the same even if the body is an empty statement.

```js
while (a) ;
//       ^ this space
```

That space separates the head and the body of the `while` statement.

I feel strongly odd if that space doesn't exist regardless of the body is an empty statement or not.

Why do you want to join the head and the body of `while` statements if the body was an empty statement?

----

I'm leaning towards to that another rule should check this rather than `semi-spacing` rule.

Currently, we don't have any rule that reports the following case:

```js
while (a)foo();
//       ^ missing space
```

Maybe we should have a rule for the space between the head and the body of some syntaxes.

**Comment by platinumazure** [comment]
> I'm leaning towards to that another rule should check this rather than `semi-spacing` rule.
> 
> Currently, we don't have any rule that reports the following case:
> 
> ```js
> while (a)foo();
> //       ^ missing space
> ```
> 
> Maybe we should have a rule for the space between the head and the body of some syntaxes.

When there isn't an empty statement as the body, I agree-- I think `semi-spacing` should handle the semicolon after `foo()` in the example, and a new rule should handle the missing space after `(a)`. But I think if the body is an EmptyStatement, it would be more intuitive to users for `semi-spacing` to handle this, as the rule would be adding or removing a space around a semicolon.

**Comment by vitaly-t** [comment]
I come from the world of C++ where I would often use `while (/*condition*/);` statement, and no IDE would enforce use of an extra space in place of an empty body. I'm only getting it now in WebStorm, for JavasScript, because that IDE relies on eslint, and so I opened a [corresponding bug with them](https://youtrack.jetbrains.com/issue/WEB-38836).

**Comment by mysticatea** [comment]
@vitaly-t Thank you for your answer.

@platinumazure I can't think that this is a responsibility of `semi-spacing` rule. It has a pretty different semantics.

We have some holes that we can't check because some spacing rules ignore semantics.

```js
while (a)foo();
//       ^ missing space
class A {}foo();
//        ^ missing space
```

- The former is the space which is between the head and the body of a syntax. If the body was a block, [space-before-blocks] rule checks it. But if the body was another statement, any rule doesn't check it. Here, I think that we can generalize the [space-before-blocks] rule.
- The latter is the space which is between two statements. If the first statement had semicolon, [semi-spacing] rule checks it. But if the first statement didn't have semicolon, any rule doesn't check it.

My proposal will be two: generalizing of [space-before-blocks] rule and separating of [semi-spacing] rule.

```jsonc
{
    // Check the space which is between the statement itself and the semicolon of the statement.
    // This is the same as the `before` option of the current `semi-spacing`, but it doesn't have `after` option.
    "bikeshade--semi-spacing": [
        "error",
        "always" | "never"
    ],
    // Check the space which is between two statements.
    // This is the same as the `after` option of the current `semi-spacing` if the previous statement had that semicolon.
    // Also, this rule checks the space even if the previous statement was a block.
    "bikeshade--space-between-statements": [
        "error",
        "always" | "never"
    ],

    // Check the space which is between the head and the body of a statement/declaration regardless of the kind of the body.
    // This is a generalized rule of `space-before-blocks` rule.
    "bikeshade--space-before-statement-body": [
        "error",
        {
            // TDB for the current options of `space-before-blocks` rule.
            "bare": "always" | "never",
            "block": "always" | "never",
            "empty": "always" | "never",
        }
    ],
}
```

[space-before-blocks]: https://eslint.org/docs/rules/space-before-blocks
[semi-spacing]: https://eslint.org/docs/rules/semi-spacing

**Comment by platinumazure** [comment]
@mysticatea Apologies, it seems I wasn't clear.

```js
while (true) /* 1 */ ;

while (true) /* 2 */ {}

while (true) /* 3 */ foo() /* 4 */ ;
```

I think `semi-spacing` should handle `/* 1 */` and `/* 4 */`, and the others should be handled by some other rule. I believe `/* 4 */` is currently being handled by the rule. I would like to keep the focus of this issue on `/* 1 */`, which I believe should be handled by the rule (as I stated earlier).

Hope this clears things up.

**Comment by mysticatea** [comment]
@platinumazure I understand your opinion, but I'm sorry, I don't agree with you because of the language spec. I think `semi-spacing` should not check the `/* 1 */`.

**Comment by platinumazure** [comment]
**TSC Summary:**

An issue was reported where the `semi-spacing` rule does not check the space before or after a control statement with empty body (such as `while (/*condition*/) ;`). After some discussion between a few team members, consensus could not be reached on whether this should be regarded as a bug, an enhancement to `semi-spacing`, or justification for a new rule altogether. Discussion seems to hinge on whether the rule should be token-based and should work on most/all semicolon tokens regardless of node context, or if the rule should be node-based and should have different functionality for EmptyStatement nodes that are the body of control statements.

**TSC Question:**

* Should the original issue be regarded as a bug, an enhancement request (i.e., is a new option needed for this case), or a feature request (i.e., is a new rule needed)?
* Should we take any action around the other gap identified (no rule for enforcing space between conditional and single statement body)?

**Comment by platinumazure** [comment]
@mysticatea Please review [this comment](https://github.com/eslint/eslint/issues/11721#issuecomment-494775794) to ensure I have adequately captured your rationale. If I haven't, please feel free to make minor edits to the comment if needed so that it accurately reflects your position. Thanks!

**Comment by platinumazure** [comment]
@mysticatea You removed the "tsc agenda" label about a month ago but I don't see any information here on what the TSC chose to do with this. Could you please add that information and then, if necessary, reopen this issue? Thanks!

**Comment by mysticatea** [comment]
Oh, sorry.

The meeting note is there: https://github.com/eslint/tsc-meetings/blob/master/notes/2019/2019-05-23.md#semi-spacing-rule-doesnt-work-after-while

TSC was leaning toward https://github.com/eslint/eslint/issues/11721#issuecomment-494353167 proposal.
Therefore, I have made an RFC: https://github.com/eslint/rfcs/pull/26
