### ISSUE TITLE
How to use .eslintrc.js of another project in the project?

### ISSUE THREAD

**Issue by moonlitnighta** [eslint/eslint#11760]
**The version of ESLint you are using.**
^5.16.0

**The problem you want to solve.**
How to use .eslintrc.js of another project in the project?
for example: 
![image](https://user-images.githubusercontent.com/22231630/58303878-9e397980-7e24-11e9-8606-552749541a37.png)

I want to use ESlint NodeApi to check the code of any project. I need to get the .eslintrc.js of the project before checking, but I can't get the plugin configured by the project when I get the configuration. How to solve this problem?
**Your take on the correct solution to problem.**
Manually install missing plugins into my project...

**Are you willing to submit a pull request to implement this change?**

**Comment by not-an-aardvark** [comment]
With ESLint v5, if you load the version of ESLint installed by the other project (e.g. `require('../path/to/other/project/node_modules/eslint')` and use that version of `CLIEngine` instead, it will be able to load that project's plugins.

Note that this will change in ESLint v6, which is currently in alpha releases. When using that version, you can use the [`resolvePluginsRelativeTo` flag ](https://eslint.org/docs/6.0.0/developer-guide/nodejs-api#cliengine) in `CLIEngine`.

**Comment by moonlitnighta** [comment]
@not-an-aardvark Thank you, your method is very effective! But eslint still doesn't seem to work, because he has to load other configurations, and the path to be loaded is my current project, not the project being checked. Can I only run eslint in my own project?
![image](https://user-images.githubusercontent.com/22231630/58306797-4f451180-7e2f-11e9-97e7-d6133c7ec041.png)

**Comment by not-an-aardvark** [comment]
My guess is that you are using `@typescript-eslint/eslint-plugin`, which uses `process.cwd` to determine where it should load a `tsconfig.json` file from. I'm not  Unfortunately, rules don't have access to the `cwd` option passed to `CLIEngine`, so they typically just use `process.cwd`. As a short-term solution, you could check whether the plugin has an option to specify the `tsconfig.json` file that it uses.

As a longer-term solution, I think it would be worthwhile to implement something like https://github.com/eslint/eslint/issues/11218 so that rules can do this correctly, but it looks like that discussion has stalled.
