### ISSUE TITLE
Support TypeScript in configuration initializer.

### ISSUE THREAD

**Issue by g-plane** [eslint/eslint#11789]
**The version of ESLint you are using.**
master

**The problem you want to solve.**
When running `eslint --init`, an option for TypeScript can be provided. Ref: https://github.com/eslint/eslint/issues/11368

**Your take on the correct solution to problem.**
Add a question or option in Inquirer questions list.

**Are you willing to submit a pull request to implement this change?**
Yes.

**Comment by platinumazure** [comment]
I'm not opposed if the team consensus is to add support to ESLint init specifically for Typescript. After all, we already explicitly ask about React. However, I'm worried about potentially having to field more requests to add support for Flow or other libraries/frameworks.

ESLint was built to get out of the business of legislating rules, and pluggability has been a core design principle in that area. But we haven't done the same with init.

So, what I would like us to at least consider is: How can we make ESLint init more pluggable? Is there a way we could let plugins extend our init somehow? If such a thing could be implemented, then I envision typescript-eslint could export a binary in their package which might be something like, `typescript-eslint-init`, and they could choose to ask all, some, or none of the core ESLint init questions and add questions related to the plugin or to the language/framework/library on which the plugin is based.

**Comment by not-an-aardvark** [comment]
Personally, I think it might be difficult to have a "pluggable `eslint --init`" along those lines due to problems with discoverability. If a user is aware of what `typescript-eslint` is, then they might not need the custom `eslint --init` anyway because they can just follow the instructions in that project's readme. Since `eslint --init` is intended for new users as an alternative to reading config documentation, it doesn't seem ideal to require them to find plugins (they might not even know what a plugin is).

**Comment by g-plane** [comment]
> 
> 
> Personally, I think it might be difficult to have a "pluggable `eslint --init`" along those lines due to problems with discoverability. If a user is aware of what `typescript-eslint` is, then they might not need the custom `eslint --init` anyway because they can just follow the instructions in that project's readme. Since `eslint --init` is intended for new users as an alternative to reading config documentation, it doesn't seem ideal to require them to find plugins (they might not even know what a plugin is).

You're right. So, IMHO, I prefer scaffolds (something like Yeoman) for new projects and/or new users.

**Comment by platinumazure** [comment]
I can certainly agree that discoverability is both (1) important, and (2) a problem with my proposal. I just don't want to get into the business of being gatekeepers for every single type of init scenario.

I'm okay with adding Typescript since its linting is actually a project some of us are trying to support. Just worried that some might see this as precedent. Maybe I'm overthinking it since I could have said the same thing about the React question and we don't get tons of requests to support other libraries in init.

**Comment by aladdin-add** [comment]
I am somewhat divergent on the issue: same reasons as @platinumazure 

we can:
+ a. supporting typescript, just like React/Vue have been supported.
+ b. pluggability. to reposition `eslint --init`, it can be used for any-level-users, not just for new ones. In this way, it can support more than React/Vue, e.g. Angular, node...(if so, we might want to move eslint-cli to another repo).

b. seems more promising!

**Comment by platinumazure** [comment]
I'm okay with adding Typescript for now. This should be a pretty simple change so I don't think an RFC is required here. I'll reopen this and add it to the TSC agenda.

**Comment by kaicataldo** [comment]
The TSC resolved this week to include a built-in TypeScript config preset and look into allowing plugins to provide additional init presets in the future.
