### ISSUE TITLE
Meta: archiving issues due to age

### ISSUE THREAD

**Issue by dandv** [eslint/eslint#11913]
Today I was reading through an issue in this repo and found someone's solution very helpful to my problem. I wanted to :+1: that answer. I couldn't, because the issue was locked to collaborators and `archived due to age`.

Later, I wanted to reply to another issue with an update. Again, I couldn't, because the issue was `archived due to age`.

I know there are reasons for that label - probably trying to avoid sending notifications to all those involved in the issue. So I'll end up creating a new issue referring to the old one, which will notify fewer people right now, but pollute the issue space, and possibly waste the time of more people in the aggregate (future users who search will find two issues etc.). Also, since the old issue is `archived due to age`, it won't record the link from the newer one. Those who land from a search on the old issue, won't see there's a newer discussion.

Just because a discussion has an arbitrary `age`, doesn't mean it's not worth discussing any more. We still discuss Socrates.

Anyway, for end-users like me, archived issue feel rather... oppressive. I want to express something, but I can't. Not trying to say that the 1st amendment would apply here or anything, but is there any chance to reconsider this policy?

Something *very* similar is in place on Reddit, and it frustrates many people:

**[Why archiving old threads is a bigger problem than we've realized](https://www.reddit.com/r/TheoryOfReddit/comments/9oujwf/why_archiving_old_threads_is_a_bigger_problem/)**

**Comment by mysticatea** [comment]
Thank you for this issue.

The reasons that we are archiving old issues are that triaging the comments of resolved issues is very tough work. (and we don't have enough time to triage.)

Because ESLint repo is received a ton of issues/comments every day and the team members are volunteers and they don't have enough time, so we have to triage problems effectively. To do so, we need enough information to investigate the reported problems. However, (1) the comments of resolved issues had often very short, (2) we cannot provide the issue template-like functionality for comments, and (3) the comments of resolved issues had often been different problems from the issues (sure, those are resolved issues). Therefore, we would like to ask to open new issues with filling our issue templates.

I agreed that it's inconvenient that GitHub doesn't show linked issues/PRs. I hope GitHub to improve that behavior :)

I'm sorry for inconvenient. But please regard that the team is using private time to maintain ESLint.

Thank you.
