### ISSUE TITLE
[Bug] No Fix for `sort-imports` ?

### ISSUE THREAD

**Issue by Industrial** [eslint/eslint#11924]
**Tell us about your environment**

* **ESLint Version:** v5.16.10
* **Node Version:** v11.13.0
* **npm Version:** v6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parser: '@typescript-eslint/parser',
  extends: [
    'plugin:react/recommended',
    // 'plugin:@typescript-eslint/recommended',
    'prettier/@typescript-eslint',
    'plugin:prettier/recommended',
  ],
  parserOptions: {
    sourceType: 'module',
    ecmaVersion: 2019,
    ecmaFeatures: {
      jsx: true,
    },
  },
  rules: {
    '@typescript-eslint/arrow-parens': [true],
    '@typescript-eslint/await-promise': [true],
    '@typescript-eslint/max-classes-per-file': false,
    '@typescript-eslint/no-console': [false],
    '@typescript-eslint/no-floating-promises': [true],
    '@typescript-eslint/object-literal-key-quotes': [false],
    '@typescript-eslint/object-literal-sort-keys': [false],
    '@typescript-eslint/ordered-imports': [false],
    '@typescript-eslint/quotemark': [true, 'single', 'avoid-escape'],
    '@typescript-eslint/semicolon': [true, 'never'],
    '@typescript-eslint/trailing-comma': [true],
    'jsx-quotes': ['error', 'prefer-single'],
    'sort-imports': [
      'error',
      {
        ignoreCase: false,
        ignoreDeclarationSort: false,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ['none', 'all', 'single', 'multiple'],
      },
    ],
  },
  settings: {
    react: {
      version: 'detect',
    },
  },
}
```

</details>

**What did you expect to happen?**
imports to be sorted with --fix

**What actually happened? Please include the actual, raw output from ESLint.**
Not that.

**Are you willing to submit a pull request to fix this bug?**
No.

**Comment by kaicataldo** [comment]
sort-imports has an autofixer, but it’s impossible for us to verify if what you’re experiencing is a bug or not without concrete reproduction steps.

**Comment by Jamesernator** [comment]
As a basic example this doesn't fix correctly:

https://eslint.org/demo/#eyJ0ZXh0IjoiaW1wb3J0IGZvbyBmcm9tICcuL2Zvby5qcydcbmltcG9ydCBiYXIgZnJvbSAnLi9iYXIuanMnXG5cbi8qIGdsb2JhbCBjb25zb2xlICovXG5cbmNvbnNvbGUubG9nKGZvbylcbmNvbnNvbGUubG9nKGJhcikiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjEwLCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImNvbnN0cnVjdG9yLXN1cGVyIjoyLCJmb3ItZGlyZWN0aW9uIjoyLCJnZXR0ZXItcmV0dXJuIjoyLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjoyLCJuby1jYXNlLWRlY2xhcmF0aW9ucyI6Miwibm8tY2xhc3MtYXNzaWduIjoyLCJuby1jb21wYXJlLW5lZy16ZXJvIjoyLCJuby1jb25kLWFzc2lnbiI6Miwibm8tY29uc3QtYXNzaWduIjoyLCJuby1jb25zdGFudC1jb25kaXRpb24iOjIsIm5vLWNvbnRyb2wtcmVnZXgiOjIsIm5vLWRlYnVnZ2VyIjoyLCJuby1kZWxldGUtdmFyIjoyLCJuby1kdXBlLWFyZ3MiOjIsIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHkiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXByb3RvdHlwZS1idWlsdGlucyI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZGVmIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2VsZXNzLWNhdGNoIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6Miwibm8td2l0aCI6MiwicmVxdWlyZS1hdG9taWMtdXBkYXRlcyI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjIsInNvcnQtaW1wb3J0cyI6Mn0sImVudiI6e319fQ==

**Comment by lydell** [comment]
As far as I know, sort-imports can only autofix member order: [playground link](https://eslint.org/demo/#eyJ0ZXh0IjoiaW1wb3J0IGZvbyBmcm9tICcuL2Zvby5qcydcbmltcG9ydCBiYXIgZnJvbSAnLi9iYXIuanMnXG5pbXBvcnQge2IsIGMsIGF9IGZyb20gJy4vYmF6LmpzJ1xuXG4vKiBnbG9iYWwgY29uc29sZSAqL1xuXG5jb25zb2xlLmxvZyhmb28pXG5jb25zb2xlLmxvZyhiYXIpIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMCwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJjb25zdHJ1Y3Rvci1zdXBlciI6MiwiZm9yLWRpcmVjdGlvbiI6MiwiZ2V0dGVyLXJldHVybiI6Miwibm8tYXN5bmMtcHJvbWlzZS1leGVjdXRvciI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNsYXNzLWFzc2lnbiI6Miwibm8tY29tcGFyZS1uZWctemVybyI6Miwibm8tY29uZC1hc3NpZ24iOjIsIm5vLWNvbnN0LWFzc2lnbiI6Miwibm8tY29uc3RhbnQtY29uZGl0aW9uIjoyLCJuby1jb250cm9sLXJlZ2V4IjoyLCJuby1kZWJ1Z2dlciI6Miwibm8tZGVsZXRlLXZhciI6Miwibm8tZHVwZS1hcmdzIjoyLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOjIsIm5vLWR1cGUta2V5cyI6Miwibm8tZHVwbGljYXRlLWNhc2UiOjIsIm5vLWVtcHR5IjoyLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOjIsIm5vLWVtcHR5LXBhdHRlcm4iOjIsIm5vLWV4LWFzc2lnbiI6Miwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjoyLCJuby1leHRyYS1zZW1pIjoyLCJuby1mYWxsdGhyb3VnaCI6Miwibm8tZnVuYy1hc3NpZ24iOjIsIm5vLWdsb2JhbC1hc3NpZ24iOjIsIm5vLWlubmVyLWRlY2xhcmF0aW9ucyI6Miwibm8taW52YWxpZC1yZWdleHAiOjIsIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjoyLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tbWl4ZWQtc3BhY2VzLWFuZC10YWJzIjoyLCJuby1uZXctc3ltYm9sIjoyLCJuby1vYmotY2FsbHMiOjIsIm5vLW9jdGFsIjoyLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOjIsIm5vLXJlZGVjbGFyZSI6Miwibm8tcmVnZXgtc3BhY2VzIjoyLCJuby1zZWxmLWFzc2lnbiI6Miwibm8tc2hhZG93LXJlc3RyaWN0ZWQtbmFtZXMiOjIsIm5vLXNwYXJzZS1hcnJheXMiOjIsIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjoyLCJuby11bmRlZiI6Miwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOjIsIm5vLXVucmVhY2hhYmxlIjoyLCJuby11bnNhZmUtZmluYWxseSI6Miwibm8tdW5zYWZlLW5lZ2F0aW9uIjoyLCJuby11bnVzZWQtbGFiZWxzIjoyLCJuby11bnVzZWQtdmFycyI6Miwibm8tdXNlbGVzcy1jYXRjaCI6Miwibm8tdXNlbGVzcy1lc2NhcGUiOjIsIm5vLXdpdGgiOjIsInJlcXVpcmUtYXRvbWljLXVwZGF0ZXMiOjIsInJlcXVpcmUteWllbGQiOjIsInVzZS1pc25hbiI6MiwidmFsaWQtdHlwZW9mIjoyLCJzb3J0LWltcG9ydHMiOjJ9LCJlbnYiOnt9fX0=)

I’m not sure if autofix of the actual import statements isn’t implemented because nobody has done it, or because it is not 100% safe. The imported modules can have toplevel side effects, and rearranging the imports will then run them in different order, which could potentially break stuff.

**Comment by platinumazure** [comment]
> The imported modules can have toplevel side effects, and rearranging the imports will then run them in different order, which could potentially break stuff.

Yes, I believe that is why we only autofix the member order. In the case of switching the imported module order, we want to give users a chance to decide if they can switch the module order (i.e., side effects are minimal/acceptable) or if they need the order to remain as it is anyway (in which case they would use eslint-disable comments).

**Comment by Industrial** [comment]
> The imported modules can have toplevel side effects, and rearranging the imports will then run them in different order, which could potentially break stuff.

That should be a code smell. An indicator for people to not write their code in this way. I don't think it should be a problem to be prevented by not implementing the sorting :S

**Comment by ljharb** [comment]
@Industrial it’s not always. Polyfills and shims are *supposed* to cause side effects and be written in that way.

However, typically the only imports with side effects are ones without a binding - just like it’s safe to reorganize properties as long as nothing crosses a spread, it’s safe to sort imports as long as nothing crosses a bindingless import.
