### ISSUE TITLE
Automatically fix strict configured as "global"

### ISSUE THREAD

**Issue by christianbundy** [eslint/eslint#12034]
**The version of ESLint you are using.** v6.1.0

**The problem you want to solve.** I want `eslint --fix` to be able to automatically add `"use strict";` at the top of modules when [strict](https://eslint.org/docs/rules/strict) is configured as `"global"`.

**Your take on the correct solution to problem.** Someone should add a fixer to the strict rule that handles the `"global"` mode.

**Are you willing to submit a pull request to implement this change?** Yes! See: https://github.com/eslint/eslint/pull/12035

**Comment by aladdin-add** [comment]
this is likely to change its behavior(we generally trying not to do such a thing), e.g:
```js
undef = void 0;
```

in strict mode, it will throw an error, since undef is not defined; in non-strict mode, it will create a global var "undef" implicitly.

I was maintaining a 3rd party plugin: [eslint-plugin-autofix](https://www.npmjs.com/package/eslint-plugin-autofix), seems it's a good idea to go there. PRs are welcome. 😄
