### ISSUE TITLE
Object Shorthand conflicts with func-names

### ISSUE THREAD

**Issue by gkatsanos** [eslint/eslint#12178]
**Tell us about your environment**
```
├─ @vue/cli-plugin-eslint@3.11.0
│  └─ eslint@4.19.1
└─ eslint@6.1.0
```
* **Node Version:** v12.6.0 
* **npm Version:** 6.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
babel
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```json
{
  "plugins": [
    "vue"
  ],
  "extends": [
    "plugin:vue/recommended",
    "airbnb-base",
    "plugin:prettier/recommended",
    "prettier/vue"
  ],
  "env": {
    "jest": true
  },
  "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": 2018
  },
  "globals": {
    "App": true
  },
  "settings": {
    "import/extensions": [
      ".vue"
    ],
    "import/resolver": {
      "node": {
        "paths": ["app/javascript"],
        "extensions": [".js", ".vue"]
      }
    }
  },
  "rules": {
    "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }],
    "no-underscore-dangle": ["error", { "allow": ["_underlying_vm_", "_componentTag"] }],
    "no-return-assign": ["error", "except-parens"],
    "no-restricted-properties": "off",
    "import/prefer-default-export": "off",
    "no-shadow": "off",
    "no-unused-expressions": "off",
    "no-param-reassign": ["error", { "props": false }],
    "quotes": ["error", "single"],
    "max-len": ["error", {
      "code": 130,
      "ignoreComments": true,
      "ignoreUrls": true
    }],
    "vue/max-attributes-per-line": [
      2,
      {
        "singleline": 20,
        "multiline": {
          "max": 1,
          "allowFirstLine": false
        }
      }
    ]
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
    '$route.query': function() {
      this.fetchData();
    },
```
```
║ 239      │ 21       │ warning  │ Unexpected unnamed method '$route.query'.              │ func-names           ║
```

```js
    '$route.query'() {
      this.fetchData();
    },
```
```

║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 239      │ 5        │ error    │ Expected longform method syntax for string literal     │ object-shorthand     ║
║          │          │          │ keys.                                                  │                      ║
```

```bash
eslint --ext .js,.vue app/javascript
```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Are you willing to submit a pull request to fix this bug?**
yes

**Comment by mdjermanovic** [comment]
It's indeed `func-names` (might have to scroll right a bit).

This should work:

```js
'$route.query': function $routeQuery() {
      this.fetchData();
    }
```

**Comment by mdjermanovic** [comment]
Sorry, I wasn't clear enough, didn't mean to say this was a bug.

It works as intended, `func-names` is configured to always require explicit function names.

This is a valid example for the given configuration:

```js
const foo = { 
  '$route.query': function $routeQuery() {
      this.fetchData();
   }
}
```

(or any other name instead of `$routeQuery`). Property name is still quoted.

**Comment by ljharb** [comment]
It looks like a bug in object-shorthand tho.

**Comment by mysticatea** [comment]
I think this is the correct behavior.

- From the error message, I guess that you are using `avoidQuotes` option of `object-shorthand`. The `object-shorthand` rule reports the property which has quoted name correctly.
- From the error message, I guess that you are using the `always` option of `func-names`. The `func-names` rule reports the anonymous function correctly.

**Comment by tacoto12** [comment]
Come on. Enough of the b.s.. 842 Lower Coalburg Rd Fultondale. Put up or shut ut


Sent from my MetroPCS 4G LTE Android Device
-------- Original message --------From: Toru Nagashima <notifications@github.com> Date: 8/29/19  3:37 AM  (GMT-06:00) To: eslint/eslint <eslint@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [eslint/eslint] Object Shorthand conflicts with func-names
  (#12178) 
I think this is the correct behavior.

From the error message, I guess that you are using avoidQuotes option of object-shorthand. The object-shorthand rule reports the property which has quoted name correctly.
From the error message, I guess that you are using the always option of func-names. The func-names rule reports the anonymous function correctly.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/eslint/eslint/issues/12178?email_source=notifications\u0026email_token=AMATDU6OTPAL4RODMVETXW3QG6DFDA5CNFSM4IRK6HW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5NW74I#issuecomment-526086129",
"url": "https://github.com/eslint/eslint/issues/12178?email_source=notifications\u0026email_token=AMATDU6OTPAL4RODMVETXW3QG6DFDA5CNFSM4IRK6HW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5NW74I#issuecomment-526086129",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ljharb** [comment]
@mysticatea are you suggesting that `avoidQuotes` should be complaining about property names that can't be unquoted?

**Comment by tacoto12** [comment]
LET'S GET IT ON!!

**Comment by mysticatea** [comment]
@ljharb No. I just talked about the current behavior.

**Comment by mdjermanovic** [comment]
The option doesn't enforce unquoted property names (this isn't the `quote-props` rule), it disallows shorthands with quoted names.

> "avoidQuotes": true indicates that long-form syntax is preferred whenever the object key is a string literal

Rules are configured to enforce this code:

```js
const foo = { 
  '$route.query': function $routeQuery() {
      this.fetchData();
   }
}
```

If you want to allow the following:

```js
const foo = { 
  '$route.query'() {
      this.fetchData();
   }
}
```

then set the `avoidQuotes` option to `false`.
