### ISSUE TITLE
Add Ethereum address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [eslint/eslint#12179]
**The version of ESLint you are using.**

NA

**The problem you want to solve.**

There is no Ethereum address to send funds to in the FUNDING.yml

**Your take on the correct solution to problem.**

I'd like to see an Ethereum address added to the `custom` property of the `FUNDING.yml` file for GitHub Sponsors. This would allow a canonical address to send funds to. For example, I'm building a project that allows developers to setup one recurring donation that is split between all of their dependencies with an Ethereum address: https://sustainus.io

**Are you willing to submit a pull request to implement this change?**

Yes, I just need to know the Ethereum address to put in

**Comment by tacoto12** [comment]
I am at my brothers.  Come get me


Sent from my MetroPCS 4G LTE Android Device
-------- Original message --------From: Jordan Last <notifications@github.com> Date: 8/29/19  3:21 AM  (GMT-06:00) To: eslint/eslint <eslint@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [eslint/eslint] Add Ethereum address to FUNDING.yml (#12179) 

The version of ESLint you are using.
NA
The problem you want to solve.
There is no Ethereum address to send funds to in the FUNDING.yml
Your take on the correct solution to problem.
I'd like to see an Ethereum address added to the custom property of the FUNDING.yml file for GitHub Sponsors. This would allow a canonical address to send funds to. For example, I'm building a project that allows developers to setup one recurring donation that is split between all of their dependencies with an Ethereum address: https://sustainus.io
Are you willing to submit a pull request to implement this change?
Yes, I just need to know the Ethereum address to put in

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/eslint/eslint/issues/12179?email_source=notifications\u0026email_token=AMATDU7JZ5WRXNYUFH2FBFLQG6BJBA5CNFSM4IR7JL6KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HIEEJ4Q",
"url": "https://github.com/eslint/eslint/issues/12179?email_source=notifications\u0026email_token=AMATDU7JZ5WRXNYUFH2FBFLQG6BJBA5CNFSM4IR7JL6KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HIEEJ4Q",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tacoto12** [comment]
Or do not fuck with me anymore 


Sent from my MetroPCS 4G LTE Android Device
-------- Original message --------From: Jordan Last <notifications@github.com> Date: 8/29/19  3:21 AM  (GMT-06:00) To: eslint/eslint <eslint@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [eslint/eslint] Add Ethereum address to FUNDING.yml (#12179) 

The version of ESLint you are using.
NA
The problem you want to solve.
There is no Ethereum address to send funds to in the FUNDING.yml
Your take on the correct solution to problem.
I'd like to see an Ethereum address added to the custom property of the FUNDING.yml file for GitHub Sponsors. This would allow a canonical address to send funds to. For example, I'm building a project that allows developers to setup one recurring donation that is split between all of their dependencies with an Ethereum address: https://sustainus.io
Are you willing to submit a pull request to implement this change?
Yes, I just need to know the Ethereum address to put in

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/eslint/eslint/issues/12179?email_source=notifications\u0026email_token=AMATDU7JZ5WRXNYUFH2FBFLQG6BJBA5CNFSM4IR7JL6KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HIEEJ4Q",
"url": "https://github.com/eslint/eslint/issues/12179?email_source=notifications\u0026email_token=AMATDU7JZ5WRXNYUFH2FBFLQG6BJBA5CNFSM4IR7JL6KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HIEEJ4Q",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kaicataldo** [comment]
Thanks for the issue. This isn't something the team would like to do at this time. Currently, our official source of funding is through Open Collective.

**Comment by lastmjs** [comment]
Sounds good
