### ISSUE TITLE
why no-global-assign doesn't work on impoart statement ?

### ISSUE THREAD

**Issue by KillianTang** [eslint/eslint#12201]
**Tell us about your environment**

* **ESLint Version:**  "eslint": "^5.13.0",
* **Node Version:**  v10.12.0
* **npm Version:**  6.4.1

**What parser (default, Babel-ESLint, etc.) are you using?**
"babel-eslint": "^10.0.1",
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  parser: 'babel-eslint',
  extends: ['airbnb', 'prettier', 'plugin:compat/recommended'],
  env: {
    browser: true,
    node: true,
    es6: true,
    mocha: true,
    jest: true,
    jasmine: true,
  },
  globals: {
    APP_TYPE: true,
    NO_CACHE: true,
    MOCK: true,
    BMap: true,
    page: true,
  },
  rules: {
    /*
            "off"或者0    //关闭规则关闭
            "warn"或者1    //在打开的规则作为警告（不影响退出代码）
            "error"或者2    //把规则作为一个错误（退出代码触发时为1）
        */
    'react/jsx-filename-extension': [1, { extensions: ['.js'] }],
    'import/no-unresolved': [2, { ignore: ['^@/', '^umi/'] }],
    'import/no-extraneous-dependencies': [
      2,
      {
        optionalDependencies: true,
        devDependencies: ['**/tests/**.js', '/mock/**.js', '**/**.test.js'],
      },
    ],
    'no-alert': 2,
    //如下新增
    'no-global-assign': 2,
    'no-param-reassign': 1, //禁止给参数重新赋值
    'react/no-multi-comp': 1,
    'no-useless-constructor': 1,
    'react/prefer-stateless-function': 1,
    'react/no-unused-state': 1,
    'no-continue': 1,
    indent: ['off', 2],
  },
  settings: {
    polyfills: ['fetch', 'promises', 'url'],
  },
  parserOptions: {
    // Parsing error: Using the export keyword between a decorator and a class is not allowed. Please use export @dec class instead.
    ecmaFeatures: {
      legacyDecorators: true,
    },
  },
};

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
import { DataView } from '@antv/data-set';
```

```bash
eslint --ext .js src mock tests
```

**What did you expect to happen?**
`Read-only global 'DataView' should not be modified.`

**What actually happened? Please include the actual, raw output from ESLint.**
no report

**Are you willing to submit a pull request to fix this bug?**
no

**Comment by KillianTang** [comment]
why I open this issue ：SonarQube report this ，and I add `no-global-assign` but no error report


![image](https://user-images.githubusercontent.com/25997259/64095031-3f26c180-cd90-11e9-9da8-fd8b42c845fe.png)


![image](https://user-images.githubusercontent.com/25997259/64095043-4cdc4700-cd90-11e9-8eb3-b5c31000c023.png)

**Comment by mysticatea** [comment]
Thank you for your issue.

Because it's a declaration, but not an assignment. The `no-global-assign` is a rule for assignments.

There are three rules around this.

- `no-global-assign` ... reports assignments of globals (e.g., `Object = 1`)
- `no-redeclare` ... reports redeclarations (e.g., `var Object = 1`)
- `no-shadow` ... reports shadowing (e.g., `function f() { var Object = 1 }`)

Then, what you want to catch is a shadowing because import declarations define variables in the module scope rather than the global scope.

```js
/*eslint no-shadow: [error, { builtinGlobals: true }] */
import { Object } from "object"
```

[Online demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tc2hhZG93OiBbZXJyb3IsIHsgYnVpbHRpbkdsb2JhbHM6IHRydWUgfV0gKi9cbmltcG9ydCB7IE9iamVjdCB9IGZyb20gXCJvYmplY3RcIlxuIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo4LCJzb3VyY2VUeXBlIjoibW9kdWxlIiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

**Comment by KillianTang** [comment]
@mysticatea   
Thanks，` no-shadow` is the answer I need
