### ISSUE TITLE
Support object distructuring in function parameters 

### ISSUE THREAD

**Issue by yuanchieh-cheng** [eslint/eslint#12253]
**What rule do you want to change?**
[prefer-destructuring](https://eslint.org/docs/rules/prefer-destructuring#prefer-destructuring-from-arrays-and-objects-prefer-destructuring)

**Does this change cause the rule to produce more or fewer warnings?**
Produce fewer warnings.

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option would be fine.

**Please provide some example code that this change will affect:**

```js
functionA({
        foo,
        bar,
} = param)
```

**What does the rule currently do for this code?**
It would show `"foo" is not defined.`

**What will the rule do after it's changed?**
The error could be disappeared.

**Are you willing to submit a pull request to implement this change?**
Yes. But I am not sure how long it would take.

**Comment by aladdin-add** [comment]
to clarify, do you mean to define a function named `functionA`? it could be:

```js
function functionA({
        foo,
        bar,
} = param){
// function body
}
```

**Comment by yuanchieh-cheng** [comment]
yes. That's what I am asking for.

**Comment by kaicataldo** [comment]
I'm a bit confused by this - `"foo" is not defined.` is the error message from the `no-undef` rule, not `prefer-destructuring`. Do you mind clarifying what the issue is? Filling out the [bug issue template](https://github.com/eslint/eslint/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md) would help us a lot here :)
