### ISSUE TITLE
max-statements ignoreTopLevelFunctions doesn't work with UMD factories

### ISSUE THREAD

**Issue by ExE-Boss** [eslint/eslint#12373]
**Tell us about your environment**

* **Node Version:** v12.10.0
* **npm Version:** v6.11.3
* **[pnpm] Version:** v3.8.1
* **Local ESLint version:** v6.5.1 (Currently used)
* **Global ESLint version:** v6.5.1 (Installed with [pnpm])

[pnpm]: https://pnpm.js.org

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```jsonc
{
	"root": true,

	"parserOptions": {
		"ecmaVersion": 3
	},

	"rules": {
		"indent": [2, "tab"],
		"max-statements": [2, 10, {
			"ignoreTopLevelFunctions": true,
		}],
		"wrap-iife": [2, "inside"],
	}
}
```

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
// Extracted from https://github.com/es-shims/es5-shim/blob/592c8f49d4d6ec0fb2f588bebdd52f6b439903e2/es5-shim.js

// UMD (Universal Module Definition)
// see https://github.com/umdjs/umd/blob/master/templates/returnExports.js
(function (/** @type {typeof globalThis} */ root, factory) {
	'use strict';

	/* global define */
	if (typeof define === 'function' && define.amd) {
		// AMD. Register as an anonymous module.
		define(factory);
	} else if (typeof exports === 'object') {
		// Node. Does not work with strict CommonJS, but
		// only CommonJS-like enviroments that support module.exports,
		// like Node.
		module.exports = factory();
	} else {
		// Browser globals (root is window)
		root.returnExports = factory();
	}
})(this, function () {
	// Shortcut to an often accessed properties, in order to avoid multiple
	// dereference that costs universally. This also holds a reference to known-good
	// functions.
	var $Array = Array;
	var ArrayPrototype = $Array.prototype;
	var $Object = Object;
	var ObjectPrototype = $Object.prototype;
	var $Function = Function;
	var FunctionPrototype = $Function.prototype;
	var $String = String;
	var StringPrototype = $String.prototype;
	var $Number = Number;
	var NumberPrototype = $Number.prototype;
	var array_slice = ArrayPrototype.slice;
	var array_splice = ArrayPrototype.splice;
	var array_push = ArrayPrototype.push;
	var array_unshift = ArrayPrototype.unshift;
	var array_concat = ArrayPrototype.concat;
	var array_join = ArrayPrototype.join;
	var call = FunctionPrototype.call;
	var apply = FunctionPrototype.apply;
	var max = Math.max;
	var min = Math.min;

	// Having a toString local variable name breaks in Opera so use to_string.
	var to_string = ObjectPrototype.toString;

	// many omitted statements…
});
```

```pwsh
pnpx eslint <path‑to‑file>
```

**What did you expect to happen?**

The file validates successfully.

**What actually happened? Please include the actual, raw output from ESLint.**

```
<absolute-path‑to‑file>
  20:9  error  Function has too many statements (21). Maximum allowed is 10  max-statements

✖ 1 problem (1 error, 0 warnings)
```

**Are you willing to submit a pull request to fix this bug?**

Unsure

**Comment by kaicataldo** [comment]
I have verified the reported behavior (see demo [here](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG1heC1zdGF0ZW1lbnRzOiBbMiwgMTAsIHsgXCJpZ25vcmVUb3BMZXZlbEZ1bmN0aW9uc1wiOiB0cnVlIH1dICovXG5cbihmdW5jdGlvbiAoLyoqIEB0eXBlIHt0eXBlb2YgZ2xvYmFsVGhpc30gKi8gcm9vdCwgZmFjdG9yeSkge1xuXHQndXNlIHN0cmljdCc7XG5cblx0LyogZ2xvYmFsIGRlZmluZSAqL1xuXHRpZiAodHlwZW9mIGRlZmluZSA9PT0gJ2Z1bmN0aW9uJyAmJiBkZWZpbmUuYW1kKSB7XG5cdFx0Ly8gQU1ELiBSZWdpc3RlciBhcyBhbiBhbm9ueW1vdXMgbW9kdWxlLlxuXHRcdGRlZmluZShmYWN0b3J5KTtcblx0fSBlbHNlIGlmICh0eXBlb2YgZXhwb3J0cyA9PT0gJ29iamVjdCcpIHtcblx0XHQvLyBOb2RlLiBEb2VzIG5vdCB3b3JrIHdpdGggc3RyaWN0IENvbW1vbkpTLCBidXRcblx0XHQvLyBvbmx5IENvbW1vbkpTLWxpa2UgZW52aXJvbWVudHMgdGhhdCBzdXBwb3J0IG1vZHVsZS5leHBvcnRzLFxuXHRcdC8vIGxpa2UgTm9kZS5cblx0XHRtb2R1bGUuZXhwb3J0cyA9IGZhY3RvcnkoKTtcblx0fSBlbHNlIHtcblx0XHQvLyBCcm93c2VyIGdsb2JhbHMgKHJvb3QgaXMgd2luZG93KVxuXHRcdHJvb3QucmV0dXJuRXhwb3J0cyA9IGZhY3RvcnkoKTtcblx0fVxufSkodGhpcywgZnVuY3Rpb24gKCkge1xuXHQvLyBTaG9ydGN1dCB0byBhbiBvZnRlbiBhY2Nlc3NlZCBwcm9wZXJ0aWVzLCBpbiBvcmRlciB0byBhdm9pZCBtdWx0aXBsZVxuXHQvLyBkZXJlZmVyZW5jZSB0aGF0IGNvc3RzIHVuaXZlcnNhbGx5LiBUaGlzIGFsc28gaG9sZHMgYSByZWZlcmVuY2UgdG8ga25vd24tZ29vZFxuXHQvLyBmdW5jdGlvbnMuXG5cdHZhciAkQXJyYXkgPSBBcnJheTtcblx0dmFyIEFycmF5UHJvdG90eXBlID0gJEFycmF5LnByb3RvdHlwZTtcblx0dmFyICRPYmplY3QgPSBPYmplY3Q7XG5cdHZhciBPYmplY3RQcm90b3R5cGUgPSAkT2JqZWN0LnByb3RvdHlwZTtcblx0dmFyICRGdW5jdGlvbiA9IEZ1bmN0aW9uO1xuXHR2YXIgRnVuY3Rpb25Qcm90b3R5cGUgPSAkRnVuY3Rpb24ucHJvdG90eXBlO1xuXHR2YXIgJFN0cmluZyA9IFN0cmluZztcblx0dmFyIFN0cmluZ1Byb3RvdHlwZSA9ICRTdHJpbmcucHJvdG90eXBlO1xuXHR2YXIgJE51bWJlciA9IE51bWJlcjtcblx0dmFyIE51bWJlclByb3RvdHlwZSA9ICROdW1iZXIucHJvdG90eXBlO1xuXHR2YXIgYXJyYXlfc2xpY2UgPSBBcnJheVByb3RvdHlwZS5zbGljZTtcblx0dmFyIGFycmF5X3NwbGljZSA9IEFycmF5UHJvdG90eXBlLnNwbGljZTtcblx0dmFyIGFycmF5X3B1c2ggPSBBcnJheVByb3RvdHlwZS5wdXNoO1xuXHR2YXIgYXJyYXlfdW5zaGlmdCA9IEFycmF5UHJvdG90eXBlLnVuc2hpZnQ7XG5cdHZhciBhcnJheV9jb25jYXQgPSBBcnJheVByb3RvdHlwZS5jb25jYXQ7XG5cdHZhciBhcnJheV9qb2luID0gQXJyYXlQcm90b3R5cGUuam9pbjtcblx0dmFyIGNhbGwgPSBGdW5jdGlvblByb3RvdHlwZS5jYWxsO1xuXHR2YXIgYXBwbHkgPSBGdW5jdGlvblByb3RvdHlwZS5hcHBseTtcblx0dmFyIG1heCA9IE1hdGgubWF4O1xuXHR2YXIgbWluID0gTWF0aC5taW47XG5cblx0Ly8gSGF2aW5nIGEgdG9TdHJpbmcgbG9jYWwgdmFyaWFibGUgbmFtZSBicmVha3MgaW4gT3BlcmEgc28gdXNlIHRvX3N0cmluZy5cblx0dmFyIHRvX3N0cmluZyA9IE9iamVjdFByb3RvdHlwZS50b1N0cmluZztcblxuXHQvLyBtYW55IG9taXR0ZWQgc3RhdGVtZW50c+KAplxufSk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)). This looks like it's behaving as intended, since the function that is generating the error is the module function (second argument to the top level function).

I don't think this a bug, and any changes we make should be considered an enhancement (and probably behind an option). I do think it's worthwhile to discuss this, though! What kind of heuristics could we use to determine if the function causing the error is the body of a UMD module? Or would it be good enough to ignore functions that are also arguments of the top level function/IIFE?

**Comment by ExE-Boss** [comment]
> Or would it be good enough to ignore functions that are also arguments of the top level function/IIFE?

That sounds like the best option to me.
