### ISSUE TITLE
Plugins fail to load when eslint is installed globally

### ISSUE THREAD

**Issue by tlvince** [eslint/eslint#1238]
I've authored a plugin [eslint-no-exclusive-tests](https://github.com/tlvince/eslint-no-exclusive-tests) that warns if certain Jasmine methods are used (`ddescribe, iit` etc.)

When eslint is installed globally (as normal), a module loader error is thrown:

``` shell
❯ eslint spec.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'eslint-plugin-no-exclusive-tests'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:122:26
    at Array.forEach (native)
    at loadPlugins (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:115:21)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:151:9)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:222:30
    at walk (/usr/local/lib/node_modules/eslint/lib/util/traverse.js:82:9)
```

As the [docs](http://eslint.org/docs/developer-guide/working-with-plugins.html) say to add eslint as a peerDependency, it gets installed locally to the project. If using the local eslint, the plugin runs as expected:

``` shell
❯ ./node_modules/.bin/eslint spec.js

spec.js
   3:0   error  Unexpected ddescribe                       no-exclusive-tests/no-exclusive-tests
```

`package.json`:

``` json
...
  "devDependencies": {
    "eslint": "^0.8.0",
    "eslint-plugin-no-exclusive-tests": "^0.2.0"
...
```

`.eslintrc`

``` yaml
plugins:
  - no-exclusive-tests
rules:
  no-exclusive-tests/no-exclusive-tests: 2
```

**Comment by huangyingjie** [comment]
Hi all,
   I ran into this issue on vim with 'syntastic'. Since I have to use local eslint, the following is my vim config:
```vim
let local_eslint = finddir('node_modules', '.;') . '/.bin/eslint'
if matchstr(local_eslint, "^\/\\w") == ''
    let local_eslint = getcwd() . "/" . local_eslint
endif
if executable(local_eslint)
    let g:syntastic_javascript_eslint_exec = local_eslint
endif
```
Now the effect between vim and 'npm run eslint' is exactly the same.

**Comment by moander** [comment]
Why is this issue closed? To call this fixed because the `npm run` workaround is documented is absurd. Node is all about simplicity, and lint is about deploying coding standards across teams, so this should in my eyes be considered a major bug..  :-1:

**Comment by lo1tuma** [comment]
> lint is about deploying coding standards across teams

This would be pretty hard if you have to tell everyone to install eslint globally in a specific version.

**Comment by moander** [comment]
Having eslint installed is just as easy as having npm or gulp installed.. But would you maintain all your gulp and grunt plugins globally too? The logic comes from project-defined plugins and configuration. The correct eslint is shipped as a devdep anyway, and npm scripts or a build server or whatever takes care of the final validation.. But in the meantime your IDE continues to work unless there are some breaking changes in the main binary, but that argument is like saying npm should stop providing local packages because node may ship a breaking change in the future.

**Comment by lo1tuma** [comment]
Sorry, I can’t follow your argumentation. What is the problem you are trying to solve and why do you think a globally installed eslint version should work with locally installed plugins?

**Comment by moander** [comment]
The globally installed eslint could just check for a lockally installed version of it self..

**Comment by mysticatea** [comment]
Can this help you?
I made a tool that runs the local eslint merely.
https://www.npmjs.com/package/eslint-cli

**Comment by moander** [comment]
Unfortunately no. I have no idea how to make my IDEs use a different command for eslint.

For the command line I solved it temporarily by adding ./node_modules/.bin to $PATH :)

**Comment by mysticatea** [comment]
@moander This tool doesn't need a different command.

**Comment by moander** [comment]
I know, but it still requires you to control the PATH of your third party programs. Your solution is perfect if it's implemented in the original eslint binary.

**Comment by lo1tuma** [comment]
@moander maybe you should file an issue on the issue tracker of your IDE to support locally installed eslint versions. Having global dependencies is a bad practice IMHO, you should always prefer to keep dependencies local.

**Comment by moander** [comment]
The issue here is clearly not the IDEs fault. The problem is related to eslint's no-local-plugins feature.

**Comment by lo1tuma** [comment]
Now we are talking about two different things.

1. Global eslint should work with local plugins
2. Global eslint should run a local eslint

----

1. Is not a good idea because you don’t know if the locally installed plugin is compatible with the globally installed eslint version. Apart from that you could also have conflicts if you have a plugin installed locally and globally but in different versions.
2. I don’t think it is worth to add this complexity to eslint, adding `./node_modules/.bin` to the `PATH` or using `npm run-script` are good solutions.

**Comment by moander** [comment]
1. The global eslint should check if a local eslint exists, and if yes use it. So all local plugins will work as long as they are compatible with the locally installed eslint.
2. It's dead simple. What's complex is to NOT support locals. Look at eslint-cli from @mysticatea

**Comment by ilyavolodin** [comment]
@moander ESLint supports local plugins perfectly fine. You just need to install and run ESLint locally to use them. Based on your comments, it seems that you are unaware of that feature.

**Comment by moander** [comment]
I can run global gulp from path using local modules. I can not run global eslint from path using local modules. Eslint claims to focus on extensibility, so loading extensions  should be a priority. To discuss if this is an issue or not for a tool like this is absurd, so this is my last comment.

**Comment by dmcaodha** [comment]
I agree with @moander here, It seems illogical to install a plugin globally. There is no sense in that. I have lost half a day to this, trying to find out that I need to use an __npm run__ workaround in order to get eslint to work. It is unintuitive.

**Comment by chevex** [comment]
Chiming in to add my support for having global eslint prefer to run locally installed eslint if found. Would have saved me several hours of hunting around. It never once crossed my mind that I should install plugins globally.

@huangyingjie You are amazing. Your little script has fixed my issues in Vim. Other IDEs aren't so flexible though and can't really toggle between using global and local eslint without it being changed manually each time.

It would really help if eslint just did the legwork of checking for a local eslint and running it instead if found. It already respects the local .eslintrc file so it seems rather intuitive to me that it should just run the local eslint to automatically ensure that the .eslintrc and related plugins are running under the correct eslint version. As it stands, each project I pull down at the office that uses a new eslint plugin that I don't have forces me to manually go over the list and install each one globally. Rather cumbersome in my opinion when the global eslint could just be a little helpful and run the local one.

**Comment by machineghost** [comment]
This seems like a classic "philosophical purity" vs. "trying to get work done" debate.  For what it's worth, I'd like to put in a vote for taking Gulp's lead and prioritizing practicality over purity, but it's your library and I know all too well how important ideological lines in the sand are to us programmers ;-)

However, there is a middle ground: you could at least break purity enough to *check* for a local version of the plug-in, and if it exists provide a message to the effect of:

>When installed globally ESLint (by design, due to the wishes of its authors) will not use the locally installed _____ plug-in.  Please install that plug-in globally if you'd like to use it with the global ESLint install."

It seems to me like doing that would eliminate the real-world "why the heck is this library complaining about something I already have installed!?!?" pain, while still maintaining the ideological purity of the local/global divide.

At the very least it would have saved me twenty minutes of Googling to figure out what was going on.  Just a thought.

**Comment by machineghost** [comment]
P.S. ESlint is awesome, and has already saved me many multiples of the time I spent Googling this problem.  Thanks for writing it!

**Comment by rstacruz** [comment]
> This is behaving as expected. If you install ESLint globally, then you must install your plugin globally as well.

Unfortunately this isn't the case.

```sh
$ npm install -g eslint eslint-{plugin,config}-standard
$ echo '{ "extends": ["standard"] }' > .eslintrc
$ eslint index.js
  /usr/local/lib/node_modules/eslint/lib/config.js:171
                    throw e;
                    ^

  Error: Cannot find module 'eslint-config-standard'
  Referenced from: /Users/rsc/Projects/hello/.eslintrc
```

**Comment by ustun** [comment]
As far as I know, webpack does exactly that: delegate to the local webpack in case a local webpack is found. Having to run local eslint from node_modules/.bin is problematic since I might be inside a particular directory and I should not be constantly thinking of giving the path to that. Having it in package.json as a script is also inconvenient.

**Comment by contra** [comment]
gulp, webpack, grunt, etc. all follow the same pattern: global cli invokes the local module version and local plugins. There is no such thing as a global install or global plugins, installing plugins globally makes no sense.

Invoking the locally installed versions is more pure and more practical.

**Comment by mysticatea** [comment]
I'd like to recommend https://www.npmjs.com/package/eslint-cli

**Comment by es6Test** [comment]
Just trying this for the first time and would like eslint to check for local versions 1st.

**Comment by suewonjp** [comment]
I'm against the idea of global cli/global plugins. **We use plugins to solve local problems or per project basis problems.** If two projects sitting in my dev. machine use two different versions of the same plugin , global/global approach might fail.

So that leaves us global/local or local/local approach.  

Local/local approach sounds good and safe and a lot reasonable. That should become standard. **Encouraging standard approach is good, however, enforcing it is another story.**

Well, Local/local approach mostly sounds inconvenient in the context of using IDEs or editors. Most of us want quick feedback, so integrating eslint to IDEs or editors has a lot of benefits. So we customize IDEs to integrate it. However, will most people welcome the idea of having to reconfigure their IDEs or whatever tools whenever they switch project? Some IDEs provide per project configuration, but not all. Some tools are not quite flexible to configure and often our organization or team forces to use certain IDEs or tools, which might be against the idea of "Everything should sit in local"

People are usually stuck with some strange situations, which are often quite against standard thinking... 

While sticking to local/local idea as a default standard approach for eslint, but providing global/local solution will be quite generous and absolutely beneficial for certain users.

**Comment by bfred-it** [comment]
Side note: eslint-based [xo](https://github.com/sindresorhus/xo#usage) has this behavior exactly:

> Note that the CLI will use your local install of XO when available, even when run globally.

It's not about global/local, it's about being able to run `eslint` from the cli of any project and have it work correctly **for that project.**

At best, the current setup is **inconsistent** since `eslint` follows the rules of the current project but looks for global plugins. Either the global `eslint` follows global config only, or it follows the full local/hierarchical configuration.

**Comment by platinumazure** [comment]
> Either the global eslint follows global config only, or it follows the full local/hierarchical configuration.

What would it even mean to follow "global config only" from inside a project? What constitutes "global config" in that case? Home directory config only? Anything outside the project directory? (Should ESLint be expected to know the project root directory?) And how would this behavior be anything but surprising to end users, when there are configuration files they configured next to (or in close ancestor directories to) the files they want to lint?

I'm interested in seeing if we could have global ESLint try to find a local install if possible, but there are a lot of use cases to think through with regard to plugin and shared config resolution, and this is not as trivial a topic as you might think.

**Comment by msartintarm** [comment]
I agree that global ESlint + local 'plugins' makes sense, the current 'global + global' implementation does not. There is a simple use case which applies to the project I'm working on. Let's say we are using a package from NPM like our own package, or eslint-config-airbnb.

the-project/.eslintrc.json: 
`{ "extends": "eslint-config-project" }`

the-project/node_modules/eslint-config-project/index.js: 
`module.exports = { "rules": { "no-console": 2 } }`

A local copy of eslint runs just fine with 'npm run eslint'. However, any editor designed to leverage the project-level .eslintrc (any editor with ESlint integration), and which tries and uses a global instance of eslint, fails. For instance, here's the error when I use emacs:

    Error: Cannot find module 'eslint-config-project'
    Referenced from: /Users/msartint/the-project/.eslintrc.json
        at Object.resolve (/usr/local/lib/node_modules/eslint/lib/util/module-resolver.js:74:19)
        at resolve (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:478:33)

I think expecting all our IDEs to recognize this use case, or for us to somehow override its PATH, is too much to ask. It seems pretty simple for ESlint to detect this really: the local install with plugins is in the same directory as the root project-level .eslintrc file. What can be simpler than that?

**Comment by schmod** [comment]
Chiming in to say that eslint is pretty much the only widely-used tool in the JS ecosystem that behaves this way.  It's unintuitive and the workaround is not difficult.

**Comment by nzakas** [comment]
Sorry everyone, this issue is closed. We have tried solving this problem in the past and its far more complicated than it seems. If you think you have a solution, please submit a pull request so we can review it. I'm locking this issue now because we are not planning on looking this any further (note the issue is two years old).
