### ISSUE TITLE
[no-extra-parens] Allow an exception for (new X()).y

### ISSUE THREAD

**Issue by domenic** [eslint/eslint#12428]
**What rule do you want to change?** no-extra-parens

**Does this change cause the rule to produce more or fewer warnings?** Fewer, if configured

**How will the change be implemented? (New option, new default behavior, etc.)?** New option, similar to the existing ones like returnAssign, nestedBinaryExpressions, etc.

**Please provide some example code that this change will affect:**

```js
const doc = (new JSDOM()).window.document;

const { document } = (new JSDOM(`<!doctype html><html><head></head><body>
  <div></div><div title=""></div><div title="yes"></div>
</body></html>`)).window;
```

**What does the rule currently do for this code?**

It requires removing the parens, i.e. that I write

```js
const doc = new JSDOM().window.document;

const { document } = new JSDOM(`<!doctype html><html><head></head><body>
  <div></div><div title=""></div><div title="yes"></div>
</body></html>`).window;
```

This is equivalent, but *it feels really weird*. Although the `new` operator binds more closely than the `.` operator in JS, this is a somewhat-surprising feature of JS, as `.` otherwise binds very high, and most space-separated operators bind quite low.

**What will the rule do after it's changed?**

Allow the above code, when a new option is configured, e.g.`"newExpressions": false`.

**Are you willing to submit a pull request to implement this change?**

Yes, although a community volunteer would be much appreciated.

**Other note**

This changed in v6.5.0 as part of https://github.com/eslint/eslint/pull/12302.

**Comment by nzakas** [comment]
Thanks for reaching out. It does seem like we should have added an option for backwards compatibility when this rule was changed.

**Comment by mdjermanovic** [comment]
I'm willing to champion and work on this.

**Comment by kaicataldo** [comment]
This has now been accepted.

**Comment by mdjermanovic** [comment]
Just to confirm the details of this enhancement, if I understand correctly the following should be done.

The option applies only to the change made in v6.5.0 (part of #12302):

```js
(new X()).y;

(new X())[y];
```

Other cases of unnecessary parens around `new X()` that were warnings in previous versions will remain warnings, regardless of how the option is set. For example:

```js
y = (new X());

f((new X()), y);

(new X())();

new (new X())();
```

The name of the option could be `enforceForNewInMemberExpressions` ?

Since it's default behavior in the actual version, the default value is `true`:

```js
/* eslint no-extra-parens: "error" */

(new X()).y; // error

(new X())[y]; // error

y = (new X()); // error

f((new X()), y); // error

(new X())(); // error

new (new X())(); // error
```

When the option is explicitly set to `false`, `(new X()).y` and `(new X())[y]` are allowed:

```js
/* eslint no-extra-parens: ["error", "all", { "enforceForNewInMemberExpressions": false }] */

(new X()).y; // ok

(new X())[y]; // ok

y = (new X()); // error

f((new X()), y); // error

(new X())(); // error

new (new X())(); // error
```

**Comment by mysticatea** [comment]
I have removed `accepted` label because there are three upvotes but there is a downvote from the team. This enhancement is a mixed reception and needs consensus.

My stance is neutral. It's hard for me to agree with the motivation to add the option because recent languages have the same precedence. But I know C++ is different.

**Comment by platinumazure** [comment]
@mysticatea Michael is no longer on the team (see README). So his downvote is a community opinion, no more.

Would you like to :-1: this issue?

**Comment by mysticatea** [comment]
Ah, [Alumni](https://eslint.org/team#alumni) isn't counted as the team's votes? In that case, I'm OK with accepted.

**Comment by domenic** [comment]
> Just to confirm the details of this enhancement, if I understand correctly the following should be done.

This makes sense to me. I think it's a reasonable question what the default should be (and thus what the name would be) but I'll leave this to the ESLint team.
