### ISSUE TITLE
[no-tabs] allow exceptions

### ISSUE THREAD

**Issue by ab-pm** [eslint/eslint#12438]
**What rule do you want to change?**

`no-tabs` (currently on eslint 6.5.1)

**Does this change cause the rule to produce more or fewer warnings?**

fewer warnings

**How will the change be implemented?**

New option.

**Please provide some example code that this change will affect:**

```js
if (inTabIndentedCode) {
⇥	// if (commented) {
⇥	// ⇥	codeInBlocks();
⇥	// }
⇥	hasProblems();
}
```
```js
const also = some`
⇥	string⇥	${literals}
⇥	use⇥	${tabulators}
`;
```

```js
… // rules:
	'indent': ['error', 'tab'],
	'no-tabs': ['error', { 'allowIndentationTabs': true }],
```

**What does the rule currently do for this code?**

It complains about `Unexpected tab character` inside the commented-out code and in the string string literal, which is too strict imo.

**What will the rule do after it's changed?**

I would propose to add some configuration options that either
* could allow lines matching a certain regex
* could allow lines in a certain AST context, e.g. string literals or comments

so that the rule would accept above code examples but still complain about tabulator characters elsewhere.

**Comment by platinumazure** [comment]
Hi @ab-pm, thanks for this issue.

Have you looked at the [`indent` rule](https://eslint.org/docs/rules/indent)? That should allow you to enforce spaces for indentation and is probably what you need.

I agree this rule is pretty strict, but before we enhance it, I just want to see if `indent` gives you what you need.

**Comment by ab-pm** [comment]
@platinumazure Yes, I am using the `indent` rule, and prefer tabs for indentation - that's why they are still to be found in the commented-out code.

What do you think should an extra option look like that is easy to use and still flexible? Something like `allowIndentationTabsInCommentedCode` and `allowTabsInTemplateStrings`?

**Comment by kaicataldo** [comment]
Is there a reason you want to enable `no-tabs` if you want to allow tabs in strings and comments?

**Comment by kaicataldo** [comment]
Understood, thank you. I think it would make sense to make the configuration option also accept an object with the following signature:

```ts
{
    allowIndentationTabs?: boolean,
    allowInComments?: boolean,
    allowInStrings?: boolean,
}
```
Thoughts?

**Comment by jesus2099** [comment]
I second this request (so it does not expire like the older ones) as I also use tabs for indenting and I don't want no-tabs to error or warn on commented-out lines of code (tab indented).
I still want to use no-tabs to warn me about tabs used for anything else than indenting.

**Comment by DarrenCook** [comment]
Can I suggest it follows the same syntax as https://eslint.org/docs/rules/no-irregular-whitespace#skipcomments

I already have this config:

```
    "no-irregular-whitespace": [
      "error",
      {
        "skipStrings": true,
        "skipTemplates": true,
        "skipRegExps": true,
        "skipComments": true
      }
    ],
```

In fact I was quite surprised when that didn't already cover tabs in comments.

I did try:

```
    "no-tabs": [
      "error",
      {
        "skipStrings": true,
        "skipTemplates": true,
        "skipRegExps": true,
        "skipComments": true
      }
    ],
```

and it has worked! But I guess all I've really done is turn off no-tabs for the whole codebase. Which I definitely don't want to do.

**Comment by mdjermanovic** [comment]
Closing per our [rules policies](https://github.com/eslint/eslint#stylistic-rule-updates).

**Comment by jesus2099** [comment]
So, @mdjermanovic, this eslint tool is also really that much anti-tabs?
When using tabs for indentation, it's normal to comment lines out with `//` preceeding tabs.
So we need the `allowInComments` for sure!

Someone took the time and effort to fix that with PR #16224 but it was closed by you. :-C

**Comment by jesus2099** [comment]
Hi @jblandry #11562, @jahorwitz #11563, @ab-pm #12438, @domnantas #12999, did you understand how to achieve what we want or **does eslint officially sucks?**

I saw several tickets like this closed because [they don't want to improve eslint](https://github.com/eslint/eslint#stylistic-rule-updates).
So eslint seems maintained by tab indentation haters who don't want to allow both styles being handled properly.

Is there a _custom rule_ (if such thing exists) that we could install?
Have you found an eslint fork for people who indent with tabs?
Is there any clever solution for tabs?

**Comment by domnantas** [comment]
Still deal with this, just ignore it now, but it is quite annoying.
<img width="664" alt="image" src="https://user-images.githubusercontent.com/51953549/195694060-b06aa71e-2542-4b0d-85b1-511dddf3b13c.png">

The solution proposed in https://github.com/eslint/eslint/pull/16224 adds 4 options, which is a bit excessive.

I don't think Eslint is dead, nor do the maintainers hate tabs. Eslint is a massive project, and sometimes you have to prioritize essential issues. @nzakas explained the reason for this policy very clearly [in this blog post](https://eslint.org/blog/2020/05/changes-to-rules-policies/)

This issue suggests adding a configuration option for `no-tabs` rule, which would be considered a **Minor** change and it goes against **No new options for stylistic rules**. My suggestion – this should be considered a bug and tabs in comments should always be ignored. Since the fix would reduce the number of errors ESLint reports, it could be released as a **Patch**. PR for this should be definitely made by the community, not core team members.
