### ISSUE TITLE
Detect file in merge conflict

### ISSUE THREAD

**Issue by s-mage** [eslint/eslint#12500]
**The version of ESLint you are using.**
5.16.0

**The problem you want to solve.**
Detect when it's a file in merge conflict and show corresponding error instead of syntax error.
<img width="996" alt="Screenshot 2019-10-28 at 14 27 19" src="https://user-images.githubusercontent.com/2388396/67696627-80f67180-f9a7-11e9-8a18-340ff29fe65f.png">

**Your take on the correct solution to problem.**

Here is what [vetur](https://github.com/vuejs/vetur) does:

<img width="576" alt="Screenshot 2019-10-28 at 14 23 43" src="https://user-images.githubusercontent.com/2388396/67696664-8eabf700-f9a7-11e9-9b3c-a2e8d8c6c57b.png">

**Are you willing to submit a pull request to implement this change?**
I have no previous experience on eslint codebase. I can try, but can't promise anything

**Comment by kaicataldo** [comment]
This sounds useful to me, however I don't think it's a good match for core. ESLint's default parser won't be able to parse this by default, since it's not valid JavaScript syntax. However, this could probably be done with a [processor](https://eslint.org/docs/developer-guide/working-with-plugins#processors-in-plugins) and a corresponding custom rule.
