### ISSUE TITLE
Rules engine?

### ISSUE THREAD

**Issue by piranna** [eslint/eslint#12585]
Is there a packet with just only the rules engine to be used on third party projects as a dependency? I'm thinking about creating a projects linter (not only code, but also files structure a projects best practices), and although I could disable eslintrc file and all rules and provide the ones I like as arguments, I ser It mostly as a hack and superfluos.

**Comment by ilyavolodin** [comment]
You can use (Node API)[https://eslint.org/docs/developer-guide/nodejs-api#linter] directly and supply your own config to it. It will skip resolving configs from file system.

**Comment by piranna** [comment]
> You can use [Node API](https://eslint.org/docs/developer-guide/nodejs-api#linter) directly and supply your own config to it. It will skip resolving configs from file system.

That was my idea (that, or wrap `eslint` cli passing it some arguments), but my question was more related about don't need to download `espree` parser and other javascript specific dependencies if I'm not going to need them. Is that an option?

**Comment by g-plane** [comment]
ESLint can't run without those dependencies, so it's impossible that you don't download them.

**Comment by piranna** [comment]
> ESLint can't run without those dependencies, so it's impossible that you don't download them.

I know :-D But they are only needed for the Javascript parsing, I think they are not needed for the rules engine, that's why I ask if it's available as a standalone package. Maybe would it need to be split out? :-)

**Comment by g-plane** [comment]
> But they are only needed for the Javascript parsing

This is wrong, so you can't run ESLint without any dependencies.

**Comment by ilyavolodin** [comment]
@piranna At some point in the past there was talk about splitting ESLint into generic linter/rules engine, but there wasn't a lot of movement done on that part. As it is currently, it would be a major undertaking to do so and we currently don't have any plans for it.

**Comment by piranna** [comment]
Ok, thank you. Where should I look to move this forward?

**Comment by ilyavolodin** [comment]
This would be a major change, so it would require a very large, well thought-out RFC (https://github.com/eslint/rfcs) that would have to go through the normal approval process. Because the change would be very large (basically it would require breaking up ESLint into a bunch of separate packages) I would not expect this process to move quickly (just a heads-up, don't want to scare you off, but wanted to set up correct expectations). In terms of finding conversations we had about this, I think @nzakas proposed it a very long time ago, in a ticket that collected proposals for a long-term vision of ESLint. If I remember correctly, it was sometime after we release ESLint v2.0.0, so you will have to search through some very old threads.

**Comment by kaicataldo** [comment]
I think this would be a really interesting thing to explore, as I could see it improving the experience for custom parsers (Babel, TypeScript) significantly, since we could separate out all the language-specific functionality into separate packages.

**Comment by piranna** [comment]
If it's of your interest, I've developed my own rules engine at https://github.com/projectlint/rules-engine. Promises based, generic purposse, configurable behaviour, and plan to add soon multi-level rules resolution :-)
