### ISSUE TITLE
Support .eslintrc.cjs and .eslintrc.mjs file

### ISSUE THREAD

**Issue by xiaoxiangmoe** [eslint/eslint#12593]
node 13.2 has been released with .mjs support without flag: https://github.com/nodejs/node/releases/tag/v13.2.0

Can we use `.eslintrc.cjs` and `.eslintrc.mjs` as config file?

**Comment by kaicataldo** [comment]
Please track https://github.com/eslint/rfcs/pull/43.

**Comment by TrejGun** [comment]
@kaicataldo 
RFC was merged a week ago
will you accept PR for mjs/cjs configs?

**Comment by kaicataldo** [comment]
@TrejGun Please track https://github.com/eslint/eslint/pull/12321. Note that we can't support `.mjs` configuration files yet due to ESLint currently being synchronous in nature. There's another [RFC](https://github.com/eslint/rfcs/pull/40) that is trying to solve that blocker so that we can eventually support ESM configuration files and plugins.

**Comment by rulatir** [comment]
Does any workaround exist currently? Is it anyhow possible to use typescript+eslint in a typescript project configured to both produce and consume ESM, or should I "vintagegrade" back to TSLint for that?
