### ISSUE TITLE
Add `ConfigArrayFactory` and `CascadingConfigArrayFactory` to the public API

### ISSUE THREAD

**Issue by manuth** [eslint/eslint#12631]
In some cases people might want to know which config-files are used for running `eslint` and whether a `package.json` even contains `eslint`-settings.

While it's easily possible to write such a functionality on one's own it's pretty much butthurt to maintain this coad oneself while `eslint` already has such a feature built-in.

It would be awesome if you could export `ConfigArrayFactory` and `CascadingConfigArrayFactory` to the export of `api.js` or add `getConfigArrayForFile` and `getCascadingConfigArrayForFile` to `CLIEngine` publicly.

**Comment by platinumazure** [comment]
Hi @manuth, thanks for the issue.

We have to consider all public API decisions carefully, because when we add something to the public API, then it can no longer be changed except in major version releases (and even then, only if absolutely necessary). These are not decisions we can take likely.

Could you please be more specific about exactly what problem you are trying to solve? Maybe there is another API already that does what you need. Or, if there isn't, maybe it would make more sense to add APIs somewhere else, such as `CLIEngine`. So, if you can share the specific problem you're trying to solve, we can think about the best approach.

**Comment by manuth** [comment]
Hello @platinumazure 
Thank you for your rapid answer!
So currently I'm writing a language-service plugin for TypeScript. Therefore I want to know several things in order to lint the files correctly:

1. Which files should I watch for changes to reload the `eslint`-configuration?  
    My plugin will automatically trigger a lint as soon as a configuration-file has changed.
2. Which folder do I have to open in order to lint the file correctly?  
    I assume I have to open either the file at the highest level in the directory-tree or the file which has `root` set to `true`, right? So I also need to know which directory's the root for linting files correctly.

What do you think would be the best way to get these features?

**Comment by kaicataldo** [comment]
We ask that all changes to core go through the RFC process outlined [here](https://github.com/eslint/rfcs/). Would you like to create an RFC for this feature?

**Comment by manuth** [comment]
@kaicataldo I'm still waiting for some team-member to tell me what's the best way to reach the goals I stated before.

Can I create an RFC without knowing about that or should I rather wait for some more comments on this issue?

**Comment by manuth** [comment]
Alright, so I created a new PR now: https://github.com/eslint/rfcs/pull/52

**Comment by kaicataldo** [comment]
@manuth Sorry, missed your reply. The RFC process is in place for exactly those kinds of conversations, so thanks for creating the RFC.
