### ISSUE TITLE
"Configured parser was not found" when using Linter API

### ISSUE THREAD

**Issue by iansan5653** [eslint/eslint#12689]
I'm attempting to run ESLint from the API to automatically lint some files. First, I get the local configuration with the `CLIEngine` using `getConfigForFile`. Then, I load the file text and run `Linter.verify(fileText, configuration, filePath)`. This seems to work great, however, when I check the output messages, this is what I see:
```
[
  {
    ruleId: null,
    fatal: true,
    severity: 2,
    message: "Configured parser 'C:\\Users\\iansanders\\Documents\\new-aui\\new-aui\\frontend\\node_modules\\@typescript-eslint\\parser\\dist\\parser.js' was not found.",
    line: 0,
    column: 0
  }
]
```

However, I know for certain that the parser file exists at this path. Am I doing something wrong, or is this a bug?

**Comment by kaicataldo** [comment]
Can you provide some more details so that we can help you debug this? 

1. Node version
2. npm/yarn version
3. ESLint version
4. Configuration file location and relevant contents
5. How you're running this script

Thanks!

**Comment by iansan5653** [comment]
Sure:

1. Node version v12.13.1
2. npm version 6.12.1
3. ESLint 6.7.2
4. Configuration file is located in the parent above where the script is running. It has `"parser": "@typescript-eslint/parser",` set.
5. The script is a TS file I am running with ts-node. It fetches the configuration like so:
```ts
 const linterConfig = new CLIEngine({useEslintrc: true}).getConfigForFile(
    targetFile
  );
```
The error occurs for both `verify` and `verifyAndFix`.

**Comment by mysticatea** [comment]
The `Linter` class doesn't load packages dynamically because the class is intended to work on browsers. You need to add the parser implementation with `linter.defineParser()` method.

And... if you are using ESLint on Node.js, you should use `CLIEngine` class rather than `Linter` class. The `Linter` class doesn't support several important features intentionally in order to work on browsers. I guess that `engine.executeOnFiles()` or `engine.executeOnText()` methods are good for you.
