### ISSUE TITLE
Allow "reportUnusedDisableDirectives" option to "error"

### ISSUE THREAD

**Issue by obweger** [eslint/eslint#12703]
**The version of ESLint you are using.**

6.8.0

**The problem you want to solve.**

I'd like to prevent (i.e., error on) unused directives via my configuration (rather than the CLI). 

**Your take on the correct solution to problem.**

I can error on unused directives via `--report-unused-disable-directives`. However, for errors to be shown in the IDE, it would be easier to allow the `reportUnusedDisableDirectives` configuration option to be set to `error`. Currently, it can only be set to `true`, which translates to `warn`.

**Are you willing to submit a pull request to implement this change?**

Yes.

**Comment by kaicataldo** [comment]
I understand why this would be useful. The current design is intentional, however. If we allowed for errors to be reported with `reportUnusedDisableDirectives`, we would limit what kind of changes we could publish in a semver-patch release (since fixing a bug that would result in fewer errors could create additional unused disable directives). You can find more information in the original RFC [here](https://github.com/eslint/rfcs/tree/master/designs/2019-core-options#-reportunuseddisabledirectives).

**Comment by obweger** [comment]
Right, thanks for the context. I wonder if we can make this a consumer choice (we would obviously have to be very explicit about this in the docs); in our case, it would be perfectly fine to fix all unused directives whenever we upgrade eslint or a plugin, especially if the unused directives would be fixable (see https://github.com/eslint/eslint/issues/11815).

**Comment by platinumazure** [comment]
Hi @obweger. Just as a note, if you haven't configured any rules to warn, you could use `--max-warnings 0` to ensure that ESLint terminates with a failure status code if unused disable directive warnings are generated in your lint run.

**Comment by kaicataldo** [comment]
There is precedence for a feature that comes with an explicit “use at your own risk because this feature can’t follow semver and may break your build” warning label in the [`eslint:all`](https://eslint.org/docs/user-guide/configuring#using-eslint-all) built in config.

**Comment by obweger** [comment]
@platinumazure 👍thanks for that! I think we can work around it with the `--report-unused-disable-directives` option, I got this to work also in the IDE. I'm happy for this issue to be closed, however _in general_ I think it would be good to have this available through the regular config!

**Comment by NickHeiner** [comment]
I would also like the option to have `reportUnusedDisableDirectives` be an error-level option when passed as config. My context:

1. I'm perfectly happy to fix errors caused by non-semver-major changes if it means that my `disable` directives were erroneous.
1. I can't enable `--max-warnings 0` because my project currently has hundreds of warnings across 11k+ files.
1. I can't use the CLI option `--report-unused-disable-directives` because of the various programmatic means (including the Jest runner) by which ESLint.
