### ISSUE TITLE
Assignment exception to no-multi-spaces

### ISSUE THREAD

**Issue by paulschreiber** [eslint/eslint#12910]
**What rule do you want to change?**
`no-multi-spaces`

**Does this change cause the rule to produce more or fewer warnings?**
Fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**
Add a new exception, `VariableAssignment`. (Analogous to `VariableDeclarator`.)

**Please provide some example code that this change will affect:**

```js
bob      = 1;
sue      = 2;
angelica = 3;
```

**What does the rule currently do for this code?**
Removes the spaces.

**What will the rule do after it's changed?**
Leave the spaces as-is.

**Are you willing to submit a pull request to implement this change?**
If necessary. It's probably better for someone else to do this.

**Comment by mdjermanovic** [comment]
Hi @paulschreiber, thanks for the issue!

We don't manually add new exceptions, this works by itself based on AST node types as defined by [ESTree](https://github.com/estree/estree).

As you can see in this [ASTExplorer snippet](https://astexplorer.net/#/gist/04b634658560f341c1024e3e7c09ade6/ff15b46d9110b22e05f991715cc9e00ad417e518) when you click on any of those spaces, they belong to `AssignmentExpression` nodes, so the exception to allow them is `"AssignmentExpression"`.

```js
/* eslint no-multi-spaces: ["error", { exceptions: { "AssignmentExpression": true } }] */

bob      = 1;
sue      = 2;
angelica = 3;
```

[ESLint Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLW11bHRpLXNwYWNlczogW1wiZXJyb3JcIiwgeyBleGNlcHRpb25zOiB7IFwiQXNzaWdubWVudEV4cHJlc3Npb25cIjogdHJ1ZSB9IH1dICovXG5cbmJvYiAgICAgID0gMTtcbnN1ZSAgICAgID0gMjtcbmFuZ2VsaWNhID0gMzsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjUsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

**Comment by paulschreiber** [comment]
@mdjermanovic Should https://eslint.org/docs/rules/no-multi-spaces be updated to listed `AssignmentExpression`?

I think the problem I'm seeing is specific to `.jsx` files. I've filed #12918.

**Comment by kaicataldo** [comment]
@paulschreiber We could update the docs to list `AssignmentExpression`, but since the [`exceptions`](https://eslint.org/docs/rules/no-multi-spaces#exceptions) option can accept all ESTree node types specified by ESTree, I'm not sure it adds much value (since someone else might want to use this option with a different node type).

PRs to make documentation clearer are always welcome, though!

**Comment by paulschreiber** [comment]
Is there a human-readable list of exceptions (with descriptions/examples)? I assumed the list on the page was canonical.

**Comment by kaicataldo** [comment]
I think [the recommendation in the docs](https://eslint.org/docs/rules/no-multi-spaces#exceptions) is the best way to figure out which node types represent what syntax:

> This option is an object that expects property names to be AST node types as defined by ESTree. The easiest way to determine the node types for exceptions is to use AST Explorer with the espree parser.

Have you tried that yet?

I agree it would be a nice thing to help folks gain some more context around the AST format we use (since it's new territory for most people!), but I'm not aware of a better way than looking at the [ESTree spec](https://github.com/estree/estree) and playing around with [AST Explorer](https://astexplorer.net/).

**Comment by paulschreiber** [comment]
I think looking at the spec/playing around with the explorer is asking too much of people, both in terms of time/effort and skill level. It would be good for the documentation to list more examples.

**Comment by kaicataldo** [comment]
Agreed that configuration by AST node type has overhead, and I would love to figure out a more intuitive way to achieve this. Very much open to suggestions, as the team hasn't found a better solution to this.

Regarding this specific case, we can definitely improve the examples, but I don't think it's reasonable to list every node type for all of the ECMAScript spec as defined by ESTree. I also don't think this would be particularly helpful, because it would be a giant list.

I think it could be useful to think about creating additional documentation (outside of the context of this rule) that better illustrates node types and what syntax they represent.
