### ISSUE TITLE
[padding-line-between-statements] add option for statements containing yield 

### ISSUE THREAD

**Issue by backbone87** [eslint/eslint#12942]
**What rule do you want to change?**
`padding-line-between-statements`

**Does this change cause the rule to produce more or fewer warnings?**
More warnings, if option enabled/configured.

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option value for STATEMENT_TYPE: `yield` or `contains-yield` since yield is an expression.

**Please provide some example code that this change will affect:**
```js
function*() {
  const a = 5;
  yield a; // control padding lines around this statement
}

function*() {
  const a = 5;
  const b = yield a; // control padding lines around this statement
}
```

**What does the rule currently do for this code?**
Nothing

**What will the rule do after it's changed?**
Apply padding line rules to statements containing a yield keyword.

**Are you willing to submit a pull request to implement this change?**
Probably wont have the time to get myself familar with the codebase/parsers.

**Comment by kaicataldo** [comment]
The first example is currently covered by the `"expression"` option because `yield a;` is an `ExpressionStatement` node, and the latter is currently covered under the `"const"` option.

Changing the rule to check for if a statement contains a specific keyword (`await` also comes to mind) seems like it could be useful, though I'm a little apprehensive of adding an option like this because it could make an already complex rule significantly more complex.

**Comment by backbone87** [comment]
expression and const are too broad. My goal is to force line paddings around all statements that yield control to the caller (return throw yield) and loop jumps (break continue). Basically everything that influences “normal“ top-down control flow
