### ISSUE TITLE
prefer-const fails to recognize circular dependencies

### ISSUE THREAD

**Issue by RubenVerborgh** [eslint/eslint#12989]
**Tell us about your environment**

Node version: v12.14.0
npm version: v6.13.4
Local ESLint version: v6.8.0 (Currently used)
Global ESLint version: Not found

**What parser (default, Babel-ESLint, etc.) are you using?**

babel-eslint

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  parser: 'babel-eslint',
  rules: {
    prefer-const: 'error',
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
let a;
const b = () => a;
a = { b };
```

```bash
eslint test.js
```

**What did you expect to happen?**

The code validates.

**What actually happened? Please include the actual, raw output from ESLint.**

```
test.js
  1:5  error  'a' is never reassigned. Use 'const' instead  prefer-const

✖ 1 problem (1 error, 0 warnings)
```

Note that `a` cannot be `const`, because it can not be defined at that point given the circular dependency on `b`.

**Are you willing to submit a pull request to fix this bug?**

I would, but I expect this to be very tricky and I have no prior experience with the code.

**Comment by mdjermanovic** [comment]
Hi @RubenVerborgh, thanks for the issue!

I believe the rule works as intended because you can rewrite the example to:

```js
const b = () => a;
const a = { b };
```

If you don't want to reference a variable which declaration appears later in the code, there's [ignoreReadBeforeAssign](https://eslint.org/docs/rules/prefer-const#ignorereadbeforeassign) option:

```js
/*eslint prefer-const: ["error", { "ignoreReadBeforeAssign": true }]*/

let a;
const b = () => a;
a = { b };
```

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgcHJlZmVyLWNvbnN0OiBbXCJlcnJvclwiLCB7IFwiaWdub3JlUmVhZEJlZm9yZUFzc2lnblwiOiB0cnVlIH1dKi9cblxubGV0IGE7XG5jb25zdCBiID0gKCkgPT4gYTtcbmEgPSB7IGIgfTsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

**Comment by RubenVerborgh** [comment]
Thanks, indeed; I had missed that option indeed.
