### ISSUE TITLE
Dead link in rules list

### ISSUE THREAD

**Issue by crystalfp** [eslint/eslint#12996]
On [rules page](https://eslint.org/docs/rules/) the link to [no-useless-backreference](https://eslint.org/docs/rules/no-useless-backreference) rule is dead.

**Comment by mdjermanovic** [comment]
Sorry about that! We should fix the prerelease script. 

That rule will be available in `v7.0.0` and indeed shouldn't appear on the rules page at this moment.

Documentation for this and other rules that have been added in prerelease versions is currently available here:

* https://eslint.org/docs/7.0.0/rules/no-useless-backreference
* https://eslint.org/docs/7.0.0/rules/default-case-last
* https://eslint.org/docs/7.0.0/rules/no-restricted-exports

You can also install `v7.0.0-alpha.2`  and try out these rules: 

`npm i eslint@next --save-dev`

I'm closing this since there's already an open issue to fix this bug: eslint/website#688
