### ISSUE TITLE
Enhancement: Allow a watch or incremental lint mode

### ISSUE THREAD

**Issue by mika76** [eslint/eslint#13000]
This is more of an enhancement and not a bug report, but it's also not a new rule so was not sure of which template to use...

This references issue https://github.com/microsoft/vscode-eslint/issues/91# where people have been asking for a way to lint the whole workspace of a project. It seems the main problem is that a missing feature in eslint is holding this base - an incremental lint or watch type feature - which would help with linting and reporting issues incrementally, since linting a whole project on every change is not feasible.

Is this something the eslint project would consider?

**Comment by kaicataldo** [comment]
I'm not sure I understand the underlying problem outlined in this issue. I have a few questions:

1. Do you mind explaining how a watcher would solve the above problem? 
1. What roadblocks have you faced when trying to implement this with the current Node API? 

Having a filewatcher that calls ESLint on individual files as they are changed should currently be feasible (ESLint also allows for caching results to speed up subsequent runs).

**Comment by 7rulnik** [comment]
Maybe eslint cache could help here? So only the first run will be expensive

**Comment by dbaeumer** [comment]
To my understanding ESLint itself is not a single file linter anymore. It does lint dependencies which results in the fact that changes to a file provide.js/ts results in errors come or go in use.js/ts (for example a symbol is now exported or not exported). This results in the fact that users want to see these errors come and go. However an outside tool can only always validate all files since it has no knowledge about the dependencies between files. There might be a third file that when provide.js/ts changes doesn't need to be validated.

A common approach compilers take is that they provider a watch / incremental mode to onyl revalidate the files that actually need to be validated.

**Comment by kaicataldo** [comment]
@dbaeumer ESLint currently only runs on single files. There are a few plugins that check extraneous files that can affect linting results, such as `eslint-plugin-import` and `@typescript-eslint`’s underlying `tsc` run. Even if we implemented a watcher, ESLint in its current iteration would unfortunately still has no knowledge of what files to watch for these integrations.

**Comment by kaicataldo** [comment]
As a follow up: it doesn’t mean it can’t be done, but would be a broader effort because it would involve adding additional APIs. I still think it might be easier/simpler to use a third party wrapper that is configured to watch whatever files the code author deems necessary.

**Comment by dbaeumer** [comment]
@kaicataldo thanks for your quick response. 

From my experience plugins that check there imports are getting more and more popular. 

Are you suggesting that this is handled by the corresponding plugin then. An outside tool has even less knowledge. And maintaining a dependency tree from the outside is not very attractive either.

**Comment by kaicataldo** [comment]
> Are you suggesting that this is handled by the corresponding plugin then.

That's right. I agree that cross-file linting could be useful, but this is a larger problem to solve that would require an [RFC](https://github.com/eslint/rfcs).

Since experimental syntax and TypeScript are not supported directly by core (which is another discussion and something I hope we can improve), there's a lot of complexity around adding this functionality to core in its current iteration. There are also additional layers of complexity for common use cases, such as Webpack aliases, that would probably need to support to make this useful.
