### ISSUE TITLE
Autofix with padded blocks breaks code formatting

### ISSUE THREAD

**Issue by julekgwa** [eslint/eslint#13038]
**Tell us about your environment**

* **ESLint Version:** v6.8.0
* **Node Version:** v10.19.0
* **npm Version:** v6.13.4

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
{
  "parserOptions": {
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "node": true,
    "es6": true
  },
  "extends": [
    "eslint:recommended"
  ],
  "rules": {
    "padded-blocks": ["error", "always"]
  }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**
ran ```npx create-react-app test-eslint```,  added a new file ```src/Test.js```  with the following code.

```js
class Test extends Component {
  render() {
    return (
      <h1>Test</h1>
    )
  }
}
```

```bash
eslint --fix src/Test.js
```

**What did you expect to happen?**
```js
class Test extends Component {

  render() {

    return (
      <h1>Test</h1>
    )
    
  }

}
```

**What actually happened? Please include the actual, raw output from ESLint.**
eslint added blank lines and broke the formatting of the code

```js
class Test extends Component {

  render() {

    return (
      <h1>Test</h1>
    )
  
}

}
```

**Are you willing to submit a pull request to fix this bug?** No

**Comment by mdjermanovic** [comment]
Hi @julekgwa, thanks for the issue!

Rules usually don't aim to preserve formatting from other rules.

In this case, it's assumed that the `indent` rule will fix the code in the next iteration.

The following input:

```js
/* eslint padded-blocks: ["error", "always"] */
/* eslint indent: ["error", 2] */

class Test extends Component {
  render() {
    return (
      <h1>Test</h1>
    )
  }
}
```

will be auto-fixed to:

```js
/* eslint padded-blocks: ["error", "always"] */
/* eslint indent: ["error", 2] */

class Test extends Component {

  render() {

    return (
      <h1>Test</h1>
    )
  
  }

}
```

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHBhZGRlZC1ibG9ja3M6IFtcImVycm9yXCIsIFwiYWx3YXlzXCJdICovXG4vKiBlc2xpbnQgaW5kZW50OiBbXCJlcnJvclwiLCAyXSAqL1xuXG5jbGFzcyBUZXN0IGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiAoXG4gICAgICA8aDE+VGVzdDwvaDE+XG4gICAgKVxuICB9XG59Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7ImpzeCI6dHJ1ZX19LCJydWxlcyI6e30sImVudiI6e319fQ==)

So, I don't think this is a bug.

That being said, maybe we could change this auto-fix to insert a newline after the previous token, instead of right before the `}` token. That would be how `padding-line-between-statements` works.

Thoughts from the team?

**Comment by julekgwa** [comment]
@mdjermanovic Thanks, this solves the issue.

**Comment by kaicataldo** [comment]
Closing this issue since the question has been answered.
