### ISSUE TITLE
add variable ignore list for `block-scoped-var`

### ISSUE THREAD

**Issue by bcko** [eslint/eslint#13241]
**The version of ESLint you are using.**
v6.8.0

**The problem you want to solve.**
`block-scoped-var` does not offer a progressive path to enable this rule.
Therefore, users have to fix all existing violations in order to enable this rule. 
For a large pre-ECMAScript 2015 codebase, it is quite difficult to fix all existing violations and enable this rule all at once.

**Your take on the correct solution to problem.**
Similar to `no-unused-vars`, have an option to add variables to ignore. By doing this way, 
- we don't make any breaking changes. (not providing variable ignore list will still work as intended) 
- we allow users to enable this rule immediately 

**Are you willing to submit a pull request to implement this change?**
Yes

**Comment by anikethsaha** [comment]
Not sure whether having a option will help you completely or not cause as you mentioned the codebase is large so you still need to do a search of variables and need to add them in the list unless you have some pattern already existed.
 
I think disabling might help more.

**Comment by bcko** [comment]
@anikethsaha thank you for your comment. I agree that there are many cases having variable ignore list won't help much.
For my company's case, having variable ignore list helps greatly.
My team evaluated `block-scoped-var` and wants to immediately enable this rule so that new code follows this rule. Existing violations + false positives (pre-webpack era module loading in the front-end) sum up to a very large number. They are not so easy to fix all at once. Especially fixing false positives needs to introduce new dependencies (ex. webpack) and new architecture. It would be great to enable and benefit from `block-scoped-var` immediately with variable ignore list and address issues one by one. 
Other rules such as `no-unused-vars` https://eslint.org/docs/rules/no-unused-vars allows ignore list, it was so great to immediately enable the rule with some ignore list and address the existing issues one by one.

**Comment by anikethsaha** [comment]
I don't have any strong opinion for any of the cases as to have it or not. 

lets see what others think.

**Comment by bcko** [comment]
> I don't have any strong opinion for any of the cases as to have it or not.
> 
> lets see what others think.

sounds good. Thank you!

**Comment by yeonjuan** [comment]
Hi @bcko :)
> For a large pre-ECMAScript 2015 codebase, it is quite difficult to fix all existing violations and enable this rule all at once.

If it is the reason for the proposal, what about [setting error level](https://eslint.org/docs/user-guide/configuring#configuring-rules) with `warn` or using [eslint-disable comment](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments)?

**Comment by bcko** [comment]
Hi @yeonjuan  Thank you for your comment. 

My team considered setting error level & using disable comment. However, decided against these alternatives due to below conditions.
- When eslint rule `block-scoped-var` is applied, the codebase emits a lot of false positives (thousands) due to the way the front-end handles modules (the front-end code needs to adopt module bundler such as Webpack to fix this issue)
- The company's CI/CD machine depends on error level.

Therefore, setting error level to `warn` would cause both CI/CD machine (no exit code) and humans (too many false positives) to miss new code that doesn't follow `block-scoped-var` ESLint rule.  

Adding variable ignore list would greatly help my company while not breaking anything to people who are already using this rule. If the ESLint community decides it is ok to add variable ignore list as a configuration option to `block-scoped-var`. I would be more than happy to open a pull request to address this issue. Thank you!

**Comment by kaicataldo** [comment]
I don't think a whitelist makes sense for this rule, since there isn't necessarily a pattern/convention for the variable declarations that are checked by this rule - they can really be named anything. I also don't think a whitelist is going to help you very much, because a whitelisted variable name won't warn in the event a new variable is added that shares the same variable name. This would mean that new errors could be introduced while you're in the process of cleaning up old ones.
My recommendation would be to either:

1. Enable this globally and disable the rule for every offending file (this could fairly easily be automated if you have a lot of files) using an `/* eslint-disable block-scoped-var */` at the top of the file. Over time, you can remove the disable comments and fix up the files.

2. Using [glob-based configuration](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns), you can start enabling the rule on smaller groups of files and increase the coverage over time.
