### ISSUE TITLE
TypeScript Reactjs: Assignment to property of function parameter 'state'

### ISSUE THREAD

**Issue by sptGabriel** [eslint/eslint#13253]
Hello I have a problem in my estlint:

Assignment to property of function parameter 'state'. eslintno-param-reassign

on this code:

state.sideisOpen = action.payload;

interface SideBar {
  sideisOpen: boolean;
}

const INITIAL_STATE: SideBar = {
  sideisOpen: true,
};

const sideBar = createSlice({
  name: 'toggleSide',
  initialState: INITIAL_STATE,
  reducers: {
    toggleSide: (state, action: PayloadAction<boolean>) => {
      state.sideisOpen = action.payload;
    },
  },
});

export const { toggleSide } = sideBar.actions;
export { sideBar };

**Comment by anikethsaha** [comment]
> toggleSide: (state, action: PayloadAction) => {
state.sideisOpen = action.payload;
},

I think it is because of ^ these

can you share your eslint config ?

make sure [props](https://eslint.org/docs/rules/no-param-reassign#props) option is not set to `true`

_Also, make sure you are using [`typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint) 's parser and plugins/rules as your code is in Typescript._

**Comment by sptGabriel** [comment]
> > toggleSide: (estado, ação: PayloadAction) => { 
> > state.sideisOpen = action.payload; 
> > }
> 
> Eu acho que é por causa desses ^
> 
> você pode compartilhar sua configuração eslint?
> 
> verifique se a opção [props](https://eslint.org/docs/rules/no-param-reassign#props) não está definida como`true`
> 
> _Além disso, verifique se você está usando [`typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint)o analisador e plugins / regras, pois seu código está no TypeScript._

hii
i have this code : 

// .eslintrc
{
  "plugins": ["prettier", "@typescript-eslint"],
  "extends": ["airbnb-typescript", "react-app", "prettier"],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "settings": {
    "import/resolver": {
      "typescript": {
        "alwaysTryTypes": true
      }
    }
  },
  "rules": {
    "indent": "off",
    "@typescript-eslint/indent": ["off"],
    "quotes": [
      2,
      "single",
      {
        "avoidEscape": true
      }
    ],
    "object-curly-spacing": ["warn", "always"],
    "no-unused-vars": [
      "warn",
      {
        "vars": "all",
        "args": "none"
      }
    ],
    "@typescript-eslint/no-unused-vars": [
      "warn",
      {
        "vars": "all",
        "args": "none"
      }
    ],
    "@typescript-eslint/no-explicit-any": [
      "error",
      {
        "ignoreRestArgs": true
      }
    ],
    "max-len": [
      "warn",
      {
        "code": 80,
        "ignoreStrings": false,
        "ignoreTemplateLiterals": false,
        "ignoreComments": true
      }
    ],
    "no-plusplus": [
      "error",
      {
        "allowForLoopAfterthoughts": true
      }
    ],
    "react/jsx-key": "error",
    "import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": [
          "**/*.test.js",
          "**/*.test.jsx",
          "**/*.test.ts",
          "**/*.test.tsx",
          "src/tests/**/*"
        ]
      }
    ],
    "react/jsx-props-no-spreading": "off",
    "import/prefer-default-export": "off",
    "react/jsx-boolean-value": "off",
    "react/prop-types": "off",
    "react/no-unescaped-entities": "off",
    "react/jsx-one-expression-per-line": "off",
    "react/jsx-wrap-multilines": "off",
    "react/destructuring-assignment": "off"
  }
}

**Comment by anikethsaha** [comment]
the code which I am suspecting is lint free for js . so I think this rule is working as expected 👍 

[demo](https://eslint.org/demo#eyJ0ZXh0IjoiY29uc3QgIHJlZHVjZXJzID0ge1xudG9nZ2xlU2lkZTogKHN0YXRlLCBhY3Rpb24pID0+IHtcbnN0YXRlLnNpZGVpc09wZW4gPSBhY3Rpb24ucGF5bG9hZDtcbn1cbn0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im5vLXBhcmFtLXJlYXNzaWduIjoyfSwiZW52Ijp7fX19)

I think this might be because of interface properties. not sure cause  !

Also, i guess, this rule has to be written for TS specific use-case in `typescript-eslint` in order to fix this cause as per eslint's core rules , it is lint-free and working as expected. 

let me know if I am missed something,
