### ISSUE TITLE
Support Specifying Ignore Patterns For consistent-return

### ISSUE THREAD

**Issue by ChayimFriedman2** [eslint/eslint#13281]
**What rule do you want to change?**
consistent-return

**Does this change cause the rule to produce more or fewer warnings?**
Fewer.

**How will the change be implemented? (New option, new default behavior, etc.)?**
New option,

**Please provide some example code that this change will affect:**
```js
const app = express();
app.get('/', function(req, res, next)) {
  fs.readFile('/path', function(err, data)) {
    if (err) {
      return next(err);
    }

    console.log(data);
    res.end();
  });
});
```

**What does the rule currently do for this code?**
When set, this rule warns about inconsistent returns. Of course this is the desired behavior, but since this is a common pattern in Express, I'd like to tell ESLint to not warn about the form `return next(...);`

**What will the rule do after it's changed?**
The default behavior will not be changed, but will be an additional option named, say, `ignore-pattern` all code matches this pattern will be ignored. We already have similar concepts in other rules.

**Are you willing to submit a pull request to implement this change?**
Yes.

**Comment by kaicataldo** [comment]
How would you design the API for `ignorePattern`?

Also, is there a reason you don't want to follow the rule here (note that the following code was modified to remove a few extra parentheses in the original example, as they are syntax errors)?

```js
const app = express();
app.get('/', function(req, res, next) {
  fs.readFile('/path', function(err, data) {
    if (err) {
      return next(err);
    }

    console.log(data);
    res.end();
    
    return undefined;
  });
});
```
You can see this in action using our [demo](https://eslint.org/demo#eyJ0ZXh0IjoiY29uc3QgYXBwID0gZXhwcmVzcygpO1xuYXBwLmdldCgnLycsIGZ1bmN0aW9uKHJlcSwgcmVzLCBuZXh0KSB7XG4gIGZzLnJlYWRGaWxlKCcvcGF0aCcsIGZ1bmN0aW9uKGVyciwgZGF0YSkge1xuICAgIGlmIChlcnIpIHtcbiAgICAgIHJldHVybiBuZXh0KGVycik7XG4gICAgfVxuXG4gICAgY29uc29sZS5sb2coZGF0YSk7XG4gICAgcmVzLmVuZCgpO1xuICAgIFxuICAgIHJldHVybiB1bmRlZmluZWQ7XG4gIH0pO1xufSk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJjb25zaXN0ZW50LXJldHVybiI6Mn0sImVudiI6e319fQ==). If this undesirable, it seems like a better option to just turn off the rule, since the purpose of the rule is to avoid implicitly returning `undefined` accidentally.

**Comment by anikethsaha** [comment]
I do think that even a ignore pattern won't help here much.

I agree this is a typical express like design pattern, I think a custom rule would be best here or turning the rule off as eslint doesn't cover individual frameworks.
