### ISSUE TITLE
Quick Fix: fix all auto-fixable problems  in vscode will remove unused function parameter

### ISSUE THREAD

**Issue by JonathonChen** [eslint/eslint#13297]
before quick fix:
```javascript
  reEditInputOnchange(row, fields, index, value) {
    row.matchAmount = value;
    this.moneyInput[index] && this.moneyInput[index].validate();
    this.handleUpdateRecordsData(row, index);
  }
```
using fix all auto-fixable problems
![image](https://user-images.githubusercontent.com/20022758/81893863-20482280-95e1-11ea-8ca1-b025d6c47e12.png)
![image](https://user-images.githubusercontent.com/20022758/81893885-2f2ed500-95e1-11ea-9902-7243e7b70ecd.png)

after quick fix:

```javascript
  reEditInputOnchange(row, index, value) {
    row.matchAmount = value;
    this.moneyInput[index] && this.moneyInput[index].validate();
    this.handleUpdateRecordsData(row, index);
  }

```
problem: function parameters order changed  causing function doesn't effect what it should be.

**Comment by anikethsaha** [comment]
This is an expected behavior. 
use [after-used for args](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tdW51c2VkLXZhcnM6IFtcImVycm9yXCIsIHsgXCJhcmdzXCI6IFwiYWZ0ZXItdXNlZFwiIH1dKi9cbmZ1bmN0aW9uICByZUVkaXRJbnB1dE9uY2hhbmdlKHJvdywgZmllbGRzLCBpbmRleCwgdmFsdWUpIHtcbiAgICByb3cubWF0Y2hBbW91bnQgPSB2YWx1ZTtcbiAgICB0aGlzLm1vbmV5SW5wdXRbaW5kZXhdICYmIHRoaXMubW9uZXlJbnB1dFtpbmRleF0udmFsaWRhdGUoKTtcbiAgICB0aGlzLmhhbmRsZVVwZGF0ZVJlY29yZHNEYXRhKHJvdywgaW5kZXgpO1xuICB9XG5cbnJlRWRpdElucHV0T25jaGFuZ2UoKSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby11bnVzZWQtdmFycyI6Mn0sImVudiI6e319fQ==) or [none](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tdW51c2VkLXZhcnM6IFtcImVycm9yXCIsIHsgXCJhcmdzXCI6IFwibm9uZVwiIH1dKi9cbmZ1bmN0aW9uICByZUVkaXRJbnB1dE9uY2hhbmdlKHJvdywgZmllbGRzLCBpbmRleCwgdmFsdWUpIHtcbiAgICByb3cubWF0Y2hBbW91bnQgPSB2YWx1ZTtcbiAgICB0aGlzLm1vbmV5SW5wdXRbaW5kZXhdICYmIHRoaXMubW9uZXlJbnB1dFtpbmRleF0udmFsaWRhdGUoKTtcbiAgICB0aGlzLmhhbmRsZVVwZGF0ZVJlY29yZHNEYXRhKHJvdywgaW5kZXgpO1xuICB9XG5cbnJlRWRpdElucHV0T25jaGFuZ2UoKSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby11bnVzZWQtdmFycyI6Mn0sImVudiI6e319fQ==)

**Comment by JonathonChen** [comment]
> This is an expected behavior.
> use [after-used for args](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tdW51c2VkLXZhcnM6IFtcImVycm9yXCIsIHsgXCJhcmdzXCI6IFwiYWZ0ZXItdXNlZFwiIH1dKi9cbmZ1bmN0aW9uICByZUVkaXRJbnB1dE9uY2hhbmdlKHJvdywgZmllbGRzLCBpbmRleCwgdmFsdWUpIHtcbiAgICByb3cubWF0Y2hBbW91bnQgPSB2YWx1ZTtcbiAgICB0aGlzLm1vbmV5SW5wdXRbaW5kZXhdICYmIHRoaXMubW9uZXlJbnB1dFtpbmRleF0udmFsaWRhdGUoKTtcbiAgICB0aGlzLmhhbmRsZVVwZGF0ZVJlY29yZHNEYXRhKHJvdywgaW5kZXgpO1xuICB9XG5cbnJlRWRpdElucHV0T25jaGFuZ2UoKSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby11bnVzZWQtdmFycyI6Mn0sImVudiI6e319fQ==) or [none](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tdW51c2VkLXZhcnM6IFtcImVycm9yXCIsIHsgXCJhcmdzXCI6IFwibm9uZVwiIH1dKi9cbmZ1bmN0aW9uICByZUVkaXRJbnB1dE9uY2hhbmdlKHJvdywgZmllbGRzLCBpbmRleCwgdmFsdWUpIHtcbiAgICByb3cubWF0Y2hBbW91bnQgPSB2YWx1ZTtcbiAgICB0aGlzLm1vbmV5SW5wdXRbaW5kZXhdICYmIHRoaXMubW9uZXlJbnB1dFtpbmRleF0udmFsaWRhdGUoKTtcbiAgICB0aGlzLmhhbmRsZVVwZGF0ZVJlY29yZHNEYXRhKHJvdywgaW5kZXgpO1xuICB9XG5cbnJlRWRpdElucHV0T25jaGFuZ2UoKSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby11bnVzZWQtdmFycyI6Mn0sImVudiI6e319fQ==)

Thx, but my expectation is fixing all fixable problems without causing bugs, especially when I got a old project and want to add eslint.
I can add this rule in the eslintrc, but I also want new code can use this rule.

**Comment by anikethsaha** [comment]
> ```js
>  reEditInputOnchange(row, fields, index, value) {
>     row.matchAmount = value;
>     this.moneyInput[index] && this.moneyInput[index].validate();
>     this.handleUpdateRecordsData(row, index);
>   }
> ```

can you share your eslint config. cause this is a [valid code with default rule's config](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgbm8tdW51c2VkLXZhcnM6IFtcImVycm9yXCJdKi9cbiAgZnVuY3Rpb24gcmVFZGl0SW5wdXRPbmNoYW5nZShyb3csIGZpZWxkcywgaW5kZXgsIHZhbHVlKSB7XG4gICAgcm93Lm1hdGNoQW1vdW50ID0gdmFsdWU7XG4gICAgdGhpcy5tb25leUlucHV0W2luZGV4XSAmJiB0aGlzLm1vbmV5SW5wdXRbaW5kZXhdLnZhbGlkYXRlKCk7XG4gICAgdGhpcy5oYW5kbGVVcGRhdGVSZWNvcmRzRGF0YShyb3csIGluZGV4KTtcbiAgfVxuXG5yZUVkaXRJbnB1dE9uY2hhbmdlKCkiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjUsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsibm8tdW51c2VkLXZhcnMiOjJ9LCJlbnYiOnt9fX0=)

the image which you share is about different rule not about `no-unused-vars`

**Comment by JonathonChen** [comment]
I tried again just now and it didn't happen again...so weird...
