### ISSUE TITLE
ESLint v7.0.0 Release Postmortem

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#13291]
# ESLint v7.0.0 Release Postmortem

@eslint/eslint-team Hi everyone!

Thank you for all the hard work on ESLint v7.0.0! Now that we have completed the release process, I thought it would be beneficial to have a postmortem to discuss things we thought went well and to figure out where we can improve for future major releases.

Some initial thoughts from me:

## Wins

1. Everyone on the team pitched in and shouldered some of the burden for this release.
1. Communication improved over the course of the release and this led to more effective collaboration, particularly in the last month or so. I particularly want to thank @mysticatea, who took the ESLint API PR I started across the finish line when I was sick last month.

## Things we can improve

1. This release took a really long time and, with our current process, regular releases were blocked while we were in the prerelease stage. This means that our last regular release was on December 20, 2019, and that a lot of non-breaking changes were held up (or only available in an experimental release). Additionally, it’s not clear how we would respond to a high priority security vulnerability in the previous major release line during this process. Can we figure out a process that allows us to continue regular releases while working on the next major release? I would also like to advocate for a process where we limit the changes in a major release to breaking changes only, which would have the side benefit of an easier migration path for consumers and end users.
1. I don’t think we had a clear idea of the scope of the changes in the release when we started the prereleases. I would like to advocate for scoping the changes and freezing the feature list before we start the release process. In the past, we’ve also waited until we had a number of breaking change PRs implemented and ready for review when we started the prerelease process, which we didn’t follow this time around.
1. I think it could be beneficial to have a major release playbook where we document our process for future releases.

---

Thanks again to everyone for all your hard work, and looking forward to this discussion!

**Comment by nzakas** [comment]
Can someone put together a rough timeline of when prereleases started and then why they were started? I wasn’t actively involved during that period of time so a little context would be helpful.

One problem is that the feature set wasn’t locked down until a couple months of prereleases were done (again, having a timeline would be beneficial for this analysis).

Another problem I noticed is that there were several unaccepted/unfinished RFCs on the candidate list, meaning that we would need to bake in time for finishing the RFCs and then implementing them, pushing out the timeline.

I also think we should take into account that several team members left in January, so there was a bit of a transition period that probably slowed things down.

**Comment by mysticatea** [comment]
> Can someone put together a rough timeline of when prereleases started and then why they were started?

- [2019-10-10 meeting](https://github.com/eslint/tsc-meetings/blob/master/notes/2019/2019-10-10.md#eslint-v7-schedule) ... v7 schedule was proposed.
- 2019-11-28 ... all RFCs of v7 had been present.
- [2019-12-05 meeting](https://github.com/eslint/tsc-meetings/blob/master/notes/2019/2019-12-05.md#when-to-start-merging-eslint-v7-breaking-changes) ... tweaked due to 4-week releases.
- 2019-12-21 ... v6.8.0 released.

(After that, I had personal troubles and lost room in mind for OSS activity until 2020-02.)
(Looks no TSC meetings in this duration.)
(There was reorganizing the team.)

- [2020-02-13 meeting](https://github.com/eslint/tsc-meetings/blob/master/notes/2020/2020-02-13.md) ... feature freeze.
- 2020-02-20 ... all PRs of breaking changes had been present.

(Some team members had met with misfortune.)

- 2020-04-25 ... RC released
- 2020-05-09 ... released

**Comment by kaicataldo** [comment]
@mysticatea @btmills @mdjermanovic @yeonjuan Would love to hear from you all as well! I should have mentioned this above, but in case this has seemed like a daunting task, we should follow a [blameless portmortem](https://www.atlassian.com/incident-management/postmortem/blameless) process, which is characterized by the following:

> In a blameless postmortem, it’s assumed that every team and employee acted with the best intentions based on the information they had at the time. Instead of identifying—and punishing—whoever screwed up, blameless postmortems focus on improving performance moving forward.

**Comment by btmills** [comment]
Thanks @mysticatea for the timeline. I took those dates and went through the [v7 PRs](https://github.com/eslint/eslint/projects/6) looking at when they were ready. Echoing much of what has already been written here, I think the delay was attributable to the intersection and cascade of a few factors:

- Our release infrastructure currently only works from a single branch.
- As a consequence of that, once we start pre-releases, we're unable to continue the stable release sequence.
- Further, we can't merge breaking changes until we're ready to start pre-releases.
- We're reluctant to start implementing large changes early that would then sit un-merged waiting to begin pre-releases.
- In the past, we've been fine implementing large changes during the pre-release cycle because it only took on the order of weeks.
- This time, however, team reshuffling, illness, and unavailability for a host of other excellent reasons introduced delays in implementing some of the large changes.

**Comment by nzakas** [comment]
Closing due to no further action needed here. The release process has evolved and v8 went very smoothly.
