### ISSUE TITLE
Local Config File Resolution throw error in file protocol

### ISSUE THREAD

**Issue by zWingz** [eslint/eslint#13359]
https://cn.eslint.org/docs/developer-guide/shareable-configs#local-config-file-resolution

I create my config `@scope/eslint-config-myconfig` in local, and install it by `npm install file:../eslint-config-myconfig`

**eslint-config-myconfig**
```js
// index.js
module.exports = {
  parser: 'babel-eslint',
  extends: ['./base.js'],
};

// base.js
module.exports = {
  extends: ['other-config'],
  rules: {
  },
};

// vue.js
module.exports = {
  extends: ['@scope/eslint-config-myconfig', 'plugin:vue/essential'],
  rules: {
  },
};
```

**project-1**
```eslintrc.js
module.exports = {
  extends: '@scope/eslint-config-myconfig/vue'
};
```

when i run `eslint src`, it throw error

```
Oops! Something went wrong! :(

ESLint: 7.1.0

ESLint couldn't find the config "@scope/eslint-config-myconfig" to extend from. Please check that the name of the config is correct.

The config "@scope/eslint-config-myconfig" was referenced from the config file in "/Users/my/scope/eslint-config-myconfig/vue.js".

If you still have problems, please stop by https://eslint.org/chat to chat with the team.

```
but it succeed after published to npm

**Tell us about your environment**

* **ESLint Version:**
7.1.0
* **Node Version:**
10.16.3
* **npm Version:**
6.11.3

## Resolved

I used `extends: ['./base']` to resolved it, but i diff to document

![image](https://user-images.githubusercontent.com/13031838/82856765-8322ad80-9f41-11ea-986e-dfc9e6ade953.png)

**Comment by anikethsaha** [comment]
Thanks for the issue. 

can you try with linking the package, like using `npm link`

**Comment by mysticatea** [comment]
Hi.

What happens if you execute `require("@scope/eslint-config-myconfig")` in the `vue.js` file of `eslint-config-myconfig` package? It's what ESLint does.

If a file contains `extends:"eslint-config-foo"`, ESLint loads it as similar to `require("eslint-config-foo")` in the file.

**Comment by zWingz** [comment]
throw error `Error: Cannot find module '@scope/eslint-config-myconfig'`

**Comment by zWingz** [comment]
@anikethsaha as same as `npm install file://`

**Comment by anikethsaha** [comment]
for modules, if you have them as dep, it should work irrespective of the path to the module. 

are you using mono repo? like for Lerna, I guess the command is `lerna link`.

**Comment by mysticatea** [comment]
> throw error Error: Cannot find module '@scope/eslint-config-myconfig', maybe it load from eslint-config-myconfig/node_modules

OK, so this is the designed behavior. You have to write `eslint-config-myconfig` as working fine with this behavior.

I'm not familiar with lerna, so I mention another solution: I guess you can use `extends:"./index.js"` or something like instead of `extends:"@scope/eslint-config-myconfig"`, because `require("./index.js")` in the `vue.js` should work fine.

**Comment by zWingz** [comment]
@mysticatea yes, i use './base` to resolved, but document recommend to use full-pkg-name

**Comment by mysticatea** [comment]
Ah, I got it. So this looks a documentation issue. Because package names in `extends` are similar to `require("package-name")` and we should not write `require()` with packages what the `dependencies` field doesn't contain.

---

...In fact, recently Node.js has supported resolving self-references (https://github.com/nodejs/modules/issues/306). So if you are using Node.js v12.16.0/v14.0.0 (or above) and the `package.json` of `eslint-config-myconfig` package contains `exports` field, `extends:"@scope/eslint-config-myconfig"` may work fine as well.

**Comment by kaicataldo** [comment]
@mysticatea Have you verified this is a documentation bug? If so, can you mark this as accepted and outline what you think the fix should be so someone from the community can make a PR?
