### ISSUE TITLE
[prefer-destructuring] used to reassign variable

### ISSUE THREAD

**Issue by zWingz** [eslint/eslint#13369]
declaration a `let` variable by object destructuring, and reassign it after, it will throw warning(error), but i don't need object destructuring

**What rule do you want to change?**
https://eslint.org/docs/rules/prefer-destructuring

![image](https://user-images.githubusercontent.com/13031838/83213459-bc069080-a194-11ea-8ef4-0b2534012bcb.png)

**How will the change be implemented? (New option, new default behavior, etc.)?**

new option

**Please provide some example code that this change will affect:**

```js
const a = {
  b: 1,
};
const c = {
  b: 1,
};

let { b } = a;
b = c.b;
```

**Comment by mdjermanovic** [comment]
Hi @zWingz, thanks for the issue!

I think this option already exists, but please let me know if I didn't understand this proposal.

This rule, by default, requires `({ b } = c);` instead of `b = c.b`.

If you don't want to enforce the use of object destructuring in assignments, you can set `AssignmentExpression.object` option to `false`, for example:

```js
/* eslint "prefer-destructuring": ["error", {
      "VariableDeclarator": {
        "array": true,
        "object": true
      },
      "AssignmentExpression": {
        "array": true,
        "object": false
      }
}]*/

const a = {
  b: 1,
};
const c = {
  b: 1,
};

let { b } = a;
b = c.b; // no errors
```

[Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IFwicHJlZmVyLWRlc3RydWN0dXJpbmdcIjogW1wiZXJyb3JcIiwge1xuICAgICAgXCJWYXJpYWJsZURlY2xhcmF0b3JcIjoge1xuICAgICAgICBcImFycmF5XCI6IHRydWUsXG4gICAgICAgIFwib2JqZWN0XCI6IHRydWVcbiAgICAgIH0sXG4gICAgICBcIkFzc2lnbm1lbnRFeHByZXNzaW9uXCI6IHtcbiAgICAgICAgXCJhcnJheVwiOiB0cnVlLFxuICAgICAgICBcIm9iamVjdFwiOiBmYWxzZVxuICAgICAgfVxufV0qL1xuXG5jb25zdCBhID0ge1xuICBiOiAxLFxufTtcbmNvbnN0IGMgPSB7XG4gIGI6IDEsXG59O1xuXG5sZXQgeyBiIH0gPSBhO1xuYiA9IGMuYjsgLy8gbm8gZXJyb3JzIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjo2LCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19)

**Comment by zWingz** [comment]
@kaicataldo thanks
