### ISSUE TITLE
Not ignoring .github/workflows by default (eslint-plugin-yaml)

### ISSUE THREAD

**Issue by aminya** [eslint/eslint#13418]
How can I make eslint not ignore `.github/workflows/*` by default inside my `eslint-plugin-yaml`

https://github.com/aminya/eslint-plugin-yaml/issues/3

**Comment by mdjermanovic** [comment]
ESLint ignores dot files and dirs by default (`".*"` pattern). This will be probably changed in some of the future major versions (ref [eslint/rfcs#9 comment](https://github.com/eslint/rfcs/pull/9#issuecomment-635520631)).

Configs can have `"ignorePatterns"`, so you could add `ignorePatterns: ["!.github"]` to plugin's `recommended` config in order to unignore `.github`.

Or, something like `ignorePatterns: ["!.github", ".github/*","!.github/workflows"]` to unignore only `.github/workflows`.

Either way, these patterns will be concatenated with patterns defined in users' configs (and maybe other shared configs) so it's probably good to document them, though I think it might be better in this case to just let the users configure this.

**Comment by JustFly1984** [comment]
@mdjermanovic +1 we want to lint `yml` files in `.github/workflow` too, thank you for advise

**Comment by JustFly1984** [comment]
@aminya can you please check if @mdjermanovic advice work for you? It looks like it did not work for us.

**Comment by JustFly1984** [comment]
@mdjermanovic @aminya I've created related issue in vscode eslint plugin repo: https://github.com/microsoft/vscode-eslint/issues/997

eslint-plugin-yaml does work for me in terminal and with lint-staged, but doesn't work at all in vscode. No highlighting, no errors in output.

**Comment by JustFly1984** [comment]
please reopen

**Comment by aminya** [comment]
I will take a look at this today. Sorry for the late responce.

**Comment by aminya** [comment]
I fixed it. It is available in `"eslint-plugin-yaml": "^0.3.0"`
