### ISSUE TITLE
Roadmap Brainstorming

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#13482]
One of the things we agreed to do is try to set a roadmap for the next 12 months or so. So far it seems like we have the following on our roadmap:

1. **Simple Config** (est: 6 months, lead: @nzakas) eslint/rfcs#9
2. **Google Season of Docs** (est: 3 months, lead: @kaicataldo )
3. **Parallel linting** (est: TBD, lead: TBD)
4. **Website redesign** (est: TBD, lead: @nzakas/@kaicataldo)

Questions for the team:

1. What else should be added that we can reasonably expect to conclude in the next 12 months?
2. Which of the TBDs are you interested in leading? (we probably only have the bandwidth for two large projects per TSC member in the next 12 months)

The goal is to be able to formalize and publish a roadmap both as a way to prioritize our work and to communicate where we see the project heading.

As this is a brainstorming issue, there are no "bad" ideas! Put them all in this issue and once we have a complete list we can discuss which we want to pursue and which we don't.

**Note:** This issue is locked so that only team members can participate. This is to keep the conversation focused while being transparent with the community. If you have other roadmap requests, please open an issue and we can consider adding it.

**Comment by btmills** [comment]
> 1. What else should be added that we can reasonably expect to conclude in the next 12 months?

- There's [a discussion in Discord](https://discord.com/channels/688543509199716507/711686958635548723/730940390860914758) about implementing an LSP server for ESLint that could be shared by lighter-weight editor integrations. Not sure where on the list of priorities that might sit.
- One potential blocker brought up in two of our existing parallel linting RFCs (RFC11 and RFC42) is plugins like `import` and `typescript` that need to build up a file map, so it might be helpful to solve that separately first.
- Depending on what comes out of GSoD, the configuration and developer docs could use a refactor. Maybe that's part of the website redesign's scope, or maybe it's its own thing.

> 2\. Which of the TBDs are you interested in leading?

- I'm intrigued by parallel linting, though @mysticatea has first dibs on that by virtue of having written one of the RFCs.
- Configuration and/or developer doc refactor.

**Comment by anikethsaha** [comment]
> 1. What else should be added that we can reasonably expect to conclude in the next 12 months?

I think extracting the logic from the core to packages under `@eslint` can be a good addition as monorepo. 
There could be some disadvantages as maintainability cost, syncing, versioning, etc. 
But advantages can be that independent packages can be helpful. useful for the ecosystem as they don't have to use the whole eslint in order to use a few API (though bundle sizes can be reduced with further optimization). 

Motivation https://github.com/eslint/rfcs/pull/58#pullrequestreview-439588225 , https://github.com/eslint/rfcs/pull/58#issuecomment-651462132, https://github.com/eslint/rfcs/pull/58#issuecomment-651706188

**Comment by mysticatea** [comment]
> 1. What else should be added that we can reasonably expect to conclude in the next 12 months?

- **Native ES modules support** (only since Node.js 14.0.0). This means two stuff: (1) ESLint can load `.eslintrc.js`/`eslint.config.js` under ES modules project. (2) ESLint can load `eslint-plugin-*`, `eslint-config-*`, and custom parsers that are written with native ES modules. Especially, it's useful if ESLint can load `.eslintrc.js`/`eslint.config.js` even if `package.json` has [`{"type": "module"}`](https://nodejs.org/api/esm.html#esm_package_json_type_field).
- **Start/end hooks for plugins and parsers**. It has been mentioned in RFC42 (parallel linting), but I think that we should discuss this feature as separated from parallel linting.
- **New syntax support**. We have been doing this always, but should the roadmap mention it? (maybe [Numeric Separators](https://github.com/tc39/proposal-numeric-separator) and [Logical Assignment](https://github.com/tc39/proposal-logical-assignment/) get Stage 4 in this month.)
- **Process of releasing experimental features**. We have several big features under discussion. Maybe it's useful if we define the releasing process of experimental features to collect feedback. 

> 2. Which of the TBDs are you interested in leading?

- I'm interested in parallel linting. I have [a prototype](https://github.com/eslint/eslint/tree/very-rough-worker-threads-poc/lib/eslint) and confirmed the prototype makes linting faster on several projects (that are using import/TypeScript plugins). RFC42 is stuck about if it should include hooks API or not, but I hope to advance RFC42 without hooks.
- I'm interested in native ES modules support. This was one of the reasons that I proposed RFC40.
- I'm interested in new syntax support. Since ES2016, I have worked on this mainly.

**Comment by nzakas** [comment]
**TSC Summary:** This issue was used for brainstorming roadmap features going forward. It seems that the ones we can agree on doing are:

* Simple Config (est: 6 months, lead: @nzakas) eslint/rfcs#9
* Google Season of Docs (est: 3 months, lead: @kaicataldo )
* Parallel linting (est: TBD, lead: @mysticatea/@btmills)
* Website redesign (est: TBD, lead: @nzakas/@kaicataldo)

I think that ESM support will come as part of simple config, so I don't think we need to specify that manually.

**TSC Question:** Given that we don't have RFCs for other ideas in this thread, can we publish the four items as our official roadmap and then add to it whenever we have an approved RFC with a team member dedicated to implementing it?

**Comment by nzakas** [comment]
Closing, as we now have our public roadmap.
