### ISSUE TITLE
ignore indent when ternary operator are used

### ISSUE THREAD

**Issue by spanwair** [eslint/eslint#13508]
what rule to use when I want indent to be working but it comes to ternary operators I would like to switch off, or even better use 2 spaces or none. Exmp:
```
amount !== undefined && rate !== undefined
? rateAmount(num, rate)
: '0';
```

**Comment by spanwair** [comment]
1. v7.5.0

2.
```
"rules": {
"indent": "off",
"@typescript-eslint/indent": [
            "error",
            2,
            {
                "CallExpression": {
                    "arguments": "first"
                },
                "FunctionDeclaration": {
                    "parameters": "first"
                },
                "FunctionExpression": {
                    "parameters": "first"
                },
                "offsetTernaryExpressions": true
            }
        ],
}
```

3. Expected indentation of 8 spaces but found 6.eslint@typescript-eslint/indent

4. I expect that when ESlint come to any ternary operator in the code it will automatically switch off, or better >> if ternary operator is on multiple lines than output rule will resolve positively for both of these examples:
 
```
amount !== undefined && rate !== undefined
? rateAmount(num, rate)
: '0';
```

```
amount !== undefined && rate !== undefined
  ? rateAmount(num, rate)
  : '0';
```

**Comment by anikethsaha** [comment]
What I understood from the description is that you want both of the code snipped 


> ```
> amount !== undefined && rate !== undefined
> ? rateAmount(num, rate)
> : '0';
> ```
> 
> 
> ```
> amount !== undefined && rate !== undefined
>   ? rateAmount(num, rate)
>   : '0';
> ```

to work without any errors right ?

If so, use [`{ "ignoredNodes": ["ConditionalExpression"] }`](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgaW5kZW50OiBbXCJlcnJvclwiLDIsIHsgXCJpZ25vcmVkTm9kZXNcIjogW1wiQ29uZGl0aW9uYWxFeHByZXNzaW9uXCJdIH1dKi9cblxuYW1vdW50ICE9PSB1bmRlZmluZWQgJiYgcmF0ZSAhPT0gdW5kZWZpbmVkXG4/IHJhdGVBbW91bnQobnVtLCByYXRlKVxuOiAnMCc7XG5cbmFtb3VudCAhPT0gdW5kZWZpbmVkICYmIHJhdGUgIT09IHVuZGVmaW5lZFxuICA/IHJhdGVBbW91bnQobnVtLCByYXRlKVxuICA6ICcwJzsiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjExLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7ImluZGVudCI6Miwibm8tZXh0cmEtcGFyZW5zIjoyfSwiZW52Ijp7ImJyb3dzZXIiOnRydWUsIm5vZGUiOnRydWUsImNvbW1vbmpzIjp0cnVlLCJzaGFyZWQtbm9kZS1icm93c2VyIjp0cnVlLCJ3b3JrZXIiOnRydWUsImFtZCI6dHJ1ZSwibW9jaGEiOnRydWUsImphc21pbmUiOnRydWUsImplc3QiOnRydWUsInBoYW50b21qcyI6dHJ1ZSwianF1ZXJ5Ijp0cnVlLCJxdW5pdCI6dHJ1ZSwicHJvdG90eXBlanMiOnRydWUsInNoZWxsanMiOnRydWUsIm1ldGVvciI6dHJ1ZSwibW9uZ28iOnRydWUsInByb3RyYWN0b3IiOnRydWUsImFwcGxlc2NyaXB0Ijp0cnVlLCJuYXNob3JuIjp0cnVlLCJzZXJ2aWNld29ya2VyIjp0cnVlLCJhdG9tdGVzdCI6dHJ1ZSwiZW1iZXJ0ZXN0Ijp0cnVlLCJ3ZWJleHRlbnNpb25zIjp0cnVlLCJlczYiOnRydWUsImVzMjAxNyI6dHJ1ZSwiZXMyMDIwIjp0cnVlLCJncmVhc2Vtb25rZXkiOnRydWV9fX0=) options. in order to ignore all the conditional operators.

**Comment by spanwair** [comment]
@anikethsaha nice this is answer to my first possibility of option (to be turn off when condition). If it is possible to find any possibility how to check expression if ternary operation comes so it can have 0 or 2 spaces at the beginning.
Anyway thanks a lot

**Comment by anikethsaha** [comment]
That would be an enhancement request. `indent` is a stylistic rule and according to our new [policy](https://eslint.org/blog/2020/05/changes-to-rules-policies), no enhancement for stylistic rules are being accepted

**Comment by nzakas** [comment]
Question has been answered, so closing.
