### ISSUE TITLE
eslint remove normal code in vscode ?

### ISSUE THREAD

**Issue by chenguzhen87** [eslint/eslint#13558]
![image](https://user-images.githubusercontent.com/28331609/89883668-0b3c5900-dbfb-11ea-8a5d-0d231c780d87.png)
when 'ctrl+s'  remove  normal code in vscode

**Comment by chenguzhen87** [comment]
![image](https://user-images.githubusercontent.com/28331609/91312299-abdb6d00-e7e6-11ea-909d-333287053cae.png)

**Comment by chenguzhen87** [comment]
I have found a another question
![image](https://user-images.githubusercontent.com/28331609/91312603-0248ab80-e7e7-11ea-9572-b3c622ddf027.png)
but it is ok
![image](https://user-images.githubusercontent.com/28331609/91312808-3a4fee80-e7e7-11ea-847b-5320f0107631.png)

**Comment by mdjermanovic** [comment]
@chenguzhen87 

`md5Pwd` in `const md5Pwd = md5Pwd(user_pass)` is a reference to itself, since it's already shadowing the upper `md5Pwd` at that point.

You can also enable other useful rules, like `no-use-before-define` and `no-shadow` to get more context, like in [this demo](https://eslint.org/demo#eyJ0ZXh0IjoiaW1wb3J0IHsgbWQ1UHdkIH0gZnJvbSBcInV0aWxzXCI7XG5cbmV4cG9ydCBkZWZhdWx0IHtcbiAgZm9vKCkge1xuICAgIGNvbnN0IG1kNVB3ZCA9IG1kNVB3ZCh1c2VyX3Bhc3MpXG4gIH1cbn0iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsibm8tdXNlLWJlZm9yZS1kZWZpbmUiOjIsIm5vLXNoYWRvdyI6Miwibm8tdW51c2VkLXZhcnMiOjJ9LCJlbnYiOnt9fX0=).

**Comment by anikethsaha** [comment]
> ![image](https://user-images.githubusercontent.com/28331609/89883668-0b3c5900-dbfb-11ea-8a5d-0d231c780d87.png)
> when 'ctrl+s' remove normal code in vscode


Try upgrading eslint to `7.x` ,looks like this is working fine in the latest version [repl](https://eslint.org/demo#eyJ0ZXh0IjoiaW1wb3J0IFRvYXN0IGZyb20gJ3RvYXN0Jztcblxub2JqLm1ldGgoVG9hc3QpIiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMSwic291cmNlVHlwZSI6Im1vZHVsZSIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJuby11bnVzZWQtdmFycyI6Mn0sImVudiI6e319fQ==)
