### ISSUE TITLE
Feature: allow lint re-triggering when dependent file changes

### ISSUE THREAD

**Issue by tomrav** [eslint/eslint#13570]
**The version of ESLint you are using.**
`7.6.0`

**The problem you want to solve.**
I am one of the maintainers of [Stylable](), a CSS pre-processor. we have recently created a new plugin for ESLint ([eslint-plugin-stylable](https://github.com/wix/stylable/tree/master/packages/eslint-plugin-stylable)). This plugin is used to validate usage of imported stylesheets in your code.

In a nutshell, during lint, we are processing imported files, and exposing diagnostics related to the information from those files. We would like to have the linting re-trigger, once one of those files changes (when running in IDE mode, previous related discussion, https://github.com/eslint/eslint/issues/13114).

Or in further details, In Stylable all stylesheets end with the suffix `.st.css` and are transpiled during build time to CSS or JS assets. Our plugin performs these actions behind the scenes during dev time and exposes diagnostics for any stylesheets that was used.

To describe a case which could easily happen to a user - I have two files, `comp.tsx` which imports `style.st.css`, and uses the exposed classes from it (similar to CSS Modules) to apply their correct namespaced class names. If the user tries to apply a non-existing class, he will get an error. 

The user can then add the missing class to `style.st.css`. However, this will not re-trigger linting by itself and would require the user to perform any sort of change to the `comp` file to have the now irrelevant warning removed. 

**Your take on the correct solution to problem.**
The behavior which we are missing, is the ability to mark some files as dependencies of a file being linted and to have the lint operation re-trigger if those dependencies change.

**Are you willing to submit a pull request to implement this change?**
Willing to try and help out, though I suspect this may be somewhat internal to how the library functions.

**Comment by anikethsaha** [comment]
Thanks for the issue. 

It looks like something which a watcher tool would do. eslint doesn't support running checks in watch mode. 
I would suggest trying [eslint-watch](https://github.com/rizowski/eslint-watch) and if it doesn't solve that, it might be good to have that feature in `eslint-watch` itself.

**Comment by tomrav** [comment]
I'll try to further clarify my intent, the main use-case I am referring to is running `eslint` as a plugin in an IDE environment (`vscode-eslint` for me). Even if the plugin were to somehow allow custom watching, I'm not sure how my plugin would communicate the required dependencies based on the rule to `eslint` itself.

The same issue would probably be encountered when using the `eslint-watch` as suggested for a CLI based flow.

As a note, I've seen similar issues happen with the `eslint-typescript` plugin for similar rules that depend on other files (usually types, promises, that sort of thing).

**Comment by anikethsaha** [comment]
IMO, It should be supported by the IDE plugins/integrations itself.  Cause I think integrating with eslint's own watcher would be much complex for the plugin than the plugin providing the watcher itself.  (for eg, it might be difficult for eslint to notify the integration plugins that there is a new linting triggered than the integration plugin notifying itself)

Maybe I am missing something here, let see what others think.

**Comment by kaicataldo** [comment]
This is an interesting use-case, but doesn't fit into ESLint's current linting strategy, for two reasons:

1) ESLint lints one file at a time and doesn't have knowledge of dependency trees (though I agree this would be a useful feature to have!).
2) ESLint is really only intended to run on JavaScript files, though the project does have APIs for custom parsers.

Before we add the ability to mark a dependency, I think we would first want to implement the ability for ESLint to have the ability to do cross-file linting for JavaScript files. This has its own set of challenges (how autofixes work in the context of this new feature, for instance) that we would also need to solve first.

In order to include this feature, we would also need to add a watcher (which I don't think is particularly useful, given the fact we have editor integrations already and wrapping ESLint in a watcher script doesn't require a ton of code).

I've worked on some projects that utilized typechecking imported class names in stylesheets (see https://github.com/kaicataldo/css-modules-ts-definitions-loader), and I didn't run into this issue. Can I ask why this shouldn't be handled the same way as other lint rules, triggering on save in the TypeScript file that imports the pre-processed styles? In other words, the workflow would be:

1. Enabling linting on save in your editor of choice.
1. Add a new CSS class to `style.st.css` and save.
1. Go back to `comp.tsx`, add a reference to the new class, and save.
1. The linting rule runs the necessary diagnostics (or is able to query another background process/watcher that's running the diagnostics in real time) and runs the rule.

**Comment by tomrav** [comment]
I understand where you're coming from and agree that the heavy lifting (watching) should be done in the environment plugin, but some information is currently missing for that to happen. I'll also note that in this case, I'm not interested in linting multiple files, or files that are non-JS, but rather linting a single file that depends on other files.

Adding a pseudo-code example:
```tsx
// comp.tsx
import { classes } from './style.st.xss';

const Comp = () => (
  <div className={classes.maybeExists}>
  </div>
)
```

In this case, I am linting the `comp.tsx` file. My plugin will find the `.st.css` file, transpile it, and check all of it's usages in `comp.tsx` to make sure they exist and are valid. 

As for the flow suggested, I see two potential problems:
1. A user can write the component side first, get diagnostics for missing classes, goes and adds them, and still sees the error until a change is made to the component file.
2. Same idea, but changing an existing class would not trigger now needed classes on the component file as it would not be linted again.

Having said all that, if you end up deciding this use-case is out of scope for eslint I could see why - this does somewhat go against the grain in regards to working on a 'single file'. 
On our end we would probably end up switching our plugin to some `.d.ts`/CLI based solution.
