### ISSUE TITLE
Per-rule performance measure and bootstraping costs

### ISSUE THREAD

**Issue by alexeyraspopov** [eslint/eslint#13695]
**The version of ESLint you are using.**

7.9.0

**The problem you want to solve.**

I came across a tweet about [Per-rule performance](https://eslint.org/docs/1.0.0/developer-guide/working-with-rules#per-rule-performance) and following comment @nzakas made: https://twitter.com/slicknet/status/1306023516681244673

> Note that the first rule always shows up as the slowest because it’s hard to exclude bootstrapping costs. The rest is quite accurate.

I can see how this works and why it worth keeping in mind. However, I assume, those who didn't see Nicholas' comment on this, may be seeing the performance report and immediately attempt to disable the very first rule by making an assumption that it really takes significant amount of time and may not be valuable. I also imagine that the difference will be bigger for larger projects

**Your take on the correct solution to problem.**

In order to avoid confusion and possibly make the report more actionable, I suggest ESLint can automatically include an empty (noop) first rule (only when `TIMING=1`) for the sake of accumulating the bootstrapping costs. This not only helps to ensure correctness of the report but also allows calculating the bootstrapping costs separately.

It can be also considered to show these costs in the report, to make it more clear how the ESLint timings work on users project.

**Are you willing to submit a pull request to implement this change?**

I wish I could, but my knowledge of ESLint codebase is limited. I only made a couple of custom rules on my projects 🤷‍♂️.

**Comment by nzakas** [comment]
Thanks for the followup from Twitter. I wasn't involved with building out this feature, so I'm not sure if this is even possible, but we'll see what the others think.

**Comment by btmills** [comment]
Check out https://github.com/eslint/rfcs/pull/42 for an extensive discussion on this same issue but coming at it from another angle. The TypeScript and import plugins in particular do an initialization step. Currently, ESLint doesn't have an API for that, so they do it on the fly. Usually that's the first time ESLint runs one of their rules on a file since that's the first opportunity they have to execute code with the full lint context. Based on the discussion in that RFC, we'll likely need to provide an API for that before we ship parallel linting. I expect that API would solve the timing issue by moving the bootstrapping process into its own dedicated step.
