### ISSUE TITLE
--ignore-path option only works with file in current directory

### ISSUE THREAD

**Issue by davidtheclark** [eslint/eslint#1382]
Given a directory structure like this ...
- root/
  - test/
    - .fooignore
    - js/
      - bar.js

... I noticed that the `--ignore-path` option doesn't seem to work as I would expect.

If from `root/test/` I run: `eslint js/bar.js --ignore-path .fooignore` I _do_ get the expected warning (`File ignored because of your .eslintignore file. ...`)

But if from `root/` I run: `eslint test/js/bar.js --ignore-path test/.fooignore` _I do not get any warning and the file is linted_, as though there were no ignore file at all.

Same goes for if from `root/test/js/` I run `eslint bar.js --ignore-path ../.fooignore` (no warning, file is linted).

Am I missing something about how to use `--ignore-path` or is this a bug?

**Comment by mcomella** [comment]
While the reasoning this occurs makes sense, I don't understand why the current state is useful. It reduces functionality because lintignore files can't specify relative paths if the working directory can change (and thus can only specify wildcards and absolute paths, though absolute paths are less useful when dealing with multiple users).

Is there a use case I'm missing? If not, can we change this functionality (or add an additional flag for backwards compatibility reasons)?

Context: as part of my work on [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1177933), we have to work around the bug by changing the working directory of our python script wrapper before running eslint.
