### ISSUE TITLE
Allow using await on global scope without async function

### ISSUE THREAD

**Issue by vla9n1k** [eslint/eslint#13832]
Since await is available for usage on global scope without async function, there should be added a rule to remove warning when using await outside of async function

Example:

const data = await fetch(url);
console.log(await data.json())

**Comment by mdjermanovic** [comment]
Hi @vla9n1k, thanks for the issue! 

> Since await is available for usage on global scope without async function, there should be added a rule to remove warning when using await outside of async function

We can't add a rule for this, because it's a parsing error.

[Top-level await](https://github.com/tc39/proposal-top-level-await) is still a stage 3 proposal. Per our [policy about experimental features](https://github.com/eslint/eslint#what-about-experimental-features), ESLint's default parser will support this syntax when it reaches stage 4.

Until then, you can use ESLint with an [external parser](https://eslint.org/docs/user-guide/configuring#specifying-parser) that supports this syntax, like [@babel/eslint-parser](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser) (you'll probably also need [@babel/plugin-syntax-top-level-await](https://babeljs.io/docs/en/babel-plugin-syntax-top-level-await) plugin). 

I'm closing this as it isn't actionable at the moment.
