### ISSUE TITLE
Bug: --fix ignores defined order and creates a JS error

### ISSUE THREAD

**Issue by darlandemarco** [eslint/eslint#13899]
**Tell us about your environment**

* **ESLint Version:** 6.8.0
* **Node Version:** 8.15
* **npm Version:** 6.4.1

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
default

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```
module.exports = {
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "rules": {
        "prefer-const": "error",
        "no-undef-init": "warn"
    }
};
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```
let foo= undefined; //foo is not reasigned so it will try to transform to const and keep initialization as undefined;
```

Eslint command:
```
node node_modules/eslint/bin/eslint.js --fix testfile.js
```

**What did you expect to happen?**
transform variable to constant but not remove the undefined init as it will become a constant.

**What actually happened? Please include the actual, raw output from ESLint.**
I have runned an autofix in a legacy code with more than 10k files. When it finds a variable that should be a constant (because it is not reasigned) and is initialized as ```undefined``` it fix the code transforming it to ```const foo;``` causing errors over the code. I tried to change the rules order to first turns it to a constant and them check the undefined init so it should be fixed (as per: https://eslint.org/docs/rules/no-undef-init). But is still happening.

**Are you willing to submit a pull request to fix this bug?**
Yes, need some guidance but I can do this :) 

![eslint](https://user-images.githubusercontent.com/15704333/100765799-a89fe080-33d6-11eb-8aae-160e28610e24.gif)

**Comment by mdjermanovic** [comment]
Hi @darlandemarco, thanks for the issue!

I can confirm that `let foo = undefined;` gets auto-fixed to `const foo;`

You're using an old ESLint version, but this happens in the actual version as well: [Online Demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IHByZWZlci1jb25zdDogXCJlcnJvclwiICovXG4vKiBlc2xpbnQgbm8tdW5kZWYtaW5pdDogXCJlcnJvclwiICovXG5cbmxldCBmb28gPSB1bmRlZmluZWQ7XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjYsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

**Comment by mdjermanovic** [comment]
> **Are you willing to submit a pull request to fix this bug?**
> Yes, need some guidance but I can do this :)

That would be great, thanks!

I think the "fix range" of `prefer-const` should be extended to the whole declaration, in order to prevent other fixes in the same pass. Then, in the second pass, `no-undef-init` will see `const` and won't report an error.

There's [fix-tracker](https://github.com/eslint/eslint/blob/master/lib/rules/utils/fix-tracker.js) helper for this purpose. We should call [retainRange](https://github.com/eslint/eslint/blob/110cf962d05625a8a1bf7b5f4ec2194db150eb32/lib/rules/utils/fix-tracker.js#L41) and then [replaceTextRange](https://github.com/eslint/eslint/blob/110cf962d05625a8a1bf7b5f4ec2194db150eb32/lib/rules/utils/fix-tracker.js#L83).

You can find some examples of use in rules such as `semi`, `no-extra-semi`, `no-else-return`, and `no-useless-return`.

A test case for `prefer-const` that should pass after the change:

```js
// https://github.com/eslint/eslint/issues/13899
{
    code: "/*eslint no-undef-init:error*/ let foo = undefined;",
    output: "/*eslint no-undef-init:error*/ const foo = undefined;",
    errors: 2
}
```

**Comment by snitin315** [comment]
Can I work on this issue?

**Comment by mdjermanovic** [comment]
@snitin315 sure, thanks! It doesn't seem anyone is working on this at the moment.
