### ISSUE TITLE
Don't require plugin unless override is triggered for some file

### ISSUE THREAD

**Issue by luxaritas** [eslint/eslint#13944]
**The version of ESLint you are using.**
7.16.0

**The problem you want to solve.**
I am aiming to create a single eslint config, with overrides based on file type. I have one set of overrides for JS files which
use a base setup of eslint/airbnb/prettier, a set for typescript using `@typescript-eslint`, and a set for Vue using Vue's take on airbnb/ts/prettier configs as well as their own plugin. Currently, if I try to use this config in a JS-only project, I still need to install the typescript and vue plugins, even though these are only specified in overrides for *.vue and *.ts files, of which there are none.

**Your take on the correct solution to problem.**
It would be ideal if these modules could be required only if the overrides would be used for some subset of the files eslint is being run on, so I don't need to create entirely separate configs that inherit from each other.

**Are you willing to submit a pull request to implement this change?**
Potentially, given pointers to what would need to be done and as long as it isn't too gnarly for a newbie to the codebase :)

**Comment by ljharb** [comment]
Those plugins need to be specified as peer deps anyways - which are always, unconditionally, required to be present. Lazy requires won’t help you there.

The solution when you need different dependencies is multiple packages (the same reason eslint-config-airbnb and eslint-config-airbnb-base are different packages).

**Comment by btmills** [comment]
Yeah, this is a package manager limitation and not something we could do in ESLint. I have a personal config, and since I'm the only one using it I just document what the "optional" plugin peer dependency versions are. If you're building a config designed for public consumption, follow @ljharb's suggestion and publish `@luxaritas/eslint-config` with the basics, `@luxaritas/eslint-config-typescript`, `@luxaritas/eslint-config-vue`, etc. with all the correct `peerDependencies`. You'd then use them as `extends: ["@luxaritas", "@luxaritas/typescript", "@luxaritas/vue"]`.
