### ISSUE TITLE
breaking: drop node v10/v13/v15 support

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#14023]
**The version of ESLint you are using.**
n/w

**The problem you want to solve.**
just like previous major releases, we can drop node v10 support in eslint v8.
* node v10  EOL: 2021-04-30
* node v13 EOL: 2020-06-01
* 
**Your take on the correct solution to problem.**
drop node v10, v13 support.

question: do we like some features introduced in node v12, so we can pick a version( e.g. ">=12.8.0")?

**Are you willing to submit a pull request to implement this change?**
y

**Comment by nzakas** [comment]
**TSC Summary:** Node.JS 10 is EOL at the end of April and Node.JS 13 EOL is the end of June.

**TSC Question:** How do we want to handle these? Should we plan on a major release to coincide with one or both?

**Comment by ljharb** [comment]
Just because it’s EOL doesn’t mean there needs to be any rush to drop support for it.

if you’re doing a major anyways, then that’s a fine time to drop support if there’s a benefit to doing so.

**Comment by btmills** [comment]
We have several small changes waiting for the next major release, so we'll start working toward a v8 release and discuss this and other changes in the [v8 project](https://github.com/eslint/eslint/projects/8) at the next TSC meeting.

**Comment by btmills** [comment]
This is now accepted as part of ESLint v8.0.0.

**Comment by nzakas** [comment]
Note: We want to use `import()` for flat config, so we probably want to ensure whatever minimum version we decide on supports that.

**Comment by mysticatea** [comment]
ES modules have gotten stable in `^12.22.0 || ^14.17.0 || >=15.3.0`.

- [v12.22.0 mark modules implementation as stable](https://nodejs.org/en/blog/release/v12.22.0/#:~:text=mark%20modules%20implementation%20as%20stable)
- [v14.17.0 mark modules implementation as stable](https://nodejs.org/en/blog/release/v14.17.0/#:~:text=mark%20modules%20implementation%20as%20stable)
- [v15.3.0 mark modules implementation as stable](https://nodejs.org/en/blog/release/v15.3.0/#:~:text=mark%20modules%20implementation%20as%20stable)

**Comment by btmills** [comment]
Thanks for looking at that, @mysticatea. In addition to those class features, there are a few other features we'll be able to start using:

- `Object.fromEntries()`.
- `Array.prototype.flat()` and `flatMap()`. There's already a todo comment for this in #14287.
- `String.prototype.matchAll()`.
- Separators in numeric literals.

Those are all supported by every version where ESM is stable.

- For Node 12, `12.22.0` is the most recent semver-minor release as of writing.
- For Node 14, `14.17.0` is the most recent release as of writing.
- For Node 15, I didn't see anything after `15.3.0` that we'd be able to use. There are some improvements to promise-based APIs and workers that have been backported to 14 but not 12, so we couldn't use them.
- For Node 16, there are syntax features after `16.0.0`, but we wouldn't be able to use them because they haven't been backported.

I recommend we adopt @mysticatea's version range proposed above: `^12.22.0 || ^14.17.0 || >=15.3.0`.

**Comment by ljharb** [comment]
(private methods and accessors only work in node v14.6+, unfortunately)

**Comment by nzakas** [comment]
Per https://github.com/eslint/eslint/pull/14592#discussion_r645899221, we are also dropping support for v15.x, which is EOL this month.
