### ISSUE TITLE
class-methods-use-this: add exclusion option for overridden and empty methods

### ISSUE THREAD

**Issue by urrri** [eslint/eslint#14077]
**What rule do you want to change?**

class-methods-use-this

**Does this change cause the rule to produce more or fewer warnings?**

fewer

**How will the change be implemented? (New option, new default behavior, etc.)?**

new options for the rule: excludeEmpty, excludeOverridden

**Please provide some example code that this change will affect:**

```js
class Base{
  async doSomething(){
    const something = await this.fetchSomething();
    //process something
    this.something = something;
  }
  fetchSomething(){} // to override
}

class Derived extends Base{
  fetchSomething(){return fetch(something);}
}
```

**What does the rule currently do for this code?**

for both "fetchSomething" methods rule shows errors, because none of them uses "this", but they are not intended to use this.

**What will the rule do after it's changed?**

for that kind of usage errors will be disabled, because it is normal not to use "this" in empty and in overridden methods.

**Comment by arminyahya** [comment]
Hi @urrri 
This rule is going to push us to use static for methods that are not using this.
I think you are looking for something like typescript **implements**.
https://stackoverflow.com/questions/38834625/whats-the-difference-between-extends-and-implements-in-typescript

**Comment by urrri** [comment]
1. I talk about JS, not TS. In JS we don't have interface and implements. 
2. In JS empty function in base class defined for 2 purposes: call it without checking for existence and declare for overriding (JSDoc, etc., like interface in TS).
3. I know and understand why this rule was created, but: 
    - polymorphism cannot be built on static methods (AFAIK)
    - overridden methods don't have to (but can) use "this" - see my example (can you rewrite it with statics and without mess?)
    
4. Returning to TS, there is not too much difference in it and same issues are there too. Maybe empty base method is not always needed.

**Comment by mdjermanovic** [comment]
I'm not in favor of `excludeOverridden`, because base and derived classes can be in different files so we can't know for sure whether or not the method is overridden. You can use the [exceptions](https://eslint.org/docs/rules/class-methods-use-this#exceptions) option or `eslint-disable-*` comments to allow some methods without `this`.

As for empty methods, it makes sense to ignore them, maybe even without an option. There's a rule that will warn if the function was accidentally left empty (`no-empty-function`). Perhaps also makes sense to ignore methods that just `throw` (i.e. "abstract" methods).

**Comment by nzakas** [comment]
We aren’t moving forward with this, so closing.
