### ISSUE TITLE
ESLint doesn't see all the quotes problems of a JS file

### ISSUE THREAD

**Issue by NicolaeTelescu** [eslint/eslint#14103]
**Tell us about your environment**

* **ESLint Version Local:** 7.18.0
* **ESLint Version Global:** Not found
* **Node Version:** 12.18.3
* **npm Version:** 6.14.5
* **Operating System:** Windows 10

**What parser (default, `@babel/eslint-parser`, `@typescript-eslint/parser`, etc.) are you using?**
I don't know. In my config file are some options about a parser, maybe that information can help you.

**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```
{
    "env": {
        "browser": true,
        "es2021": true,
        "node": true,
        "amd": true,
        "jquery": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended"
    ],
    "parserOptions": {
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "rules": {
        "react/prop-types": "off",
        "react/jsx-uses-react": "warn",
        "react/react-in-jsx-scope": "off",
        "quotes": [
            "error",
            "double",
            {
                "avoidEscape": true
            }
        ]
    },
    "globals": {
        "React": true,
        "ReactDOM": true,
        "ReactRedux": true,
        "ReactRouterDOM": true,
        "Redux": true
    },
    "settings": {
        "react": {
            "version": "detect"
        }
    }
}
```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```
import {HomePage} from "./structure/HomePage/HomePage.js";
import {PackItemPages} from './structure/item/_PackPages.js';
import {allReducers} from './redux/reducers/index.js';


const Provider = ReactRedux.Provider;

const Router = ReactRouterDOM.BrowserRouter;
const Switch = ReactRouterDOM.Switch;
const Route = ReactRouterDOM.Route;


function App() {
	return (
		<div className='flex-container'>
			
			<Header />
			<Message />
			<Switch>
				<Route path='/' exact component={HomePage} />
				<Route path="/items" component={PackItemPages} />
			</Switch>
			<Footer />
		
		</div>
	);
}
```

I use VS Code with the ESLint extension so text editor shows me the errors.

**What did you expect to happen?**
I wanted to see the 'flex-container' and 'path' value as a problem because they have simple quotes, not double quotes, as I can see at the second and at the third line in the code, where are imports.

**What actually happened? Please copy-paste the actual, raw output from ESLint.**

**Steps to reproduce this issue:**

1. If you create a component in React, the strings from there can't be checked by ESLint. At least, that is happening in my code.

**Are you willing to submit a pull request to fix this bug?**
Unfortunately no, but I wish to see where and how code will be modified to know more and be more prepared in the future to submit some pull requests, if they can help.

**Images:**
This image can show that there are no more errors than quotes and that the errors are happening just for the imports, as I said.

![ESLint problem](https://user-images.githubusercontent.com/36912215/107846796-40ff0c00-6def-11eb-836b-96e8cd64c9da.png)

**Comment by NicolaeTelescu** [comment]
As an user told me: _It might be because it's a JSX prop value, not a JS string literal (try if it can detect className={'flex-container'})_. In this way ESLint could see the problem :).

**Comment by mdjermanovic** [comment]
Hi @NicolaeTelescu, thanks for the issue!

The `quotes` rule works as intended in this case, because it checks only string literals.

For JSX attributes you can use the [jsx-quotes](https://eslint.org/docs/rules/jsx-quotes) rule, as in [this demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGpzeC1xdW90ZXM6IFtcImVycm9yXCIsIFwicHJlZmVyLWRvdWJsZVwiXSAqL1xuXG5mdW5jdGlvbiBBcHAoKSB7XG5cdHJldHVybiAoXG5cdFx0PGRpdiBjbGFzc05hbWU9J2ZsZXgtY29udGFpbmVyJz5cblx0XHRcdFxuXHRcdFx0PEhlYWRlciAvPlxuXHRcdFx0PE1lc3NhZ2UgLz5cblx0XHRcdDxTd2l0Y2g+XG5cdFx0XHRcdDxSb3V0ZSBwYXRoPScvJyBleGFjdCBjb21wb25lbnQ9e0hvbWVQYWdlfSAvPlxuXHRcdFx0XHQ8Um91dGUgcGF0aD1cIi9pdGVtc1wiIGNvbXBvbmVudD17UGFja0l0ZW1QYWdlc30gLz5cblx0XHRcdDwvU3dpdGNoPlxuXHRcdFx0PEZvb3RlciAvPlxuXHRcdFxuXHRcdDwvZGl2PlxuXHQpO1xufSIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6NSwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6eyJqc3giOnRydWV9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=).

**Comment by NicolaeTelescu** [comment]
Thank you for the response!

I really didn't know that for those attributes was another rule for quotes. I will close this issue.
