### ISSUE TITLE
There is no synchronously `ESLint#lintFiles` method like `CLIEngine#executeOnText`

### ISSUE THREAD

**Issue by JounQin** [eslint/eslint#14203]
**The version of ESLint you are using.**

v7.21.0

**The problem you want to solve.**

I'm trying to write a remark related eslint plugin to lint code blocks inside, but `ESLint#lintFiles` only works with `Promise`, and eslint rule doesn't allow asynchronous.

So I have to use the deprecated `CLIEngine#executeOnText` method.

I know maybe I should use `preprocessor` instead, but the different APIs are confusing.

**Your take on the correct solution to problem.**

Provide a synchronized version of `ESLint#lintFiles`, or support asynchronous rule.

**Are you willing to submit a pull request to implement this change?**

Maybe if I can do.

**Comment by mdjermanovic** [comment]
Hi @JounQin, thanks for the issue!

I'm not sure if a solution with running ESLint again from a rule is the best approach, since rules don't have the full context (e.g., provided CLI/API options) from the main run. It also doesn't seem optimal, especially given that we already have the processors feature for the purpose of linting code blocks. It would be probably better to explore if there's something missing in the processors feature for your use case.

**Comment by JounQin** [comment]
@mdjermanovic I tried processor, but it's buggy.

https://github.com/eslint/eslint/issues/14207

**Comment by nzakas** [comment]
Yes, the intent is only to have Async methods going forward so we can eventually do parallel processing, so I don’t think we want to add any sync methods.

Agree with @mdjermanovic that we should try to work within the processors world to solve this problem.

**Comment by JounQin** [comment]
OK, I got processor working although it still has some problems because of virtual filename.

Looks forward to parcelle processing!
