### ISSUE TITLE
Don't run builtin rules on TypeScript or Flow-specific AST nodes

### ISSUE THREAD

**Issue by jedwards1211** [eslint/eslint#14252]
Without warning today, `no-undef` errors started appearing in my project on things like the `Node` in `React.Node`, even though I have `eslint-plugin-flowtype` configured with `flowtype/define-flow-type`.  I upgraded all of my `eslint`-related deps to the latest versions and it's still happening.  I tried making a repository to reproduce this issue but no luck...

This is aggravating, and I question why it should have ever happened.  Why does `eslint` even run `no-undef` on `Identifier`s inside `TypeAnnotation`s, `TSTypeAnnotation`s, etc?  Is there really a good reason not to skip these node types entirely in all builtin rules?  I sure doubt it.  My guess is that limitations of the current architecture make it hard to exclude rules from certain subtrees of the AST?

**Comment by mdjermanovic** [comment]
Hi @jedwards1211, thanks for the issue!

The `no-undef` rule is based on scope analysis, which is provided by parsers. The issue here is that the parser you are using marks those identifiers as unresolved references to variables, and ESLint just treats them accordingly. I think this should be fixed in the parser or in the `flowtype/define-flow-type` rule.

**Comment by btmills** [comment]
Closing as this doesn't require changes in ESLint.

@jedwards1211 FWIW, I also use `flowtype/define-flow-type` and have not seen this issue. Since you didn't provide any repro details, I can't say for sure, but I'd guess there's something about your configuration that's causing you to see those messages.
