### ISSUE TITLE
Add fix/suggestions to `no-unused-vars` rule

### ISSUE THREAD

**Issue by fisker** [eslint/eslint#14585]
**What rule do you want to change?**

Add fix or suggestions to `no-unused-vars`.

**Does this change cause the rule to produce more or fewer warnings?**

No

**How will the change be implemented? (New option, new default behavior, etc.)?**

Not sure, but I think at least some variables not has side effect can be safely removed.

**Please provide some example code that this change will affect:**

```js
const foo = 1
```

```js
import fs from 'fs'
```

**What does the rule currently do for this code?**

No fix, no suggestions.

**What will the rule do after it's changed?**

Auto-fix errors or at least has suggestions.

**Are you willing to submit a pull request to implement this change?**

Maybe.

**Comment by nzakas** [comment]
We’ve discussed auto fixes for this before, but we decided against it because removing declarations is destructive and in the context of an editor, where fixes are applied quickly, this can be frustrating. It’s much better to let the end user investigate than assume we know that the declaration isn’t needed.

I’m not sure suggestions make much sense doe this rule. The only possible suggestion would be to remove the declaration, and I don’t know that there’s any value in that.

**Comment by tchakabam** [comment]
@nzakas i'd agree with you about the "default" or "recommended" behavior for sure.

but then again, why not make this behavior optional also, so that people can opt-in when they want to run that autofix? 

Imagine a codebase needing to be cleaned up with a lot of unused vars.

**Comment by DamienCassou** [comment]
> Imagine a codebase needing to be cleaned up with a lot of unused vars.

That's exactly my use case. I'm fine checking hundred automatic changes but I'm too lazy to do the changes myself.

**Comment by bmish** [comment]
I kind of wish it was possible to mass apply a specific rule suggestion, but that capability was explicitly against the [suggestion RFC](https://github.com/eslint/rfcs/tree/main/designs/2019-suggestions). So if I really need to do that in order to migrate my large codebase, I'll actually go in and edit a rule to temporarily convert the suggestion into an autofixer.

In my plugin rules, I’ve also added rule options (`autofix`, `useOptionalChaining`, etc) for users who want to opt-in to more aggressive autofixing behavior or an autofix that requires a higher Node version.

**Comment by nzakas** [comment]
@tchakabam we don’t have a way to optionally apply auto fixes in this way. Suggestions is intended primarily for the editor use case, so that also doesn’t solve your problem of wanting to remove all unused variables in a codebase. I suppose we could provide the suggestions and you could write a tool on top of ESLint that uses that data to apply the fixes, but I don’t see us adding a way to do this type of mass variable removal in the core.

**Comment by mdjermanovic** [comment]
> Imagine a codebase needing to be cleaned up with a lot of unused vars

Maybe the `autofix/no-unused-vars` rule from [eslint-plugin-autofix](https://www.npmjs.com/package/eslint-plugin-autofix) can be helpful for this use case.

**Comment by tchakabam** [comment]
I see, thanks for explaining Eslints general take on such things @nzakas 👍
