### ISSUE TITLE
Add autofix to `no-negated-condition`

### ISSUE THREAD

**Issue by fregante** [eslint/eslint#14792]
_Sorry for ignoring the template but nothing applied as this doesn't actually change the behavior._

Can `no-negated-condition` be autofixable? It seems "relatively easy" to swap the blocks:

```js
if (!foo) {
	alert('❌')
} else {
	alert('✅')
}
```

```js
if (foo) {
	alert('✅')
} else {
	alert('❌')
}
```

Keywords: autofixed auto fix fixed fixable

**Comment by nzakas** [comment]
The larger the area to fix, the more dangerous the fix becomes. Also, keep in mind that because autofix is applied in editors, it can be very disorienting to move around large blocks of code.

My opinion is that autofix isn't a good idea for this rule, but I'm open to other opinions.

**Comment by fregante** [comment]
I'm struggling to think of an issue that could arise from flipping 2 blocks, as long as their scope can be safely detected even without curly braces (which I assume it can)

The diff argument makes sense, but eslint and prettier also make larger diffs with the indentation/wrapping changes, which are not always hidden by "hide whitespace changes."

**Comment by mdjermanovic** [comment]
I think it makes sense to provide this fix as a [suggestion](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions), but given that stylistic rules are [frozen](https://github.com/eslint/eslint#stylistic-rule-updates), I'm not in favor of adding any new features to `no-negated-condition` since it is a stylistic rule.

**Comment by ljharb** [comment]
I like it as a suggestion versus an autofix particularly because half the time this rule warns me, i extremely intentionally and strongly want the negated condition to go first, so I appreciate the opportunity to put in the disable comment.

**Comment by nzakas** [comment]
If we do anything, I agree that a suggestion would be the best choice. I’m still not sure how useful it is but will defer to the consensus.

**Comment by bmish** [comment]
I'd support a suggestion for this. Perhaps suggestions should be exempt from the stylistic rule freeze: 
* Suggestions are a [relatively new feature](https://eslint.org/blog/2019/11/eslint-v6.7.0-released#suggestions-api) so there are still many existing rules that could benefit from having them added
* All new code for a suggestion is typically confined to the suggestion function and not the rule's primary code path
* The only behavior change for a suggestion occurs when a user explicitly chooses to accept a suggestion

**Comment by nzakas** [comment]
@bmish The reason stylistic rules are frozen is because we don’t want to continue maintaining them. Adding suggestions adds more surface area for problems and therefore adds more maintenance. Eventually we would like to deprecate and remove the stylistic rules and freezing them is the first step in that direction.
