### ISSUE TITLE
Add a --min-errors options to the CLI

### ISSUE THREAD

**Issue by samdouble** [eslint/eslint#14893]
**The version of ESLint you are using.**
6.8.0

**The problem you want to solve.**
I want to use eslint in our CI pipeline and prevent unlinted code to be merged to the development branch.
But we're just introducing eslint and we currently have over 4500 linting errors.
Rather than getting our error count down to 0 and then introducing eslint to our pipeline (which is unrealistic and would take a long time), I would like to make it an iterative process where we would introduce eslint to our pipeline right now and gradually lower the minErrors to 0 over time. Having a minErrors option would also help us make sure that our error count cannot go up with new commits.

**Your take on the correct solution to problem.**
In a similar fashion to **--max-warnings <Int>**, I would add a **--min-errors <Int>** option to the CLI (default: 0).
If the errorCount is zero OR inferior to the value specified by minErrors, a zero exit code would be returned.

**Are you willing to submit a pull request to implement this change?**
Yes, I would like to.

**Comment by nzakas** [comment]
What we suggest in this type of use case is that you set rules to “warn” instead of “error”. That way, you can set max-warnings to determine the threshold where you want to break CI.

What I’ve done personally is just started by setting only the rules I want fixed immediately to “error” and other rules that will break CI in the future are set to “warn”. Then, I slowly transitioned the warnings into errors as we got better at fixing them.

I think either of these two approaches should solve your use case without adding any new features.

**Comment by samdouble** [comment]
Yes, you are right. That could work!

Thank you for taking the time to review my change proposal.
