### ISSUE TITLE
Change Request: Turn `off` warning when run with `--quiet` flag

### ISSUE THREAD

**Issue by hipstersmoothie** [eslint/eslint#15137]
### ESLint version

7.13.0

### What problem do you want to solve?

We use the `--quiet` flag on CI to not display warnings, but the rules still run.

### What do you think is the correct solution?

 Instead eslint should turn these rules `off` when `--quiet` is set which will in turn make eslint complete faster.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
interesting idea. Do I understand correctly that your concern is performance? Do you have any numbers showing how this would affect your CI run? How many rules do you set to “warn” currently?

**Comment by nzakas** [comment]
No response so closing.

**Comment by fregante** [comment]
Hello, I got a use-case: `import/no-cycle` is terribly slow, bringing my eslint from 90s to 5 minutes. I want to enable it as a warning so I can see them in the IDE, but I don't want to slow down CI nor regular eslint runs.

Regardless of performance, though, I don't see why hidden rules should run. This is like running all rules even when they're off.

My current solution is to enable it in my config but then add `--rule '{\"import/no-cycle\": \"off\"}'` to the npm script, but that still doesn't cover the rest of the warnings I have (which is a lot since we're enabling/fixing them over time)
