### ISSUE TITLE
Bug: eslint --fix break code in special case for eqeqeq

### ISSUE THREAD

**Issue by tony21921** [eslint/eslint#15241]
### Environment

Node version: v16.11.0
npm version: v8.0.0
Local ESLint version: v7.32.0
Global ESLint version: Not found
Operating System: darwin 20.6.0

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

Default configuration. Run ng lint fix.

```bash
ng lint --fix
```
</details>

## app.component.html
```html
...
<div *ngIf=" var1 == 2 && obj2.attr != 'value'">
</div>
...
```
## app.component.ts
```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['.app.component.scss']
})
export class AppComponent {
  var1 = 2;
  obj = {
    attr: 'value'
  };
}
```

### What did you expect to happen?

The issue should be fixed. '==' be replaced with '===' and '!=' be replaced with '!=='.

```html
...
<div *ngIf=" var1 === 2 && obj2.attr !== 'value'">
</div>
...
```

### What actually happened?

The first token on the line was not fixed, and the second was replace with blank space in between ('=' added after tailing space).

```html
...
<div *ngIf=" var1 == 2 && obj2.attr != ='value'">
</div>
...
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

In same project, the fix works fine when there is only one issue in a line, or without space after the token '==' or '!='.
It happens when there are multiple tokens in one line with space after token.

If I remove the space after the 2nd token, it will the fixed, but the first token is not.

**Comment by mdjermanovic** [comment]
Hi @tony21921, thanks for the issue!

> ```
> <div *ngIf=" var1 == 2 && obj2.attr != ='value'">
> </div>
> ```

Core `eqeqeq` rule by design doesn't provide auto-fix for `obj2.attr != 'value'`.

In [this demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZXNsaW50IGVxZXFlcTogZXJyb3IgKi9cblxub2JqMi5hdHRyICE9ICd2YWx1ZSciLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19), the rule reports an error but doesn't fix the code (Fixed Code tab).

Can you run linting without `--fix` to see which rule reports an error on `obj2.attr != 'value'`? It could be that this is an issue with another rule.

**Comment by snitin315** [comment]
No response, closing.
