### ISSUE TITLE
Bug: Unable to use eslint-formatter-codeframe installed globally

### ISSUE THREAD

**Issue by blindspeed90** [eslint/eslint#15248]
### Environment

Node version: v16.13.0
npm version: v6.14.10
Local ESLint version: Not found
Global ESLint version: v8.1.0 (Currently used)
Operating System: win32 10.0.19042

### What parser are you using?

Default (Espree)

### What did you do?

Tried running from the cmdline with:

--formatter codeframe
--formatter eslint-formatter-codeframe

I tried to glean what I could from the cli-engine.js getFormatter(format) method to see if there were other possible patterns to try.

### What did you expect to happen?

I expected eslint to find the newly split out codeframe formatter.

### What actually happened?

Sadly it only worked when installed locally, not globally.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Personally I use the HTML report concatenated with the codeframe one.  I would have loved if the HTML report did this, and additionally each detail error/warning was a # link to the code at the bottom.

**Comment by mdjermanovic** [comment]
Hi @blindspeed90, thanks for the issue!

ESLint doesn't support loading globally installed modules from locally installed ESLint. There are probably some workarounds you could use (e.g., passing an absolute path, or configuring `NODE_PATH` environment variable), but we would recommend installing the formatter locally.

**Comment by blindspeed90** [comment]
This was a globally installed ESLint, not local.  See the Environment entry above.

**Comment by mdjermanovic** [comment]
You're right, sorry. I'll take a look tomorrow.

**Comment by mdjermanovic** [comment]
I can reproduce this. ESLint `require`-s formatters relative to `cwd`, so it won't find a globally installed module.

https://github.com/eslint/eslint/blob/796587ad950f6804d60473c2b5998ed3ec71c59e/lib/cli-engine/cli-engine.js#L1022

However, this works as intended because this use case isn't supported. ESLint doesn't support globally installed configs/plugins/parsers/formatters even when ESLint is installed globally. While it is possible to install ESLint globally and use its built-in features, it is recommended to install ESLint and all related modules locally. 

Aside from the workarounds mentioned in my previous comment, another option is to install the formatter in `node_modules` of a parent directory (e.g., your home directory) so that the Node.js module resolution algorithm can find it.

**Comment by blindspeed90** [comment]
... and I passed "--format eslint-formatter-codeframe" on the command-line.

**Comment by ljharb** [comment]
Encouraging global usage wouldn’t be a net benefit; eslint should only be used locally.

**Comment by blindspeed90** [comment]
Why?  I'm just installing it globally so I can use it in all of my projects; why have to download for each?

**Comment by ljharb** [comment]
Because each project needs to keep track of which version of eslint and eslint things it’s using, and other developers need to be able to use those too.

If you have a thousand projects on your machine, you should have a thousand copies of eslint installed as well.

**Comment by ackava** [comment]
Problems with local install, 
1. Biggest problem is conflicting packages used by eslint and our development projects. Either eslint is using different version because it hasn't upgraded or we are using different version due to lack of support of certain feature. This is the reason we are still using global old tslint, it allows us keeping our stuff separate.
2. Projects stay old, unless we manually go in each project to upgrade code stays as it is.
3. Switching between different projects with different eslint is nightmare as either we go and upgrade all projects or switch our styles.

I feel every argument for keeping local eslint far less important then keeping our development workflow conflict free.

**Comment by nzakas** [comment]
@blindspeed90 if you are willing to submit a pull request with tests, we can consider changing this.

**Comment by nzakas** [comment]
No response, so closing.
