### ISSUE TITLE
Change: (parserOptions: ecmaVersion reporting) Descriptive Error Messages on Invalid Syntax

### ISSUE THREAD

**Issue by wunderBarr7** [eslint/eslint#15264]
### ESLint version

8.1.0

### What problem do you want to solve?

In the event syntax is found which is not supported in the specified `ecmaVersion`, append which syntactic feature is the culprit and which version it is a feature of.

### What do you think is the correct solution?

I'd like EsLint to add more descriptive information to parsing error messages in the event the error occurs from a syntax feature not present in the specified `ecmaVersion`.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

Examples include:

.eslintrc.json
``
{
    "parserOptions": 
     {
          "ecmaVersion": 6,
          ... } }
``

`let a = async function() { ... };`

Current error message: `"Parsing error: Unexpected token function"`

Proposed new output: `"Parsing error: Unexpected token function. Culprit: 'async' keyword introduced in ECMAScript 2017, esLint settings: ES6"`

`/(?:\s*(?<!\\),\s*)+/gm`

Current error message: `"Parsing error: Invalid regular expression: /(?:\s*(?<!\\),\s*)+/: Invalid group"`

Proposed new output: `"Parsing error: Invalid regular expression: /(?:\s*(?<!\\),\s*)+/: Invalid group. Culprit '(?< )' regular expression negative lookbehind introduced in ECMAScript 2018, esLint settings: ES6"`

The proposed outputs are merely suggestions, however they convey the idea.

**Comment by mdjermanovic** [comment]
Hi @wunderBarr7, thanks for the issue!

I agree that this would be useful.

However, ESLint itself doesn't parse code and doesn't produce parsing errors. Parsing errors are coming from parsers, so this is something that could only be done in the parser. There are indeed some parsers that produce these kinds of messages (for example, [tenko](https://astexplorer.net/#/gist/bd26c2cd7917aeb397fe7982c85464e3/f4697bd0958a43b18f5e6eda7c263f7ecde7b22c)).

ESLint's default parser is Espree, which is built on top of Acorn. If you'd like to leave this suggestion there, here's the repository:

https://github.com/acornjs/acorn

I'm closing this issue since it isn't actionable in ESLint.
