### ISSUE TITLE
Bug: calculateConfigForFile returns a promise when it doesn't need to

### ISSUE THREAD

**Issue by geek** [eslint/eslint#15274]
### Environment

Node version: 16
npm version: 7
Local ESLint version: 8.2.0
Global ESLint version: 8.2.0
Operating System: mac

### What parser are you using?

Default (Espree)

### What did you do?

<summary>calculateConfigForFile exported by eslint is async when it doesn't need to</summary>

### What did you expect to happen?

Only functions that are async are marked as such

### What actually happened?

calculateConfigForFile is marked as async

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @geek, thanks for the issue!

This method is intentionally async, per https://github.com/eslint/rfcs/pull/40. Please see [this section](https://github.com/eslint/rfcs/tree/main/designs/2019-move-to-async-api#-the-other-methods) for the reasoning (note that `getConfigForFile` was later renamed to `calculateConfigForFile`). Also, the new flat config system we're working on (https://github.com/eslint/eslint/issues/13481) supports [async config functions](https://github.com/eslint/rfcs/tree/main/designs/2019-config-simplification#can-a-config-be-an-async-function), so that is another reason why this method must be async.
