### ISSUE TITLE
Change Request: lintFiles without `node:fs`

### ISSUE THREAD

**Issue by jimmywarting** [eslint/eslint#15341]
### ESLint version

v8.0.0

### What problem do you want to solve?

I wan't to run some lint stuff against files that are only held in memory or originating from [native file system access](https://web.dev/file-system-access/). so it could possible run in the browser. 
so `eslint.lintFiles(glob_patterns)` doesn't really cut the mustard, in fact any use of `node:fs` would not work...

I want to be able to add files manually.

### What do you think is the correct solution?

I wish there was some possible way to resolve/walk files manually (in a async manner) that could return a File or Directory handle instead.

Something that resolves to something similar to [vinyl-fs](https://github.com/gulpjs/vinyl-fs)... aka:
A class holding metadata such as name, size, type, a method to read/write to but with a newer spec'ed api using: [FileSystemFileHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle) and [FileSystemDirectoryHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle)

so something like:
```js
const root = await navigator.storage.getDirectory()
const dirHandle = await root.getDirectoryHandle('project-xyz')

eslint.lintFiles('*.js', dirHandle)
```

or something more generic that isn't tied to any system: 
```js
const root = await navigator.storage.getDirectory()
const dirHandle = await root.getDirectoryHandle('project-xyz')

eslint.lintFiles('*.js', {
  async listDir(x) {
    return ['foo.js']
  },
  async readFile(path) {
    return dirHandle.getFileHandle(path).then(handle => handle.getFile()).then(file => file.text())
  }
})
```

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by jimmywarting** [comment]
Applying a [onion-architecture](https://www.codeguru.com/csharp/understanding-onion-architecture/) strategy would be handy to kind of make it more browser/Deno friendly 

abstract away the higher core function for something that can be replaced with a configuration of your own, the less eslint has access to node's core module the better...

**Comment by nzakas** [comment]
Why don’t you use lintText() for this? lintFiles() is strictly meant for file system usage.

**Comment by jimmywarting** [comment]
i want to lint more than just one file, plus some lint rule/stuff can validate files related to other files like "./xyz/foo.js" don't export a method "xyz"

**Comment by nzakas** [comment]
This would be a pretty significant change for a very narrow use case. At this point, I’m not sure it’s worth the effort, but if you want to put together an RFC to describe how you envision implementing it, we can consider it.

**Comment by nzakas** [comment]
Closing as we won’t be moving forward with this.

**Comment by EloB** [comment]
@nzakas I might have another use case for this. I'm not sure that it needs to be extensible fs but it might be good.

# My current problem
The project I've joined had a broken Eslint configured for quite awhile. Don't ask me why. So they piled up a lot issues approx 20k warnings/error. A lot of these were fixable by `--fix` but they still have a lot of issues and they will never prioritize this. I'm pretty sure a lot of developers faced this when they can't convince non-tech stakeholders about this issue.

# Theoretical problems
- Another problem I've come up with is when you want to add Eslint to an existing project and pick a strict preset like Airbnb's.
- Another problem might be when you add or modify a rule.

Both these might introduce a lot of lint issues. If you then are using for instance `husky` and `lint-staged` you might be forced to fix lint issues and you will probably think twice before you do above. In my current project they have some really nasty lint issues that will take some time to fix. I still need to be productive and don't want to create a bad routine of always `--no-verify`.

## My solution
I've created a small cli tool that runs Eslint on both HEAD and staged files then compares the result and fails the process if it contains any new errors. The script is more or less in POC state.

<details>
  <summary>Click here to show code</summary>
  
```js
// eslint-disable-next-line import/no-extraneous-dependencies
const { ESLint } = require('eslint');
const { promisify } = require('util');
const cp = require('child_process');
const path = require('path');

const exec = promisify(cp.exec);
const ERROR = 2;

const rootPath = path.resolve(__dirname, '..', '..');
const files = process.argv.slice(2).map((filePath) => path.relative(rootPath, filePath));

const getFile = async (file, revision) => (await exec(`git show ${revision}:${file}`)).stdout;

const hasErrors = (reports = []) => reports.some(({ errorCount }) => errorCount);

const groupErrors = (reports) =>
  reports.reduce((obj, { filePath, messages }) => {
    messages.forEach(({ ruleId, message, severity }) => {
      if (severity !== ERROR) return;
      const key = JSON.stringify([filePath, ruleId, message]);
      obj[key] ??= 0; // eslint-disable-line no-param-reassign
      obj[key] += 1; // eslint-disable-line no-param-reassign
    });
    return obj;
  }, {});

const testFile = async (eslint, filePath, revision = '') => {
  const content = await getFile(filePath, revision);
  return eslint.lintText(content, { filePath });
};

const errorOutput = async (eslint, reports) => {
  const formatter = await eslint.loadFormatter();

  console.log('ESLint contains new errors');
  console.log(formatter.format(reports));

  process.exit(1);
};

const eslintApi = new ESLint();

const next = async () => {
  const filePath = files.shift();
  if (!filePath) return null;
  if (filePath.startsWith('..')) return next();
  const newReport = await testFile(eslintApi, filePath);
  if (!hasErrors(newReport)) return next();
  try {
    const oldReport = await testFile(eslintApi, filePath, 'HEAD~1');

    const newGroup = groupErrors(newReport);
    const oldGroup = groupErrors(oldReport);

    if (Object.entries(newGroup).some(([key, value]) => value > (oldGroup[key] ?? 0)))
      throw new Error('Contains new errors');
  } catch (e) {
    console.log(e);
    await errorOutput(eslintApi, newReport);
  }
  return next();
};
next();
```
</details>

I think this could be simplified a lot. Something that I've noticed. This is my first time using the Eslint API directly instead of CLI tool. Is that for instance `import/no-unresolved` doesn't really work when using `eslint.lintText(code, { filePath })`. Do you think this feature request might solve this?
