### ISSUE TITLE
Bug: prefer-destructuring couldn't auto fix in this condition 

### ISSUE THREAD

**Issue by zzzgit** [eslint/eslint#15379]
### Environment

Node version: new
npm version: new 
Local ESLint version: new 
Global ESLint version: new 
Operating System: macos

### What parser are you using?

Default (I don't know)

### What did you do?

![image](https://user-images.githubusercontent.com/1060733/144435528-9c12eb25-dc55-473f-995a-b73c6051c9e5.png)

### What did you expect to happen?

The above is a `typescript` code snippet. 

`eslint` could correctly lint it but it couldn't fix it automatically. The lint tip is as this: `Use array destructuring. eslint(prefer-destructuring)`

So, I don't what's the problem.

### What actually happened?

only lint here, no auto-fix available.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by zzzgit** [comment]
Okay, I now know how to fix it.

I should change this line from

`[card] = this.getShoe().deal()`

to 

`;[card] = this.getShoe().deal()`

However, it's not a pretty way I think. Is there any other means I can use?

**Comment by mdjermanovic** [comment]
Hi @zzzgit, thanks for the issue!

> `eslint` could correctly lint it but it couldn't fix it automatically. The lint tip is as this: `Use array destructuring. eslint(prefer-destructuring)`

This works as intended. Array destructuring isn't autofixable because the rule can't know for sure if the object on the right side is an array or just an object with a `"0"` property.

For example:

```js
function deal() {
    return { 0: "foo" }
}

let card
card = deal()[0] // 'foo'
```

Autofixing this to array destructuring would produce invalid code:

```js
function deal() {
    return { 0: "foo" }
}

let card
;[card] = deal() // Uncaught TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
```

The above example is actually a false positive for this rule, but since it's rare to have non-array objects with such properties, user can add an `// eslint-disable-line prefer-destructuring` comment. However, even though it is a rare case, fixes should be always safe, so we decided not to autofix array destructuring.

> `;[card] = this.getShoe().deal()`
> 
> However, it's not a pretty way I think. Is there any other means I can use?

That's exactly the expected code in this case. If you do not want to use array destructuring outside declarations, you can configure the rule with `"AssignmentExpression": { "array": false }`.
