### ISSUE TITLE
Bug: 'PATHEXT' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by q00u** [eslint/eslint#15403]
### Environment

Node version: v16.13.1
npm version: 8.2.0
Local ESLint version: 8.4.1
Operating System: Windows 10 (21H2, Build 19044.1348)

### What parser are you using?

Default (Espree)

### What did you do?

```
I ran .\node_modules\.bin\eslint --init
```
I selected `style` `esm` `No` `guide` `JSON`

Installed the dependencies for airbnb, and .eslintrc.json was successfully created.

And then it says:
```
D:\dev\advent2021>PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.CPL
'PATHEXT' is not recognized as an internal or external command,
operable program or batch file.

D:\dev\advent2021>endLocal   & goto #_undefined_#   2>NUL  || title C:\WINDOWS\system32\cmd.exe   & ""  "\..\eslint\bin\eslint.js" --init
'""' is not recognized as an internal or external command,
operable program or batch file.
```

Broken batch file, maybe?

### What did you expect to happen?

No errors

### What actually happened?

```
D:\dev\advent2021>PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.CPL
'PATHEXT' is not recognized as an internal or external command,
operable program or batch file.

D:\dev\advent2021>endLocal   & goto #_undefined_#   2>NUL  || title C:\WINDOWS\system32\cmd.exe   & ""  "\..\eslint\bin\eslint.js" --init
'""' is not recognized as an internal or external command,
operable program or batch file.
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by aladdin-add** [comment]
> D:\dev\advent2021>PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.CPL

seems the error was from your input, not running by eslint.

reminder: once you created the `.eslintrc*`, you can run `npx eslint .` to lint your files.

**Comment by q00u** [comment]
What input?

**Comment by aladdin-add** [comment]
D:\dev\advent2021>PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.CPL

what's it used for?

**Comment by q00u** [comment]
I didn't add that. I didn't run that. That came from the `eslint --init`. THAT's the bug I'm reporting.

**Comment by mdjermanovic** [comment]
> D:\dev\advent2021>PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.CPL
> 'PATHEXT' is not recognized as an internal or external command,
> operable program or batch file.
> 
> D:\dev\advent2021>endLocal   & goto #_undefined_#   2>NUL  || title C:\WINDOWS\system32\cmd.exe   & ""  "\..\eslint\bin\eslint.js" --init
> '""' is not recognized as an internal or external command,
> operable program or batch file.

These commands are from `.\node_modules\.bin\eslint.cmd` script that was [created by `npm`](https://github.com/npm/cli/blob/4dbeb007d0d6350284c7b1edbf4d5b0030c67c66/node_modules/cmd-shim/index.js#L107-L113).

`.\node_modules\.bin\eslint` runs `eslint.cmd`, which then runs `node D:\...\node_modules\eslint\bin\eslint.js`.

What looks strange here is that the command should be `SET PATHEXT=.COM;...` instead of `PATHEXT=.COM;...`, and that these commands were run after eslint finished. 

It's possible that this happened:

1. `.\node_modules\.bin\eslint --init` runs `eslint.cmd` script.
2. The script then runs `node ...\eslint\bin\eslint.js --init`.
3. In one of the `eslint --init` steps, `npm install` is called.
4. `npm install` overwrites `eslint.cmd` with a newer version (maybe you recently upgraded `node`/`npm`?)
5. eslint finishes and exits, but  `eslint.cmd` is still running.
6. Script interpreter loads new `eslint.cmd` and continues from the same offset, which happens to be at `PATHEXT=.COM;...` in the new version.

> ```
> I ran .\node_modules\.bin\eslint --init
> ```
> 
> I selected `style` `esm` `No` `guide` `JSON`
> 
> 
> Installed the dependencies for airbnb, and .eslintrc.json was successfully created.

Can you repeat the same steps and see if this will happen again?

**Comment by q00u** [comment]
Same ouput.

```
found 0 vulnerabilities
Successfully created .eslintrc.json file in D:\dev\advent2021

D:\dev\advent2021>PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.CPL 
'PATHEXT' is not recognized as an internal or external command,
operable program or batch file.

D:\dev\advent2021>endLocal   & goto #_undefined_#   2>NUL  || title C:\WINDOWS\system32\cmd.exe   & ""  "\..\eslint\bin\eslint.js" --init
'""' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by q00u** [comment]
Running on a different computer, I got:

```
Successfully created .eslintrc.json file in C:\Users\pgabriel\dev\temp\aoc2021\advent2021

C:\Users\pgabriel\dev\temp\aoc2021\advent2021>slint\bin\eslint.js" --init
The system cannot find the path specified.

C:\Users\pgabriel\dev\temp\aoc2021\advent2021>ENDLOCAL

C:\Users\pgabriel\dev\temp\aoc2021\advent2021>EXIT /b 3
```

**Comment by mdjermanovic** [comment]
Can you share the content of `.\node_modules\.bin\eslint.cmd`, and also check was it changed after `eslint --init` finishes?

**Comment by q00u** [comment]
eslint.cmd as it exists upon running `yarn install eslint`:

```cmd
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\eslint\bin\eslint.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\eslint\bin\eslint.js" %*
)
```

eslint.cmd as it exists after running `.\node_modules\.bin\eslint --init`:

```cmd
@ECHO off
GOTO start
:find_dp0
SET dp0=%~dp0
EXIT /b
:start
SETLOCAL
CALL :find_dp0

IF EXIST "%dp0%\node.exe" (
  SET "_prog=%dp0%\node.exe"
) ELSE (
  SET "_prog=node"
  SET PATHEXT=%PATHEXT:;.JS;=;%
)

endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "%_prog%"  "%dp0%\..\eslint\bin\eslint.js" %*
```

**Comment by mdjermanovic** [comment]
> eslint.cmd as it exists upon running `yarn install eslint`:
> 
> ```batchfile
> @IF EXIST "%~dp0\node.exe" (
>   "%~dp0\node.exe"  "%~dp0\..\eslint\bin\eslint.js" %*
> ) ELSE (
>   @SETLOCAL
>   @SET PATHEXT=%PATHEXT:;.JS;=;%
>   node  "%~dp0\..\eslint\bin\eslint.js" %*
> )
> ```
> 
> eslint.cmd as it exists after running `.\node_modules\.bin\eslint --init`:
> 
> ```batchfile
> @ECHO off
> GOTO start
> :find_dp0
> SET dp0=%~dp0
> EXIT /b
> :start
> SETLOCAL
> CALL :find_dp0
> 
> IF EXIST "%dp0%\node.exe" (
>   SET "_prog=%dp0%\node.exe"
> ) ELSE (
>   SET "_prog=node"
>   SET PATHEXT=%PATHEXT:;.JS;=;%
> )
> 
> endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "%_prog%"  "%dp0%\..\eslint\bin\eslint.js" %*
> ```

This seems to be exactly as described in https://github.com/eslint/eslint/issues/15403#issuecomment-989970171. `eslint.cmd` runs ESLint and waits. ESLint runs `npm install`, which modifies `eslint.cmd`. Then, the cmd interpreter detects a change, reloads `eslint.cmd`, and continues executing from the next byte offset (189), which is the space just before `PATHEXT=` in the new version of `eslint.cmd`. It's a side effect of running a command (`npm install`) that modifies `node_modules` by a package (ESLint) installed in the same `node_modules`.

This issue will be fixed by extracting `eslint --init` into a separate package (https://github.com/eslint/eslint/issues/14768).
