### ISSUE TITLE
Change Request: support for experimental import assertions syntax

### ISSUE THREAD

**Issue by mizozobu** [eslint/eslint#15623]
### ESLint version

v8.9.0

### What problem do you want to solve?

Node.js v16.14.0 is now LTS, and [importing JSON modules now requires experimental import assertions syntax](https://nodejs.org/en/blog/release/v16.14.0/#importing-json-modules-now-requires-experimental-import-assertions-syntax).

```js
import info from './package.json' assert { type: 'json' };
const info = await import('./package.json', { assert: { type: 'json' } });
```

Currently ESlint `v8.9.0` gives `Parsing error: Unexpected token assert`.

### What do you think is the correct solution?

- Support for experimental import assertions syntax right away.
- Exclude node v16.14.0 or higher from `engines` in `package.json` until experimental import assertions syntax is supported in eslint.
    https://github.com/eslint/eslint/blob/345e70d9d6490fb12b18953f56f3cea28fd61d83/package.json#L147-L149
- Maybe not support experimental import assertions syntax until `--experimental-json-modules` is unflaged in nodejs (and document it).

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @mizozobu, thanks for the issue!

> Currently ESlint `v8.9.0` gives `Parsing error: Unexpected token assert`.

As described in our [policies around experimental syntax](https://github.com/eslint/eslint#what-about-experimental-features), ESLint's default parser only supports the latest ECMAScript standard. The [Import Assertions proposal](https://github.com/tc39/proposal-import-assertions) is still in Stage 3. If and when the proposal reaches Stage 4, ESLint's default parser will support this syntax.

In the meantime, you can use ESLint with [@babel/eslint-parser](https://www.npmjs.com/package/@babel/eslint-parser).

> * Exclude node v16.14.0 or higher from `engines` in `package.json` until experimental import assertions syntax is supported in eslint

The [engines](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines) field specifies Node versions where the package works on, and ESLint works on Node v16.14.0 or higher because the published ESLint package doesn't use any features that are not supported on Node v16.14.0 or higher.
