### ISSUE TITLE
Bug: can't escape `]` in `.eslintignore`

### ISSUE THREAD

**Issue by beltekylevi** [eslint/eslint#15642]
### Environment

Node version: v14.17.0
npm version: v8.3.0
Local ESLint version: v8.9.0 (Currently used)
Global ESLint version: Not found
Operating System: darwin 21.2.0

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```js
module.exports = {
  rules: {
    "no-console": "error",
  },
};

```
</details>

I've set up [minimal example repository](https://github.com/beltekylevi/eslint-eslintignore-glob-pattern-issue) to reproduce the issue but I'll describe the issue here as well.

I have a few files and some of them contain special characters like `[`.
```
➜  eslint-eslintignore-glob-pattern-issue git:(main) ✗ find src
src
src/index].js
src/[index].js
src/index.js
src/[index.js
```

I'd like to ignore all of them so I have them listed in an `.eslintignore` using `\` to escape the special characters.
```
➜  eslint-eslintignore-glob-pattern-issue git:(main) ✗ cat .eslintignore 
src/index.js
src/\[index.js
src/index\].js
src/\[index\].js
```

### What did you expect to happen?

All files listed in `.eslintignore` to be ignored, zero errors.

### What actually happened?

Two of the files won't be ignored when I lint them using ESLint.
```
➜  eslint-eslintignore-glob-pattern-issue git:(main) ✗ npm run lint

> eslint-eslintignore-glob-pattern-issue@1.0.0 lint
> eslint '**/*.js' --ignore-path .eslintignore


[removed]/eslint-eslintignore-glob-pattern-issue/src/[index].js
  1:1  error  Unexpected console statement  no-console

[removed]/eslint-eslintignore-glob-pattern-issue/src/index].js
  1:1  error  Unexpected console statement  no-console

✖ 2 problems (2 errors, 0 warnings)
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

The same glob patterns work in `.gitignore`.

```
➜  eslint-eslintignore-glob-pattern-issue git:(main) cat .gitignore
node_modules/
src/\[app\].js
src/app\].js
➜  eslint-eslintignore-glob-pattern-issue git:(main) git status --ignored
On branch main
Ignored files:
  (use "git add -f <file>..." to include in what will be committed)
        node_modules/
        src/[app].js
        src/app].js

nothing to commit, working tree clean
```

**Comment by mdjermanovic** [comment]
Hi @beltekylevi, thanks for the issue!

This seems to be a bug in ignore v4.0.6:

```js
const ignore = require("ignore");

// logs `false` with ignore v4.0.6, `true` with ignore v5.2.0
console.log(
    ignore().add("src/\\[index\\].js").ignores("src/[index].js")
);

```

The bug was fixed in [v5.1.5](https://github.com/kaelzhang/node-ignore/releases/tag/5.1.5) ("fixes escaping for square brackets"), but `@eslint/eslintrc` still [uses v4.0.6](https://github.com/eslint/eslintrc/blob/9b719813fc6f023b722168a4f67d895106e875ce/package.json#L72).

We could update the dependency in `@eslint/eslintrc` to `"ignore": "^5.2.0"` and this issue would most likely be fixed (we would certainly add tests to confirm). Since ignore v5 has a breaking change, we should probably use it with `{ allowRelativePaths: true }` option to get the v4 behavior that eslintrc might be relying on, as we did in https://github.com/eslint/eslint/pull/15439 for eslint/eslint.

That update seems a bit risky though, and eslintrc will be replaced by the new config system in the next major release anyway. 

@nzakas what do you think, should we switch to ignore v5.2.0 in `@eslint/eslintrc` and see what happens?

**Comment by nzakas** [comment]
I’d like to avoid anything that changes how eslintrc behaves at this point, as that will make the new config system work more complicated. If we can upgrade without affecting any existing tests, then I think that’s okay, but if we need to change any existing tests then we should wait for the new config system.

**Comment by snitin315** [comment]
I tried upgrading `ignore` in https://github.com/eslint/eslintrc/pull/72 and it doesn't affect any existing tests.

**Comment by snitin315** [comment]
Let's keep it open until we update `eslintrc` in `eslint` itself. - https://github.com/eslint/eslint/pull/15666

**Comment by beltekylevi** [comment]
Many thanks for your work.
