### ISSUE TITLE
Change Request: Add specific links to labels in the Contributing Guidelines

### ISSUE THREAD

**Issue by kinb98** [eslint/eslint#15864]
### ESLint version

v8.15.0

### What problem do you want to solve?

Currently in the contributing guidelines, in the [working on Issues](https://eslint.org/docs/developer-guide/contributing/working-on-issues) page, there are various labels mentioned (like bug, good-first-issue etc.) but only some of those point to the url of those labels in the Issues page.

![Screenshot of Guidelines](https://user-images.githubusercontent.com/34712617/167676370-bdc38677-11dc-425b-95f7-f74b5779702b.png)

### What do you think is the correct solution?

The best solution is to change all those labels with their respective urls on the issues page for direct and easy access.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I can work on this if the team agree to it.

**Comment by mdjermanovic** [comment]
Hi @kinb98, thanks for the suggestion!

I believe it's intentional that only labels we're using for accepted issues have links pointing to the list of issues, because those are the only issues that are ready to implement and thus the issues we want to direct new contributors to.

We had links for other labels, but we removed them in https://github.com/eslint/eslint/commit/7d390b29272cef351d95ed5950a0bcec2be6725e.

**Comment by nzakas** [comment]
We aren’t making any changes here, so closing.
