### ISSUE TITLE
Change Request: Autofix eqeqeq when set to "smart"

### ISSUE THREAD

**Issue by whaaaley** [eslint/eslint#15900]
### ESLint version

8.14.0

### What problem do you want to solve?

Auto fixing `eqeqeq` was removed a long time ago https://github.com/eslint/eslint/issues/4578

Could auto fix for `eqeqeq` be added again but in a limited capacity, just for `smart`? Which are the safe places to use `==`?

### What do you think is the correct solution?

Autofix `eqeqeq` when set to `smart` and `smart` only.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @whaaaley, thanks for the issue!

Can you provide a few examples of code that could be autofixed?

**Comment by whaaaley** [comment]
Sure! Basically only these cases mentioned here: <https://eslint.org/docs/rules/eqeqeq#smart>
+ Comparing two literal values
+ Evaluating the value of `typeof`
+ Comparing against `null`

The following:
```js
typeof foo === 'undefined'
'hello' !== 'world'
0 === 0
true === true
foo === null
```

Would become:
```js
typeof foo == 'undefined'
'hello' != 'world'
0 == 0
true == true
foo == null
```

I'd like this just for consistency within files when using the `smart` option.

**Comment by mdjermanovic** [comment]
> The following:
> 
> ```js
> typeof foo === 'undefined'
> 'hello' !== 'world'
> 0 === 0
> true === true
> foo === null
> ```
> 
> Would become:
> 
> ```js
> typeof foo == 'undefined'
> 'hello' != 'world'
> 0 == 0
> true == true
> foo == null
> ```

Thanks for clarifying! But given how the rule works, this looks like a request for different functionality of the `"smart"` option rather than just autofixing, because `"smart"` allows all these cases, as in [this demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnQgZXFlcWVxOiBbXCJlcnJvclwiLCBcInNtYXJ0XCJdKi9cblxuLy8gdGhlc2UgYXJlIGFsbG93ZWRcbnR5cGVvZiBmb28gPT09ICd1bmRlZmluZWQnXG4naGVsbG8nICE9PSAnd29ybGQnXG4wID09PSAwXG50cnVlID09PSB0cnVlXG5mb28gPT09IG51bGxcblxuLy8gdGhlc2UgYXJlIGFsbG93ZWQsIHRvb1xudHlwZW9mIGZvbyA9PSAndW5kZWZpbmVkJ1xuJ2hlbGxvJyAhPSAnd29ybGQnXG4wID09IDBcbnRydWUgPT0gdHJ1ZVxuZm9vID09IG51bGwiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7fSwiZW52Ijp7fX19).

```js
/*eslint eqeqeq: ["error", "smart"]*/

// these are allowed
typeof foo === 'undefined'
'hello' !== 'world'
0 === 0
true === true
foo === null

// these are allowed, too
typeof foo == 'undefined'
'hello' != 'world'
0 == 0
true == true
foo == null
```

> Could auto fix for `eqeqeq` be added again but in a limited capacity, just for `smart`? Which are the safe places to use `==`?

We can't autofix code that isn't reported as a problem. Since the `"smart"` option does not actually enforce the use of `==` instead of `===` in these examples, it isn't likely that this rule was ever autofixing them.

**Comment by nzakas** [comment]
We won’t be making a change here, so closing.
