### ISSUE TITLE
Bug: inconsistent ignoring files

### ISSUE THREAD

**Issue by vitonsky** [eslint/eslint#15931]
### Environment

Node version: 14.18
npm version: 6.14.15
Local ESLint version: 7.32
Global ESLint version: 7.32
Operating System: ubuntu

### What parser are you using?

@typescript-eslint/parser

### What did you do?

- add `node_modules` to `.eslintignore` file
- run `eslint --fix **/*.{ts,tsx,js}`

### What did you expect to happen?

All files in project except `node_modules` will scanned and fixed

### What actually happened?

Eslint confused and don't understand what i want. Eslint display a weird and pointless suggestions.

![image](https://user-images.githubusercontent.com/86191922/170837514-5db086a5-c368-464c-b394-b131c259d6b9.png)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Probably it may be solved if i will modify comand `eslint --fix **/*.{ts,tsx,js}` to exclude `node_modules`, but in this case a file `.eslintignore` absolutely useless, so i don't think it's expected behavior

**Comment by mdjermanovic** [comment]
Hi @vitonsky, thanks for the issue!

> * run `eslint --fix **/*.{ts,tsx,js}`

Your shell expands the glob and sends a list of files to eslint, which then sees them as if they were entered one by one on the command line and reports the ignored ones because it assumes you would not want to skip linting any files that were explicitly listed on the command line.

Can you try with quotes:

`eslint --fix "**/*.{ts,tsx,js}"`

This way, eslint will get the glob instead of a list of files.

**Comment by vitonsky** [comment]
Yes, it's solve my problem, thank you.

But what about some CLI flag allowed ignore to all files listed explicitly?

It's useful to other cases. For example, when i use eslint with `lint-staged`, all files will specify explicitly. In case when all these files should be ignored, we may got this error. I got this error just now, but for `stylelint`.

I think it's be useful if we can do something like `eslint --fix --allow-ignore-all foo.js bar.ts`

**Comment by mdjermanovic** [comment]
Actually, for an ignored _file_ eslint will just return a lint warning. In your example, `node_modules/big.js` is a directory (npm package named `big.js`).

Since `lint-staged` specifies a list of files, it should work well because lint warnings do not cause exit with error status.

Unless you're using [`--max-warnings`](https://eslint.org/docs/user-guide/command-line-interface#--max-warnings) flag. For that use case, we have accepted issue https://github.com/eslint/eslint/issues/15010 and we are working on the design in  https://github.com/eslint/rfcs/pull/90 .

**Comment by vitonsky** [comment]
Ok, thanks for explaining. Now all clear for me.
I hope other users will find this page while googling this error.
