### ISSUE TITLE
Rule Change: Maybe prefer-const should not autofix

### ISSUE THREAD

**Issue by cakoose** [eslint/eslint#15943]
### What rule do you want to change?

prefer-const

### What change to do you want to make?

Generate more warnings

### How do you think the change should be implemented?

Other

### Example code

```js
let foundStudent = null;
for (const student of students) {
    if (student.name === targetName) {
        // Bug: we forgot to do 'foundStudent = student' here!
        break;
    }
}
console.log(foundStudent);
```

### What does the rule currently do for this code?

The autofix will change the `let` to a `const`. This fixes the symptom and further hides the true bug.

### What will the rule do after it's changed?

Maybe it's better for prefer-const to _not_ perform any autofixes?

### Participation

- [x] I am willing to submit a pull request to implement this change.

### Additional comments

- The bug in the code is that the programmer forgot to set `foundStudent`.
- The prefer-const rule sort of catches this bug.
- The prefer-const rule's autofix, if applied, would mask this bug!

I think it's common for people to trust the autofixes and not check them, e.g. my team has our IDEs configured to apply all autofixes on save. The prefer-const autofix is dangerous in that it deals with the symptom and hides the root cause.

I noticed there's a 3rd-party ESLint plugin that lets you disable autofixes for specific rules: [eslint-plugin-disable-autofix](https://npm.io/package/eslint-plugin-disable-autofix). Their first example disables the autofix for the the prefer-const rule :-)

**Comment by mdjermanovic** [comment]
> The autofix will change the `let` to a `const`. This fixes the symptom and further hides the true bug.

This indeed looks like a case where autofix for a best practice / stylistic rule hides an actual bug in the code. I think that should be avoided in general.

> Maybe it's better for prefer-const to _not_ perform any autofixes?

Given the above, this seems reasonable. However, this particular autofix is very useful when enabling this rule for the first time in a large codebase. The fix is technically correct as it doesn't change the behavior of the code. If the user doesn't want to manually verify each case, not having the autofix feature could be a blocker for enabling this rule.

> I think it's common for people to trust the autofixes and not check them, e.g. my team has our IDEs configured to apply all autofixes on save. The prefer-const autofix is dangerous in that it deals with the symptom and hides the root cause.

ESLint provides option [`--fix-type`](https://eslint.org/docs/user-guide/command-line-interface#--fix-type) in CLI, `fixTypes` in the [API](https://eslint.org/docs/developer-guide/nodejs-api#-new-eslintoptions).

If your IDE supports this option, you could configure it to autofix on save only `layout` problems. These are problems reported by formatting rules, mostly whitespace-related.

I also wouldn't mind adding an option to disable autofixes (or provide them as suggestions) for specified rules in the eslint config file.

**Comment by cakoose** [comment]
> I also wouldn't mind adding an option to disable autofixes (or provide them as suggestions) for specified rules in the eslint config file.

There was an earlier issue for this: https://github.com/eslint/eslint/issues/7549. That discussion there ended up centering on CLI autofixes vs IDE autofixes. I think a slightly better way to frame it is in terms of autofixes that are always safe vs autofixes that you must explicitly opt in to.

For you example of enabling a new rule in a very large codebase, you can opt in to the more aggressive autofixes after reading the docs. But seems dangerous to have them on by default. Maybe that's what "suggestion" vs "layout" can be used for, but I'm not sure if the rule authors think of them that way.

**Comment by nzakas** [comment]
@mdjermanovic what are you looking for feedback on here?

Im 👎 to disabling autofix for this rule. There will always be edge cases but the utility of this autofix has been proven over time.

**Comment by cakoose** [comment]
Agree that the tool can't always be perfect, but this was the first time I ran into a case where an ESLint rule identifies a real bug (indirectly) and the autofix _masks_ that bug. And, subjectively, the situation didn't feel like _too_ much of an edge case.

But I'm just a casual ESLint user. Maybe someone with more experience knows of other similar autofixes? (As someone who is on the more conservative side, it would be great to know which autofixes should consider turning off for my codebase 😄.)

**Comment by cakoose** [comment]
> The problem is ESLint can’t know what code you forgot to write. 😄

Yes, it can't know for sure, but some assumptions have worse consequences than others. For example, with the trailing whitespace autofix, it's locally predictable and there's very little chance of masking a real bug. With the prefer-const autofix, that's not the case.

If you have a somewhat well-tested codebase that doesn't follow the prefer-const rule, I can see how the autofix is useful for getting everything converted over to the prefer-const style.

But if you're programming in a codebase that follows the prefer-const rule, you typically only type `let` when you intend to modify the variable later. And if you forget to do that, it's nice to have the linter say "hey, this is weird" rather than throwing away your original intent.

> Generally the best time to autofix is on precommit, so you know the code is as complete as possible.

Are you taking about at `git commit` time or `git push` time? I think `git commit` time is way too early, since people often commit to save their incomplete work, e.g. at the end of the day or when switching branches to look at something else.

Even at `git push` time, I don't think the code is as complete as possible. Bugs slip through that phase all the time and even at that point I'd rather have ESLint report a potential bug rather than hide it.

**Comment by nzakas** [comment]
@cakoose Again, we just can't know every situation for everyone's code. We aim to get things right 90% of the time, and given how long this rule has been around, I think we are hitting that. I'm sorry it didn't work for your use case, but I don't think that necessarily means we need to make a change. But maybe someone else on the team feels differently.

I don't think it's worth either of our time to debate back and forth where there is already clearly disagreement, so I'll leave my last comment as my final input unless another team member wants to chime in with a different opinion.

**Comment by cakoose** [comment]
I also don't want to rehash points where we fully understand each other but simply disagree. But your reply of "we just can't know every situation for everyone's code" made me think maybe there's still a misunderstanding?

To clarify where I'm coming from:
1. I don't expect ESLint to work for every situation for everyone's code. But that doesn't mean there's never room for improvement.
2. I'm not only thinking about my use case. I've already used [eslint-plugin-no-autofix](https://www.npmjs.com/package/eslint-plugin-no-autofix) to disable the prefer-const autofix in my codebases. The point of filing this issue is to make ESLint better for everyone.

The problem with the prefer-const autofix is subtle. I've been using ESLint for years and only noticed it recently. And it surprised me because it seems more dangerous than any other autofix.

But I'm just a regular user, so I haven't accumulated the broad experience that the ESLint maintainers have. That's why I'm genuinely curious -- are there any other autofixes that are similarly dangerous? Is prefer-const the only one so far?

**Comment by JounQin** [comment]
The bug is introduced by yourself, not autofixing IMO.

**Comment by mdjermanovic** [comment]
I'm not in favor of removing the autofix feature from the `prefer-const` rule.

I would be in favor of adding a configuration option to disable autofixing for specified rules. We tend not to provide autofixes that could mask bugs. For example, `no-unused-vars` could automatically remove unused variable declarations, but that might mask a bug in the form of missing code that was intended to use those variables. The same can be said for `prefer-const` - maybe the code that was intended to reassign the variable is missing. Since this is subjective, I wouldn't be opposed to providing a way for users to disable autofixes that they consider unsafe.

**Comment by cakoose** [comment]
Does anybody have ideas for the user experience of such a feature? Some ideas:

Option A:
- Allow the rule/autofix metadata to declare itself as "potentially dangerous"
- Have the `prefer-const` autofix declare itself as potentially dangerous.
- Provide an option in eslintrc or as a CLI flag to not apply potentially dangerous autofixes.

Option B:
- Provide a way in eslintrc to disable the autofixes for a rule.
- What should the schema for that look like?

What's nice about option A is it provides good choices for the user. What's nice about option B is that it's more flexible for the user.

**Comment by twohair** [comment]
I think it should be fixed automatically before committing.

**Comment by nzakas** [comment]
> Provide a way in eslintrc to disable the autofixes for a rule.

I think there is a lot hidden complexity down this path. We will need to consider shareable configs closely in this, because if shareable configs turn in auto fixing for all rules, putting it on the consumer of a shareable config to set everything back to default will be a laborious task.

I’m willing to entertain an RFC to convince me otherwise but my initial opinion is that this granularity of control would be destructive for end users.

**Comment by nzakas** [comment]
@mdjermanovic how interested are you in pursuing this idea of individually configuring files for autofixing?
