### ISSUE TITLE
[new docs site] UI bug with on rules index and details pages

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#15977]
For the new documentation site, we have a UI bug when displaying information about recommended/fixable/suggestions on both the rule index page and the rule details pages.

Basically, we can have 0-3 of these showing at any time. When only one is shown, it should take the full width of the page, like this:

![Frame 407](https://user-images.githubusercontent.com/38546/172688886-4cb4aae0-51a3-4031-8b37-b69feda144ff.png)

This part is actually working correctly. 👍 

When two are shown, it should look like this:

![Frame 407](https://user-images.githubusercontent.com/38546/172688815-6bd04506-3d5b-41e1-baea-301cdd743bce.png)

And when three are shown, it should look like this:

![Frame 407](https://user-images.githubusercontent.com/38546/172689051-99ec0f5a-1380-4f72-a281-070cc8a3df0f.png)

The rules index page should always show three, but right now it is not styled correctly and is wrapping to two lines:
https://new.eslint.org/docs/rules/

The rules details pages stack the messages one on top of the other (once this PR is merged: #15902)

**Comment by btmills** [comment]
I believe this is working as intended. In sufficiently wide windows (~1300px), I'm seeing the three side by side on https://new.eslint.org/docs/rules/. On narrower windows, it automatically wraps due to the [`auto-fit` and `minmax` on the `grid-template-columns`](https://github.com/eslint/docs.eslint.org/blob/080f0366a5ac7e30018f9cbd75ee90c1cadafd90/src/assets/scss/components/rules.scss#L1-L17).

![Screen Shot 2022-06-08 at 10 21 50 PM](https://user-images.githubusercontent.com/1709537/172750546-982876e0-2900-4dcb-ba40-80402dcec6c1.png)

**Comment by nzakas** [comment]
Ah gotcha. My screen apparently doesn't go wide enough to see that view.

Then the only outstanding issue is that the background colors and borders are missing.

**Comment by DeepshikaS** [comment]
I would like to work on this. Border and background color needs to be added right?

1. Current UI:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/30730124/174390327-bca34051-2f23-41a4-be3a-2d2043c41c30.png">

2. Expected UI :
<img width="600"  alt="image" src="https://user-images.githubusercontent.com/30730124/174390353-a6c45c99-a2fc-4f67-8094-701e33ddb288.png">

Basically, It should look like the 2nd Image?

**Comment by nzakas** [comment]
Correct. 👍

**Comment by nzakas** [comment]
Fixed by https://github.com/eslint/eslint/pull/16082
