### ISSUE TITLE
.eslintignore itself ignored

### ISSUE THREAD

**Issue by MikeMcl** [eslint/eslint#1601]
I may be re-opening a can of worms best kept closed, but given the directory structure

```
root
|-- foo
|   |-- bar.js
|   |-- .eslintignore
|   |-- .eslintrc
```

I believe that many users (e.g. #1382) would expect the `.eslintignore` file to be applied prior to the linting of `bar.js`, and that the globs in the `.eslintignore` file would be considered relative to the path of the ignore file itself. I also think they would expect this to be true regardless of the directory from which they were executing the ESLint command-line tool.

But currently,  ESLint does not look for an ignore file in directories below the current working directory and globs in an `.eslintignore` file are always considered relative to the cwd. This means that the ignore file in the directory structure above will be ignored when linting the `foo` directory with

```
root$ eslint foo
```

This behaviour is inconsistent with that of the `.eslintrc` file in the directory structure which will be applied irrespective of the cwd, and a further inconsistency is that all `.eslintrc` and `package.json` files in the directory and parent directories of a linted file are applied, rather than only one file as is the case with the `.eslintignore`.

I think that `.eslintignore` files should be treated in the same way as `.eslintrc` files so all such files in parent directories are applied, with lower directories taking precedence over higher. This would also be consistent with how git treats `.gitignore` files (although git only looks up to the top of the work tree not the file system).

> Patterns read from a .gitignore file in the same directory as the path, or in any parent directory, with patterns in the higher level files (up to the toplevel of the work tree) being overridden by those in lower level files down to the directory containing the file. These patterns match relative to the location of the .gitignore file.
> [git-scm.com](http://git-scm.com/docs/gitignore).

I would be interested in attempting to implement the following:
- An `.eslintignore` file is looked for in the directory of the file being linted and in its parent directories, irrespective of the cwd.
- The globs in the `.eslintignore` file are considered relative to the directory in which it resides.
- All `.eslintignore` files are applied from parent directories up to the file system root.

Looking through the issues I can see that the latter used to be the implemented behaviour, which was then changed due to performance and other issues #928  #1069 #930.

Nevertheless, I still think that ideally the above should apply. If it is found to be too expensive in terms of performance, then I would agree that it is better to stick with the current behaviour.

**Comment by segrey** [comment]
>The globs in the .eslintignore file are considered relative to the directory in which it resides.

@nzakas If I understand correctly, current eslint behavior is to evaluate the globs of .eslintignore relative to the current working directory. What current working directory should IDE specify when running eslint? The problem is that IDE doesn't know how globs from .eslintignore were developed. Let's consider the following sample project structure
```
└── app
    ├── client
    │   └── .eslintignore
    │   └── .eslintrc
    └── server
         └── .eslintignore
         └── .eslintrc
```
If `app/` directory opened in IDE, IDE considers `app/` as a root project directory. But specifying `app/` directory as a current working directory when running eslint is incorrect if globs from `client/.eslintignore` (`server/.eslintignore`) were developed to match files relative to `app/client/` (or `app/server/`).

**Comment by nzakas** [comment]
I'm not sure what you're asking. You can only have one .eslintignore file at the root of the project.

**Comment by segrey** [comment]
The question is what current working directory should IDE specify with running eslint?

**Comment by nzakas** [comment]
The root of the project.

**Comment by segrey** [comment]
That's correct, but it isn't always clear where the root of the project is, if the project contains several sub-projects. Please see my previous example. For example, some people would like to work on both `client/` and `server/` assuming the root of the project is `app/`. Others would prefer to work on `client/` only assuming the root of the project is `app/client/`.

**Comment by nzakas** [comment]
Then it would be up to the IDE to sort that out. We don't deal with IDE integrations directly, so you'd need to work with the people who wrote the integration to figure out such cases.

**Comment by segrey** [comment]
Hi,
Sorry for the delay. I think my question isn't fully about IDE integration (but I write ESLint integration for WebStorm), but it's also about how ESLint users realize what working directory should be used when running eslint (e.g. in Terminal). In case of a project that contains several sub-projects (e.g. my example with `client/` and `server/` sub-projects) what working directory would a new developer use to run eslint for .js files in `client/`? If I understand correctly, the new developer should examine patterns from a corresponding `.eslintignore` and use such a working directory that relative paths are matched by these patterns.
If yes, isn't it a complication for eslint usage? I could be wrong though. I'd appreciate any links to discussions that provide insights into pros of the current behavior. Thanks.

Here is how it is implemented in WebStorm (https://youtrack.jetbrains.com/issue/WEB-16314).
WebStorm project model has "Content Root" concept. A content root is a directory opened in WebStorm. It's possible to configure several content roots for a project, but no content root can be an ancestor of some other content root. To guess proper working directory WebStorm does the following. When running eslint for a .js file it finds a content root directory that is an ancestor of the .js file and uses it as a working directory.
It's worth to note that content root is simply an opened directory (via File | Open...). So, eslint working directory depends on opened directory too (e.g. it can be `app/` or `app/client/` from my previous example). That means that the guessed working directory isn't guaranteed to be proper. No idea how it can be improved to guarantee proper eslint working directory.
Thanks.

**Comment by nzakas** [comment]
Go to the root of your project, wherever `package.json` is, and that's where `.eslintignore` should be. I'm not sure why using it is any more complicated than using `package.json` and `npm`. They have the same relationship: one file at the room level, and `npm` CLI can't function without `package.json` in the current working directory.

**Comment by segrey** [comment]
Thank you for the fast reply. Your suggestion makes sense. Thanks. I've changed logic how working directory is calculated. Now it works like this: before linting a JavaScript file, two possible candidates are calculated:
* a content root directory that is an ancestor of the JavaScript file
* a directory that contains `.eslintignore` (searching from the JavaScript file's folder and then moving up to the filesystem root).
If these directories are equal, the working directory is the same.
Otherwise, one of these two directories that is closer to the JavaScript file in filesystem tree is chosen as a working directory.
Doing it in this way allows to eliminate influence of `.eslintignore` files located outside the project (e.g. in home directory).
Although the new logic is better than the old logic, it is still a heuristic. It guesses working directory, but there could be an error if patterns from `.eslintignore` match paths relative to some other directory (not the directory containing the `.eslintignore`).

>Go to the root of your project, wherever package.json is, and that's where .eslintignore should be. I'm not sure why using it is any more complicated than using package.json and npm. They have the same relationship: one file at the room level, and npm CLI can't function without package.json in the current working directory.

The difference between `npm` CLI and `eslint` CLI is that working directory is irreverent for patterns from .npmignore (these patterns match relative to the location of the .npmignore file).
