### ISSUE TITLE
Change Request: replace `js-yaml` with `yaml`

### ISSUE THREAD

**Issue by remcohaszing** [eslint/eslint#16024]
### ESLint version

8.18.0

### What problem do you want to solve?

ESLint doesn’t parse YAML files correctly, because `js-yaml` isn’t strictly compliant with the YAML spefication. I’ve provided some more details in [this discussion answer](https://github.com/orgs/remarkjs/discussions/1006#discussioncomment-2955255).

As a result, tools that do use a spec compliant YAML parser, may interpret `.eslintrc.yaml` configuration files different from ESLint itself.

### What do you think is the correct solution?

I’d like ESLint to replace [`js-yaml`](https://github.com/nodeca/js-yaml) with [`yaml`](https://github.com/eemeli/yaml).

The problem with just replacing it, is that some users may rely on this incorrect behaviour.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

This affects [`@eslint/eslintrc`](https://github.com/eslint/eslintrc) as well.

**Comment by mdjermanovic** [comment]
> ESLint doesn’t parse YAML files correctly, because `js-yaml` isn’t strictly compliant with the YAML spefication. I’ve provided some more details in [this discussion answer](https://github.com/orgs/remarkjs/discussions/1006#discussioncomment-2955255).
> 
> As a result, tools that do use a spec compliant YAML parser, may interpret `.eslintrc.yaml` configuration files different from ESLint itself.

This seems like a breaking change because ESLint could start interpreting existing user configs differently after the change. Since eslintrc config functionalities are frozen, we are not making any changes to the loading of eslintrc YAML config files. The new [Flat Config](https://github.com/eslint/eslint/issues/13481) system will not support YAML config files.

Other than config files, we use `js-yaml` in production only in the `tap` formatter, but I'm not sure if there would be any differences there if we replace the library.

**Comment by nzakas** [comment]
I agree. Given that YAML configs are going away in the near future, I don’t see the value in risking a breaking change at this time.
