### ISSUE TITLE
support hashbang

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint#16158]
### Syntax name

hashbang

### Syntax proposal URL

https://github.com/tc39/proposal-hashbang

### Example code

```js
#!/usr/bin/env node
// in the Script Goal
'use strict';
console.log(1);
```

### Implementation Checklist

- [ ] Ecma262 update: https://github.com/tc39/ecma262/pull/2816
- [ ] ESTree update: 
- [ ] Acorn update: 
- [ ] `eslint-visitor-keys` update: 
- [ ] `espree` update: 
- [ ] `eslint-scope` update: 
- [ ] `eslint` update: 

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Per https://github.com/estree/estree/pull/224, this will not be included in ESTree.

Acorn update: https://github.com/acornjs/acorn/commit/b2ecf7a378097a95c9244209cd5e4aff748c2b2c (released in Acorn v8.8.0)

It doesn't seem that this requires any changes in `eslint-visitor-keys` and `eslint-scope`.

**Comment by mdjermanovic** [comment]
ESLint already supports hashbang comments, regardless of parser and ecmaVersion, by [replacing `#!` with `//`](https://github.com/eslint/eslint/blob/2aadc93272f1ab7f40246c6b18c4056660f2b3a2/lib/linter/linter.js#L779) before parsing to make it appear as a line comment, and then [updating that comment's type to `"Shebang"`](https://github.com/eslint/eslint/blob/2aadc93272f1ab7f40246c6b18c4056660f2b3a2/lib/source-code/source-code.js#L215-L221) after parsing. This comment type is documented in working-with-rules ([Accessing Shebangs](https://eslint.org/docs/latest/developer-guide/working-with-rules#accessing-shebangs)), and core rules for which this is important are already using it. Maybe we should just leave this as is?

Since `espree` can be used separately from ESLint, it seems we should update it to support hashbang comments on its own when ecmaVersion >= 2023.

**Comment by nzakas** [comment]
Yeah, I don’t think a change in ESLint is necessary.

> Since espree can be used separately from ESLint, it seems we should update it to support hashbang comments on its own when ecmaVersion >= 2023.

:+1:

**Comment by aladdin-add** [comment]
closing as completed.
