### ISSUE TITLE
Fix automaticcaly the "sort-keys" rule by alphabetically

### ISSUE THREAD

**Issue by NerOcrO** [eslint/eslint#16167]
### ESLint version

8.20.0

### What problem do you want to solve?

The "sort-keys" is awesome by the fixable command line is not implemented :(
It's boring to do it by hand.

### What do you think is the correct solution?

Some examples where this feature is implemented:
- eslint-plugin-import → [import/order](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md)
- stylelint → [stylelint-order](https://github.com/hudochenkov/stylelint-order)

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

Good job guys!

**Comment by nzakas** [comment]
Thanks for the input. As [stated in the README](https://github.com/eslint/eslint#stylistic-rule-updates), we actually aren't making any further updates to rules that enforce stylistic preferences. If you have a strong preference for such a change, you can always copy the existing rule into a custom rule and make it behave the way you want.

**Comment by JoseLion** [comment]
@nzakas the problem is that it's not possible to do this Prettier. They have also mentioned that it's something [out of the scope of their project](https://github.com/prettier/prettier/issues/1096#issuecomment-291012181). Wouldn't it make sense to add fixers to existing stylistic rules that cannot be accomplished with Prettier or similar? 🤔 It would be an outstanding benefit for rules like this one 🙂

**Comment by bmish** [comment]
There are some third-party versions of this rule that are autofixable, here's one I found after a brief search:

* https://www.npmjs.com/package/eslint-plugin-sort-keys-fix
