### ISSUE TITLE
no-extra-parens rule doesn't work properly

### ISSUE THREAD

**Issue by BIG293** [eslint/eslint#16168]
### Environment

ng lint --fix

### What parser are you using?

@typescript-eslint/parser

### What did you do?

const subject = new ReplaySubject<(number | string)[]>(1)

I've enabled the no-extra-parens rule

### What did you expect to happen?

nothing

### What actually happened?

the invocation parentheses are marked as extra and removed by the --fix option

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @BIG293, thanks for the issue!

For TypeScript code, you should use [`@typescript-eslint/no-extra-parens`](https://typescript-eslint.io/rules/no-extra-parens/) rule instead of the core `no-extra-parens` rule.

If `@typescript-eslint/no-extra-parens` removes these parentheses, please open an issue in the typescript-eslint repository:

https://github.com/typescript-eslint/typescript-eslint
