### ISSUE TITLE
Bug: no-implicit-coercion errors when multiplied by fractions with numerator of 1

### ISSUE THREAD

**Issue by CreativeTechGuy** [eslint/eslint#16373]
### Environment

Node version: N/A
npm version: N/A
Local ESLint version: 8.24.0
Global ESLint version: N/A
Operating System: N/A

### What parser are you using?

Default (Espree)

### What did you do?

[ESLint Playground Demo](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc29sZS5sb2coTWF0aC5QSSAqIDEvNCkiLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOiJsYXRlc3QiLCJzb3VyY2VUeXBlIjoic2NyaXB0IiwiZWNtYUZlYXR1cmVzIjp7fX0sInJ1bGVzIjp7Im5vLWltcGxpY2l0LWNvZXJjaW9uIjpbImVycm9yIl19LCJlbnYiOnsiZXM2Ijp0cnVlfX19)

```js
console.log(Math.PI * 1/4)
```

### What did you expect to happen?

This would not be an error since the `* 1` isn't logically part of the previous token but part of the following division.

### What actually happened?

This is marked as an implicit conversion error and suggested to be changed to the following which is clearly missing the intent:

```js
console.log(Number(Math.PI)/4)
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

This is a special case that seems specific to the following pattern: `<number> * 1 / <number>`. While I do realize that the `* 1` is unnecessary here, for readability of math expressions it is very valuable such as the example of working with `PI` but applies to any number multiplied by a fraction.

I'd like a special case/exception made to the rule's checks that if the ` * 1` is immediately followed by a `/` then it is not an error.

**Comment by mdjermanovic** [comment]
Hi @CreativeTechGuy, thanks for the issue!

> ```js
> console.log(Math.PI * 1/4)
> ```

I think the rule works as intended because this is technically `(Math.PI * 1) / 4`.

> I'd like a special case/exception made to the rule's checks that if the ` * 1` is immediately followed by a `/` then it is not an error.

You could add parentheses around the expression that should logically be an operand of `*` to make it become an actual operand of `*`. In the original example, the expression would be `Math.PI * (1/4)`. Here's a [playground demo](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc29sZS5sb2coTWF0aC5QSSAqICgxLzQpKSAvLyBubyBlcnJvciIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsibm8taW1wbGljaXQtY29lcmNpb24iOlsiZXJyb3IiXX0sImVudiI6eyJlczYiOnRydWV9fX0=) where the rule does not report implicit coercion. I'm not in favor of adding the proposed exception but curious what other team members think about it.

**Comment by CreativeTechGuy** [comment]
Hi @mdjermanovic! Thanks for the reply. I know it can be worked around, but I've been running into this so often lately when doing math that it seemed like it could be improved. It seems like always a false positive since I cannot think of a case where the `* 1 /` pattern is used and the intent is to coerce the number rather than multiply by a fraction. I guess I'm saying it shouldn't hurt and can make the rule a little smarter. :)

If it would tip the scales, I'd be willing to submit the PR to add this.

**Comment by mdjermanovic** [comment]
> It seems like always a false positive since I cannot think of a case where the `* 1 /` pattern is used and the intent is to coerce the number rather than multiply by a fraction

That's a good point, as `/` coerces its operands to numbers anyway. I'm not opposed to adding this exception (by default, no option) and treating this as a bug fix, but let's hear from the rest of the team first.

**Comment by snitin315** [comment]
I'm also not opposed to treat it as a bugfix 👍🏻

**Comment by mdjermanovic** [comment]
I can work on this.
