### ISSUE TITLE
Update escope

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#1642]
In order to fully support ES6, we need to support ES6 scoping. escope 2.x  has been updated to support ES6, but it's interface is different so requires a bit of work to merge in.

**Comment by nzakas** [comment]
Working on this.

**Comment by Constellation** [comment]
@nzakas 

One note, in the next release, I'll change the details and update the major number.

* Update and Clean up the scopes. They are clasified into several class. `Scope#type` string of FunctionExpressionNameScope is changed from `'function'` to `'function-expression-name'`.
* I'll drop the TDZ scope. Instead of it, marking the variables referring the TDZ scopes as TDZ.

Do you have any other requests?

**Comment by Constellation** [comment]
But, maybe, the change becomes not so large, so changing the current version doesn't conflict I think.
When publishing the next version, I'll inform you and I'll support to update the escope library :)

**Comment by nzakas** [comment]
Okay, I'll probably hold off until that is complete. In the meantime, I left a comment here:
https://github.com/estools/escope/issues/33#issuecomment-69466633

**Comment by nzakas** [comment]
Related to #917
