### ISSUE TITLE
Change Request: stop running rules set to "warn" when `--quiet` is used

### ISSUE THREAD

**Issue by me4502** [eslint/eslint#16450]
### ESLint version

v8.25.0

### What problem do you want to solve?

Currently, running ESLint with `--quiet` will run all of the rules set to `"warn"` but disregard the results. This results in wasted time and resources for data that is never used. Given fixers are turned off for warnings when `--quiet` is in use, it makes sense for the actual rules to not run either.

It's fairly common practice to have many rules set to "warn" for best practices within an IDE, and to then run in `--quiet` mode on CI or precommit to detect any rule violations that are considered actual errors from making it through the pull request pipelines. In setups like this, many slower rules are often setup for viewing in an IDE with only a small subset marked as error for blocking CI.

In an example case of a larger project, I'm seeing a change from 4m39s to 22s just by disabling all "warn" ESLint rules. This is a substantial amount of wasted resources.

### What do you think is the correct solution?

I believe that the `--quiet` flag should disable processing of rules that are marked `"warn"`, as the data will be disregarded anyway. The only case I believe it should still run, is when `--max-warnings` is passed as well, as together they produce noticeable results since https://github.com/eslint/eslint/pull/14242, so this change would only be for cases where the `--max-warnings` flag has not been provided.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

This is a duplicate of a previously archived issue that was closed due to no response from author; https://github.com/eslint/eslint/issues/15137. I'm creating a new one as I believe my issue includes the requested justification that was originally asked for before closing.

This comment on the prior ticket also mentions a single specific rule that would heavily benefit from this change - https://github.com/eslint/eslint/issues/15137#issuecomment-1077176606

**Comment by mdjermanovic** [comment]
Hi @me4502, thanks for the issue!

> In an example case of a larger project, I'm seeing a change from 4m39s to 22s just by disabling all "warn" ESLint rules. This is a substantial amount of wasted resources.

It looks like this could bring significant performance improvements in use cases like the one you described, so I'm supportive of exploring ways to implement this change. This change likely requires new options in the [ESLint APIs](https://eslint.org/docs/latest/developer-guide/nodejs-api), so it would have to go through the [RFC process](https://github.com/eslint/rfcs), but let's first hear if the rest of the team supports this idea, and thoughts about the design. We could add a flag to exclude rules set to `"warn"`, or perhaps a more generic solution like an option to pass in a function that would get rule config and return `true`/`false` (`false` if the rule should not be run) or maybe even a function that would get the whole config for a file and return a new config so it could filter out rules that `"warn"`.

> The only case I believe it should still run, is when `--max-warnings` is passed as well, as together they produce noticeable results since #14242, so this change would only be for cases where the `--max-warnings` flag has not been provided.

Another case that should be taken into account is `--report-unused-disable-directives`. If a rule wasn't run because of the `--quiet` flag, then we should probably also ignore `eslint-disable` directives for that rule, otherwise they would be reported as unused.

**Comment by snitin315** [comment]
I'm in favor of this change 👍🏻.

However, changing how `--quiet` works by default can be a breaking change. 

> a more generic solution like an option to pass in a function that would get rule config and return true/false (false if the rule should not be run.

I feel that a generic solution would be better and we will have to check compatibility with `--max-warnings`, `--report-unused-disable-directives`, and `eslint-disable`. This change definitely needs an RFC.

**Comment by nzakas** [comment]
I think this makes sense. We will likely only be able to implement it in `FlatESLint`, though, as I don't think it makes sense to implement in two places (`FlatESLint` and `ESLint`) given that we will be removing `ESLint`.

Let's move forward with an RFC.

**Comment by me4502** [comment]
I've written up a draft RFC for this change, https://github.com/eslint/rfcs/pull/104.

I opted to design the API with a predicate for extensibility, but the CLI flag for just this specific functionality as a compromise on power vs simplicity.

**Comment by nzakas** [comment]
Thanks @me4502! We will take a look.

**Comment by ColtHands** [comment]
I propose not to change the `--quiet` flag but to add `--ignore-warnings` or `--skip-warnings`, since sometimes we need threshhold for how much warnings you have introduced with `--max-warnings`

**Comment by mdjermanovic** [comment]
@ColtHands we're discussing the design for this change in the RFC, please post your suggestions there: https://github.com/eslint/rfcs/pull/104

**Comment by sam3k** [comment]
2023-11-30 tsc-meeting note: this issue is close to done. Just making the final changes.
