### ISSUE TITLE
Change Request: Slight adjustment to logic introduced in #16348

### ISSUE THREAD

**Issue by scalvert** [eslint/eslint#16492]
### ESLint version

^8.25.0

### What problem do you want to solve?

⚠️ I want to start by quickly saying that I acknowledge this issue I'm identifying is only manifesting due to our unorthodox usage of formatters. That said, I believe we can arrive at a reasonable solution that will maintain the current logic, while restoring the prior behavior in our formatter.

The PR #16348 added the ability to pass `--max-warnings` to formatters, which is a great addition. There's nothing inherently problematic about the solution apart from the execution ordering. 

Our formatter, [eslint-formatter-todo](https://github.com/lint-todo/eslint-formatter-todo), provides a mechanism whereby you can defer fixing errors until a later date. This allows for organizations that have huge codebases to roll out new lint rules without breaking tons of consumers, and has become an invaluable part of our code maintenance workflows.

As part of this formatter, we modify the results to contain a new severity: `todo`. This allows us to indicate to the formatter whether to output errors or not - if they're `todo`, we ignore them unless an env var is set.

After the following change:

https://github.com/eslint/eslint/blob/69216ee69c7172e847b64e0e934b5121a34d0ea3/lib/cli.js#L432-L464

the order of _when_ errors were counted has changed. This has resulted in the exit code of the CLI returning non-zero, since the count of the results occurs _before_ the formatter is run rather than what it previous was, which was after. 

### What do you think is the correct solution?

If we could work the logic back to where the results count occurs after the formatters run, that would solve our problem. I'm totally happy to contribute this fix.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

Just want to also tag @btmills to get their thoughts, since they were the one who implemented this change!

**Comment by mdjermanovic** [comment]
Hi @scalvert, thanks for the issue!

> If we could work the logic back to where the results count occurs after the formatters run, that would solve our problem.

Formatters aren't really expected to modify the results, so there are many ways to break this. For example, we might decide to clone or freeze the results at some point to prevent accidental changes. I think a better course of action would be to explore other ways to solve the problem that `eslint-formatter-todo` aims to solve.

As for a temporary workaround, since the formatter modifies the results to alter eslint's exit code calculations, maybe you could do `process.exit(code)` directly in the formatter instead. That's not really what formatters should be doing, but they shouldn't modify the results to affect the exit code either.

 I’m curious what other team members think about this.

**Comment by scalvert** [comment]
Hey @mdjermanovic, thanks for taking the time to reply.

> Formatters aren't really expected to modify the results, so there are many ways to break this. For example, we might decide to clone or freeze the results at some point to prevent accidental changes.

This is why my issues is prefaced with a big fat ⚠️ to indicate my awareness that we're deviating from what would be considered normal. 

> As for a temporary workaround, since the formatter modifies the results to alter eslint's exit code calculations, maybe you could do process.exit(code) directly in the formatter instead.

This is absolutely an option for us, but I was trying to minimize the formatter's fully escaping from the flow of the CLI. We can for sure use this as a workaround and put a comment in the code as to the why of it.

Either way, it _is_ possible for us to update the logic so that the call ordering would be similar to what it was before, though as you've suggested that's not going to guarantee future operability.

**Comment by tylerbecks** [comment]
+1 I'm a consumer of eslint-formatter-todo and would love to see this ticket come to life. The amount of warnings we have is unwieldy and having `--quiet` would help us so much.

**Comment by mdjermanovic** [comment]
In the [2022-12-01 TSC meeting](https://github.com/eslint/tsc-meetings/blob/main/notes/2022/2022-12-01.md), we discussed this issue and decided not to make any changes. It is necessary to count warnings before running the formatter in order to pass additional data ([`context.maxWarningsExceeded`](https://eslint.org/docs/latest/developer-guide/working-with-custom-formatters#the-context-argument)) to the formatter. We'll not recalculate the data after running the formatter because formatters are not expected to modify lint results and affect the exit code.
