### ISSUE TITLE
Bug: `no-var` autofix is not working

### ISSUE THREAD

**Issue by mvorisek** [eslint/eslint#16610]
### How to reproduce?

config:
```
'no-var': ['error']
```

code:
```js
var fx = function (i = 0) {
  if (i < 5) {
    return fx(i + 1);
  }
  console.log(i);
};

fx();
```

### What did you expect to happen?

`var fx` autofixed to `let fx`

I tried the code in a sandpit and it behaves the same.

### What actually happened?

not autofixed, `Unexpected var, use let or const instead  no-var` error is generated

(autofix of `var` -> `let` works in other cases, the problem is present only when the variable is referred in anonymous function in the same declaration)

**Comment by mdjermanovic** [comment]
Hi @mvorisek, thank for the issue!

I can reproduce this. The variable is referenced in its initializer, so the rule considers the fix unsafe because the reference might be evaluated in TDZ. I think we can make a small change to ignore the reference if the initializer is a function definition, as in that case the reference certainly cannot be evaluated in TDZ. I'm working on the fix.

**Comment by amareshsm** [comment]
@mdjermanovic I would like to give it a try. Can I work on this?

> ignore the reference if the initializer is a function definition

Like this?
```
    if (!declarator.init || declarator.init.type === 'FunctionExpression') {
                return false;
    }
 ```

**Comment by mdjermanovic** [comment]
Ah, I've already started working on this and prepared PR https://github.com/eslint/eslint/pull/16611.
