### ISSUE TITLE
Bug: No restricted imports pattern not working with combined exclamation point and asterisk

### ISSUE THREAD

**Issue by chaptergy** [eslint/eslint#16672]
### Environment

Node version: v16.15.1
npm version: v8.11.0
Local ESLint version: v8.29.0
Global ESLint version: Not found
Operating System: win32 10.0.19044

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```json
[...]
"rules": {
        "no-restricted-imports": [
            "error",
            {
                "patterns": [
                    {
                        "group": [
                            "foo",
                            "!foo/**"
                        ],
                        "message": "Do not import from foo, but instead from a specific module, e.g. foo/bar"
                    }
                ]
            }
        ]
    },
[...]
```
</details>

```js
import forbiddenBar from "foo";
import allowedBar from "foo/bar";
```

See [ESLint demo](https://eslint.org/play/#eyJ0ZXh0IjoiaW1wb3J0IGZvcmJpZGRlbkJhciBmcm9tIFwiZm9vXCI7XG5pbXBvcnQgYWxsb3dlZEJhciBmcm9tIFwiZm9vL2JhclwiO1xuaW1wb3J0IGFsbG93ZWRCYXIyIGZyb20gXCJmb28vc3ViL2JhclwiOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnsibm8tcmVzdHJpY3RlZC1pbXBvcnRzIjpbImVycm9yIix7InBhdHRlcm5zIjpbeyJncm91cCI6WyJmb28iLCIhZm9vLyoqIl0sIm1lc3NhZ2UiOiJEbyBub3QgaW1wb3J0IGZyb20gZm9vLCBidXQgaW5zdGVhZCBmcm9tIGEgc3BlY2lmaWMgbW9kdWxlLCBlLmcuIGZvby9iYXIifV19XX0sImVudiI6eyJlczYiOnRydWV9fX0=)

### What did you expect to happen?

Have imports which use `foo` directly show a linting error, while all imports, which use a more specific import like `foo/bar` do not have it.

### What actually happened?

All imports using `foo`, even the more specific ones from `foo/bar` show the same linting error

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

The same thing happens if the pattern is `["foo", "!foo/*"]`, but it works when it is `["foo", "!foo/"]`

**Comment by mdjermanovic** [comment]
Hi @chaptergy, thanks for the issue!

This works as intended since the patterns in this rule work per the [.gitignore specification](https://git-scm.com/docs/gitignore).

> ```json
> "group": [
>    "foo",
>    "!foo/**"
> ],
> ```

In this case, pattern `foo` matches directory `foo/`. Pattern `!foo/**` matches files and directories under `foo/`, but not the `foo/` directory itself, so it doesn't re-include `foo/`. Per the following .gitignore rule, files and directories under excluded `foo/` are considered excluded (i.e., ignored; for this rule, restricted):

> It is not possible to re-include a file if a parent directory of that file is excluded.

You can configure `["foo", "!foo/"]` as you suggested, or add `"foo"` to `paths: []` instead of `patterns: []`.
