### ISSUE TITLE
Docs: Non-readable diagrams when the dark theme is on

### ISSUE THREAD

**Issue by myshov** [eslint/eslint#16683]
### URL(s)

https://eslint.org/docs/latest/developer-guide/code-path-analysis

### What did you do?

Turn on the dark theme

### What did you expect to happen?

Diagrams are readable

### What actually happened?

The black arrows of diagrams almost invisible on the dark background of the site

### Participation

- [X] I am willing to submit a pull request for this issue.

### Additional comments

As a workaround we can use `filter: invert(100%);` for the images when the dark theme is on

**Comment by mdjermanovic** [comment]
Transferred to eslint/eslint, as the code path analysis document is in this repo.

**Comment by myshov** [comment]
@mdjermanovic hi! I believe that we have to change styles of the site itself too

**Comment by mdjermanovic** [comment]
Styles for the docs pages are also in this repo. While at this, I'm not sure if we should change styles to invert colors or make sure that those images have a light background so that they look the same in both light and dark modes. @eslint/website-team thoughts?

**Comment by harish-sethuraman** [comment]
My suggestions are 
- we can change the colors of the image's nodes that are not visible by editing the image
- apply styles to those SVG elements and directly import it instead of using img tag? (so we can fill colors to specific node depending on the theme)
- add common background color that works well with dark and light theme? 

PS: we cant change the styles of the site itself?

**Comment by amareshsm** [comment]
`invert()` won't work I guess. 

| light theme | dark theme with `invert` property  |
|-----|-----|
|  <img width="500" alt="image" src="https://user-images.githubusercontent.com/30730124/208681837-a191ca17-59d0-4d9f-ade8-bc046bba0bfd.png"> |  <img width="500" alt="image" src="https://user-images.githubusercontent.com/30730124/208681667-de1da40b-f36c-4720-b96e-354e54755615.png"> |

As @harish-sethuraman  suggested we use SVG or add common background color that works well with both themes.

**Comment by kecrily** [comment]
I like the idea of SVG themes, we can make a special id for them and then override them uniformly.

**Comment by myshov** [comment]
> invert() won't work I guess.

at least it is more readable and the colors are distinguishable. But anyway I also like the idea with SVG. Btw SVG supports the media query `prefers-color-scheme` https://blog.tomayac.com/2019/09/21/prefers-color-scheme-in-svg-favicons-for-dark-mode-icons/

**Comment by harish-sethuraman** [comment]
I'd like to hear @eslint/eslint-tsc's thoughts on this too. We might want to make it consistent going forward where these kind of UI differences occurs.

**Comment by nzakas** [comment]
It's important to note that these SVG images are automatically generated through [GraphViz](https://graphviz.org/), so any solution we choose should not involve manually editing the SVG.

I think the easiest solution would be to just set the background-color to white on all SVGs that are in the content of a documentation page.

**Comment by kecrily** [comment]
If it's auto-generated, then maybe we can also consider the mermaid + light/dark theme option. Just a thought

**Comment by nzakas** [comment]
They are generated by hand right now. :)

**Comment by Tanujkanti4441** [comment]
What about applying this background color ? It's quite similar with the whole background and arrows are also visible enough.

![Annotation 2023-01-18 204544](https://user-images.githubusercontent.com/86398394/213213387-158311f6-063e-4cfc-9fcb-c610fb7d149f.png)
![Annotation 2023-01-18 205711](https://user-images.githubusercontent.com/86398394/213213474-e68c6518-ebed-48a1-8a5b-0cfefd012358.png)

**Comment by nzakas** [comment]
There's not enough contrast between the background and the black lines/dots.

I think we can just start by applying a white background to these diagrams?

**Comment by Tanujkanti4441** [comment]
But instead of applying pure white in background can we apply colors that are more soothing to eyes in dark mode and same time have enough contrast with lines/dots
like this

![Screenshot 2023-01-22 at 20-13-02 Code Path Analysis Details - ESLint - Pluggable JavaScript Linter](https://user-images.githubusercontent.com/86398394/213922793-bd2d5f8d-5d5c-4525-b9e7-df838c2b4f83.png)
![Screenshot 2023-01-22 at 20-15-38 Code Path Analysis Details - ESLint - Pluggable JavaScript Linter](https://user-images.githubusercontent.com/86398394/213922796-b3edd51c-4462-429d-ba98-cd99f9bad245.png)

![Screenshot 2023-01-22 at 20-16-22 Code Path Analysis Details - ESLint - Pluggable JavaScript Linter](https://user-images.githubusercontent.com/86398394/213922800-1f0bd72a-000f-482f-a578-29d585e8a31b.png)

**Comment by nzakas** [comment]
If we choose white then there’s no border in light mode at all. 

If the website team wants to choose an off white color, they can. I’d just like to get this issue closed. :)
