### ISSUE TITLE
New Rule: Unnecessary template string

### ISSUE THREAD

**Issue by michaeljohansen** [eslint/eslint#16745]
### Rule details

Error on unnecessary template string

### Related ECMAScript feature

Template string

### What type of rule is this?

Warns about a potential problem

### Example code

```js
const var1 = 'hello'; // OK
const var2 = `${'hello'}`; // Error
```

### Why should this rule be in the core instead of a plugin?

The rule regards a core ECMAScript feature. It will increase readability and reduce unnecessary evaluation. I assume it would also be possible to implement a `--fix` for it.

In my opinion, such a rule wouldn't need to cover all possible situations, but at least the clear "singel string in template string" scenarios.

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

### Additional comments

Time and time again I've seen teammates use string interpolation when a simple variable would do the same job with a few less characters, one less evaluation, and a bit better readability. It mostly happens when people edit existing code where the string interpolation was necessary, but when they removed something from that string (and made the template string redundant) they forgot to remove the template itself.

**Comment by mdjermanovic** [comment]
Hi @michaeljohansen, thanks for the issue!

Per our [rules policies](https://eslint.org/blog/2020/05/changes-to-rules-policies/), this rule doesn't qualify for inclusion in the core since it isn't related to new ECMAScript features that reached stage 4 in the preceding 12 months.

There's an accepted proposal in `eslint-plugin-unicorn` for a rule that, I think, covers this:

https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1261

You can also configure the [no-restricted-syntax](https://eslint.org/docs/latest/rules/no-restricted-syntax) rule with the following selector to catch these patterns:

```
TemplateLiteral[expressions.length=1][quasis.0.value.cooked=''][quasis.1.value.cooked=''] > Literal[raw=/^[\u0022\u0027]/]
```

[Playground demo](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXJlc3RyaWN0ZWQtc3ludGF4OiBbXCJlcnJvclwiLCB7XG4gICAgc2VsZWN0b3I6IFwiVGVtcGxhdGVMaXRlcmFsW2V4cHJlc3Npb25zLmxlbmd0aD0xXVtxdWFzaXMuMC52YWx1ZS5jb29rZWQ9JyddW3F1YXNpcy4xLnZhbHVlLmNvb2tlZD0nJ10gPiBMaXRlcmFsW3Jhdz0vXltcXHUwMDIyXFx1MDAyN10vXVwiLFxuICAgIG1lc3NhZ2U6IFwiVW5uZWNlc3NhcnkgdXNlIG9mIHRlbXBsYXRlIGxpdGVyYWwuXCJcbn1dICovXG5cbmNvbnN0IHZhcjEgPSAnaGVsbG8nOyAvLyBPS1xuY29uc3QgdmFyMiA9IGAkeydoZWxsbyd9YDsgLy8gRXJyb3JcbiIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6ImxhdGVzdCIsInNvdXJjZVR5cGUiOiJzY3JpcHQiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnsiZXM2Ijp0cnVlfX19)
