### ISSUE TITLE
Add maxWarnings as a configuration option

### ISSUE THREAD

**Issue by lourd** [eslint/eslint#16804]
### ESLint version

8.32.0

### What problem do you want to solve?

Resurrecting #13391:

I want to make having a max warnings config value of 0 opt-out instead of opt-in.

My team has a monorepo managed with Nx. It's setup where we share most configuration for each target (library or application) in a root .eslintrc.json, which each target then extends in its own .eslintrc.json file.

One key configuration that can't be shared is the max warnings. When making a new library or application, the developer has to remember to add that to the additional configuration file (in Nx's case, the [configuration for the eslint executor in the `project.json`](https://nx.dev/packages/linter/executors/eslint#maxwarnings)).

This often gets forgotten, causing linter warnings build up and making it difficult to get back into good shape.

### What do you think is the correct solution?

I'd like eslint to have the ability to set maxWarnings as a property in a .eslintrc.json file, not just through the command line.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
We can consider this again, but keep in mind that allowing `maxWarnings` to be set in a configuration file also means that any configuration file you import from anywhere could set it without you being aware.

**Comment by Rec0iL99** [comment]
@eslint/eslint-team folks your feedback here would be appreciated. 

`maxWarnings` in `.eslintrc.*` was originally proposed in #13391, but was rejected then because of https://github.com/eslint/rfcs/pull/9. 

@lourd are you interested in implementing this if approved by the team? The core team is currently focused on implementing a new config system. You can track it's progress here https://github.com/eslint/eslint/issues/13481 and [rfc](https://github.com/eslint/rfcs/tree/main/designs/2019-config-simplification).

**Comment by mdjermanovic** [comment]
I'm not sure if `maxWarnings: number`, as the equivalent of the CLI option [`--max-warnings`](https://eslint.org/docs/latest/use/command-line-interface#--max-warnings), makes sense in configuration files because it's not max per file but max per run, so it's conceptually related to a specific run. For example, in this repository we have one configuration file but two commands that run eslint on different files ([`eslint . --ignore-pattern "docs/**"`](https://github.com/eslint/eslint/blob/b09a512107249a4eb19ef5a37b0bd672266eafdb/Makefile.js#L537) and [`eslint docs`](https://github.com/eslint/eslint/blob/b09a512107249a4eb19ef5a37b0bd672266eafdb/Makefile.js#L560)). If we'd use `--max-warnings`, it would have different values ​​in different commands rather than a single value in the configuration file.

**Comment by nzakas** [comment]
@mdjermanovic yeah, that's my feeling as well. I don't believe it belongs in the config file, so closing.

**Comment by lourd** [comment]
Those points all make sense. Thank you for the thoughtful consideration!
