### ISSUE TITLE
Change Request: Add environment aware rulesets (i.e. NODE_ENV='development')

### ISSUE THREAD

**Issue by jkohlin** [eslint/eslint#16857]
### ESLint version

8.33.0

### What problem do you want to solve?

When developing I want to be able to use `debug` and `console.log`but obviosly I don't want it in production so it would be nice to be able to set that somewhere. 

### What do you think is the correct solution?

Either in a separate file like `.eslintrc.development.json` but preferably in the overrides section in `.eslintrc.json` like: 
```json
{
    "rules": {
        "no-console": "error"
    },
    "overrides": [
        {
            "contexts": ["development", "local"],
            "rules": {
                "no-console": "off"
            }
        }
    ]
}
```

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @jkohlin, thanks for the issue!

This functionality can already be achieved in JavaScript configuration files by exporting different configurations for different environments. For example, this way you can conditionally turn off the `no-console` rule:

```js
// .eslintrc.js
module.exports = {
    rules: {
        "no-console": "error",
        ...process.env.NODE_ENV === "development" ? { "no-console": "off" } : {}
    }
}
```

Given that the current eslintrc config system is frozen and that the [new config system](https://eslint.org/docs/latest/use/configure/configuration-files-new) only supports JavaScript config files, I think there's no need to include this feature in the config system because the same functionality can easily be achieved programmatically.

**Comment by nzakas** [comment]
Closing, as there is already a workaround available.
