### ISSUE TITLE
Bug: (fill in)

### ISSUE THREAD

**Issue by raztud** [eslint/eslint#16863]
### Environment

Node version: 
npm version: 
Local ESLint version: 
Global ESLint version: 
Operating System: 

### What parser are you using?

Default (Espree)

### What did you do?

The **correct** example from [consistent-return](https://eslint.org/docs/latest/rules/consistent-return) 
![image](https://user-images.githubusercontent.com/1500732/216948533-2d4495b4-4552-412e-8ac6-3672211c9df1.png)

it contradicts the recommendation from [no-else-return](https://eslint.org/docs/latest/rules/no-else-return) rule
![image](https://user-images.githubusercontent.com/1500732/216948962-52b48b88-fae2-4993-8ba8-076d142ad63f.png)

### What did you expect to happen?

to have consitent example

### What actually happened?

there is a inconstent example in docs

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @raztud, thanks for the issue!

> ![image](https://user-images.githubusercontent.com/1500732/216948533-2d4495b4-4552-412e-8ac6-3672211c9df1.png)

This example is correct for the `consistent-return` rule, so the documentation is fine. Rules have distinct responsibilities and a code example that is "valid" for one rule may be "invalid" for another rule because they're checking different things. These two rules are not contradicting because it is possible to write the code in a way that will be valid for both rules. If you'd like to add another example (without `else`), a PR is welcome. I'm closing this issue as the documentation is correct and this isn't a bug.
