### ISSUE TITLE
Change Request: Allow for a way to use multiple severity levels in a rule definition

### ISSUE THREAD

**Issue by HadrienPierart** [eslint/eslint#16919]
### ESLint version

5.16

### What problem do you want to solve?

I am setting the rule `import/no-restricted-paths` for a project, and while I want to prevent some directories to be imported in other, I would also want to show some warnings when some imports are made should should be kind of deprecated / refactored into something else.

### What do you think is the correct solution?

Allow for multiple levels inside the array of the rule definition

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @HadrienPierart, thanks for the issue!

The functionality of allowing multiple severity levels per rule has been discussed several times, and the conclusion is to use a workaround with making a clone of the rule so that it can be configured separately. For details, please see the discussion in https://github.com/eslint/eslint/issues/14061.
