### ISSUE TITLE
How we use option in .eslintrc.*?

### ISSUE THREAD

**Issue by LwCoderNovice** [eslint/eslint#16946]
### Syntax name

options

### Syntax proposal URL

https://www.ecma-international.org/publications-and-standards/standards/ecma-404/

### Example code

```js
options: {
'output-file': '...',
'format': '...'
}
```

### Implementation Checklist

- [ ] Ecma262 update: 
- [ ] ESTree update: 
- [ ] Acorn update: 
- [ ] `eslint-visitor-keys` update: 
- [ ] `espree` update: 
- [ ] `eslint-scope` update: 
- [X] `eslint` update: 

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

_If I use multiple options, the command will be too long. And I can't use the third build tool._

**Comment by Rec0iL99** [comment]
Hi @LwCoderNovice, thanks for the suggestion. I just want to confirm to make sure we're on the same page. You have a lot of options that you want to pass to your CLI when executing ESLint from the terminal, so you want to include those options in the `.eslintrc.*` config file.

I don't think your proposal will be accepted for the `.eslintrc.*` because we aren’t currently making any changes to the current config system while we are putting our focus on the new one. You can track it's progress here #13481 and [rfc](https://github.com/eslint/rfcs/tree/main/designs/2019-config-simplification).

I'm leaving this open for someone from the core team to confirm and close if needed.

**Comment by mdjermanovic** [comment]
`format` and `output-file` are CLI-specific options so they wouldn't make sense in eslint config files as ESLint can also be used through [API](https://eslint.org/docs/latest/integrate/nodejs-api). You can always run eslint CLI from a script and maintain options in the script.
