### ISSUE TITLE
Bug: Missing link in the sidebar for Selectors

### ISSUE THREAD

**Issue by Mikilll94** [eslint/eslint#17130]
### URL(s)

This page does not have a navigation link on the left sidebar

https://eslint.org/docs/latest/extend/selectors

### What did you do?

I cannot find a navigation for this page on the left sidebar.

### What did you expect to happen?

Navigation link for this page should be present on the left sidebar.

### What actually happened?

Navigation link for this page is not present on the left sidebar.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
This is intentional. Pages related to writing rules, such as [Code Path Analysis](https://eslint.org/docs/latest/extend/code-path-analysis),  [Scope Manager](https://eslint.org/docs/latest/extend/scope-manager-interface) and [Selectors](https://eslint.org/docs/latest/extend/selectors) are linked only from the [Custom Rules](https://eslint.org/docs/latest/extend/custom-rules) page.
