### ISSUE TITLE
Bug: .eslintrc-foo.js ignored by default, when it shouldn't?

### ISSUE THREAD

**Issue by kkmuffme** [eslint/eslint#17373]
### Environment

Node version: 16.19.0
npm version: 8.9.0
Local ESLint version: 8.45.0
Global ESLint version: 8.45.0
Operating System: RHEL

### What parser are you using?

Default (Espree)

### What did you do?

I want to run eslint for `.eslintrc-foo.js` like:
`eslint --no-eslintrc --config my-config.js .eslintrc-foo.js`

### What did you expect to happen?

No error/normal linting

### What actually happened?

>File ignored by default. Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override

Using `--ignore-pattern '!.eslintrc*'` fixes this issue, however the docs state:

>dot-files (**except for .eslintrc.\***) as well as dot-folders and their contents are ignored

Therefore .eslintrc-foo.js should not report an "ignored" error here, as it shouldn't be ignored by default.

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fasttime** [comment]
Hi @kkmuffme! I think the documetation is correct:

https://github.com/eslint/eslint/blob/71349a1f709baa361bd656a7ce4a7d35d857a9a8/docs/src/use/configure/ignore.md?plain=1#L70

What this means is that ESLint ignores any file whose name starts with ".eslintrc." or files that are located in a directory whose name starts with a dot (".").
Now, you didn't specify where your ".eslintrc-foo.js" file is located, but I can tell that this filename is not matched by the pattern `.eslintrc.*`, because there is no "." after ".eslint".
By contrast, a file named ".eslintrc.foo.js" (with "." instead of "-") should not be ignored, and no warning should be reported.
