### ISSUE TITLE
Change Request: Straightforward support of external processors

### ISSUE THREAD

**Issue by eyalroz** [eslint/eslint#17380]
### ESLint version

v8.45.0

### What problem do you want to solve?

I want to use a preprocessor on my almost-JS-code, before eslint'ing it. However - this processor is not Javascript code, it's an some executable.

<sub>(Not so important, but: It's Mozilla's venerable XUL preprocessor, which I use as a Thunderbird extension author. The [preprocessor](http://software.hixie.ch/utilities/unix/preprocessor/preprocessor.pl), written by Ian Hixon, uses C-preprocessor-style commands, e.g. `#ifdef`, `#else`, `#endif`; but macros need explicit expansion with `#expand`. It's a perl script.)</sub>

I realize that it is (probably) possible to write a JS wrapper for an external processor which will invoke it - but:

1.  I've never personally done something like that - issuing arbitrary commands on a host system, handling file paths etc., in JS. 
2. I believe that many (or even most) cases of preprocessor use are of such external processors, and individual users should not have to each implement this on their own.
3. IIANM, one needs to write a plugin for that purpose, which is yet another complication.

### What do you think is the correct solution?

I think it would be useful for eslint to offer more directly support for external processors, i.e. allowed a user to say more simply that they want an external process, and specify a path to it and some command-line template (or even - no command line template and just invoke it with the filename). And for that not involve any plugins.

### Additional comments

Related documentation pages:

* [Using preprocessors](https://eslint.org/docs/latest/extend/plugins#processors-in-plugins)
* [Defining preprocessors](https://eslint.org/docs/latest/extend/custom-processors)

**Comment by fasttime** [comment]
Thanks for the issue @eyalroz. ESLint processor are not comparable to C-preprocessors because they need to do more than just transforming an input text into an output text. The details are explained in the [custom processor documentation](https://eslint.org/docs/latest/extend/custom-processors) page you linked in your issue. That's also a good place to start for those who want to learn how to write a processor. 

> I realize that it is (probably) possible to write a JS wrapper for an external processor which will invoke it

Unfortunately, this is not the case. An ESLint processor must implement an interface to:
* Transform an input file into a collection of pseudo-files.
* Filter the problems reported by ESLint and map them to locations in the original file.
* Optionally apply fixes to the original file.

I don't think there exists a _straightforward_ way to reduce these functions into a call to an external script or executable. So I'm afraid that this suggestion won't be feasible.

**Comment by eyalroz** [comment]
Ok, then - I will close this bug and open a separate one about preprocessor support.
