### ISSUE TITLE
Change Request: deprecate `no-new-symbol`, recommend `no-new-native-nonconstructor`

### ISSUE THREAD

**Issue by fasttime** [eslint/eslint#17446]
### ESLint version

v8.46.0

### What problem do you want to solve?

The [`no-new-symbol`](https://eslint.org/docs/latest/rules/no-new-symbol) rule is not unique, because it reports a subset of the problems reported by the more recent [`no-new-native-nonconstructor`](no-new-native-nonconstructor) rule.

### What do you think is the correct solution?

This is a proposal to deprecate `no-new-symbol` and replace it with `no-new-native-nonconstructor` in the list of recommended rules.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

This would be a breaking change per our [semantic version policy](https://github.com/eslint/eslint#semantic-versioning-policy), so it should be scheduled for the next major version.

**Comment by mdjermanovic** [comment]
Thanks for the issue, we probably would have missed this. Marked as accepted because in https://github.com/eslint/eslint/issues/16322 we already agreed to deprecate `no-new-symbol`. Per our semver policies, "An existing rule is deprecated" is not a breaking change, but in this case (the rule is in `eslint:recommended`) it indeed seems better to deprecate this rule in a major version for the reasons described in https://github.com/eslint/eslint/pull/16368#pullrequestreview-1169545681.

**Comment by nzakas** [comment]
@fasttime you are free to start implementing this as we are gearing up for v9.0.0.
