### ISSUE TITLE
Change Request: Attach default options as an object to rules

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#17448]
### ESLint version

v8.46.0

### What problem do you want to solve?

Right now, there's no programmatic way to determine what any given rule's default options are. Many rules define functions like `normalizeOptions` ([`array-bracket-newline`](https://github.com/eslint/eslint/blob/e52b98bf25d882da4efd5559ce5974b6697cf701/lib/rules/array-bracket-newline.js#L102)), [`array-element-newline`](https://github.com/eslint/eslint/blob/e52b98bf25d882da4efd5559ce5974b6697cf701/lib/rules/array-element-newline.js#L120), [`object-curly-newline`](https://github.com/eslint/eslint/blob/e52b98bf25d882da4efd5559ce5974b6697cf701/lib/rules/object-curly-newline.js#L99)) or `parseOptions` ([`no-implicit-coercion`](https://github.com/eslint/eslint/blob/e52b98bf25d882da4efd5559ce5974b6697cf701/lib/rules/no-implicit-coercion.js#L22), [`use-before-define`](https://github.com/eslint/eslint/blob/e52b98bf25d882da4efd5559ce5974b6697cf701/lib/rules/no-use-before-define.js#L20)) that apply various, subtly different value defaults.

As a result, the only user-facing way to determine a rule's default options is to read the docs. But the docs themselves aren't consistent in phrasing. For example:
* [`array-callback-return`](https://eslint.org/docs/latest/rules/array-callback-return#options) phrases its options as _`"<key>": <value> (default) <explanation>`_
* [`accessor-pairs`](https://eslint.org/docs/latest/rules/accessor-pairs#options) phrases its options as _`<key> <explanation> (Default <default>)`_

Furthermore, there's also no way for tooling to determine the default options for any rule. Which is making it hard for us in typescript-eslint to automate our docs pages for extended rules (https://github.com/typescript-eslint/typescript-eslint/issues/6841#issuecomment-1668497510).

### What do you think is the correct solution?

In typescript-eslint, we added a `defaultOptions` property on rules. It's visible in the [Custom Rules guide](https://typescript-eslint.io/developers/custom-rules#rulecreator), which suggests users wrap rule creation with a `createRule`:

```ts
import { ESLintUtils } from '@typescript-eslint/utils';

const createRule = ESLintUtils.RuleCreator(
  name => `https://example.com/rule/${name}`,
);

export const rule = createRule({
  create(context) { /* ... */ },
  defaultOptions: [ { /* ... */ } ],
  meta: { /* ... */ },
  name: "..."
});
```

Under the hood, `createRule` wraps `create` to fill in `defaultOptions` for any option not provided by the ESLint config. You can see the exact logic here: https://github.com/typescript-eslint/typescript-eslint/blob/9c17395d7cd6da7e2db59f9bde2c81264a33da97/packages/utils/src/eslint-utils/applyDefault.ts. It's a deep merge, not a shallow `Object.assign`.

Would ESLint core be interested in adding an equivalent to this logic? And/or, would you like an RFC written for it?

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I don't believe this would be a breaking change the way #14709 is. Making the new field optional means rules can opt into it if they please.

**Comment by bmish** [comment]
I'd love to be able to programmatically tell what the default options are for a rule, also for automatic documentation purposes.

It should be noted that some defaults can be documented inside the JSON Schema (`meta.schema`), but I'm not sure this is sufficient to represent all defaults (I think there was a past discussion about this, but can't remember where).

**Comment by nzakas** [comment]
I think this is worth exploring and I'd be open to an RFC. The original intent was for the JSON schema to be the source of truth for default options (indeed we used this when `--init` scanned files to figure out which options to best suggest) but it ended up being more complicated than it was worth.

If we were to implement something like this, some things I'd expect to see:

1. If default options are specified, then ESLint should merge those options with any explicit options specified by the user. That way, we can avoid checking for the presence of certain options inside the rule itself.
2. `defaultOptions` inside of `meta` rather than at the top level.
3. `RuleTester` should validate the default options against the rule options schema.

**Comment by bradzacher** [comment]
> It should be noted that some defaults can be documented inside the JSON Schema (meta.schema), but I'm not sure this is sufficient to represent all defaults

It's definitely possible to do this - though personally I don't like it because it's technically possible to do things like `{type: 'number', default: 'hello'}` which compile fine and will even work fine if you pass the option! It will only error if you skip the value and the default is used.

Additionally from a type-safety perspective - it gets pretty hairy trying to safely type the `default` value. For simple cases like above - sure - easy, but for more complex cases (arrays / objects) it's mostly not possible.

Which was the reason we went with the separate `defaultOptions` prop in the typescript-eslint utilities as it allowed us to simply take the user's defined option type and use it for the default - easy validation!

**Comment by JoshuaKGoldberg** [comment]
I still plan on writing an RFC Soon™️.

**Comment by JoshuaKGoldberg** [comment]
* Reference implementation: https://github.com/eslint/eslint/pull/17580
* RFC: https://github.com/eslint/eslint/pull/17580

**Comment by nzakas** [comment]
RFC is open, so not stale.

**Comment by mdjermanovic** [comment]
Implemented by https://github.com/eslint/eslint/pull/17656.
