### ISSUE TITLE
Rule Change: no-redeclare

### ISSUE THREAD

**Issue by Ayc0** [eslint/eslint#17565]
### What rule do you want to change?

no-redeclare

### What change to do you want to make?

Implement autofix

### How do you think the change should be implemented?

A new option

### Example code

```js
import { foo, foo } from 'bar';
```

### What does the rule currently do for this code?

It sends an error for the 2nd foo, but doesn't propose to auto remove it

### What will the rule do after it's changed?

It'll auto remove it.
This could be placed behind a `autofix: boolean` in the config of the rule to introduce a breaking change right now

### Participation

- [X] I am willing to submit a pull request to implement this change.

**Comment by nzakas** [comment]
Thanks for the suggestion. This error is actually coming from the parser, not from `no-redeclare`. You can see it in action [here](https://eslint.org/play/#eyJ0ZXh0IjoiaW1wb3J0IHsgZm9vLCBmb28gfSBmcm9tICdiYXInOyIsIm9wdGlvbnMiOnsiZW52Ijp7fSwicnVsZXMiOnt9LCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e30sImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6Im1vZHVsZSJ9fX0=).

Because the error comes from the parser, all parsing stops and ESLint can't work on the file. So I'm afraid there is nothing we can do here.

**Comment by Ayc0** [comment]
In your example and in the parser `espree`, I indeed have a crash from the parser itself:

<img width="1135" alt="image" src="https://github.com/eslint/eslint/assets/22725671/e43fbb11-fbe2-41dc-9a21-297c883ba8df">
<img width="1213" alt="image" src="https://github.com/eslint/eslint/assets/22725671/b2255d35-4c3a-4407-84da-4bf4a82dcb2c">


But in `@typescript-eslint/parser` it seems to be able to handle multiple specifiers from the same import declaration:

<img width="1512" alt="image" src="https://github.com/eslint/eslint/assets/22725671/fd3e3c28-722c-4920-b928-5397106d1551">


I think I should've opened this issue on `typescript-eslint` instead (I thought it was just a port of the native ESLint rule for TS, but they may fully recode this rule as the parser is behaving differently)

Thanks for the reply!
