### ISSUE TITLE
Bug: Missing comment son parenthesised expressions

### ISSUE THREAD

**Issue by lachrist** [eslint/eslint#17637]
### Environment

Node version: v20.2.0
npm version: 9.6.6
Local ESLint version: v8.51.0
Global ESLint version: none
Operating System: darwin

### What parser are you using?

Default (Espree)

### What did you do?

<details>
<summary>Configuration</summary>

```
export default [
  {
    plugins: {
      custom: {
        rules: {
          "log-comments": {
            create: (context) => ({
              Literal(node.value) {
                console.log(node, {
                  inside: context.sourceCode.getCommentsInside(node),
                  before: context.sourceCode.getCommentsBefore(node),
                  after: context.sourceCode.getCommentsAfter(node),
                });
              },
            }),
          },
        },
      },
    },
    rules: {
      "custom/log-comments": "error",
    },
  },
];
```
</details>

```js
/** @type {Foo} */ ("foo");

/** Bar */ "bar";

```

### What did you expect to happen?

Finding a comment on both literal nodes.

### What actually happened?

```
foo { inside: [], before: [], after: [] }
bar {
  inside: [],
  before: [
    {
      type: 'Block',
      value: '* Bar ',
      start: 29,
      end: 39,
      range: [Array],
      loc: [Object]
    }
  ],
  after: []
}
```

### Link to Minimal Reproducible Example

Not possible to add custom rules, please refer to description

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @lachrist, thanks for the issue!

> ```js
> /** @type {Foo} */ ("foo");
> ```

> foo { inside: [], before: [], after: [] }

I'm assuming the bug report is about empty `before`.

This works as intended because there's a `(` token before `"foo"`, so the `/** @type {Foo} */` comment doesn't appear _directly_ before `"foo"`. 

https://eslint.org/docs/latest/extend/custom-rules#accessing-the-source-code

> `getCommentsBefore(nodeOrToken`): Returns an array of comment tokens that occur directly before the given node or token 

In other words, `SourceCode#getCommentsBefore(nodeOrToken)` returns comments that are between the first token before `nodeOrToken` and `nodeOrToken`. In this case, it correctly returns an empty list of comments between `(` and `"foo"`.

You could check if the node is parenthesized ([`@eslint-community/eslint-utils`](https://www.npmjs.com/package/@eslint-community/eslint-utils) provides function [`isParenthesized`](https://eslint-community.github.io/eslint-utils/api/ast-utils.html#isparenthesized) that might be helpful for this) and in that case pass the left parenthesis token to `SourceCode#getCommentsBefore`.

**Comment by lachrist** [comment]
@mdjermanovic thanks for your reply and sorry for mislabelling this. And thanks for providing a solution! I'm sure other people ran into this because parenthesised expression is commonly combined with block comments. Maybe it is worth mentioning it in the documentation here: https://eslint.org/docs/latest/extend/custom-rules?

**Comment by mdjermanovic** [comment]
A PR to clarify this behavior is welcome. Since there's a dedicated section for these methods, it could be added there:

https://eslint.org/docs/latest/extend/custom-rules#accessing-comments
