### ISSUE TITLE
Change Request: (Add the possibility to change MAX_AUTOFIX_PASSES)

### ISSUE THREAD

**Issue by wassim-ben-amor** [eslint/eslint#17651]
### ESLint version

v7.32.0

### What problem do you want to solve?

When using the report fixer, I need to make more then 10 changes. As a workaround I need to launch eslint command twice.

### What do you think is the correct solution?

I think it would be great to make MAX_AUTOFIX_PASSES configurable with keeping the default value to 10.
For example:
`npx eslint . --max-autofix-passes Int`

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @wassim-ben-amor, thanks for the issue!

Can you provide an example where more than 10 passes are needed to fix the code? 10 already seems like a lot and usually indicates that there are conflicting rules in the configuration.

**Comment by wassim-ben-amor** [comment]
Hello @mdjermanovic ,
For example, I have a custom rule to have a proper format of package.json of a package in a monorepo. 
Let's say for each script of the scripts object, there must be a definition of a global variable before launching the script.
If we have more then 10 scripts, we need to run the eslint --fix command more than 1 time.

**Comment by nzakas** [comment]
I'm not in favor of this. The fact that ESLint does multiple passes for autofixing is an implementation detail that may or may not change in the future. As such, we shouldn't be exposing this as a configurable option to users.

**Comment by mdjermanovic** [comment]
Sorry for the delay from my side. I agree with @nzakas. The way autofixing works is an implementation detail that may change in the future and therefore shouldn't be configurable. For instance, we considered applying whitespace and code fixes separately from each other, in which case it would become unclear what exactly this option refers to. Since we're not in favor of this change and there's already a workaround with running `--fix` multiple times, I'm closing this issue.
