### ISSUE TITLE
Function scoped inline configurations

### ISSUE THREAD

**Issue by ifraixedes** [eslint/eslint#1766]
Hi there, 

It would be nice to inline rules were function scoped as jshint does (mentioned in Inline configuration section in [docs](http://jshint.com/docs/))

This issue has some relation with eslint/eslint#1512

After did a quick search in the issue tracker and I couldn't find something like this which has already been reported before and was closed as eslint doesn't want to apply it in that way, I've decided to open this issue, if it has been reported before, my apologies no find it and create this duplicated issue.

**Comment by nzakas** [comment]
This is pretty complicated for us, so while it's a nice idea, we likely won't get around to investigating it anytime soon. If someone wants to put in the effort to research and purpose a solution, happy to review it.

**Comment by ifraixedes** [comment]
Ok, no rush for my part if it was, I would take it but I don't have currently much free time. 

Moreover it is an enhancement because  using `/*eslint-disable*/` & `*/eslint-enable*/` cover the use case.

Thanks to considering it.

**Comment by dantman** [comment]
Here are two comments from my dupe (#2832) that might be useful.

> I understand eslint can't suddenly make all the `/* eslint */` comments suddenly block/function scoped. So considering eslint doesn't support single line `// eslint ...` style configuration, I like using single line inline configuration when I'm writing scoped stuff. I suggest we add support for `// eslint ...`, `// eslint-env ...`, ... as block or function scoped inline configuration.
>
> If anyone is worried about people mistaking `//` rules for the non-scoped rules you can wrap around a small piece of code. Then we could add the requirement that scoped rules must be declared at the top of their scope and consider use elsewhere to be a linter error.

**Comment by dantman** [comment]
Inspecting the code I can see how implementation might be tricky.

Right now 
* The source is parsed and transformed into a nested syntax tree.
* eslint traverses this whole tree firing enter/exit events for all node types.
* All rules (active in the config files?) are handled during this walk by event listeners listening for those events.
* I think this process also saves a list of comments in the file. And it ends without any inline config parsing.
* After this parsing eslint only holds on to a reduced ast that contains a list of comment nodes and a flat list of syntax tokens with no structure.
* eslint parses all the comments in the file for inline configuration. For each it saves what rules to enable/disable/change and the start position (line+col) to begin that at.
* Then when reporting the errors/warnings eslint looks up the line+col of the error/warning and the (inline) config and sees if it should ignore the report.

So the actual inline configuration is currently entirely based on line+col positions. Run at a stage where the nested tree structure is gone.

Implementing func/block scoped rules is going to require parsing of at least the scoped inline rules to be done during the same tree traversal as when the rules themselves are handled instead of afterwards.

Then it can be implemented in one of two ways.

**A)**
Scoped inline rules will need to be associated with their scope node. Either by abusing the ast node by recording the eslint rules in it. Or using an object => object map (collections module or an es6 map should work).

Error/warning reports will need to pass along what scope they belong to in addition to line+col.

Finally, when deciding whether to ignore the report based on scoped rules. The scope will be grabbed, it and its parents will be checked for any inline configuration that would say to ignore it (walk through the `.upper` in each scope node).

**B)**
When parsing scoped inline rules in the tree traversal. The enable/disable/changed rules will be recorded with both a start line+col position and an end line+col position. These positions will be the start/end pos of the scope node (eg: The FunctionDeclaration's block).

When deciding whether to ignore a report. Both the position based and scoped inline config will be examined in the same way. At a line+col position basis. With the change that if one of those contains an end position in addition to a start position it will be obeyed.

----

As an ideal A would be nice. Properly handling scope by using the scope in the ast itself. However practically I have a feeling that B will have less trouble being implemented. As rules don't need to declare the scope of what they report. And there won't be any confusion or messy implementations of how to resolve conflicts in which inline configuration has a higher precedence when line+col based and scope based inline configurations are mixed.

For B it may be ideal to move parsing of both line based and scoped inline configuration to the traversal, instead of done line based ones after. As that will be the easiest way to preserve any parse order based inline config precedence order.

**Comment by nzakas** [comment]
Code speaks louder than words :) if you want to try it out, we are happy to review

**Comment by dantman** [comment]
I tried working with the code a bit and it appears I'm partially wrong.

During traversal the enter callback does have access to everything necessary to parse block commits the way they need to.

However it appears that eslint actually iterates through the list of inline config comments **before** it sets up and starts the traversal of the tree. This tree traversal is actually where eslint adds in `.parent` onto nodes. And as a result that list of comment nodes eslint uses has none of the context necessary to understand where in the ast (relative to blocks, functions, etc...) it is.

eslint then incorporates the inline rules into the config it uses to parse that file (so eslint actually avoids running unused rules).

Unfortunately this means that the only way to parse out block comments is to traverse the ast twice. Once to parse block comments (and setup `.parent`). And once more to emit node/exit events used by rules implementations – after rules have been setup.

Do the eslint developers consider traversing the ast twice for each file acceptable?
((I don't know the performance implications))

**Comment by nzakas** [comment]
We need to avoid traversing the AST multiple times, as it's a perf issue.

**Comment by dantman** [comment]
Ok. So that's a problem.

I can only see two potential alternatives to look into.

A) See if there's any way at all to do a lite traversal over the tree. (Only looking at function/block nodes and the leading comments in the blocks)

B) Re*write* the way rules are handled. So instead of initializing all the ones used up-front and then ignoring some. The rules structure becomes a dynamic thing. eslint starts with a set of rules then as it encounters inline configuration adds any new rules it needs. (theoretically this should be possible as rule related things should happen after the comment; however theoretically I do not know if there are any rules that might be enabled inline but actually require handling something like a Program:enter event to initialize)

Though, maybe I'm wrong and it could be possible to scan block inline configuration comments up front without context and include their rules. But do the contextual parsing of what sections of code they apply to later. (option C)

**Comment by nzakas** [comment]
Partial traversal is still traversal, so that doesn't help the situation much.

Option B seems very risky.

Overall, I'm concerned that trying to implement this will cause a perf issue or otherwise be so much work that it causes a lot of existing functionality to break. In either case, this isn't a high enough priority for me to rationalize accepting either scenario since we are talking about a third way to disable rules inline.

If you'd like to keep exploring, I'd welcome the discussion, I just think any solution to this needs to be performant and not involve rewriting a ton of stuff.

**Comment by joezimjs** [comment]
I'd like to vote up this issue. Generally, this can be worked around by moving code that needs different rules into a separate file and making sure you do linting before combining files, but this may not be ideal since we'd break things down based on linting preferences rather than what makes sense for the code itself.

**Comment by platinumazure** [comment]
@eslint/eslint-team Is this still something we want to look at, or will our current suite of `eslint-disable-*` comments be sufficient at this point?

**Comment by ilyavolodin** [comment]
I think somebody already tried to implement this a while back, and it proven to be too hard to do, and would require a lot of additional code. In my mind, it's not worth it.

**Comment by joezimjs** [comment]
What you have is definitely sufficient in my mind. When I originally voted/commented before I hadn't been able to find the documentation for the `eslint-disable-*` comments, but now that I know they exist, these comments are great.

**Comment by nzakas** [comment]
Given that there hasn't been any movement on this in a long time, I think we can safely close it. Definitely not a priority.
