### ISSUE TITLE
Add an `--ignore-unknown` CLI option (a la Prettier)

### ISSUE THREAD

**Issue by aradalvand** [eslint/eslint#17713]
### ESLint version

v8.48.0

### What problem do you want to solve?

When using ESLint on staged files in a Git pre-commit hook, it errs on unknown file extensions:

![image](https://github.com/eslint/eslint/assets/26527405/547c6cb9-622e-4ef6-a78d-9e3883d225ad)

### What do you think is the correct solution?

Prettier addressed this very issue a few years ago with the `--ignore-unknown` option: https://github.com/prettier/prettier/issues/8136
A similar flag could be added to ESLint.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Hi @aradalvand, thanks for the issue!

This option already exists:

https://eslint.org/docs/latest/use/command-line-interface#--no-warn-ignored

The option is available only in the [new flat config system](https://eslint.org/docs/latest/use/configure/configuration-files-new) since the eslintrc config system has been deprecated.

Iin the new flat config system, files with unknown extensions are considered ignored, so this option should cover all examples from the original post.
