### ISSUE TITLE
Rule Change: Make an exception for max-params in case of a callback

### ISSUE THREAD

**Issue by MARCxGAMBIT** [eslint/eslint#17727]
### What rule do you want to change?

max-params

### What change to do you want to make?

Implement suggestions

### How do you think the change should be implemented?

A new option

### Example code

```js
sap.ui.define([
    "sap/ui/base/ManagedObject",
    "sap/ui/core/Fragment",
    "sap/ui/core/syncStyleClass",
    "sap/ui/model/json/JSONModel"
], (ManagedObject, Fragment, syncStyleClass, JSONModel) => {

    const BaseFragment = ManagedObject.extend("myapp.ext.fragments.BaseFragment", {
        constructor(controller) {
            ManagedObject.prototype.constructor.call(this);
            // more code
        },
    });
});
```

### What does the rule currently do for this code?

I am using a web framework by SAP. Instead of using regular imports they have their own syntax to load dependencies. Path to the dependencies is passed as an array, second param is a callback with as many params as there are dependencies in the array. It's not uncommon to have like 20 dependencies (and then 20 params in the callback).

I want to be able to enforce max-params for my own code, but if a callback in a lib or framework expects 10 params then so be it.

### What will the rule do after it's changed?

The rule will make an exception for callbacks that I do not call myself and therefore cannot refactor the code to pass an object instead of 10 individual params.

### Participation

- [ ] I am willing to submit a pull request to implement this change.

**Comment by Rec0iL99** [comment]
Hi @MARCxGAMBIT, thanks for the issue. We currently aren't making any further changes to the stylistic rules due to the policy change stated in the [README](https://github.com/eslint/eslint#stylistic-rule-updates).

You can try disabling the rule for a specific callback function by using [configuration comments](https://eslint.org/docs/latest/use/configure/rules#disabling-rules) or copy the existing core rule into a custom rule and add your own options.

```js
sap.ui.define([
    "sap/ui/base/ManagedObject",
    "sap/ui/core/Fragment",
    "sap/ui/core/syncStyleClass",
    "sap/ui/model/json/JSONModel"
], 
// eslint-disable-next-line max-params
(ManagedObject, Fragment, syncStyleClass, JSONModel) => {

    const BaseFragment = ManagedObject.extend("myapp.ext.fragments.BaseFragment", {
        constructor(controller) {
            ManagedObject.prototype.constructor.call(this);
            // more code
        },
    });
});
```

[playground](https://eslint.org/play/#eyJ0ZXh0IjoiLyplc2xpbnQgbWF4LXBhcmFtczogW1wiZXJyb3JcIiwge21heDogM31dKi9cbi8qZXNsaW50LWVudiBlczYqL1xuXG5zYXAudWkuZGVmaW5lKFtcbiAgICBcInNhcC91aS9iYXNlL01hbmFnZWRPYmplY3RcIixcbiAgICBcInNhcC91aS9jb3JlL0ZyYWdtZW50XCIsXG4gICAgXCJzYXAvdWkvY29yZS9zeW5jU3R5bGVDbGFzc1wiLFxuICAgIFwic2FwL3VpL21vZGVsL2pzb24vSlNPTk1vZGVsXCJcbl0sIFxuLy8gZXNsaW50LWRpc2FibGUtbmV4dC1saW5lIG1heC1wYXJhbXNcbihNYW5hZ2VkT2JqZWN0LCBGcmFnbWVudCwgc3luY1N0eWxlQ2xhc3MsIEpTT05Nb2RlbCkgPT4ge1xuXG4gICAgY29uc3QgQmFzZUZyYWdtZW50ID0gTWFuYWdlZE9iamVjdC5leHRlbmQoXCJteWFwcC5leHQuZnJhZ21lbnRzLkJhc2VGcmFnbWVudFwiLCB7XG4gICAgICAgIGNvbnN0cnVjdG9yKGNvbnRyb2xsZXIpIHtcbiAgICAgICAgICAgIE1hbmFnZWRPYmplY3QucHJvdG90eXBlLmNvbnN0cnVjdG9yLmNhbGwodGhpcyk7XG4gICAgICAgICAgICAvLyBtb3JlIGNvZGVcbiAgICAgICAgfSxcbiAgICB9KTtcbn0pOyIsIm9wdGlvbnMiOnsiZW52Ijp7fSwicnVsZXMiOnt9LCJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e30sImVjbWFWZXJzaW9uIjoibGF0ZXN0Iiwic291cmNlVHlwZSI6Im1vZHVsZSJ9fX0=)
