### ISSUE TITLE
Indent Rule completely ripped straight from JSCS with incorrect attribution

### ISSUE THREAD

**Issue by mikesherov** [eslint/eslint#1774]
https://github.com/eslint/eslint/blob/master/lib/rules/indent.js

Has a copyright notice claiming I own the copyright to the original code when it belongs to Marat Dulin and contributors. It is also missing a copy of our MIT license which must be present in any significant copy of the software.

I'll also use this opportunity to ask why eslint feels it needs to copy all of JSCS's rules:  https://github.com/eslint/eslint/search?q=missing+rule&type=Issues&utf8=%E2%9C%93 It seems to me that the two projects have very different goals, and I wonder whether the ESLint team feels like it's a duplication of effort to port all of JSCS's rules over to ESLint. JSCS's ambitions are to remain a style checker and formatter promoting existing style guides. I always believed that ESLint's goals were to make a pluggable linter and had most of its ambitions in code correction.

ESLint can choose any path forward it wants, and there'll be no hard feelings if ESLint continues down its current course of copying every rule we implement, but I'm legitimately curious if there isn't a better way forward here.

**Comment by mikesherov** [comment]
Furthermore, I'd like to claim the $100 bounty for this issue: https://www.bountysource.com/issues/2827565-new-rule-indent

**Comment by Aintaer** [comment]
![:wink:](http://i.imgur.com/H2ntBPd.gif)
:+1:

**Comment by markelog** [comment]
/cc @mdevils 

> I'm legitimately curious if there isn't a better way forward here

seems like we're competitors in some sense, which is very peculiar

**Comment by nzakas** [comment]
Sorry, it was on my list to go through and verify the copyright and license before our next release, I'll be sure to get this fixed. I'll also make sure you get the bounty, just need to be investigate how to do that. Would you prefer the money be donated to JSCS or something else?

As for the goal of ESLint, we have said from the start that we make no distinction between stylistic and non stylistic rules, we are happy to provide both. Our users have repeatedly asked us to support rules that already exist in WebStorm, JSLint, JSHint, and JSCS, and we do our best to support the ones we can. I don't see that trend changing anytime soon.

To be clear, our plan is not "literally copy everything from JSCS", this is the first time this happened because someone wanted to see if it would work. In every other case, someone wrote new code, and I expect that to be the case for most requests going forward. If someone does copy code, I'll do a better job of verifying the copyright and license information before merging to avoid further confusion.

**Comment by mdevils** [comment]
Wow. I can't believe `eslint` developing is like this.

**Comment by mrjoelkemp** [comment]
From #1698 by @nzakas:

> I wouldn't call this blindly copying, I think we've done a good job of poking at what's there and seeing what breaks.

and your response:

> Our users have repeatedly asked us to support rules that already exist

I don't see why you just wouldn't consider directing people to use JSCS for the indentation rule and/or strengthening the indent rule there instead of creating *yet another* divergence in tools.

The JSCS team has always been *very* open to directing people to ESLint for use-cases that don't fit the tool's mission and to welcoming new contributors. 

Was it never discussed to just make the JSCS rule better?

> This is the biggest gap between ESLint and both JSHint and JSCS

In line with the comment from @mikesherov, does ESLint need to be a superset of both tools? Seems like an impossible, never-ending, catch-up task given the rate of development on both projects.

**Comment by mikesherov** [comment]
@nzakas I was of course kidding about the bounty. Donate it to a charity of your choice. 

I'd like to focus my question further: 
1. Why didn't the ESLint team reach out to us to see if we're interested in collaborating, especially after other maintainers of ESLint expressed doubts and discomforts over "blindly copying"?
1. Does the ESLint team not find it odd to copy rules from JSCS if the stated goal of that effort is to replace JSCS?

**Comment by michaelficarra** [comment]
I've said it many times: eslint should only make structural assertions. Anything that requires token position information and other insignificant concrete syntax should be pushed off to jscs. This would allow eslint to take an existing AST as input. But my opinion doesn't hold much weight around here.

**Comment by rwaldron** [comment]
> Our users have repeatedly asked us to support rules that already exist in WebStorm, JSLint, JSHint

JSHint is actively deprecating and ultimately removing all style related rules, in favor of JSCS. The project is so committed to this goal that @mikesherov was made a core committer in order to more efficiently contribute to by helping users that file issues related to this change (and of course his other great talents). The response has been overwhelmingly positive, as users are genuinely excited to learn about JSCS and integrate it into projects.

**Comment by nzakas** [comment]
ESLint was started to completely replace JSHint (style and non-style rules alike), and the subsequent decision to remove style rules from JSHint coupled with the creation of JSCS doesn't mean that the original goal is invalid. I've said both privately and publicly that I think both JSHint and JSCS are useful, and I'd never fault anyone for using either or both and completely ignoring ESLint if they so choose.

Today, ESLint has a not-insignificant user base that does not want to use two separate tools. We have heard this repeatedly. Obviously, this is a different mode of operation than what JSHint+JSCS users prefer, and I don't see any reason why either of us should be forcing anyone in either direction.

As I've mentioned, this particular rule was submitted by an outside contributor and I did my best to handle the situation appropriately. I clearly could have handled it better and, in retrospect, I should have contacted someone on the JSCS team to talk through the implications of this pull request. Most of you know me and know that I do my best to be as collaborative and transparent as I possibly can, and in this case, I fell short. I'm sorry.

So here's what I'm going to do:

1. Revert the commits related to the indent rule.
1. We will no longer accept contributions containing code from JSCS unless someone from the JSCS team has explicitly stated on the pull request that they approve.
1. Personally donate $100 on BountySource to both JSHint and JSCS.

**Comment by mikesherov** [comment]
Thank you for the apology. I was mostly upset because I want everyone to move forward collaboratively and together, and I'm seeing a lot of overlapping work in this space. Duplicated effort is my enemy here. I suppose I too reacted a bit harshly, and I hope we can continue to work together effectively in our other shared endeavors, like espree and esprima.

I'm not sure why we can't share functionality by having JSCS be a dependency of ESLint or vice versa, You'd save a lot of time and effort. But I suppose we can talk about that another time.

1. With regards to the indentation rule, you don't need to revert it if you include the required license information, because now I'm giving permission, as required by clause 1 of the ESLint CLA. However, I suggest you take the approach JSCS will be taking and add additional rules to indentation as independent rules that use the underlying engine. People are crazy with how they intend!
1. Thanks.
1. We have nothing we can do with the money. Please instead donate it directly to http://www.blackgirlscode.com/

Thanks!

**Comment by puzrin** [comment]
> Wow. I can't believe eslint developing is like this. 

@mdevils No need to make such conclusions from single 3-rd party PR. Independent indent rule is available as [plugin](https://github.com/nodeca/eslint-plugin-nodeca) for a long time.

**Comment by mikesherov** [comment]
@puzrin the matter is settled, but for the record: The PR was reviewed and discussed at length. Everyone involved knew it was a straight copy. Simply accept the fact that it was the wrong thing to do in this case, and everyone goes home happy.

**Comment by rwaldron** [comment]
> We have nothing we can do with the money. Please instead donate it directly to http://www.blackgirlscode.com/

Same for JSHint.

**Comment by nzakas** [comment]
@mikesherov thanks Mike. I will donate to http://www.backgirlscode.com and resubmit the reverted commit with the updated attribution information. I'll then add you to the pull request so you can verify the attribution is accurate before merging.

@rwaldron sure thing Rick.

**Comment by nzakas** [comment]
![donation](https://cloud.githubusercontent.com/assets/38546/6087134/c10fd7b2-adfc-11e4-8a2c-657b172ea758.png)

**Comment by puzrin** [comment]
@mikesherov , i've reviewed code quickly, but i didn't knew that it was taken as is from JSCS, seriously. I had a couple of similar complains (sometime shit happens with large codebases), and know very well, that even MIT code should be copied with proper attribution.

The point of my message is that it not good to generalaze single bad situation to all project. And link to license clear code as a proof, that eslint can care about indents independently.

I don't  mean anyhow, that accepting PR with missed attribution is ok. Just a wish to avoid generalizations.

**Comment by mikesherov** [comment]
@puzrin, please...


![](http://i.imgur.com/uRJWytw.jpg)

**Comment by markelog** [comment]
> I'm not sure why we can't share functionality by having JSCS be a dependency of ESLint or vice versa, You'd save a lot of time and effort

I think its great idea! Both projects are supposed to be pluggable, if we would agree on the one universal interface, we could easily share the code and move both projects forward.

Only need to find right place to have discussion about it.

**Comment by mikesherov** [comment]
Hooray, the true winners here are Black Girls Code!

**Comment by puzrin** [comment]
Let's double their fun, lol

![bg](https://cloud.githubusercontent.com/assets/319465/6087565/3064a2a8-ae5e-11e4-8933-23781800cc2c.png)

**Comment by nzakas** [comment]
Thanks everyone for their comments. I'm going to lock this issue so we can all move on.
