### ISSUE TITLE
Bug: Breaking change since 8.52.0. Attempt to clone rule config contains non-serializable fields

### ISSUE THREAD

**Issue by LIMPIX31** [eslint/eslint#17767]
### Environment

Node version: 19.9.0
npm version: 9.6.3
Local ESLint version: 8.53.0
Global ESLint version: 8.53.0
Operating System: Linux

### What parser are you using?

@typescript-eslint/parser

### What did you do?

# Configuration

```js
'import-sort/imports': [
    'error',
    {
      matchers: [
        {
          name: 'side',
          fn: (s) => s.startsWith('\0'),
        },
        {
          name: 'relative',
          fn: (s) => s.startsWith('.'),
        },
        {
          name: 'node',
          fn: (s) => s.startsWith('node:') || nodeMatcher.test(s),
        },
        {
          name: 'privileged',
          fn: (s) => privilegedMatcher.test(s),
        },
        {
          name: 'workspace',
          fn: (s) => workspaceRegex.test(s),
        },
        {
          name: 'unqualified',
          fn: () => true,
        },
      ],
    },
  ],
```

### What did you expect to happen?

Work the same as before 8.52.0

### What actually happened?

Following breaking change https://github.com/eslint/eslint/commit/5de9637fc925729a83d5a5e9e868a41792a184e3 does `JSON.parse(JSON.stringify())` serialization of rule config.

This causes eslint to crash with an error serialize fields that cannot be serialized by `JSON.stringify`. In my case the functions.

```
Error: Key "rules": Key "import-sort/imports": (s) => s.startsWith('\0') could not be cloned.
```

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Consider disabling cloning

**Comment by mdjermanovic** [comment]
Configurations were always expected to be serializable, and rules are not supposed to have options that accept functions. Some features, in particular [`--print-config`](https://eslint.org/docs/latest/use/command-line-interface#--print-config) and [`--cache`](https://eslint.org/docs/latest/use/command-line-interface#--cache), don't work well with non-serializable configs, though silently. For instance, if you change a function that is rule's option, ESLint will not invalidate the cache because it doesn't see the change in the serialized config, so you'll be still getting cached lint results that may now be wrong because of the configuration change.

I think this is not a bug, but rather a good opportunity to make a hard requirement that rules can't have function options. @nzakas what do you think?

**Comment by nzakas** [comment]
Yes, configs were never intended to support functions. If a config isn't serializable, there are all kinds of potential side effects. I'm kind of surprised that this type of rule configuration was working at all to this point. To me, allowing functions in rule options is the bug.

**Comment by LIMPIX31** [comment]
I think I got the answer I needed, so I'll close the issue.
