### ISSUE TITLE
Change Request: use the cache more effectively when fixing files

### ISSUE THREAD

**Issue by kkmuffme** [eslint/eslint#17805]
### ESLint version

v8.54.0

### What problem do you want to solve?

It would be great if there could be a little discussion about using the cache more effectively to speed up eslint on repeated runs.

https://eslint.org/docs/latest/use/command-line-interface#caching

>Autofixed files are not placed in the cache. Subsequent linting that does not trigger an autofix will place it in the cache.

1) is there a specific reason for this?

----

2) when using `content` strategy, it should save both the input and output. (but only overwrite the input in existing cache file if it's DIFFERENT from the output or the cache file doesn't exist yet)

e.g. what happens tons of times is:
branch featureX - file A: eslint runs and auto-fixes something and is added to the cache (when eslint is run again)
switch branch
branch featureY - file A: file A is the same file as in featureX branch (before eslint ran there), but cache isn't used, since the cache file only stored the "after" run content.

This is especially annoying if you switch branch, then come back to the previous branch later (all auto-fixes of eslint are gone, bc not committed back then) and eslint needs to run everything again, even though files are same as before.

This is what happens in CI all the time and is probably wasting 1000s of CPU hours a day, given in how many CI pipelines eslint is used.

Eslint could be much, much faster if the cache would be used more effectively by always storing a before and after content version, instead of just after.

### What do you think is the correct solution?

See above

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
> > Autofixed files are not placed in the cache. Subsequent linting that does not trigger an autofix will place it in the cache.
> 
> 1. is there a specific reason for this?

For reference, this was discussed in https://github.com/eslint/eslint/pull/10571.

We could possibly improve this, but I'm not sure if it's worth the complexity since usually only a small number of files are autofixed.

> 2\. when using `content` strategy, it should save both the input and output. (but only overwrite the input in existing cache file if it's DIFFERENT from the output or the cache file doesn't exist yet)

Can you please expand on this? I'm not sure I understand the proposal.

> e.g. what happens tons of times is: branch featureX - file A: eslint runs and auto-fixes something and is added to the cache (when eslint is run again) switch branch branch featureY - file A: file A is the same file as in featureX branch (before eslint ran there), but cache isn't used, since the cache file only stored the "after" run content.
> 
> This is especially annoying if you switch branch, then come back to the previous branch later (all auto-fixes of eslint are gone, bc not committed back then) and eslint needs to run everything again, even though files are same as before.

This seems to me like an uncommon scenario, as autofixed files are typically committed. In the scenario you described, file A was previously committed although it had fixable lint errors, and the two branches are now separately autofixing the same file in the same way?

> This is what happens in CI all the time and is probably wasting 1000s of CPU hours a day, given in how many CI pipelines eslint is used.

Can you clarify how this can happen in CI? I don't think `--fix` is commonly used in CIs.

**Comment by mdjermanovic** [comment]
Thanks for the details. I ask about use cases because eslint caching is intended to improve performance in common ones. Caching is generally a complex problem, and I don't think we would want to make it more complex by storing multiple versions of the same file to address an edge case or an uncommon use of ESLint. I still think that having files with fixable lint errors committed is not a common scenario.

> It's common with legacy projects where eslint is added or also when adding new eslint rules/plugins to a project's config. e.g. I am working on file B in the branch to add a feature.
> Since eslint runs for the whole project, it auto-fixes file A, I didn't even touch. This auto-fixed file doesn't get committed, since it's not part of what I'm working on .

File A should have been autofixed and committed in the same commit that added new rules/plugins. It's uncommon to enable a new rule and commit only the new configuration without fixing the errors reported by the rule.

> Another probably even more common scenario is where other tools (e.g. prettier,...) modify the file on every run because there are conflicting errors between those tools. This leads to the cache file never being used, as there are (the same) fixes applied on every run.

This looks like a case where conflicting rules should be disabled as they seem useless because other tools override them.

> > Can you clarify how this can happen in CI? I don't think --fix is commonly used in CIs.
> 
> It's used commonly in the build step to ensure the fixed code is actually valid and, as in the above example, if other tools run on it too.

Can you provide links to some projects that run `eslint --fix` in CI? I think that fixing source code in CI is fairly uncommon.

**Comment by Rec0iL99** [comment]
@kkmuffme there's a [comment](https://github.com/eslint/eslint/issues/17805#issuecomment-1837112017) for you to look into.

**Comment by fasttime** [comment]
> I'm not really familiar with JS open source (only contribute to other languages open source) so I can't provide you a public repo link - however for closed source I have worked with various companies that applied code style fixes automatically in CI/CD pipelines as one part of the purpose of CI/CD is to reduce load on developers by running automatically what can be run automatically.

I think it will be difficult to explore this proposal without a repository to start with. Even if someone decides to prototype a new caching model with the ideas exposed here, it won't be possible to verify the impact of their changes without a repro of some kind.

**Comment by bmish** [comment]
The ideas mentioned for improving the cache sound interesting. Perhaps they would be more compelling if we knew they wouldn't significantly increase the complexity of the caching logic.

But having realistic scenarios in which these improvements would help is important too. I agree with @mdjermanovic that, in general, linting violations should not be committed, and that it's unusual for CI to be running autofix. It's generally best practice to not enable a lint rule for a project or a file until that project or file is in compliance with the rule. To go along with your "clean as you code" approach, you can enable linting one file or one folder at a time, rather than enable it everywhere for code that isn't in compliance yet.
