### ISSUE TITLE
How to config two different parsers in flat config

### ISSUE THREAD

**Issue by JackieCheung** [eslint/eslint#17880]
### Environment

Node version: v21.4.0
npm version: v10.2.4
Local ESLint version: v8.56.0 (Currently used)
Global ESLint version: v8.48.0
Operating System: darwin 23.2.0

### What parser are you using?

vue-eslint-parser

### What did you do?

As the parserOptions key has been moved into languageOptions in the new config system, how to configure two different parsers just like defining in .eslintrc
```
  parser: 'vue-eslint-parser',
  parserOptions: {
    ecmaVersion: 'latest',
    parser: '@typescript-eslint/parser',
    sourceType: 'module'
  }
```

### What did you expect to happen?

Want to know how to configure two different parsers in the new config system.

### What actually happened?

There is no relevant explanation in the doc.

### Link to Minimal Reproducible Example

https://eslint.org/docs/latest/extend/plugin-migration-flat-config

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @JackieCheung, thanks for the issue! 

> As the parserOptions key has been moved into languageOptions in the new config system, how to configure two different parsers just like defining in .eslintrc
> 
> ```
>   parser: 'vue-eslint-parser',
>   parserOptions: {
>     ecmaVersion: 'latest',
>     parser: '@typescript-eslint/parser',
>     sourceType: 'module'
>   }
> ```

Top-level `parser` in eslintrc is `languageOptions.parser` in flat config, with the difference that in flat config it must be an object (loaded parser, not module specifier like in eslintrc). This is explained in the configuration migration guide:

https://eslint.org/docs/latest/use/configure/migration-guide#custom-parsers.

`parserOptions.parser` is an option specific to `vue-eslint-parser`. ESLint doesn't see this configuration as "two parsers", but one parser (`vue-eslint-parser`) with options that will be just passed to it. How `parserOptions.parser` should be configured in flat configs depends only on `vue-eslint-parser`, because `vue-eslint-parser` handles this option. If this isn't already explained in the docs for this parser, you can submit an issue to the `vue-eslint-parser` repository:

https://github.com/vuejs/vue-eslint-parser
