### ISSUE TITLE
Repo: Remove unused tools/update-rule-types.js

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#18121]
Splitting out of https://github.com/eslint/eslint/pull/18005#discussion_r1458066125: it looks like [`tools/update-rule-types.js`](https://github.com/eslint/eslint/blob/cace6d0a3afa5c84b18abee4ef8c598125143461/tools/update-rule-types.js) can be safely deleted.

> Yeah, it was a one-time thing, just kept it around because we had to do several rounds before we got everything correct. It's probably safe to remove at this point.

**Comment by fasttime** [comment]
Probably [tools/rule-types.json](https://github.com/eslint/eslint/blob/b4e0503a56beea1222be266cc6b186d89410d1f2/tools/rule-types.json) is also safe to delete. Besides update-rule-types.js, that file is only referenced in [Makefile.js](https://github.com/eslint/eslint/blob/93ffe30da5e2127e336c1c22e69e09ec0558a8e6/Makefile.js#L677), to make sure that it contains an entry for each rule. But at this point, since there are no other references, that check could be also safely removed.

**Comment by fasttime** [comment]
@JoshuaKGoldberg would you like to submit a PR for this change?
