### ISSUE TITLE
Repo: 'documentation' label added and removed quickly on PRs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/eslint#18183]
In #18181, I sent the PR as a draft and force-pushed a few times while working on small changes. The expectation I had was that nothing would happen between force pushes to clutter the timeline shown on GitHub.

In actuality, two repo bots both took action after each push:

1. [@eslint-github-bot](https://github.com/apps/eslint-github-bot) would add the `documentation` label
2. `@github-actions bot` ([`actions/labeler`](https://github.com/actions/labeler)) would then immediately remove the `documentation` label

<img width="874" alt="Screenshot of the two actions steps happening after each of three force pushes" src="https://github.com/eslint/eslint/assets/3335181/abb37dcb-fa01-4be9-84e9-b0bc5aac8583">

I got a chuckle out of this one. But also couldn't figure it out - why is the label being _removed_?

**Comment by harish-sethuraman** [comment]
I had mentioned something similar in this https://github.com/eslint/eslint/pull/18109#discussion_r1489004544


To verify what might be wrong I re ran the labeller action. Seems like it didn't flag even after the changes were made in the docs directory. May had some issues with glob for nested routes?

But we should consider keeping this label at one place is what I feel.  cc: @snitin315

**Comment by kecrily** [comment]
One thing shouldn't be done by two bots. We should choose one or the other.

**Comment by Tanujkanti4441** [comment]
If we see this PR [18175](https://github.com/eslint/eslint/pull/18175) (just for example) then the new labeler is not interfering with the github bot, is it possible that the new pr-labeler adds labels only when existing file has been changed not on adding new files.

**Comment by nzakas** [comment]
I think I know what's going on here. It's not that one bot is adding a label and the other is removing it. It's that the labeler action uses the [set labels](https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#set-labels-for-an-issue) API to assign labels, which removes any existing labels while adding new ones.

It's possible this is a bug in the labeler action because it [gets the existing labels](https://github.com/actions/labeler/blob/83720bce8638d1b5b7b15ae76465522ca7ea2eec/src/labeler.ts#L42) before deciding what to do. Does anyone want to follow up on that?

**Comment by nzakas** [comment]
There's an existing issue on the labeler action:
https://github.com/actions/labeler/issues/763

**Comment by nzakas** [comment]
No response on the labeler action. So, we can prevent our bot from adding this label to solve this problem...however, the issue is that the bot is used in all of our repos and the labeler action is not.

Maybe we should just disable the `documentation` label in the labeler action?
