### ISSUE TITLE
Bug: flat CLI command --no-warn-ignored does not work

### ISSUE THREAD

**Issue by allinne** [eslint/eslint#18219]
### Environment

Node version: v20.6.1
npm version: 9.8.1
Local ESLint version: 8.51
Global ESLint version: -
Operating System:  MacOS Ventura 13.6.1

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

I use lint-staged@15.2.0 to run pre-commit hook
</details>

```js
{
  "*.{js,jsx,ts,tsx}": [
    "eslint --fix --max-warnings=0 --no-warn-ignored"
  ],
  "*.{html,css,less,ejs}": [
    "prettier --write"
  ]
}
```

### What did you expect to happen?

No warning regarding --no-warn-ignored 

### What actually happened?

Got an error in console: 
```
Invalid option '--warn-ignored' - perhaps you meant '--ignore'?
```

If I do `npx eslint -h` the console shows me:
```

Miscellaneous:
  --init                          Run config initialization wizard - default: false
  --env-info                      Output execution environment information - default: false
  --no-error-on-unmatched-pattern  Prevent errors when pattern is unmatched
  --exit-on-fatal-error           Exit with exit code 2 in case of fatal error - default: false
  --debug                         Output debugging information
  -h, --help                      Show help
  -v, --version                   Output the version number
  --print-config path::String     Print the configuration for the given file
```
There is no `--no-warn-ignored` documentation.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/allinne/eslint-no-warn-ignored

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @allinne, thanks for the issue!

As noted in [`--no-warn-ignored` documentation](https://eslint.org/docs/latest/use/command-line-interface#--no-warn-ignored), this option is available in [flat config](https://eslint.org/docs/latest/use/configure/configuration-files-new) mode only. Since you're using an `.eslintrc.cjs` config file, you're running ESLint in eslintrc mode, where this option is not available. You'll need to switch your configuration to flat config to use this option.
