### ISSUE TITLE
Bug: Unable to test rules in v9 in both flat config and eslintrc

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#18292]
### Environment

Node version: n/a
npm version: n/a
Local ESLint version: v9.0.0
Global ESLint version: none
Operating System: n/a

### What parser are you using?

Default (Espree)

### What did you do?

A contributor ran the RuleTester with `ESLINT_USE_FLAT_CONFIG=false`, but it seems like there's no way my eslint plugin can maintain compatibility with eslint v9 and eslintrc (since unless it's tested, it's not compatible)

### What did you expect to happen?

I expected RuleTester to function just like it did in eslint v8, so I can test rules via eslintrc.

### What actually happened?

https://github.com/import-js/eslint-plugin-import/pull/2996#issuecomment-2041884005 reports it's an error

### Link to Minimal Reproducible Example

https://github.com/import-js/eslint-plugin-import/pull/2996#issuecomment-2041884005

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
As we [announced](https://eslint.org/blog/2023/10/flat-config-rollout-plans/#flat-config-by-default-in-eslint-v9.0.0), `RuleTester` in v9 now tests against flat config because that is the default configuration system.

Functionally, if your rules pass `RuleTester` in v9, they should work with eslintrc also, as the fundamental parts of rule tester remain the same, it's really just the format of the options that have changed.

If you really need to test eslintrc specifically, then you'll need to use ESLint v8.x for that.

**Comment by ljharb** [comment]
It makes perfect sense for RuleTester to test it by default, but I don't understand why eslint 9, which still supports two config systems, has failed to provide a way to test both.

**Comment by aladdin-add** [comment]
I'm 👍 to the change.

Remember: users can still use eslintrc with eslint v9 (`ESLINT_USE_FLAT_CONFIG=false`), but it's no longer testability.
