### ISSUE TITLE
Need literal number exception for no-extra-parens

### ISSUE THREAD

**Issue by bedney** [eslint/eslint#1836]
Messaging a Number literal in JavaScript is legal, as long as the literal is wrapped in parentheses:

(123).sayHi();

The `no-extra-parens` rule is catching this and shouldn't be.

**Comment by michaelficarra** [comment]
Use `123..sayHi()` or `123 .sayHi()`.

**Comment by bedney** [comment]
Those forms are hard to guess and look unnatural.

Also, 123.45..sayHi() doesn't work, whereas (123.45).sayHi() does.

But all of that is beside the point. (123).sayHi() is a legal construct from the earliest ECMAScript days.

**Comment by michaelficarra** [comment]
> Also, 123.45..sayHi() doesn't work

But `123.45.sayHi()` works.

> all of that is beside the point.

It's not besides the point because the rule is asking you to avoid parens when they are not required. And these parentheses are 100% not required, as I've shown.

> (123).sayHi() is a legal construct

`(((((123))))).sayHi()` is also legal, what is your point?

**Comment by nzakas** [comment]
Hey guys, let's keep the conversations civil. We're all trying to learn.

@bedney I think the point here is that there's a difference between legal JS syntax and the patterns that a rule flags. Some perfectly legal patterns will get picked up by various rules as violating the rules but that doesn't mean it's invalid syntax. So what we are really talking about is if a pattern should be flagged or not. Sometimes we as exceptions to rules because they are common and sometimes we suggest turning the rule off of it's not common.

**Comment by bedney** [comment]
@nzakas - Agreed.

In the end, after surveying my quite substantial codebase for these occurrences, there really weren't many of them so I ended up just commenting the rule off and on around them. Then I realized that this was some really old code from E3 days (like from 2002) and I retested the expressions that @michaelficarra suggested above and he was indeed right - they worked! It makes me think that one of 2 things happened: Either they changed the numeric literal parsing rules in E5 or the browser parsers have improved to the point where they can handle such syntax.

In any case, I closed the issue as I didn't see the discussion heading to a good place. Thanks both to you and @michaelficarra for continuing to improve this great tool (and educate its users! :-) ).
