### ISSUE TITLE
FlatCompat not working anymore with eslint v9

### ISSUE THREAD

**Issue by codeflorist** [eslint/eslint#18405]
I was using this solution to import the tailwindcss-plugin into the flat-config:
https://github.com/antfu/eslint-config/issues/315#issuecomment-1799052876

this was working with eslint v8, but with v9 it is not working anymore. The tailwindcss-rules don't seem to get applied.

**Comment by mdjermanovic** [comment]
It seems that the cause of the problem is that `eslint-plugin-tailwindcss` doesn't support ESLint v9 yet.

In particular, the plugin is still using `context.parserServices` property:

https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/lib/util/parser.js

This property has been removed in ESLint v9:

https://eslint.org/docs/latest/use/migrate-to-9.0.0#-removed-multiple-context-methods

https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/

When I replace `context.parserServices` with `context.sourceCode.parserServices` locally in the `lib/util/parser.js` file inside `node_modules/eslint-plugin-tailwindcss`, I'm getting the expected `tailwindcss/classnames-order` rule warning with ESLint v9.

Can you submit an issue to the plugin's repo?

https://github.com/francoismassart/eslint-plugin-tailwindcss

**Comment by codeflorist** [comment]
@mdjermanovic I've updated the corresponding issue with your info.

Many thanks for taking a look at it and for your detailed solution!
