### ISSUE TITLE
Docs: double negative in configuration file resolution

### ISSUE THREAD

**Issue by MikeMcC399** [eslint/eslint#18418]
### Docs page(s)

- [v8 > Configuration Files (New) > Configuration File Resolution](https://eslint.org/docs/v8.x/use/configure/configuration-files-new#configuration-file-resolution) and
- [v9 > Configuration Files > Configuration File Resolution](https://eslint.org/docs/latest/use/configure/configuration-files)

### What documentation issue do you want to solve?

Both pages contain the sentence:

> If none of the files are not found, it checks the parent directory for each file.

This is a double negative and it does not make sense the way it is written.

### What do you think is the correct solution?

Remove the word "not", so the sentence becomes:

> If none of the files are found, it checks the parent directory for each file.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by fasttime** [comment]
Thanks for spotting this @MikeMcC399! I don't think we can fix the wording in the v8 docs at this time, because that would require doing a new v8.x release, which isn't planned. But feel free to [submit a pull request](https://eslint.org/docs/latest/contribute/pull-requests) to fix the v9 docs. The file to edit is [docs/src/use/configure/configuration-files.md](https://github.com/eslint/eslint/blob/main/docs/src/use/configure/configuration-files.md?plain=1).

**Comment by MikeMcC399** [comment]
@fasttime 

Thanks for confirming!
- https://github.com/eslint/eslint/pull/18419 should do the trick, at least for `v9` docs.
