### ISSUE TITLE
'consistent-this' should not check parameters

### ISSUE THREAD

**Issue by feross** [eslint/eslint#1846]
This pattern is common:

```js
function MyClass () {
  // ...
}

MyClass.prototype.func = function (msg, code) {
  decorate(msg, code, this)
  // ...
}

function decorate (er, code, self) {
  // ...
}
```

With the eslint rule:

```json
{
  "consistent-this": [2, "self"]
}
```

It incorrectly fails with the message: "Designated alias 'self' is not assigned to 'this'." Can we not check parameter names?

**Comment by nzakas** [comment]
Interesting question. It seems like the rule is behaving correctly. This seems like a personal exception, and we usually recommend manually disabling the rule with a comment in those situations.

**Comment by feross** [comment]
Hm, what about adding an "args" option that can be set to `false`?

**Comment by nzakas** [comment]
My point is that the rule enforces using a specific identifier to assign `this` to. You aren't assigning `this` to it, so I'm not sure the rule should change because you are, in fact, violating the rule by using `self` as an argument. 

This isn't about implementation details, it's about whether an exception makes sense, and I'm not yet convinced it does.

**Comment by doberkofler** [comment]
I had to disable this rule quite a few times because of this code pattern and understand the concern.
I also get @nzakas point that this exception would somehow contradict the original intention of this rule (assigning `this` to a specifically named variable) but do not see any alternative to allowing an exception as suggested by @feross, if we do not want continuing to manually disable the rule.

**Comment by nzakas** [comment]
The rule is really just "ensure that an identifier named x is always assigned the value of this". So this is my conundrum, do we allow an exception that is, indeed, a failure of the existing rule? Maybe the answer is yes, but I need to hear from more people.

**Comment by feross** [comment]
@nzakas Apologies, `jscs` actually enforces both of the rules I listed.

So, what we're really talking about is adding an option/exception that distinguishes between identifiers that are defined in *variables* versus *arguments*.

**Comment by nzakas** [comment]
Yes, that's the question.

**Comment by gyandeeps** [comment]
did we land on something here?

**Comment by nzakas** [comment]
No, still looking for more opinions.

**Comment by IanVS** [comment]
No further opinions have been brought forth in five months.  Anyone care to weigh in?

**Comment by nzakas** [comment]
Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
