### ISSUE TITLE
Change Request: Add autofix for func-style

### ISSUE THREAD

**Issue by camsteffen** [eslint/eslint#18478]
### ESLint version

9.3.0

### What problem do you want to solve?

I'd like to add autofix capability to the func-style lint. I haven't contributed before but I started toying with a local branch and I have it generally working.

Any reason this wouldn't be accepted?

I'd like to just start with the "declaration" option if that's okay. Selfishly, that's the case that I care for. But also there are some extra complications with the "expression" case - namely deciding between var/let/const and between arrow and non-arrow functions.

I can't think of any cases where the fix would break code due to hoisting.

I'm not sure what to do about TypeScript. I suppose it will "just work" for the most part. But one particular case that I foresee being a concern is where there is a type annotation for the entire function: `const x: T = () => {}` or `const x = () => {} as T`. Are there any options for handling these cases besides forking the lint in typescript-eslint?

### What do you think is the correct solution?

Example:
```diff
- const x = () => {};
+ function x() {}
```

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by fasttime** [comment]
Thanks for the issue and for the willingness to help @camsteffen. The `func-style` rule is not autofixable because in some cases replacing a function declaration with a function expression or vice-versa is not guaranteed to preserve the original semantics. Even so, we could think about implementing [suggestions](https://eslint.org/docs/latest/extend/custom-rules#providing-suggestions) for that rule. Unlike autofixes, suggestions are applied manually on request in IDEs. In this way, developers get a chance to review the code before fixing it.

To make your proposal clear, could you please add an example of code that you think could be autofixed, and show how the fixed code would look like?

**Comment by camsteffen** [comment]
> The `func-style` rule is not autofixable because in some cases replacing a function declaration with a function expression or vice-versa is not guaranteed to preserve the original semantics.

I believe the problematic cases can be reduced to only when `var` is used. If `let` or `const` is used, I don't think there is actually any risk of changing semantics since JS does not allow re-declaring the same name with `let` or `const` in the same scope. So, if that is true, could we make it a suggestion for just the `var` case?

Example problem case:

```js
var a = () => console.log('x');
var a = () => console.log('y'); // changing this to a function declaration will change output from y to x
a();
```

> To make your proposal clear, could you please add an example of code that you think could be autofixed, and show how the fixed code would look like?

I added a simple example to OP. Let me know if you'd like to see more.

**Comment by fasttime** [comment]
Thanks for the update. You already noted a situation where converting a function expression into a declaration could change the behavior of the code. While this should be easy to detect by static code analysis, other edge cases may not be that trivial. Consider for example:

```js
const x = () => {};
// ...
if (x.prototype) {
    console.log('unexpected');
}
```

In the above code, if the arrow function `x` is replaced with a function declaration, the code will print `unexpected` because the regular function declaration has different properties that the regular function. It is not always obvious to infer just from the program structure whether applying the fix will preserve the original behavior or not. Typically, built-in ESLint rules do not autofix the code if there is a chance that doing so will result in changing the logic, because those _fixes_ have a potential to introduce hard-to-find bugs.

Another option I mentioned is to add suggestions to the rule for this kind of fix. Alternatively, if you prefer to have the fix applied automatically regardless of the edge cases, you could always fork the `func-style` rule and update it to fit your preferences.

**Comment by camsteffen** [comment]
Hmm I see. Thanks for explaining. Dodging the code-breaking cases is indeed harder than I thought. The issue you highlighted only applies to arrow functions, but I'm afraid that is the primary use case. So auto-fixing seems to be off the table.

I think I would still like to contribute with suggestions if I may. The suggestions can still be auto-applied with an extra flag, right? I think that would still be useful in cases where users are willing to take the risk.

**Comment by fasttime** [comment]
Unfortunately, [a previous request](https://github.com/eslint/eslint/issues/15392) to add suggestions to the `func-style` rule has been rejected because that rule is considered stylistic, and no new features are being added to stylistic rules. I don't think that a new request to add suggestions would be accepted by the team, despite the fact that that rule seems so popular. At this point, I recommend that you fork that rule and add autofix functionality by yourself. If you do that, feel free to share your rule in [a discussion](https://github.com/eslint/eslint/discussions/new?category=show-and-tell) or in chat, and maybe someone else will benefit from your work.

**Comment by camsteffen** [comment]
I may be grasping at straws here, but the readme and blog post seem to leave a grey area for adding suggestions. The spirit of the policy seems to be to not add new options, or that the lint _api_ is frozen.

Thinking about a fork or new lint, I would take the opportunity to re-think the semantics of the lint. I would want to have a `no-const-functions` lint that specifically lints usages with `const`. This would compose well with no-var/prefer-const lints and would allow mutable variables to have functions (maybe that's weird, but that's a different concern). So in a way func-style feels like an artifact of a pre-ES6 world.

Anyways, I guess that's all moot since eslint isn't accepting new stylistic changes. Maybe I'll get inspired and create a plugin. :)

**Comment by fasttime** [comment]
> I may be grasping at straws here, but the readme and blog post seem to leave a grey area for adding suggestions. The spirit of the policy seems to be to not add new options, or that the lint _api_ is frozen.

You are correct, I can only tell from experience that requests to add suggestions or autofix to a _frozen_ rule are typically rejected.

> Thinking about a fork or new lint, I would take the opportunity to re-think the semantics of the lint. I would want to have a `no-const-functions` lint that specifically lints usages with `const`. This would compose well with no-var/prefer-const lints and would allow mutable variables to have functions (maybe that's weird, but that's a different concern). So in a way func-style feels like an artifact of a pre-ES6 world.

Some blogs actually recommend using function expressions over declarations for various reasons. My personal impression is that function declarations are more common. The `func-style` rule lets you choose both, which is why we consider it stylistic.

> Anyways, I guess that's all moot since eslint isn't accepting new stylistic changes. Maybe I'll get inspired and create a plugin. :)
 
Good luck with that 👍🏻 I'm going to close this issue now. Feel free to open a new one when you want to suggest another change.
