### ISSUE TITLE
Docs: CommonJS examples

### ISSUE THREAD

**Issue by bukowa** [eslint/eslint#18505]
### Docs page(s)

https://eslint.org/docs/latest/use/configure/rules#using-configuration-files

### 
![yesgooo](https://github.com/eslint/eslint/assets/38087302/06ae1454-beb8-4a55-b879-20bbb2fae81c)
![ahaaasssaduahsdyuasydusad](https://github.com/eslint/eslint/assets/38087302/dae7187d-9adf-43d6-9f90-4be196ebb052)

### solution:
````js
module.exports =  {
    // Other ESLint configuration settings...
    rules: {
        // Other rules...
        'vue/multi-word-component-names': 'off'
    }
};
````

**Comment by mdjermanovic** [comment]
Hi @bukowa, thanks for the issue!

ESLint configuration files can be ESM or CommonJS, as explained in the Configuration Files docs:

https://eslint.org/docs/latest/use/configure/configuration-files#configuration-file.

I don't think we should clutter the documentation by showing every example in both formats, as examples in the two formats would be pretty much the same except for the difference in importing and exporting.

Perhaps we could update the documentation so that the "configuration file" text before examples is always a link to the Configuration Files docs?

@eslint/eslint-team thoughts?

**Comment by snitin315** [comment]
I agree, we don't need to show examples in both the formats.

>Perhaps we could update the documentation so that the "configuration file" text before examples is always a link to the Configuration Files docs?

This sounds good to me 👍🏻

**Comment by Tanujkanti4441** [comment]
What if we give both the examples in single container that will be shown up by corresponding buttons of `ESM` and `CommonJS`
something like this:
![Screenshot 2024-05-26 190201](https://github.com/eslint/eslint/assets/86398394/f4b87671-ac6c-4e91-837d-d8e45af7f232)
![Screenshot 2024-05-26 190721](https://github.com/eslint/eslint/assets/86398394/45cb3c18-e3d8-43a3-b856-c6273965c87c)

**Comment by bukowa** [comment]
That looks great, it also instantly shows what is the difference and why there's a difference!

**Comment by snitin315** [comment]
This will increase maintenance overhead, we will need to write two different examples.

**Comment by nzakas** [comment]
We do already have a tabs component:
https://eslint.org/docs/latest/component-library/code-tabs

But I agree with @mdjermanovic and @snitin315, I think providing two formats for every example is too much overhead and will likely lead to errors going forward. Unless there's a way to automatically generate the CommonJS version and the tabs, then I think adding a link is the best option.

**Comment by Tanujkanti4441** [comment]
agreed for adding a link, as @mdjermanovic suggested i also feel it would be good to add a text as link before the example that will be easily visible to readers.

**Comment by mdjermanovic** [comment]
Here's a PR to add links: https://github.com/eslint/eslint/pull/18535
