### ISSUE TITLE
Bug: (v8) eslint@8 dep file-entry-cache@6 deprecated transient dependencies

### ISSUE THREAD

**Issue by lorand-horvath** [eslint/eslint#18528]
### Environment

Node version: 18
npm version: 10
Local ESLint version: 8
Global ESLint version: 
Operating System:  Win

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>Configuration</summary>

```
npm install eslint@8
```
</details>

```js
npm install eslint@8
```

### What did you expect to happen?

No deprecations reported in dependencies.

### What actually happened?

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

### Link to Minimal Reproducible Example

http://localhost:1234

### Participation

- [x] I am willing to submit a pull request for this issue.

### Additional comments

More details in this `vite` issue report: https://github.com/vitejs/vite/issues/17306#issuecomment-2141309450
`eslint@8` dependency `file-entry-cache` should be bumped from v6 to v8 to fix the dependency tree deprecations:
```
"eslint": "^8.57.0"
  "file-entry-cache": "^6.0.1"
    "flat-cache": "^3.0.4"
      "rimraf": "^3.0.2" - deprecated
        "glob": "^7.1.3" - deprecated
          "inflight": "^1.0.4" - deprecated, leaks memory
```

PR here: https://github.com/eslint/eslint/pull/18529

**Comment by lorand-horvath** [comment]
@nzakas Would you please take a look at the deprecation warnings caused by the old `file-entry-cache@6` in `eslint@8` ? It should be updated to v8, if possible, same as in `eslint@9`. Thanks!

**Comment by lorand-horvath** [comment]
PR here https://github.com/eslint/eslint/pull/18529

**Comment by nzakas** [comment]
We aren't doing any further releases of ESLint v8.x.

We can look at updating the dependency for the next ESLint v9.x release.

**Comment by lorand-horvath** [comment]
> We aren't doing any further releases of ESLint v8.x.

@nzakas That's surprising, considering the weekly downloads of eslint 9.x have barely passed 1 million, while 8.x is more like 30 million. The React, Vue, Svelte and other JS framework teams haven't been able to update their related plugins to eslint 9 yet.
Anyhow, this is entirely up to you, but maybe this is not the way to go?

**Comment by nzakas** [comment]
Major version releases often see slow upgrades, so that's not a deciding factor. People generally upgrade when they have time to work through breaking changes. In the meantime, plugins are being updated to v9.

In any event, a deprecated package is no cause for concern and doesn't rationalize a departure from overall release strategy.

**Comment by aladdin-add** [comment]
## a workaround:
### 1. npm users: adding this to the package.json
```js
  "overrides": {
    "eslint": {
      "file-entry-cache": "8.x"
    }
  }
```

### 2. yarn users: adding this to the package.json
```js
  "resolutions": {
    "eslint/**/file-entry-cache":  "8.x"
  }
```

**Comment by aladdin-add** [comment]
@nzakas it has been upgraded in v9: https://github.com/eslint/eslint/pull/17903.

If we don't want to backport it to v8, we can just close it.

**Comment by lorand-horvath** [comment]
@aladdin-add I already provided a PR. What backport??

**Comment by mdjermanovic** [comment]
Yes, eslint v9 is already using file-entry-cache v8, so we can close this.

https://github.com/eslint/eslint/blob/2c8fd34bf1471efbd6e616b50d4e25ea858a6989/package.json#L88

I agree with @nzakas's https://github.com/eslint/eslint/issues/18528#issuecomment-2142938456.

If you want to avoid deprecation warnings, the workaround suggested in https://github.com/eslint/eslint/issues/18528#issuecomment-2144319167 should work.

Also note that eslint v8 couldn't use file-entry-cache v8 as a dependency because it doesn't support all versions of Node.js that eslint v8 supports.

https://www.npmjs.com/package/file-entry-cache/v/8.0.0?activeTab=code

```
"engines": {
    "node": ">=16.0.0"
  },
```

**Comment by lorand-horvath** [comment]
@mdjermanovic I bumped file-entry-cache to v8 in the first place https://github.com/eslint/eslint/pull/18529
and provided the workaround https://github.com/vitejs/vite/issues/17306#issuecomment-2141309450 several days before any of you guys at eslint thought of doing that. But hey, whatever, amazing open sourcing and gatekeeping going on!
