### ISSUE TITLE
Change Request: Remove dependency on abandoned  `text-table` dependency

### ISSUE THREAD

**Issue by jonkoops** [eslint/eslint#18618]
### ESLint version

v9.5.0

### What problem do you want to solve?

ESLint currently depends on [`text-table`](https://www.npmjs.com/package/text-table) to format the stylish output. This dependency has not had any new versions published since 2013, and the maintainer has since deleted all their accounts and repositories.

### What do you think is the correct solution?

Probably the easiest solution for now would be to in-line the relevant parts of the `text-table` package into the stylish formatter. Alternatively a different library could be used, which might be considered a breaking change if the shape of the output is relied upon by users.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by snitin315** [comment]
I don't see any problem using text-table because it’s currently serving its purpose well, and we haven't faced any issues. Copying the same code into our codebase doesn't make sense. Using another library might change the output, potentially causing a breaking change. Users can always define and use their [custom formatters](https://eslint.org/docs/latest/extend/custom-formatters) if needed.

I'd like to hear what other team members think about this change. @eslint/eslint-team

**Comment by aladdin-add** [comment]
coping is not too bad to me - it can be helpful if we run into issues in the future at least we can modify.

another minor benifit is it can reduce a bit installing size, since these files seems no need to be published:

![image](https://github.com/eslint/eslint/assets/13050025/ef68ed24-4ac0-4baa-9598-4aefb1fb36fa)

**Comment by jonkoops** [comment]
Note also that there is [some post-processing](https://github.com/eslint/eslint/blob/44915bb95dfa21f946021d77b3b361e7e9b140e0/lib/cli-engine/formatters/stylish.js#L78) performed on the output of `text-table`. So copying the code in might also allow some reduction in code-complexity there by handling those steps earlier on. Some code could possibly also be stripped from `text-table` since the alignment is [already hard-coded](https://github.com/eslint/eslint/blob/44915bb95dfa21f946021d77b3b361e7e9b140e0/lib/cli-engine/formatters/stylish.js#L73-L76).

**Comment by nzakas** [comment]
A package that does what its intended to do doesn't have to have active maintenance for us to use it. It's working as intended, so I don't see the value in spending time on figuring out how to remove it.

**Comment by jonkoops** [comment]
@nzakas if I were to extract the essentials from `test-table` and refactor the existing code, would such a PR be welcome at all?
