### ISSUE TITLE
es6jsx: no-unused-vars misses implicit React variable usage in JSX

### ISSUE THREAD

**Issue by davidagraf** [eslint/eslint#1867]
I'm using eslint v0.14.1 and getting no-unused-vars errors in the following dummy JSX code:

```jsx
var React = require('react');
var Table = require('Table.jsx');

module.exports = (
  <Table />
);
```

The React variable is used in the transform js code:
```javascript
var React = require('react');
var Table = require('Table.jsx');

module.exports = (
  React.createElement(Table, null)
);
```

But no reference is used in the JSX code. Therefore eslint shows an error:

```
./node_modules/eslint/bin/eslint.js src/Test.jsx 

src/Test.jsx
  3:4  error  React is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

**Comment by nzakas** [comment]
This is behaving as expected. We run linting on the original code, not the transpiled code. In the original code, `React` is unused.

**Comment by lencioni** [comment]
Is there a way to satisfy this linter for this case without disabling it entirely?

**Comment by nzakas** [comment]
I think the best way is to add `React` as a global in your `.eslintrc` files.

**Comment by lencioni** [comment]
After adding `React` as a global in my `.eslintrc` file I still get the warning

> error  React is defined but never used  no-unused-vars

since I still need to `require` React in these files. Any suggestions?

**Comment by nzakas** [comment]
Hmm, I'll need to double-check that, I thought it should work. 

I'm really unfamiliar with React. Do you need to include it even if you don't make a direct reference to it?

The brute force way is to do:

```js
/*eslint-disable no-unused-vars*/
var React = require('react')
/*eslint-enable no-unused-vars*/
```

**Comment by davidagraf** [comment]
@nzakas The JSX syntax (https://facebook.github.io/jsx/) is the reason of the issue. When creating react components in JSX, the React variable is used implicitly. E.g. the JSX code
```
<Table />
```
is transformed to the JS code
```
React.createElement(Table, null)
```
by the JSX transformer.

Therefore, the usage of JSX syntax requires the variable React without accessing it explicitly.

**Comment by nzakas** [comment]
Ah OK. Then this is probably the best we can do - we don't build in library-specific exception cases.

**Comment by lencioni** [comment]
This is a function of JSX itself, which it appears that ESLint supports. Would it make sense to modify the behavior of no-unused-vars to not throw this error for this case iff the `jsx` language option is enabled?

**Comment by nzakas** [comment]
No. ESLint supports JSX syntax as defined in the [spec](http://facebook.github.io/jsx/). We don't specifically support React, just like we don't specifically support jQuery.

**Comment by nzakas** [comment]
Just for some more color, when I investigated if there was a way to support this without hardcoding `React` into ESLint, I found:

1. If you don't explicitly declare `var React` and you set `React` in the `globals` config of `.eslintrc`, you won't get a warning if it's not used.
2. Explicitly declaring `var React` puts `React` into the ESLint path to have its references tracked.
3. We could add a way to pass exceptions to the rule, but there would be no way to distinguish two variables with the same name from one another (i.e., if there were two functions with local `React` variables and you said `React` shouldn't be checked, then you could potentially end up missing an unused reference simply because it shared the same name as the one you wanted to omit).

Point 3 is the closest we came to having a solution, but scoping rules are complicated enough that it opens up the possibility of missing errors accidentally, which would ultimately lead to someone asking if we could have an exception so they could treat variables with the same name differently.

We try really hard to make ESLint as flexible as possible without baking-in library-specific knowledge, which is why we make it easy to disable rules in a number of different ways. Trying to account for all the semantic quirks of every library out there would leave us in a vulnerable position if those semantics ever change and open us up to endless work trying to accommodate everyone's favorite library. 

What we are striving for here is making everything pluggable enough that people can create their own library-specific plugins, allowing us to keep that knowledge out of the core while also allowing people to continue to developing for ESLint in the way that makes the most sense to them.
