### ISSUE TITLE
Change Request: replace `chalk` dependency with a lighter alternative

### ISSUE THREAD

**Issue by trivikr** [eslint/eslint#18686]
### ESLint version

v9.7.0

### What problem do you want to solve?

Recently, the [Ecosystem Performance](https://e18e.dev/) was formed to cleanup, speedup, levelup the JavaScript Ecosystem.
Socket Security team wrote a blog post about it https://socket.dev/blog/javascript-community-launches-e18e-initiative-to-improve-ecosystem-performance

On the e18e cleanup channel on Discord, multiple solutions are being discussed. One of them is to replace `chalk` with `picocolors`.

I see that eslint uses chalk https://github.com/eslint/eslint/blob/a7016a50d88011f279d52b9355a5662e561c414c/package.json#L78

And the upgrade to chalk@5.x is blocked because it's ESM only https://github.com/eslint/eslint/issues/15560#issuecomment-2176641357

### What do you think is the correct solution?

Replace `chalk` with a lighter alternative like `picocolors`.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Can you explain what "lighter alternative" means? What effect will this have on the user experience?

**Comment by trivikr** [comment]
> Can you explain what "lighter alternative" means?

It usually means an alternative with a smaller size (install/publish/bundle).

The dependency `chalk@4.x` which eslint uses has [~33 kB publish size and ~105 kB install size](https://packagephobia.com/result?p=chalk@4.0.0).

<details>
<summary>Screenshot</summary>

<img width="767" alt="Screenshot 2024-07-15 at 8 32 55 AM" src="https://github.com/user-attachments/assets/8351a140-67d6-4414-b8a8-27dd900b4de9">

</details>

On other hand, picocolors has [5.03 kB install/publish size](https://packagephobia.com/result?p=picocolors)

<details>
<summary>Screenshot</summary>

<img width="588" alt="Screenshot 2024-07-15 at 8 34 10 AM" src="https://github.com/user-attachments/assets/4bad253b-2eb1-4c7f-b067-3f2e1142d554">

</details>

The lighter alternatives sometimes come with performance benefits too.
The picocolors benchmarks state it's 2X faster than chalk in their README.

> What effect will this have on the user experience?

Nothing, AFAIK. From the existing migrations, the picocolors API is mostly compatible with that of chalk.
* Vite moved to picocolors in Dec'21 https://github.com/vitejs/vite/pull/6277
* Babel moved to picocolors in Mar'24 https://github.com/babel/babel/pull/16359
* Jest just agreed to switch to picocolors https://github.com/jestjs/jest/issues/15189#issuecomment-2228549431

**Comment by nzakas** [comment]
Thanks. In general, we don't switch dependencies unless there's some evidence of how it positively impacts the user experience. My guess is that our users won't actually see any performance difference since chalk is only used to output results. I don't see a compelling argument here to make a switch, but I'll leave it up to @eslint/eslint-tsc to weigh in with their opinions.

**Comment by mdjermanovic** [comment]
I also don't think ESLint users would see any performance difference, so the only question is whether reducing install size by ~100kB (including removing two transitive dependencies) is a compelling argument. I'm fine with switching to `picocolors` for this purpose if it provides the same functionalities we're using from `chalk`.

**Comment by fasttime** [comment]
I think that @nzakas is correct, package size (including dependencies) and performance impact for `chalk` are in a range that's far below what affects user experience. I'm fine with switching to an alternative like `picocolors` if that's the preference, but I don't see a strong reason to do so.

**Comment by snitin315** [comment]
`colorette` is also an alternative we can explore,  as per [these benchmarks](https://github.com/jorgebucaran/colorette?tab=readme-ov-file#benchmarks) it seems to be the fastest.

|  Package | Size   | Benchmark |
|---|---| --- |
| chalk   | [33kb](https://packagephobia.com/result?p=chalk@4.0.0)  |  `1,786,703 ops/sec` |
|  picocolors  | [5kb](https://packagephobia.com/result?p=picocolors)   | `2,871,758 ops/sec` |
|  colorette  | [16.6kb](https://packagephobia.com/result?p=colorette)  | `3,002,751 ops/sec`  |

**Comment by nzakas** [comment]
I just don't think runtime performance is a deciding factor here. 

To keep install size in perspective, ESLint v9.7.0 has a [9.45 MB install size](https://packagephobia.com/result?p=eslint%409.7.0), so saving 105 KB doesn't really make a dent in the weight of ESLint.

Does anyone on the team want to champion this switch? I'm happy to go along if someone feels strongly about such a change.

**Comment by sindresorhus** [comment]
I'm the creator of Chalk. Chalk isn't just bigger—it's better. The types are well-documented, the API is more user-friendly, and it covers edge cases the smaller alternatives simply don't. Chalk is mature, battle-tested, and reliable.

But beyond the technical aspects, there's something more critical: trust and long-term maintenance. I've been a pillar in the open-source community for years, and I’m not going anywhere. On the other hand, those smaller packages could be abandoned at any time.

In ESLint's case, a few kB of install size does not make any difference. And when they either move to ESM or can target Node.js 22, they can upgrade to Chalk 5, which is substantially faster and smaller.

And if you're really concerned about install size, I also maintain one of the smallest color libraries available: [`yoctocolors`](https://github.com/sindresorhus/yoctocolors).

**Comment by Fuzzyma** [comment]
@sindresorhus the people behind e18e are a whole community and trusted by lots of people of the ecosystem. I am extremely thankful for what chalk did for the js ecosystem but taking the tarball size of chalk into account, this is 2460.29 GB of traffic generated per month because people install eslint and pull in chalk (according to npm).
Yes it might not seem much to shave off a few KB of eslint but I think the JS ecosystem should move forward as a whole and embrace smaller and faster alternatives whenever possible.

**Comment by SukkaW** [comment]
@nzakas TBH please re-consider this request here. `chalk` is big and slow because it provides many functionalities that ESLint doesn't need at all:

- chained-style nesting: ESLint doesn't use these methods at all
- 256 color support: ESLint only uses a handful of colors, no more than 5

In the end, since more and more JavaScript world is moving to `picocolors`, it makes sense for ESLint to switch as well. In fact, ESLint is currently the only library in all of my `mode_modules` that depends on `chalk`, and the disk occupation is truly reduced.

**Comment by sindresorhus** [comment]
> chalk is big and slow

This is just false. I have already commented on the performance:

> And don't fall for flawed micro-benchmark marketing. [Micro-benchmarks are generally flawed](https://sindresorhus.com/blog/micro-benchmark-fallacy) because they measure performance in unrealistic, isolated scenarios, often giving a distorted view of real-world performance. All the coloring packages are more than fast enough.

---

> 256 color support: ESLint only uses a handful of colors, no more than 5

That has no impact on performance and very little impact on size.

**Comment by sindresorhus** [comment]
> Yes it might not seem much to shave off a few KB of eslint but I think the JS ecosystem should move forward as a whole and embrace smaller and faster alternatives whenever possible.

Chasing smaller dependencies without regard for maturity or stability is shortsighted. ESLint is critical infrastructure, reliability and long-term maintenance outweigh shaving off some kilobytes. Chalk exists for a reason: it handles edge cases, has clear types, and is battle-tested. Swapping it out for marginal gains, based on flawed micro-benchmark marketing, introduces churn for zero real-world benefit. Optimizing the ecosystem means making smarter choices, not just smaller ones.

**Comment by sindresorhus** [comment]
> In the end, since more and more JavaScript world is moving to picocolors

It may be getting more popular, but that's partly because the e18e community encourages people to spam popular projects about switching to it.

**Comment by 43081j** [comment]
just a few remarks:

chalk is bigger and slower, it is what it is.

so now that we know picocolors has a non-zero performance gain over chalk, it is upto us all to justify why to keep chalk.

In all of the above, we have a few suggestions/claims to fill this justification (with my notes beneath each one):

- It handles edge cases
  - does it? show us one that ESLint will encounter as of today
- It has clear types
  - what makes them clearer than all other colour libraries? _for the usage ESLint has_ (which is a plain string input/output function)
- It is battle tested
  - picocolors, at 86M downloads/week, is battle tested
- "I'm not going anywhere"
  - see below

Sindre - your remarks stand unproven, especially in the context of ESLint. Answer the questions above, and maybe it turns out there actually is a valid reason to use chalk.

And i'll add one myself, which i think is actually the one that matters:

- Does the team have capacity to see such a change through? (i.e. even if we all agree to do it, it takes team time to review the change and test it. is that worth it?)

On a side note:

> I've been active in the open-source community for over a decade, and I’m not going anywhere

Honestly, I find this damaging to the community, as you're actively preventing would-be maintainers from helping out the community and being more involved in OSS. Many of them, we'll never know if they'd also be in this community a decade, because they were already pushed out and people were convinced not to use their arguably better packages.

It would be better to justify the package itself, and _show_ that it is better for whatever reason. 

### My suggestion

ESLint should use `styleText` when possible, i.e. _no dependency_.

We're working right now on nesting support inside that. Once that lands, it should provide the same common functionality all these libraries provide.

Until then, picocolors now de-dupes better in many projects, and is provably faster and smaller. Switch to it if you have the capacity.

The only reason you should keep chalk is if you don't have the time as a team. That is a valid reason, though, so just let us know (ESLint maintainers) if its the case. Then we can wait for `styleText` instead and hope you do have time when it is ready.

**Comment by SukkaW** [comment]
> We're working right now on nesting support inside that. Once that lands, it should provide the same common functionality all these libraries provide.

Also, as for today, [ansis](https://www.npmjs.com/package/ansis) library provides all `chalk`'s functionality. It has 5.8M weekly downloads now, also battle tested. Anyone relying on `chalk`'s special API (which ESLint actually doesn't) can give `ansis` a try.

Besides, adding the installation size of both `picocolors` and `ansis` together, it will still be smaller than `chalk` (wink wink).

**Comment by PinkaminaDianePie** [comment]
For those who comes to this issue after reports of malware in 3rd-party dependencies: it's possible not just to replace `chalk` with `picocolors`, but `eslint` with `oxlint` (modern rust-based alternative): https://oxc.rs/docs/guide/usage/linter.html
