### ISSUE TITLE
Change Request: Future of `standard` / `xo` style CLI

### ISSUE THREAD

**Issue by voxpelli** [eslint/eslint#18800]
_Up to date proposal in this comment below: https://github.com/eslint/eslint/issues/18800#issuecomment-2437343415_

### ESLint version

9.9.0

### What problem do you want to solve?

[`standard`](https://github.com/standard/standard) has long used [`standard-engine`](https://github.com/standard/standard-engine) to package itself up as a self-contained CLI, and prior to flat configs it came with two benefits:

- it avoided having all the plugins as peer dependencies (now solved by flat configs)
- it enabled running the rule set without any additional configuration, avoiding opening the door to possible endless rule discussions

[`standard-engine`](https://github.com/standard/standard-engine) also came drawbacks:

- it needed custom editor integration rather than working out of the box with eslint-capable environments

In the ESLint 9 Flat Config version of `standard` (published as [`neostandard`](https://github.com/neostandard/neostandard) due to governance discussions) we aimed to skip [`standard-engine`](https://github.com/standard/standard-engine) as Flat Configs essentially made it redundant, but it left us without a self-contained CLI, requiring config files which may encourage rule discussions and customisations, something we have been requested to solve https://github.com/neostandard/neostandard/pull/2

Other similar tools have the same issue, such as eg. [`xo`](https://github.com/xojs/xo): https://github.com/xojs/xo/issues/702#issuecomment-2152882133

_Originally posted at https://github.com/neostandard/neostandard/issues/33_

### What do you think is the correct solution?

I want to try and find a solution where people can use `neostandard`, `xo` etc without having to set up an `eslint.config.js` where they potentially open themselves up to extensions and modifications of the shared config.

 _See up to date proposal in this comment below: https://github.com/eslint/eslint/issues/18800#issuecomment-2437343415_

<details>
<summary>Original thoughts, now outdated</summary>
It could eg be:

* `neostandard`, `xo` being able to wrap the ESLint CLI and publish as their own CLI:s, resulting in eg `neostandard --semi --fix` (I drafted on this in https://github.com/neostandard/neostandard/pull/2/files#diff-180b3d2af89416b99563fff8c37eb8ca1ef7591fc1ddd736b5dacf740ccd3760R87-R90)
* `neostandard`, `xo` shared configs being possible to configure for ESLint in some other way, eg:
  * (ignoring the name of the arguments) `eslint --shared-config=neostandard --shared-config-semi --fix`
  * In `package.json` adding something like:
    ```json
    "eslint": {
      "shared-config": "neostandard",
      "shared-config-options": {
        "semi": true
      }
    },
    ```
</details>

No matter the solution I think its key to have a solution that editors and other eslint-capable environments understand, avoiding the need to build custom integrations for eg. VSCode, as both `standard` and `xo` has done.

### Participation

- [X] I am willing to submit a pull request for this change.

### Additional comments

I think the success of both `standard` and `xo` has shown that some people desire a tool that's less configurable by the users – delegating it completely to a third party.

With Flat Configs now solving the peer dependency need the need for [`standard-engine`](https://github.com/standard/standard-engine) style solutions is less and working towards officially supporting "ESLint distributions" like `standard` and `xo` would be great and avoid having work duplicated across multiple VSCode extensions etc. – providing better and wider support for everyone.

**Comment by nzakas** [comment]
> I want to try and find a solution where people can use neostandard, xo etc without having to set up an eslint.config.js where they potentially open themselves up to extensions and modifications of the shared config.

Is there a reason you don't just write your own CLI using the `ESLint` class? You can just specify `configFile: false` and then ESLint won't pick up any other config files. Or is there something else I'm missing?

The current CLI is not, in any way, meant to be a public API, and I don't see that changing, at least until after the core rewrite. It would require a lot of thought into how to develop such an API so it was both maintainable for us and non-fragile for consumers. 

Overall, though, I find this request very difficult to parse. It would help if you could update the description with a bulleted list of "I'd like a user of neostandard to be able to...". I have no idea why people use standard or xo over ESLint, nor what their user experience is like, and all of that is important context for this discussion. For example, I have no idea what "shared-config" and "shared-config-options relates to. So...you really need to download all of that context into this issue for the rest of us. :smile:

**Comment by voxpelli** [comment]
I'll let eg. @wesleytodd chime in on some of the use cases, but some quick replies:

> Is there a reason you don't just write your own CLI using the ESLint class?

That's what `standard` (and `xo`) currently does, see eg. [here in`standard-engine`](ttps://github.com/standard/standard-engine/blob/cf701384c130889b9107efe3a0c26c586dca588c/index.js#L88-L93)

But doing so essentially reduces ESLint to an internal implementation details where [text editor support](https://github.com/standard/vscode-standard), [output formatting](https://github.com/standard/snazzy) etc requires custom implementations rather than being part of the ESLint ecosystem and leveraging and contributing to it.

> The current CLI is not, in any way, meant to be a public API, and I don't see that changing.

Whether the CLI would be the public API or not is not important – important is being able to leverage text editor support, output formatting etc. I'm aware that this is not a use case that ESLint has been modeled for currently, but I much rather spend time figuring this out than building a `neostandard-engine` or similar.

>  I have no idea why people use standard or xo over ESLint, nor what their user experience is like, and all of that is important context for this discussion.

Eg. @wesleytodd described the challenge with config files over prebuilt bundled configs like this (https://github.com/neostandard/neostandard/pull/2#issuecomment-2135446338):

>  I have seen on quite a few teams and orgs that once the file is there, if you are not really clear in your expectations that it is not edited directly folks will start creeping in with new rules and changes. And that inevitably leads to 80 column rules, super slow cyclomatic complexity analysis plugins, or other things that don't help most modern developers.

Configurabilty / extensibility is a double-edged sword – with great power comes great responsibility and in some contexts the power can lead to endless bike-shedding and/or misconfigured rules (eg. "why is ESLint so slow!?" when someone added a really costly rule without knowing it was costly)

> For the most part, it seems like their use is relatively low and possibly declining

Depends on how one counts. According to ecosyste.ms:

*standard:*

* Dependent packages: 33,227
* Dependent repositories: 230,513

*xo:*

* Dependent packages: 12,156
* Dependent repositories: 110,652

*eslint:*

* Dependent packages: 424,118
* Dependent repositories: 1,569,244

They combined have ≈10% the packages and ≈20% the repositories of ESLint.

And standard/neostandard was/is used in eg. fastify, undici, npm, request and other current/historic pillars of the of the node.js ecosystem.

While xo is used by four out five [most downloaded modules on npm](https://packages.ecosyste.ms/registries/npmjs.org/packages?order=desc&sort=downloads) and by modules like type-fest (which has 4x as many downloads as ESLint)

**Comment by nzakas** [comment]
> While xo is used by four out of five [most downloaded modules on npm](https://packages.ecosyste.ms/registries/npmjs.org/packages?order=desc&sort=downloads) and by modules like type-fest (which has 4x as many downloads as ESLint)

I'm not sure this counts considering it's Sindre who wrote both xo and those packages. :smile: This may actually be overinflating xo's numbers.

> But doing so essentially reduces ESLint to an internal implementation details where [text editor support](https://github.com/standard/vscode-standard), [output formatting](https://github.com/standard/snazzy) etc requires custom implementations rather than being part of the ESLint ecosystem and leveraging and contributing to it.

I have no idea how you can achieve what you're describing (your own CLI) and also just have it work with all of the existing ESLint tooling out-of-the-box. The VS Code extension doesn't use the CLI at all, it uses the `ESLint` API, so any CLI-based approach will have no effect on it. This is the cost of white labeling ESLint. 

If the problem statement is "we don't want developers on the team to modify our project's ESLint configuration", it seems like that's better solved with some kind of automation in the project rather than through ESLint itself.

**Comment by wesleytodd** [comment]
Hey, I will try and start from the top and address as much as I can in one comment. That said, I wonder if this might be a discussion better had in a VC or something, as even reading this thread already has enough going on that it might be difficult for us all to follow.

> it needed custom editor integration rather than working out of the box with eslint-capable environments

This has been the largest point of feedback I have seen from folks when I mention `standard` or the variants. And while it is not yet mentioned in this thread, one way to avoid changes to the `eslint` implementation could be to add support for a  standard (not `standard`, just the normal meainging of that word) cli api that the official editor integrations could support directly.

> I have no idea why people use standard or xo over ESLint, nor what their user experience is like, and all of that is important context for this discussion.

This is one of the things that I have also commonly heard, but as someone who has used both in OSS and at companies I can say confidently that *removing* the config file boilerplate from application and library repos is the best way to avoid bikeshedding discussions about rule configurations.

Leaving those decisions to groups who are more well informed than most end users is *good*. It is why ESLint has federated config in the first place, and `standard` and friends just take one small extra step past what ESLint does alone. So I think the best way to think about it is "exactly why someone might choose `airbnb` but with the added benefit of not being able to easily override the config" (yes I mean benefit).

Take for example, these two PRs:

1. https://github.com/expressjs/serve-static/pull/171
2. https://github.com/expressjs/serve-static/pull/172

After a lengthy discussion (I can link to the OpenJS slack if you want to read it), my fellow contributor still added a rule exception. The goal of `standard` and friends is to *not* have that type of discussion in individual projects, and as you can see in my original PR the end result is nearly the same just without the need to call out an exception and one less config file in the root.

In the projects where I use `standard` I have gone years without having these conversations, and that leaves us more time to focus on what we actually need to ship. For `express` for example, we need to rescue the project from years of inactivity, not bikeshed if we should have semis or spaces after parens. In my work context, that means never seeing comments like `// eslint-disable-next-line complexity` because no one can easily slip in a bad cyclomatic complexity rule (this was mentioned in our slack thread because it was something I came across at work while we were having that discussion). 

> I do want to put the popularity of these standalone utilities in context.

This is totally valid. And I would say that if large changes were being requested, or disruptive ones, it would be totally reasonable to decline for this reason. That said, IMO any changes to better support strong opinions *benefits* everyone, and can be done with fairly small changes. 

Additionally to the points about usage in popular projects, the Express org long ago agreed we were moving toward using `standard`. It was only with the stall out in leadership that it never got done. So once we get past the major release we are working on we will also be in that list of popular projects that depend on it. And we need to remember, download stats in this are misleading since they are highly "app project" heavy where as `standard` is more popular with library authors.

> (eg. "why is ESLint so slow!?" when someone added a really costly rule without knowing it was costly)

An example of this is the prettier integration. For years folks just said "well this is slow" and moved on with their day afaict (that's what folks said at netflix in support threads anyway, so while anecdotal I think it is pretty common). It didn't need to be slow, they just had a poorly configured integration. If we *enable* better tools for avoiding those config footguns it benefits everyone, not just the folks who want to commit to a stronly opinionated rule set. 

---

In closing for now, I would love to see some consennsus here on how to better support this use case. If that ends up with just the vscode plugin adding support I am actually probably alright with that, but making it easier for teams to bundle their own highly opinionated config-less setups would be an awesome goal imo.

**Comment by voxpelli** [comment]
> one way to avoid changes to the `eslint` implementation could be to add support for a standard (not `standard`, just the normal meainging of that word) cli api that the official editor integrations could support directly

I thought about this yesterday as well as another possible solution

**Comment by nzakas** [comment]
While I can understand the benefit of disallowing configuration changes on a team, my opinion remains that this is something other kinds of tooling can resolve fairly easily. But I hear that you like this setup and want to continue using it.

That said, we a have a lot to keep us busy on ESLint, and given that this is still a relatively small percentage of use cases, we don't have the time to go deep into exploration of what might work. If you (@voxpelli and @wesleytodd) want to propose something concrete, we can take a look at it. 

As I mentioned previously, IDEs don't use CLIs for their extensions, so I don't think trying to define a "standard CLI" is going to get you the editor integration you want.

Before going further, I'd suggest you talk with some folks on the VS Code team to get a better understanding of their constraints and how the extensions are meant to work.

**Comment by fregante** [comment]
@voxpelli correct me if I'm wrong, it seems that you're looking for a way to **declare a base config without creating `eslint.config.js`.** The only advantage of this would be to limit the ability to further customize the config.

I find that argument a bit lacking, a 10-line diff won't deter anyone annoyed enough to want to disable a rule globally:

```diff
  {
  	"name": "my-project",
- 	"eslint": {
- 		"shared-config": "xo"
- 	}
  }
```

and

```diff
+ import xo from 'xo'
+ 
+ export default xo({
+ 	rules: {
+ 		"some-rule": "off"
+ 	}
+ });
```

I think you can already deter changes with two patterns:

- use `export {default} from 'xo'` so it's not immediately clear where/how to customize rules
- _don't_ accept `rules` in your config function, so that customizing rules would mean having to turn the default export into an array
	```diff
	import xo from 'xo'
	
	export default xo({
		semi: false,
-		rules: {
-			"some-rule": "off"
-		}
	});
	```

Either way, it's still easy for anyone determined enough.

IMHO the only argument for a `eslint.shared-config` key in package.json would be to _avoid yet another dotfile_ at the root of projects, but I don’t think that's worth it, because soon enough people will request more keys and we're back to eslintrc.

**Comment by voxpelli** [comment]
@fregante I think @wesleytodd described the wish better:

> I can say confidently that removing the config file boilerplate from application and library repos is the best way **to avoid bikeshedding discussions about rule configurations**.
>
> **Leaving those decisions to groups who are more well informed than most end users is good.** It is why ESLint has federated config in the first place, and standard and friends just take one small extra step past what ESLint does alone.

Currently projects like `standard` and `xo` achieves that by custom code. If we could instead circle back and find a common solution upstream to that, then it would be a win for everyone.

**Comment by fregante** [comment]
I get that but:

- most of what you quoted applies to shared configs in general, which are already well supported
- `standard` has an `eject` command that makes it exceedingly easy to allow customization
- adding `eslint.shared-config` would only make it easier to forgo the strict `standard` CLI since it means you can just call `$ eslint .` instead of `$ standard`, correct?
- `xo` _does_ allow customization of rules via the `xo.rules` key, without ejecting, so that leaves only `standard` with such a strict behavior

We agree that `eslint.shared-config` would have its benefits, I just don't think they're great enough over `export {default} from 'standard'` in `eslint.config.js`

**Comment by voxpelli** [comment]
> `shared-config-options` would already be too much

Thinking about this further, `shared-config-options` would be completely unnecessary as any configuration needed could be achieved by eg:

* Publish multiple config files in the shared config, eg `neostandard/semi`, `neostandard/semi-ts` or similar 
* The shared config reading a config file of its own, `neostandard.yml` or whatever, and this could be implemented entirely within the shared config implementation.

So a `"eslint-shared-config"`, `"eslint-preset"` or similar option that provides a discoverable equivalent to `--config=./path/to/config.js`, so that `"eslint-preset": "neostandard"` or possibly `"eslint-preset": "neostandard/semi"` would become the default config when running `eslint`, rather than the current `eslint.config.js`, that would achieve a lot of the needs I think.

(I believe it's currently not possible to specify a module directly as the config, `--config=neostandard`, so that would be the first step I guess, then second step making it possible to specify in a discoverable way)

---

When it comes to the fact that eg the VSCode extension doesn't use the CLI: If it has implemented its own config resolution mechanism in such a way that an addition of a that `"eslint-preset": "neostandard"` mechanism would not be automatically supported there, then I think that shows a separate issue that should be addressed as well:

Tools built on top of ESLint should not duplicate such logic but rather rely on the very same logic that ESLint itself uses.

So if that's the case, then it likely shows a need for an API that exposes that logic in one way or another.

---

@fregante I see no issue with `eslint` and `neostandard` being possible to use interchangeably to run the config.

**Comment by voxpelli** [comment]
> When it comes to the fact that eg the VSCode extension doesn't use the CLI: If it has implemented its own config resolution mechanism in such a way that an addition of a that `"eslint-preset": "neostandard"` mechanism would not be automatically supported there, then I think that shows a separate issue that should be addressed as well:
> 
> Tools built on top of ESLint should not duplicate such logic but rather rely on the very same logic that ESLint itself uses.
> 
> So if that's the case, then it likely shows a need for an API that exposes that logic in one way or another.

Looked into it, this is not the case, the [VSCode extension uses](https://github.com/microsoft/vscode-eslint/blob/2fbc0e9f686412de7caae89bcd58598cf64e0e85/server/src/eslint.ts#L1006) the [`calculateConfigForFile()`](https://github.com/eslint/eslint/blob/c69b40667a288bed1290b34b37387dc671295bb0/lib/eslint/eslint.js#L1260-L1277) API, so any tweaks in how it resolves configs will be mirrored by the VSCode extension

**Comment by voxpelli** [comment]
Enabling `"eslint-preset": "neostandard"` could essentially entail modifying [`findFlatConfigFile()`](https://github.com/eslint/eslint/blob/c69b40667a288bed1290b34b37387dc671295bb0/lib/eslint/eslint.js#L273-L287) to look something like this (**rough**) sketch:

```js
async function findFlatConfigFile(cwd, hasUnstableTSConfigFlag) {
    const filenames = hasUnstableTSConfigFlag ? FLAT_CONFIG_FILENAMES_WITH_TS : FLAT_CONFIG_FILENAMES;

    const configFilePath = await findUp(
        filenames,
        { cwd }
    );

    if (configFilePath) {
       return configFilePath;
    }

    const pkgFilePath = await findUp(
        ['package.json'],
        { cwd }
    );

    if (!pkgFilePath) {
        return;
    }

    const pkg = JSON.parse(await fs.readFile(pkgFilePath, 'utf8'));

    return pkg['eslint-preset']
        // The 'eslint-preset' should be pointing to a module, so we need help resolving the path
        ? require.resolve(pkg['eslint-preset'], { paths: [cwd] })
        : undefined;
}
```

**Comment by voxpelli** [comment]
An alternative solution that could be even better would be to modify `locateConfigFileToUse` instead.

By both adding support for module specifiers in `--config` by using the ['resolve-from`](https://www.npmjs.com/package/resolve-from) module to do `configFilePath = resolveFrom(cwd, configFile);` in:

https://github.com/eslint/eslint/blob/c69b40667a288bed1290b34b37387dc671295bb0/lib/eslint/eslint.js#L416

And by adding a section prior to that which enables resolving the `--config` from the `package.json` file:

```js
    if (configFile === undefined) {
        const pkgFilePath = await findUp(
            ['package.json'],
            { cwd }
        );
    
        if (pkgFilePath) {
            const pkg = JSON.parse(await fs.readFile(pkgFilePath, 'utf8'));
            configFile = pkg['eslint-preset'];
        }
    }
```

Would be a small downside performance wise, but could be iterated upon I think

**Comment by voxpelli** [comment]
I had totally missed that an entirely new config lookup was in the progress, https://github.com/eslint/eslint/pull/18742, so I guess those investigations of me above is good for nothing else than clarifying my idea at a conceptual level 🙃

The config loading is now handled by [`ConfigLoader`](https://github.com/eslint/eslint/blob/main/lib/config/config-loader.js) and is considered unstable until ESLint 10.x

Maybe that means we can still extend it in ways like this?

**Comment by nzakas** [comment]
> Maybe that means we can still extend it in ways like this?

You're going to have to be more specific. You discussed a lot of stuff in the previous comments that, as you said, doesn't really jibe with the new config loading scheme. It would be helpful for you to summarize what your current proposal is.

**Comment by voxpelli** [comment]
> You discussed a lot of stuff in the previous comments

I have tried to look into where a `"eslint-preset": "neostandard"` resolution could happen, to see if its feasible. This is the one thing I have discussed.

Since I don't know where it might make sense and I've gotten no pointers I spent time investigation it myself and documented the places that I found that could make sense, to see if any of them would make sense to you.

> It would be helpful for you to summarize what your current proposal is.

# Proposal summary

Two related but essentially separate proposals:

1. Enable an equivalent to the `--config` CLI option to be specified in a declarative way that editor extensions etc can discover and leverage 
2. Enable a module to be referenced in the config (eg. `npx eslint -c neostandard`)

My suggestion for `1.` is adding support to read a `"eslint-preset": "..."` from `package.json` (or `"eslint-config"` or whatever, the name of the key is not core to my proposal).

`2.` is not strictly necessary, but `npx eslint -c ./node_modules/neostandard/index.js` hurts my eyes

## Out of scope of proposal

The implementation suggestions for these are not part of my proposal. I'm simply trying to help push things forward by trying to figure out where one would feasibly add this.

**Comment by nzakas** [comment]
I'm afraid this just doesn't fit with the direction of ESLint. We are explicitly getting out of the "pass a string and we'll figure out how to load it" game. There are just too many sharp corners there.

**Comment by voxpelli** [comment]
@nzakas That's the exact reason why I split the proposal into two distinct parts, so that the objection against one wouldn't necessitate the object of the other, and your objection is against `2.`, not `1.`, right?

And I wrote explicitly:

> `2.` is not strictly necessary, but `npx eslint -c ./node_modules/neostandard/index.js` hurts my eyes

Do you have any take on `1.`?

> too many sharp corners there

In what way? In node.js one would either use the `require` algorithm or the `import` algorithm?

Is it that its unclear which directory that the `require` / `import` should be relative to?

**Comment by voxpelli** [comment]
@nzakas And the main proposal? This one:

>  1. Enable an equivalent to the `--config` CLI option to be specified in a declarative way that editor extensions etc can discover and leverage
> 
> My suggestion for `1.` is adding support to read a `"eslint-preset": "..."` from `package.json` (or `"eslint-config"` or whatever, the name of the key is not core to my proposal).

Can we achieve this either directly in ESLint or by making the config lookup somewhat extendible[^2]

[^2]: So that an extension like the ESLint VSCode extension doesn't have to reimplement everything that eg #18742 reintroduced

**Comment by nzakas** [comment]
ESLint doesn't read package.json, so adding a new key there doesn't make sense.

**Comment by voxpelli** [comment]
@nzakas Again – that’s not the proposal – this is:

> Enable an equivalent to the `--config` CLI option to be specified in a declarative way that editor extensions etc can discover and leverage

**Comment by nzakas** [comment]
@voxpelli I'm sorry, this thread hasn't been the easiest to follow.

Give me a concrete proposal to evaluate and we can go from there.  Just note that there's really not an appetite to revisiting how ESLint is configured, so I don't want to get your hopes up.

**Comment by voxpelli** [comment]
> this thread hasn't been the easiest to follow

Yeah, there hasn’t been a very collaborative response so I have had to guess a lot and have had try to find ways to push this forward without really any guidance. That makes it a bit all over the place.

> Give me a concrete proposal to evaluate and we can go from there

So you essentially wants a PR for how to implement a solution to this rather than a discussion on how to solve the problem? Feels premature to do a PR. My initial intent was to do an RFC, but was told that one should open an issue here before doing an RFC.

> Just note that there's really not an appetite to revisiting how ESLint is configured

I’m not asking to revisiting it – I’m looking for a constructive discussion about how we through the most minimally possible addition can avoid the historic, and nowadays very needless, duplication of work that happens in standard and xo and in the tooling support for those.

---

Maybe someone else in the ESLint team is more aware of what standard and xo has been doing and would have an easier time understanding me?

Or maybe one of @fregante, @wesleytodd, @sindresorhus, @feross or such can try phrasing this in a more constructive and concrete way than I’m evidently able to do?

I would have closed this issue if I felt it had been understood and refuted – but as you’re saying, it’s not being understood, so I’ll leave it open and hope someone else will be able to better describe it or better understand it.

**Comment by ctcpip** [comment]
Without getting into implementation proposals, the fundamental ask, at its core, is the desire to abstract away the actual ESLint configuration (file).

They want to be able to:

```sh
npm i --save-dev eslint
npm i --save-dev my-eslint-config-project
```

And the project will somehow automatically load the config specified in `my-eslint-config-project` without needing any eslint config files in the project, and it would **just work** with existing ESLint plugins in vscode, work via the CLI, etc.

**Comment by fregante** [comment]
> Enable an equivalent to the `--config` CLI option to be specified in a declarative way that editor extensions etc can discover and leverage

I think the answer is clear: eslint.config.js

It seems that eslint has no intention of loading package.json, so that means it has to load the config from another file. "The other file" already exists and is eslint.config.js

Starting from this baseline, is there anything that eslint can do to simplify the loading of neostandard? I think not, as the smallest amount of config is still something like `export {config} from 'neostandard'` in your eslint.config.js file.

**Comment by voxpelli** [comment]
@fregante So `xo` will ditch the `xo` command and only use `eslint-config-xo` through `eslint.config.js` going forward? Or `xo` will continue to maintain `xo` as a separate ecosystem?

---

I’m not saying it has to be in the package.json file.

If one would want to get eg the VSCode extension to detect and use neostandard then though some kind of extension to or complement of the current configuration lookup would be needed.

Essentially one of these options I think would be needed (but probably exists others as well so don’t disregard this list just because my feverish mind can’t come up with more alternatives right now):

1. ESLint itself supports looking for a property in eg package.json
2. ESLint in its programmatic API enables the caller to provide a function or object that provides additional lookups of configs that it falls back to after its own checks – and the VSCode extension then uses that to extend the lookup
3. The VSCode extension adding a totally separate config step that looks for these configs prior to invoking ESLint and which then provides ESLint with the absolute path to the found config – this would mean that any useful logic within the ESLint config system would essentially have to be duplicated

**Comment by voxpelli** [comment]
A fourth idea (that I don’t really like) would be to suggest a new naming scheme, eg:

`eslint-preset-neostandard`

And the presence of such a one in the dependencies would auto-configure everything.

**Comment by fregante** [comment]
I'm just a moderator for XO, not a maintainer. I expect Sindre will maintain XO as is for the foreseeable future.

**Comment by voxpelli** [comment]
Let’s skip this, I don’t have the energy for it
