### ISSUE TITLE
Change Request: Improve eslintrc error message

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#19020]
### ESLint version

HEAD

### What problem do you want to solve?

Currently, if the ESLint CLI is run in eslintrc mode, we output the following message:

> You are using an eslintrc configuration file, which is deprecated and support will be removed in v10.0.0. Please migrate to an eslint.config.js file. See https://eslint.org/docs/latest/use/configure/migration-guide for details.

As reported in [this discussion](https://github.com/eslint/eslint/discussions/18456?notification_referrer_id=NT_kwDNlpKxMTA2NzMwMDEwMzg6Mzg1NDY&notifications_query=reason%3Amention#discussioncomment-10904454), this doesn't really give enough context to figure out why ESLint is running in eslintrc mode.

### What do you think is the correct solution?

Update the error message to contain the following information:

1. If `ESLINT_USE_FLAT_CONFIG=false` is explicitly set. The poster in the previously mentioned comment had this set from a previous installation and it took a while to realize it.
2. If possible, the location of the configuration file used. I'm not sure how easy it will be to get this info, but it's worth looking into.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
> 1. If `ESLINT_USE_FLAT_CONFIG=false` is explicitly set. The poster in the previously mentioned comment had this set from a previous installation and it took a while to realize it.
> 2. If possible, the location of the configuration file used. I'm not sure how easy it will be to get this info, but it's worth looking into.

The location of the configuration file used depends on the input files/patterns. A single run can also use multiple configuration files. All that logic is deep inside `@eslint/eslintrc` and seems difficult to extract. If the user wants to see the location of the configuration file(s) used, they can use the `--debug` flag.

In my understanding of the linked discussion, the problem was _why_ eslint works in the eslintrc mode. The presence of eslintrc config files doesn't trigger the eslintrc mode, so I think the locations are less important for the problem. Only `ESLINT_USE_FLAT_CONFIG=false` triggers the eslintrc mode.

So I think updating the message to something like this would address the problem:

> You are using an eslintrc configuration file, which is deprecated and support will be removed in v10.0.0. Please migrate to an eslint.config.js file. See https://eslint.org/docs/latest/use/configure/migration-guide for details. An eslintrc configuration file is used because you have the ESLINT_USE_FLAT_CONFIG environment variable set to false. If you want to use an eslint.config.js file, remove the environment variable. If you want to find the location of the eslintrc configuration file, use the `--debug` flag.

**Comment by nzakas** [comment]
Good point, and I like your suggested error message update. 👍

**Comment by mdjermanovic** [comment]
Here's a PR: https://github.com/eslint/eslint/pull/19023
