### ISSUE TITLE
Add support for ExportDeclaration in no-unused-vars rule

### ISSUE THREAD

**Issue by phpnode** [eslint/eslint#1903]
Currently, each of the following will be consider `foo` to be unused.
```js
export var foo = 123;
export function foo () {}
export class foo {}
```

I opened a PR for this: #1890 but at the moment, espree does not support ES6 module syntax, (although there is a PR for it [here](https://github.com/eslint/espree/pull/43)) so I'm unsure how to add tests for this, do you have any suggestions? 

I'm using [babel-eslint](/babel/babel-eslint) which produces these newer AST node types.

**Comment by nzakas** [comment]
We really need to wait until we can write tests for this, which means waiting for the Espree changes.

**Comment by Cellule** [comment]
Since I've been looking into this matter for the past hour I figured I'd give links to follow various discussions on this.
First of all,
espree merged https://github.com/eslint/espree/pull/43 which is not complete therefore we can't assume it will remain like that. Plus, the discussion on this particular matter is located at https://github.com/eslint/espree/issues/72
Also there is an open discussion on this on https://github.com/jquery/esprima/issues/311

I also use babel-eslint and I would like to see this integrated.
Regarding espree, you have to watch out for the `export default` case. I know babel-eslint will produce a  node like `{ type: 'ExportDeclaration', default: true }`, but right now espree produces `{ type: 'ExportDefaultDeclaration' }`  [source here](https://github.com/eslint/espree/blob/bb258cb099f211a058eaeccc12a158c987bfa58a/lib/ast-node-types.js#L105)
Depending on the choice of espree, babel-eslint might need to convert the node to match.

**Comment by caridy** [comment]
@Cellule, Babel will align with the AST structure in the following days. We have finished the formalization process for all implementations (more details here: https://github.com/estree/estree/pull/38), and I'm sure @sebmck will be carrying on the work on babel very soon.

**Comment by sebmck** [comment]
@caridy 1 week max. Waiting on marijnh/acorn#216 which will require a rewrite of all the custom Babel parser extensions (ES7 etc).

**Comment by nzakas** [comment]
Working on this
