### ISSUE TITLE
CLI: Use ecmaFeatures option

### ISSUE THREAD

**Issue by gyandeeps** [eslint/eslint#1940]
Should be allow passing in ecmaFeatures from our CLI interface. As of now we allow everything except ecmaFeatures option.

**Comment by nzakas** [comment]
I'd like to hold off on this until we figure out how to support ES6 going forward. If we change parsers (which we might), then we might not have the granularity of `ecmaFeatures` anymore.

**Comment by gyandeeps** [comment]
Sounds good. We can hold off for now and put this issue in the backlog.

Ecma feature has already made its way into a lot code of the rules. Changing this would make a lot of parts of the application prone to errors. (Just a thought).

**Comment by nzakas** [comment]
Rules only rely on the AST structure, they don't know about ecmaFeatures as that only affects the parser.

**Comment by gyandeeps** [comment]
I am sorry i dint say it right.
A lot rules test code contains ecmaFeatures in the code.

**Comment by nzakas** [comment]
Yup, I'm aware. The real cruz of this issue is if people are primarily going to be swapping in an outside parser to get more advanced features. Already we have people swapping in esprima-fb and babel-eslint, both of which ignore `ecmaFeatures`. So...we just need to see where the trends are going. :)

**Comment by gyandeeps** [comment]
Closing as we dont see any demand for this option.
