### ISSUE TITLE
Require semicolon after import statements

### ISSUE THREAD

**Issue by skevy** [eslint/eslint#2174]
Semicolons are not enforced after import statements.

Example:

import * as utils from './utils'

should be enforced to have a semicolon:

import * as utils from './utils';

Right now, with the semi rule on in eslint, this does not warn or throw an error.

**Comment by nzakas** [comment]
Thanks, we will get that fixed. I suspect the same is true for `export` statements

**Comment by skevy** [comment]
Yah, meant to include that in the initial report.

Anyway...thanks!

**Comment by skevy** [comment]
Awesome. Thanks for fixing @gyandeeps @nzakas

**Comment by AaronHarris** [comment]
Is it possible that this could be a configurable option for the 'semi' rule? Eg.

`"omitImportAndExport": true` ignores the semicolons for lines containing only containing imports and exports. There are cases where you want to enforce semicolons in regular code, but may not want/need them for import and export statements for code beautification and since they follow their own 'special syntax' anyways.

**Comment by not-an-aardvark** [comment]
@AaronHarris Feel free to create a new issue to propose that if you'd like. However, my initial impression is that this seems like a very user-specific preference, so it might be a better fit for a plugin.
