### ISSUE TITLE
Configure file extensions in .eslintrc

### ISSUE THREAD

**Issue by necolas** [eslint/eslint#2274]
AFAICT, this is not supported at the moment. Example:

1. You have a Node app
2. Your React components use the `.jsx` extension.
3. You have one `.eslintrc` at the root for Node, and nested `.eslintrc` with `jsx: true`.

It seems you have to run `eslint . --ext .js,.jsx` which is ok, but my intent is really to scope parsing of `.jsx` files to the subtree that contains them. That's why I thought rc-level config might make sense.

**Comment by lo1tuma** [comment]
Duplicate of #1674.

You could apply `ecmaFeatures: { jsx: true } ` only to the subtree. Would this solve your problem?

**Comment by necolas** [comment]
I'm already doing that. It works, but it's not exactly the intent. Since a previous request was closed, I'll just close this. Thanks

**Comment by nzakas** [comment]
This has come up as a possibility for 2.0.0 via glob patterns: https://github.com/eslint/eslint/issues/2203#issuecomment-88654556

If accepted into the roadmap, there will be a new tracking issue.

**Comment by sekmo** [comment]
since this page pops up at the top when we search for "eslintrc specify file extensions", it would be great to write an update as of 2017 (I'm still looking how to speficy the file extensions on the eslitrc file) :-)

**Comment by not-an-aardvark** [comment]
This is now possible (see the documentation [here](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns)).

```
{
  "overrides": {
    "files": "your/globs/**/*.js",
    "rules": {
      "some-rule": "off"
    }
  }
}
```

**Comment by sekmo** [comment]
There is no way to get a .js.erb file linted? I'm trying with this configuration:
```
{
  "extends": "airbnb",
  "rules": {
    "func-names": ["error", "never"],
    "no-var": 0,
    "vars-on-top": 0
  },

  "overrides": {
    {
      "files": "app/**/*.js.erb"
    }
  }
}```

**Comment by ljharb** [comment]
It would still be ideal to replicate the `--ext` option in config files; every CLI option and config option should generally be symmetric.

**Comment by not-an-aardvark** [comment]
By default, when you run ESLint on glob patterns (e.g. `eslint 'foo/**/*'`), only `.js` files get linted. To lint other kinds of files, you can either:

* Specify those files directly (`eslint foo/bar.js.erb foo/baz.js.erb`)
* Use the [`--ext`](https://eslint.org/docs/user-guide/command-line-interface#--ext) option on the command line to indicate that globs should include `.erb` files.

The `overrides` option that I linked before is useful if you want to use a different configuration for different glob patterns, but it's not necessary if you just want to lint other kinds of files using the same configuration.

Note that if your file is not valid JavaScript, ESLint will still attempt to parse it as JavaScript and will probably return a parsing error. (Presumably, your `.js.erb` file contains ERB with embedded JavaScript, but is not a valid JavaScript file on its own.) This is because ESLint doesn't natively understand the `.erb` format, so it wouldn't be able to figure out where the JavaScript is in your file. To extract the JavaScript blocks from your ERB, you can use something like [`eslint-plugin-html`](https://github.com/BenoitZugmeyer/eslint-plugin-html).

**Comment by sekmo** [comment]
So there is no way to add the `.js.erb` extension on `.eslintrc`?

**Comment by not-an-aardvark** [comment]
That's correct. You can specify which files get linted with command-line arguments, but you can't do this with a config file.

**Comment by not-an-aardvark** [comment]
@ljharb 

> It would still be ideal to replicate the `--ext` option in config files; every CLI option and config option should generally be symmetric.

Making CLI options and config options symmetric is not really a goal at the moment; there are some CLI options like `--fix` which intentionally require user opt-in.

For more discussion on specifying extensions without command-line flags, see https://github.com/eslint/eslint/issues/8920.

For more discussion on statically declaring command-line flags in general, see https://github.com/eslint/eslint/issues/9484.
