### ISSUE TITLE
 Plugin processors and CLIEngine API

### ISSUE THREAD

**Issue by BenoitZugmeyer** [eslint/eslint#2331]
Right now, plugin processors are only run when calling `executeOnFiles`. Yet, some external software may want to lint text chunks with `executeOnText`.

Here is two legitimate use cases:
* a text editor may want to lint unsaved code. It knows the file path and thus, the file extension from the previous save. See AtomLinter/linter-eslint#52
* a bundler like grunt executing on text streams instead of rereading the file many time. See BenoitZugmeyer/eslint-plugin-html#2

`executeOnText` may have a new optional argument, indicating the file path. If the path is known, it can be use to apply preprocessors on the text. Also, it could load the specific config file if any .eslintrc is in a parent directory of the file path.

What do you think?

**Comment by BenoitZugmeyer** [comment]
Oh, on the same subject, eslint could add a `--filename` option like [jshint](https://github.com/jshint/jshint/blob/master/src/cli.js#L21) passed to `executeOnText` as the second argument.

**Comment by BenoitZugmeyer** [comment]
Wow I didn't see #1950 and #2326 . Sorry about that. So we already have the second parameter on `executeOnText` ! Now, we only need to apply processors if the file path is given.

**Comment by nzakas** [comment]
Yup, we'll leave this open to apply processors to text when a filename is specified.

**Comment by tikotzky** [comment]
@nzakas in order to apply the processors you would need the full file path. Should we assume that the full path will be passed in to `--stdin-filename`? and if yes perhaps the option should be changed to `--stdin-filepath`.
I can try to get processors working but was just wondering your thoughts on this first.

**Comment by nzakas** [comment]
There's no need for the full path, processors are applied based on file extension only.

**Comment by tikotzky** [comment]
ok

**Comment by gyandeeps** [comment]
@tikotzky Are you planning on working on this?

**Comment by tikotzky** [comment]
@gyandeeps definitely  won't be able to get to it before late next week. Feel free to tackle it if you'd like.

**Comment by gyandeeps** [comment]
There is no rush from my side also. Take your time. I just wanted to know if you were still planning to do it or not.

**Comment by tikotzky** [comment]
@nzakas I made the changes needed to run processors when calling `executeOnText` here: https://github.com/tikotzky/eslint/tree/process-executeOnText

I'm waiting for #2651 to get merged before opening a PR because those tests are needed to prove that the processor is running when calling `executeOnText`
