### ISSUE TITLE
ignoring ~/.eslintrc even if in hierarchy

### ISSUE THREAD

**Issue by G3z** [eslint/eslint#2400]
I noticed the behavior changed with https://github.com/eslint/eslint/issues/2279 (thanks to @nzakas for the patience).
If I get this right the intended behavior is:
  1. global (`~/projects/.eslintrc`) and local (`~/projects/Client/ProjectA/.eslintrc`) = global + local
  2. global (`~/projects/Client/.eslintrc`) and local (`~/projects/Client/ProjectA/.eslintrc`) = global + local
  3. global (`~/.eslintrc`) and local (`~/projects/Client/ProjectA/.eslintrc`) = local
  4. global (`/.eslintrc`) and local (`~/projects/Client/ProjectA/.eslintrc`) = global + local

isn't this confusing ?

**Comment by ilyavolodin** [comment]
The reason number 3 doesn't follow the same pattern, is because `~/.eslintrc` is global to the whole system. If you have multiple projects on your system, they might not share any configuration between them and having a file in your user directory will apply to all of them. If we were to revert the checkin that introduced this feature, you wouldn't have any way to exclude `~/.eslintrc`.
We also added a way to manually extend configuration file by specifying `extends` property inside `.eslintrc`. I suggest you use that if you want to have a shared config with globals.

**Comment by nzakas** [comment]
It's more accurate to say that `~/.eslintrc` is only used if there are no local config files. This was always the way it was intended to work.

For example, consider you clone the ESLint project and run our lint command. It's possible the lint could fail just on your computer because your personal style is different than the one in the project. That's pretty confusing. So, we dying use your personal config unless there is no other config.
