### ISSUE TITLE
Automate CLA verification

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#2503]
We should automate CAL verification for eslint. @michaelficarra suggested a very simple solution of checking another github repository. The same could be done with google document, if it will be made public.

**Comment by nzakas** [comment]
I'm not willing to have a public document with email addresses, I see that as a violation of trust.

I wrote a bot for work that reads this info from a Google spreadsheet, so I know it's pretty simple to do. Just haven't had the energy to do it for us. :-/

**Comment by michaelficarra** [comment]
The email address you use to make commits will be just as public as wherever the CLA signatures are read from.

**Comment by matz3** [comment]
You may have a look at https://cla-assistant.io/. Any feedback appreciated.

**Comment by nzakas** [comment]
@michaelficarra there's a difference. Not everyone wants their email address added to a published list. It's not about security, it's about not forcing people's information into public aggregation.

@matz3 looks interesting! Where can I read more? I'm always skeptical of new hosted solutions as they tend to get forgotten over time by their maintainers (like CLA Hub).

**Comment by matz3** [comment]
@nzakas The company behind this is [SAP](https://www.sap.com). Apart from the page and GitHub repo there are currently no further information. What exactly would you like to know more about it?

**Comment by nzakas** [comment]
* Who is using it?
* Where is the list of signees stored?
* Is there a way to import/export the signee data?
* How committed to this project are the maintainers?
* How long has this been running?
* If there's a problem, who can I contact for help?

**Comment by thojansen** [comment]
hi @nzakas .. **CLA assistant** is mainly built in order to  simplify the contribution process and to handle the CLAs for SAP open source projects. So the main customer of the tool is SAP itself and our team (mainly referred to as the GitHub team as SAP) is committed to this project and driving it (we are also building other open source tools like http://review.ninja). We have released it couple weeks ago and we are making our first experience with it. The next stage for us is now to also onboard other open source projects / companies in order to find the best solution to this problem.

For now we host the tool on pivotal.io and the database is hosted by mongolab.com. As soon SAP gets its own cloud foundry platform ready for external usage we will probably move to this one. In case you have a smart solution on how to store the information who has signed the CLA (even directly on GitHub), let us know. Happy to discuss this in more detail.

In the current state of the implementation you are not able to import/ export the signee data. You can see the list of signees on the user interface. Export is the next feature we are going to implement as soon we are finished with the redesign.

In case of problems or for any further questions and requests you can just open an issue in GitHub or work with us together on the project. It would be awesome if eslint would be joining.

**Comment by nzakas** [comment]
Thanks - the project looks a bit too young and limited for us to use right now, but we all keep an eye on it.

**Comment by gcochard** [comment]
@nzakas I'd be willing to take a look at automating this if you share the code for the bot you wrote.

**Comment by ilyavolodin** [comment]
Btw, jQuery has a bot that checks for CLA, I wonder if they open-sourced it.

**Comment by ilyavolodin** [comment]
They did: https://github.com/jquery/jquery-license

**Comment by nzakas** [comment]
Looks like just the guts, not the actual not.

**Comment by gcochard** [comment]
I think it's enough to go off of. Would the `release` function of `Makefile.js` be a good place to put this?

**Comment by gcochard** [comment]
Also, @nzakas can you put up a one-line sample (my entry or bogus data is fine) of the google spreadsheet that is currently serving as the CLA?

**Comment by nzakas** [comment]
My concern is that this appears to require the spreadsheet to be publicly accessible, and I don't like that - I don't want to have a list of emails anyone can peruse at their leisure.

**Comment by gcochard** [comment]
I'll look into the spreadsheets API and see if you can get at private data with an access token.

**Comment by gcochard** [comment]
It looks like the API allows access once a token has been created, but it may expire eventually. It would be easiest to create a web service for verification, but that would be an entirely new codebase. I would be happy to provide it, though hosting it would require something like Heroku which recently changed their free teir to require 6 hours of downtime per day.

If On the other hand, it was run as a local script at build time it would require an oauth token in the .travis.yml. In order to work with travis-ci it would only be able to run on commits made by Eslint or members.

It would be possible to run as part of the release,  but then only someone with access to the spreadsheet would be able to make releases.

**Comment by nzakas** [comment]
I actually have already written code that does this. Just sit tight.

**Comment by ilyavolodin** [comment]
Closing in favor of #3068
