### ISSUE TITLE
Watch capabilities

### ISSUE THREAD

**Issue by rizowski** [eslint/eslint#2513]
Hey, I was wondering if you guys would be interested in having a `--watch` or/and  `-w` command available for eslint? I can definitely throw up a pull request if you are.

**Comment by nzakas** [comment]
No, that's outside the scope of this project. You should use another tool with ESLint to accomplish this (Grunt and Gulp both support watching).

**Comment by mtscout6** [comment]
I would personally love to have this feature. I don't personally use either Grunt or Gulp, as I find them clunky and inefficient. I use webpack, but the current state of the eslint-loader is a non-starter due to MoOx/eslint-loader#21. Even if that was fixed though it does not cover everything that I would want linted in a project. 

Take into consideration [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) (which is very similar to our internal projects):

- No use of Grunt or Gulp
- Webpack only touches JavaScript files for delivered assets and tests
- Would still like to lint webpack configuration files, build, and release scripts.

All of the above is achievable today with the current eslint cli tool, with the exception of a watch mode.

**Comment by nzakas** [comment]
Again, i see this as outside of ESLint's responsibility and don't intend to support it. There are plenty of file watching utilities already available.
