### ISSUE TITLE
Shareable configs with plugin dependencies don't work as expected

### ISSUE THREAD

**Issue by feross** [eslint/eslint#2518]
I just published a shareable config for [`feross/standard`](https://github.com/feross/standard) called  [`eslint-config-standard`](https://github.com/feross/eslint-config-standard). Great feature idea!

The shareable config depends upon `eslint-plugin-react` in its [package.json](https://github.com/feross/eslint-config-standard/blob/master/package.json#L14) and [eslint config](https://github.com/feross/eslint-config-standard/blob/master/index.js#L23).

However, ESLint can't seem to find the react plugin. So users of the shared config need to know which plugins are depended on and install them along with the shareable config. Not ideal.

Can we fix this?

**Comment by nzakas** [comment]
Did you try adding the plugin as a peer dependency on your config package?

**Comment by feross** [comment]
No didn't try that, but I don't think this is a solution going forward. npm plans to stop automatically installing peerDependencies in the next major version, 3.0.0 (see: https://github.com/npm/npm/issues/6565). This puts the burden of installing the required plugins onto the user of the shared config.

**Comment by nzakas** [comment]
Unfortunately, peer dependency is what makes the most sense. It might not be as clean as an regular dependency, but it is the correct relationship, and users will be warned to install it.

**Comment by feross** [comment]
How does a peer dependency make the most sense? The shareable config *depends* on the plugin, hence `eslint-config-standard` should depend on `eslint-plugin-react`.

From the npm documentation: 

> In some cases, you want to express the compatibility of your package with an host tool or library, while not necessarily doing a require of this host. This is usually referred to as a plugin. Notably, your module may be exposing a specific interface, expected and specified by the host documentation.

There is actually a peer dependency here, but it's not on `eslint-plugin-react`, it's on a specific version of `eslint` since the config isn't likely to work correctly with future semver major version. `eslint` is the "host" of the shareable config.

Unless I'm missing something, making `eslint-config-standard` peer-depend on `eslint-plugin-react` just so that npm warns the user to install it seems like an abuse of peer dependencies.

**Comment by lo1tuma** [comment]
The shareable config only provides the config for the plugin but don’t actually make any use of it. So, in my opinion, a peer dependency describes the relationship much better.

**Comment by feross** [comment]
The user experience of using a shareable config with plugins is disappointing. These are the usage instructions that I'm using right now: 

---
Shareable configs are designed to work with the `extends` feature of `.eslintrc` files.
You can learn more about
[Shareable Configs](http://eslint.org/docs/developer-guide/shareable-configs) on the
official ESLint website.

To use the JavaScript Standard Style shareable config, first run this:

```bash
npm install eslint-config-standard eslint-plugin-react
```

Then, add this to your .eslintrc file:

```
{
  "extends": "standard"
}
```

---

Asking the user to install a plugin they've never heard of isn't ideal.

**Comment by nzakas** [comment]
@feross peer dependency is the only relationship that makes sense. Think about it, what is the alternative? If we hack ESLint to look into your config package dependency, then your config has control over the version of the plugin being used, which makes no sense. Also, what if the user already has the plugin installed? It would be weird not to use it. So obviously, that isn't a viable solution due to the confusion. 

We have always recommended people install plugins at the same level as ESLint itself. Shareable configs are no different, and I don't see why the introduction of the latter would affect the usage pattern of the former.

Your complaint here is really more about how peer dependencies work. That's something you need to take up with npm. I'm also disappointed that the change will force manual installation of peer dependencies, but neither of us can change that through arguing here.

**Comment by gcochard** [comment]
So, with npm@3, it should be possible to list `eslint-plugin-react` as a direct `dependency` instead of `peerDependency`, and [npm will flatten the node_modules directory](http://blog.npmjs.org/post/111968476155/npm-weekly-6) and put `eslint-plugin-react` at the same level as `eslint-config-standard`, and `eslint`. Does that solve the issue or am I mistaken?

**Comment by ilyavolodin** [comment]
@gcochard Yes, flatten node_modules will solve this problem once npm 3.0 hits and everyone upgrades to it (that will be a while, there's still a lot of people using npm<2.0)

**Comment by nzakas** [comment]
@gcochard no, it doesn't. The implementation of dependencies will, but that doesn't change the fact that these are peers and not direct dependencies. You should never specify a plugin as a dependency for a shareable config, even in npm 3.

**Comment by IanVS** [comment]
What is the correct relationship if one config extends from another config?  For example, I want to create `eslint-config-ianvs` which extends `eslint-config-standard` and tweaks a few things to my liking.  Seems to me like I'd use a direct dependency on `eslint-config-standard` and a peer on `eslint`, correct?
