### ISSUE TITLE
Optionally relax `no-empty` restriction for catch blocks

### ISSUE THREAD

**Issue by timkendrick** [eslint/eslint#2558]
I know this has been covered [before](https://github.com/eslint/eslint/issues/2187), however I find the need for an "this page is intentionally left blank" comment in a `catch` block a bit irritating, and I assume I'm not alone in this.

Context: I'm currently thinking of making the switch from JSHint to ESLint for all my public and private projects, so we're talking about a couple of hundred thousand lines of code. However there are a few situations when an empty `catch` block makes sense (e.g. when loading some user-input text that may or may not be written as JSON, try parsing it as JSON first. If this fails, then just keep the string value that they typed). Having to write a seemingly-superfluous comment that actually has a hidden meaning for the linter just seems to me like a hack.

I assumed ESLint was a flexible, unopinionated linter but it seems like @ljharb was kind of [shot down](https://github.com/eslint/eslint/issues/2187#issuecomment-88148229) when he suggested this _optional_ behavior (which seems perfectly reasonable to me). As somebody who's currently getting their first impressions of ESLint, this reminds me of the bad old JSLint days when Douglas Crockford decided that it was non-negotiable that all your `var` declarations have to be at the top of a function, and if you don't agree then you can find a new linter.

I'd hope that that the choice of linter wouldn't need me to rewrite any of my existing code. While you might say that it indicates code smell or whatever – fine, but this is subjective to some degree, and sometimes you don't have the option to rewrite the code in question (for reasons of time, or repo permissions, or office politics, or whatever). I'm not saying this should be the default, but could we at least have an _option_ to relax the `no-empty` restriction for `catch` blocks?

**Comment by xjamundx** [comment]
@timkendrick My understanding is that ESLint won't ever be able to to provide every rule or every exception people might want to have. It was setup as a platform to make it easy for teams to write their *own rules* that were right for them. If you'd like help setting up a custom rule that disallowed empty blocks, except for `catch` I'd be more than glad to help!

**Comment by nzakas** [comment]
Thanks for the feedback. It's worth pointing out that being unopinionated means that we don't force you to do anything, you can opt-out of anything ESLint is doing, including turning off any rule you don't like. You can also create and distribute your own rules if you don't want to use the built-in ones.

Being unopinionated *does not* mean we always do what is requested. We have a lot of users to consider when making changes, so the decision isn't always straightforward. Design decisions must be made for rules both in the interest of consistency, simplicity, and speed. What makes sense to you might not make sense in the context of the project.

We also make no guarantees that there's some configuration that "just works" with your code out of the box.

In the case of this rule, as I'm sure you read in the original issue, the problem with allowing all empty `catch` blocks to be valid is that you can't distinguish between between intentional and accidental empty blocks. Empty `catch` blocks swallow errors, and that's pretty dangerous when done unintentionally.

As we grow, adding options to rules are implicit messages that something is OK and that we feel comfortable that you aren't in danger by using it. In this case, you very much are in danger of missing something important, and I'm not sure we want to be promoting something this dangerous.

We also have the problem of rule exceptions, where one we introduce one type of exception, we tend to get more exception requests and it's harder to rationalize not adding them because we added one before.

So, as I how you can see, this issue is more complex than it seems.

**Comment by timkendrick** [comment]
Thanks for the responses, and sorry if I sounded snarky in my original comment. I wasn't saying that you should always do what is requested, however I saw that some people called for a rule that raises an error empty `catch` blocks, while some people wanted to maintain the previous (JSHint-compatible) behaviour of allowing empty `catch` blocks, so that's why I assumed adding an option to the rule would be the best solution to please everybody.

Obviously I realize that if you opt out of certain warnings then you're leaving yourself open to making unintentional mistakes: in my mind, opting out of a default linting rule means that you understand that what you're doing is potentially risky and accept that it could have bad consequences, but you choose to proceed with it regardless because you understand the risks. I appreciate that you're trying to protect your users from potential danger, but this can seem overly restrictive if you don't give them an option to opt out (which is why I brought up the JSLint comparison).

Nonetheless, I completely accept your point that you can always turn off the `no-empty` rule entirely if need be, and adding further options to rules just fragments the codebase. I also realize that this is your project and you've invested a massive amount of your own time in it, so obviously you should be allowed to govern its behavior. Coming from JSHint, I also didn't know that it would be easy to add new rules to ESLint, which is why I was placing a lot of importance on having everything exposed in the configuration: @xjamundx, do you have an example of setting up a custom rule that disallowed empty blocks, except for `catch`?

Anyway, thanks for providing ESLint, it's a really impressive tool!

**Comment by xjamundx** [comment]
Yeah @timkendrick give me like 30 minutes and I'll post up the code for you here.

**Comment by timkendrick** [comment]
Thanks @xjamundx – that'd be amazing! I've read through the docs on adding rules, and it all makes sense, it's just my unfamiliarity with AST tokens that's holding me back... probably a good opportunity for me to learn something new!

**Comment by xjamundx** [comment]
Basically what you want to do is take the existing rule https://github.com/eslint/eslint/blob/master/lib/rules/no-empty.js#L27 and add `CatchClause` as one of the exceptions on that line.

1. Then rename the file to something like `no-empty-except-catch.js` and stick it in a `rules/` folder.
2. Enable the rules in your config with `no-empty-except-catch: 2` and disable the old rule.
2. Then make sure to add the `rulesdir` to your config as per http://eslint.org/docs/user-guide/command-line-interface#--rulesdir

Let me know if that works (or doesn't) :)

**Comment by xjamundx** [comment]
p.s. if you want to dive into eslint a bit checkout this video starting around the 10th minute https://vimeo.com/119903352

**Comment by ilyavolodin** [comment]
@timkendrick Getting familiar with AST is actually very easy. Just use this tool: http://esprima.org/demo/parse.html

**Comment by timkendrick** [comment]
Thanks @xjamundx, that worked like a charm! I had no idea it'd be that easy.

Also thanks for the link @ilyavolodin, looks like a great way for me to finally get to grips with AST!

**Comment by xjamundx** [comment]
Awesome @timkendrick glad that worked! You can also check out this other video I did if you want to learn more about ASTs:
https://skillsmatter.com/skillscasts/5778-don-t-be-scared-of-abstract-syntax-trees

**Comment by timkendrick** [comment]
Great, checking that out now. Thanks again!
