### ISSUE TITLE
Trying to use eslint in browser

### ISSUE THREAD

**Issue by omerts** [eslint/eslint#2585]
Hello,

I am trying to lint in a browser, and I have set the env config to browser: true, but I get errors because the eslint rule loader is trying to read files using fs, which isn't available in the browser.

**Comment by lo1tuma** [comment]
You could use browserify or webpack to create a bundle which can be executed in the browser. This is what we are doing for our [online demo](http://eslint.org/demo/). This approach has some caveats, e.g. plugins are not supported that way.

Except for our online demo we don’t have any plans to provide a browser version of ESLint.

See also this [discussion](https://groups.google.com/forum/#!topic/eslint/_If8mxLNdgI) in our mailing list.

**Comment by omerts** [comment]
@lo1tuma, I am already using webpack. It looks like webpack bundles the fs usage into the compiled file.

**Comment by nzakas** [comment]
You can't use ESLint directly with webpack or browserify without modification. Your best bet is to check out the repo and run `npm run browserify` to create a browser version that works.

**Comment by michaelficarra** [comment]
Maybe we should split the CLI portion of the project into its own module that consumes this one so we have a clear separation of responsibilities? (I know this is never going to happen, but I just couldn't live with myself if I didn't put it out there -- it's the right thing to do).

**Comment by nzakas** [comment]
There's already a very clear separation of responsibilities in the repo: http://eslint.org/docs/developer-guide/architecture

Not sure another module would have any benefit since the architecture would be the same.

**Comment by kevinbarabash** [comment]
I tried using `browserify`, but `load-rules.js` uses `readdirSync` to get a list of a rules.  It would be nice if the rules could be loaded using `require`.  Maybe there could be a build step which generates a module that loads all of the rules using `require`.

**Comment by finom** [comment]
I'm using eslint in an application compiled by webpack. It works for me but I have to dance around tricks. 

1) I have to pull and build eslint via ``install`` script 
```
    "install": "npm run browserify-eslint",
    "browserify-eslint": "shx rm -rf eslint && git clone https://github.com/eslint/eslint eslint && cd eslint && npm install && npm run browserify",
```
... instead of using it in my dependencies. The installing of deps and dev deps takes a lot of time.


2) Webpack outputs warnings
```
WARNING in ./eslint/build/eslint.js
Critical dependencies:
619:484-491 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original sourc
e to get better results.
 @ ./eslint/build/eslint.js 619:484-491
```

3) I cannot include ``babel-polyfill`` into the app because build/eslint already includes it. But I want to do this myself to control its version and to put it into the beginning of the application bundle.

----------

It looks just not right. As I can guess the browser version is made for /demo/ on the website. Why don't to make environment-agnostic API and then wrap it by CLI stuff?

I like eslint and I use it in all projects I do but the browser version is made without your love :)

@nzakas I guess this may be very minor for you and I'm sure you're not going to fix this issue right now but I'd like you at least reopen the issue because it is still actual.

**Comment by ilyavolodin** [comment]
@finom It was a conscious decision to not support anything other than Node (browser support for demo is internal only, and we don't provide support for it externally). You can read more about that here: https://www.smashingmagazine.com/2015/09/eslint-the-next-generation-javascript-linter/#legacy-problems

**Comment by finom** [comment]
I've found a way to "webpackify" it. If somebody is interested, let me know.

**Comment by kevinbarabash** [comment]
@finom I'm interested.

**Comment by FredyC** [comment]
@finom I would be interested as well.

**Comment by abhishiv** [comment]
@finom, would you mind sharing how?

**Comment by abhishiv** [comment]
For anyone who gets stuck at this, it looks like @finom was talking about [this](https://github.com/circlecell/eslint.io/blob/master/tools/webpackify-eslint.js)

Works for me!

**Comment by finom** [comment]
@kevinbarabash @FredyC @abhishiv sorry for long response. Yes, I just had to modify browserify script a little. Also [this tool](https://github.com/circlecell/eslint.io/blob/master/tools/bundle-configs.js) compiles configs to simple json so you can use the most of them in a browser.

**Comment by abhishiv** [comment]
Hey, @nzakas I'm aware that the eslint team didn't set out to target browser, but since it has a long time since that decision was made, and the ecosystem has changed a lot, have you thought about reconsidering it?

In the case of this issue for example, it seems a lot of people are maintaining their custom forks to mitigate this issue, and run eslint in the browser. 

While it would be a simple fix to make eslint compatible with webpack/browserify. Would you be willing to accept a PR with this fix?

**Comment by slorber** [comment]
I am interested to run ESLint in the browser,

Context: https://react-reboot.now.sh/
