### ISSUE TITLE
Recursive mode

### ISSUE THREAD

**Issue by clark800** [eslint/eslint#2600]
When the user runs `eslint --recursive index.js`, eslint recursively checks all files required in index.js and additionally checks the following new rules:
1. `no-undef-import`: for `var x = require('x');` checks that for all properties `y` accessed as `x.y` are defined in `module.exports` in x.js. In the less common case that `module.exports` is dynamically generated, the user can inline disable the rule.
2. `no-unused-exports`: all properties in module.exports are used in some other file, unless if this is the top-level file passed on the command line.

**Comment by ilyavolodin** [comment]
While this is possible to do, I think it would be extremely hard. I can see how this would be useful, I just don't think the effort to get this in would be justifiable.

**Comment by gyandeeps** [comment]
wow I didn't know about this CLI option, its an eslint option?
its not documented on the CLI page: http://eslint.org/docs/user-guide/command-line-interface

**Comment by ilyavolodin** [comment]
@gyandeeps It's a request, even though it's phrased like a statement.

**Comment by gyandeeps** [comment]
lol... thanks for clarifying @ilyavolodin ... i got confused there....
I dont know why this sounds like a third part concept (from eslint behalf) where they (third party project) can use eslint to achieve this.
Just a thought...

**Comment by gyandeeps** [comment]
Now since I understand the proposal in this issue, I dont think I am convinced that this functionality should be built into eslint. As purpose of eslint is to lint files which are provided by the user. 
Now you can build another tool which can depend on eslint internally and do the things which you are proposing. That would make sense to me.

Since you want the smartness built with `require` but then this idea opens up door to support ES6 `imports`, requireJs, commonjs, etc. After all these case it becomes a bigger concept. With this being said Eslint has to start thinking about how all the module loaders work and then come with the list of files to lint.

Thats is why I think this would be an excellent individual tool which can rely on eslint for linting functionality. This is what I think.

**Comment by ilyavolodin** [comment]
Right now, you wouldn't be able to write a third-party tool for this, since we do not expose any way to affect escope per file.

**Comment by gyandeeps** [comment]
I think we can, Users will actually call the third-party-toll with their one file name. Then tool will be smart enough to figure out all the dependent files and call eslint withe the collection of files. 
With this eslint doesn't have to change.

**Comment by ilyavolodin** [comment]
Proposed rules would have to be aware of all of the global/exported variables in each imported file, and will have to lint against them. In order to do that, we need to be able to modify scope property of ruleContext. We do not currently expose a way to do that (somebody found a way to hack it, but it's not supported functionality).
In any case, I think this is out of scope for ESLint itself.

**Comment by ilyavolodin** [comment]
This feature is currently out of scope. Closing.
