### ISSUE TITLE
no-unused-vars behavior with global variables

### ISSUE THREAD

**Issue by arturadib** [eslint/eslint#2631]
When the scope is `all`, and you declare a global variable in one file:

```
// file1.js
myGlobal = 123;
```

but you only consume the variable in another file:

```
// file2.js
console.log(myGlobal);
```

ESLint doesn't pass (because it's only looking at each file individually). Since almost invariably global variables are used across files, this really reduces the utility of the `all` option.

Any chance ESLint can do a quick pass across all files first so it's aware of global var definitions and usages? Thanks for the awesome project @nzakas !

**Comment by arturadib** [comment]
PS: this is particularly helpful for Meteor

**Comment by gyandeeps** [comment]
Why not just say 

```
/* global myGlobal */
```

On top of the file in which it gets consumed.
Docs: http://eslint.org/docs/user-guide/configuring#specifying-globals

**Comment by xjamundx** [comment]
Each file is read independently of the other files. Also in a lot of projects the files don't leak globals (most module systems used on both client and server), so this would be a pretty big change indeed.

**Comment by arturadib** [comment]
> Why not just say

I did. Here's the file:

```
/*global myGlobal:true*/

myGlobal = 123;
```

and here's the error message:

```
file1.js
  3:0  error  myGlobal is defined but never used  no-unused-vars
```

Using the default rule:

```
"no-unused-vars": [2, {"vars": "all", "args": "after-used"}]
```

**Comment by arturadib** [comment]
> Also in a lot of projects the files don't leak globals

We must be talking about something else. By definition, any global leaks. (`window.*` leaks on browsers, and so does `global.*`)

**Comment by rabbitfang** [comment]
The global variable declaration needs to occur in the file(s) that global is used in. So in `file1.js` you would add
```js
/*global myGlobal:true */
```

**Comment by arturadib** [comment]
> The global variable declaration needs to occur in the file(s) that global is used in.

It is. Here it is the file again:

```
// file1.js
/*global myGlobal:true*/
myGlobal = 123;
```

and here's the error message:

```
file1.js
  3:0  error  myGlobal is defined but never used  no-unused-vars
```

As discussed, this happens because ESLint doesn't know I'm actually using `myGlobal` in `file2.js`...

**Comment by lo1tuma** [comment]
Related: https://github.com/eslint/eslint/issues/1200

**Comment by xjamundx** [comment]
@lo1tuma yeah that's probably a good idea. of course a short term fix would be just to use `window.myGlobal` which should not have that problem and will hopefully be a bit more explicit (for example if you ever move to module system without implicit globals

**Comment by ilyavolodin** [comment]
@xjamundx `/*exported */` will only solve part of the problem. It will just mark certain variables that are unused as used, so they wouldn't show up in the error log. As far as I understand this question asks for more then that. Being able to do a full scan of all files first and build global scope from all of them and then verify local variable usage against that global scope.
@arturadib We use escope to generate scopes for a given file, there is no "quick pass" with that approach. In order to get scope, we have to parse the whole file using `espree` then pass AST over to escope so it would generate scopes. That alone probably takes a very large chunk of execution of ESLint. So what you asking for will decrease performance by a huge margin. The same question was asked very recently here: #2600 We suggested creating another tool on top of ESLint that would collect all variable information from all files and then pass it into ESLint.

**Comment by nzakas** [comment]
I'm sorry, this is very far outside the scope of what ESLint is meant to do and I don't see addressing this. I think the best advice we can offer is that you build a tool that grabs global definitions from your files and outputs an eslintrc file with the `globals` predefined. Then, you can use `extends` to import it.

**Comment by qodesmith** [comment]
I was experiencing the same thing. I ended up just putting all the globals I was using inside the `globals` property within my `.eslintrc.js` file. The only drag was that each one had to be named individually like such:
```
'globals': {
  'var1': true,
  'var2': true,
  ...
}
```

Since each global is going to get a value of `true` anyway, would have been nice to be able to do it in an array like so:
```
'globals': {
  ['var1', 'var2', 'var3']: true
}
```
