### ISSUE TITLE
ecmaFeatures `globalReturn` stops working when `modules` is true

### ISSUE THREAD

**Issue by feross** [eslint/eslint#2636]
`globalReturn` stops working when `modules` is true.

```js
"ecmaFeatures": {
    "globalReturn": true,
    "modules": true
}
```

**Comment by nzakas** [comment]
As designed.

**Comment by feross** [comment]
Why?

**Comment by nzakas** [comment]
Modules can't be wrapped in function scope, so a global return isn't possible.

**Comment by feross** [comment]
Thanks for explaining.

**Comment by feross** [comment]
Any chance that we can revisit this?

When I have both of these rules enabled, I really want eslint to be a bit clever-er. When we're not in an ES6 module (no `export` keyword usage), my global return preference should be honored. Can we only forbid global return when we're in an ES6 module?

**Comment by michaelficarra** [comment]
@feross There's no way for the eslint parser to tell if you want to parse the program as a Script or a Module other than the fact that you told it which you wanted.

**Comment by feross** [comment]
Any advice for what a general purpose tool like [`standard`](https://github.com/feross/standard) should do in this situation?

**Comment by michaelficarra** [comment]
You're not going to like it, but you need two modes: Script and Module. All ECMAScript tooling that supports ES6 has to operate under these two modes, and yours is no exception.

**Comment by nzakas** [comment]
To echo what @michaelficarra said: you need to tell the parser upfront what it is you're parsing, this will be true both in browsers and Node when implemented natively, as it's not just syntax but also scoping rules that change.

Since that is pretty much how modules were designed to work, it would be a good idea to ask your users to make this decision upfront as well.
