### ISSUE TITLE
Create "eslint:recommended" to extend from

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#2713]
As part of the 1.0.0 change to use `--reset`, we need to define "eslint:recommended" as a way to back in recommended defaults. 

- [ ] update eslint.json so only "potential errors" are on by default
- [ ] add "eslint:recommended" as a hardcoded option for `extends` that merges in eslint.json
- [ ] update `--init` to automatically add `extends: "eslint:recommended"` for easy quick start

**Comment by gcochard** [comment]
I can take this on. Should have a PR ready today.

**Comment by gcochard** [comment]
One question, should we update the docs to state that rules that are on by default (e.g., missing "off by default") are the rules in `"eslint:recommended"`?

**Comment by ilyavolodin** [comment]
We would probably need to rewrite docs for this feature all together.

**Comment by gcochard** [comment]
I'll start with a branch that exhibits the correct behavior and update the tests so they all pass again.

After that's working, we should discuss what should change in the docs.

**Comment by gcochard** [comment]
This will take a little bit longer than I originally estimated, as I will have to re-think the tests related to this behavior. I think I will modify all existing tests for configs to include an explicit `extends: "eslint:recommended"` and then add a few tests to ensure that only syntax errors are flagged with no config.

I will also update all tests related to the reset flag (if they exist) to drop the flag and ensure they still pass.

**Comment by ilyavolodin** [comment]
Take your time, no rush

**Comment by jokeyrhyme** [comment]
While you're at it, would it be possible to sneak in an "eslint:all" definition? There are quite a few rules that are disabled by default (pre-1.0), and this would be especially helpful for someone that appreciates strict linters. I fully expect that a few would need to be overridden (e.g. quotes and cyclical complexity), but this would drastically reduce the size of my .eslintrc files.

**Comment by gcochard** [comment]
I'd like to keep this as simple as possible for now. Please open a separate issue to track `eslint:all` and I'll get to it as soon as this one is finished.

**Comment by jokeyrhyme** [comment]
@gcochard thanks. :)

**Comment by baer** [comment]
I just came across this issue and I see that a project I just started plying with might be duplicating some work here... Since it's done though, I wanted to broach an idea:

It seems like maintaining default configuration for any variant of js (React, Node, Browser, Test, Phantom, Coffee etc.) is a really difficult proposition. There may be rules in the Error section but complete config defaults will be very contentious. Furthermore, the mission of ESLint is to provide amazing static analysis tooling so trying to provide much in the way of defaults is really a distraction. I'd like to propose that configuration be largely if not entirely managed via an external package using shared config rather than putting it in core.

I've taken a stab at this already (before I found this issue) for the following three reasons:

1. Managing config across many projects was tedious.
2. getting started on a new project is too hard. I love the idea of [JSCS's presets](https://github.com/jscs-dev/node-jscs/tree/master/presets) and wanted to create that for ESLint
3. Managing the addition and deprecation of rules in a monolithic shared config was very error prone and low in visibility.

In solving these issues I was able to create a composable config builder with a small (but growing) collection of defaults for a new project. This is all very new - as in the last two weeks so any feedback on this project or efforts in ESLint that would obviate it's need would be much appreciated.

https://github.com/baer/eslint-config-defaults
https://www.npmjs.com/package/eslint-config-defaults

**Comment by gcochard** [comment]
@baer Most of the changes I am working on are related to getting the tests passing with no default rules. The Makefile currently verifies the rules in the default config, ensuring they match up with the documentation. As part of resolving this issue, we will rework that to ensure the "recommended" rules show up in place of "default", and that they match the documentation.

Moving forward from the `v1.0.0` release, there will be no rules removed until a semver-major release. That will ensure stability and increase visibility. Additionally, no rules will be added to the default ruleset until a semver-minor release. I hope that addresses point 3. For point 2, we have the `--init` option. For point 1, I agree. Shared configs will be instrumental in helping to manage configs across multiple projects.

Do any of the committers have any opinions on this? /cc @nzakas @ilyavolodin @btmills.

**Comment by nzakas** [comment]
@baer this isn't really related to the topic at hand. Can you either send a message to the mailing list or, if you are going to request a feature, file a new issue? Happy to discuss, just want to keep issue discussions on-topic.

**Comment by baer** [comment]
I didn't know about `--init` :). Still I wonder if managing defaults should be a part of core. On the one hand the tool should be as easy and accessible as possible for beginners/newcomers. Linting is awesome and there should be no barriers to entry. On the other, it seems like a whole separate project and a side not to ESLint's core mission trying to manage a set of sensible defaults for every project type.  

I'd love to hear folks chime in.

**Comment by baer** [comment]
@nzakas Sorry, I probably wasn't explaining myself all that well. What I meant to ask is if this issue can be closed and have ESLint `--init` (internally) import an external ruleset. Possibly a community created one or possibly a separate repo under the eslint org on github.

**Comment by nzakas** [comment]
I'm afraid not doing this issue isn't really an option. This is part of our 1.0.0 roadmap and the approach was discussed thoroughly a while back. We need to have some built-in defaults and those belong as part of this repo.

So, if you'd like to continue talking about what can be done in addition to this issue, please open another issue or contact the mailing list.

**Comment by baer** [comment]
Sounds good, thanks for the feedback and thanks to you and everybody on this project for maintaining such an awesome tool.

**Comment by nzakas** [comment]
@gcochard are you still working on this?

**Comment by gcochard** [comment]
@nzakas I am but I don't want to be a blocker. What's the schedule look like for 1.0?

If I'm not done by the 4th, I'll make a PR as-is and throw it back for someone else to take.

**Comment by nzakas** [comment]
Schedule is ASAP :) I'd like to get a release candidate out next weekend (July 11)
