### ISSUE TITLE
Rule Proposal: no-class-assign

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#2718]
This rule is similar to [`no-func-assign`](http://eslint.org/docs/rules/no-func-assign).

The following patterns are considered warnings:

```js
class A { }
A = 0;
```

```js
class A {
  b() { A = 0; }
}
```

```js
let A = class A {
  b() { A = 0; }
};
```

The following patterns are not considered warnings:

```js
let A = class A { };
A = 0;
```

```js
let A = class {
  b() { A = 0; }
};
```

```js
class A {
  b() { let A = 0; } // shadowing
};
```

I'm happy to work if it was accepted.

**Comment by ilyavolodin** [comment]
Hmm... I think it's a reasonable request, but I think what I might consider is renaming `no-func-assign` to something like `no-assign` and making two option, `function` and `class`. Although I don't like the name...

**Comment by mysticatea** [comment]
In fact, many there are rules about re-assignment: 

- [no-ex-assign](http://eslint.org/docs/rules/no-ex-assign)
- [no-param-reassign](http://eslint.org/docs/rules/no-param-reassign)
- [no-native-reassign](http://eslint.org/docs/rules/no-native-reassign)
- [no-undef](http://eslint.org/docs/rules/no-undef) - for explicit globals.
- and, #2719 (no-const-assign)

**Comment by nzakas** [comment]
@ilyavolodin I think it's too close to 1.0.0 to make that change now. I'd prefer a separate rule.

**Comment by michaelficarra** [comment]
I'm not sure about the first one. All of the other examples emit warnings if and only if they would cause runtime failures. But the first example will emit a warning and will not fail at runtime.

**Comment by nzakas** [comment]
I don't believe the point of this rule would just be to catch runtime errors - it's to flag when you are overwriting a variable that you should not overwrite, just like the other similar rules.

**Comment by michaelficarra** [comment]
What you "should not overwrite" was already kind of defined by the language, since it allows writing to the outer variable, but not the inner one. I thought this rule was just trying to enforce that restriction statically (like #2719 would with `const` declarations), which is both possible to do and likely @mysticatea's intent since these issues were filed at the same time. Should all but the first example in this issue (and maybe function expression name bindings?) be merged into #2719? Then this issue could be only about things that won't actually cause a runtime error.

**Comment by mysticatea** [comment]
I thought, most developer doesn't feel that the `FunctionDeclaration` statement is a variable, so the `no-func-assign` rule exists. 
The `ClassDeclaration` statement has a same kind of issue.

And at same time, the `ClassDeclaration` and the named `ClassExpression` have an issue about assigning to the name from its class body. It raises a runtime error.

I think @michaelficarra is right on semantics, but I think if rules are separated by syntax, it's understandable easily.

**Comment by nzakas** [comment]
@michaelficarra you're arguing language design over developer concerns here, and since ESLint is developer-focused, we must bias towards what is useful to people outside of what the language provides. In this case, I can see the concern that @mysticatea is bringing up and agree that it's analagous to function declarations.
