### ISSUE TITLE
Start search .eslintignore from directory where placed .eslintrc

### ISSUE THREAD

**Issue by evilebottnawi** [eslint/eslint#2856]
Default directory for search is
```javascript
if (!directory) {
    directory = process.cwd();
}
```
I use intellij and my working project not on top level directories.
Project - ./project
Working directory in project - ./project/themes/mytheme/.eslintrc
intellij start command for eslint from ./project directory and eslint can't find .eslintignore
Many IDE work similarly.

**Comment by nzakas** [comment]
We can't just start looking for .eslintignore in the sand directory as .eslintrc because you could have many .eslintrc files but only one .eslintignore file.

I'm not very familiar with IntelliJ, but I'd imagine there must be a way to specify the current working directory for a command?

**Comment by evilebottnawi** [comment]
@nzakas  i am not change working directory

**Comment by ilyavolodin** [comment]
IntelliJ doesn't allow changing working directory only for ESLint. Most of the rest of the integrations allow you to set working directory when you configure ESLint integration (IntelliJ allows this for a lot of other integrations, like Karma and Mocha). The only way you can do this is by changing root directory in the project or moving .eslintignore file to the root directory.
The change you are proposing is not going to work at all, because you can have 20 subdirectories, and each one of them can have .eslintrc file, what do you consider root at that point? Closest .eslintrc? Farthest? What if you don't have .eslintrc at all? Or you configure eslint through package.json.
I think your best bet is to create a ticket for IntelliJ and request additional field for working directory.

**Comment by evilebottnawi** [comment]
@ilyavolodin thanks for answer, i create ticket IntelliJ

**Comment by segrey** [comment]
Created IntelliJ issue https://youtrack.jetbrains.com/issue/WEB-17378
Related discussion - how IntelliJ calculates working directory https://github.com/eslint/eslint/issues/1601#issuecomment-99798501

**Comment by evilebottnawi** [comment]
@ilyavolodin bump!

**Comment by segrey** [comment]
@evilebottnawi Probably, it'd be better to close this issue, because the issue should be resolved in IDE integration, not ESLint itself. Well, odeally, ESLint could be working directory agnostic, but looks like there are reasons to not do that.
Clarification: unfortunately, WebStorm 10.0.4 detects `.eslintignore` incorrectly, so working directory is always set to the nearest content root.
The bug will be fixed in WebStorm 10.0.5 (no release ETA unfortunately). Fixed behavior is described in https://github.com/eslint/eslint/issues/1601#issuecomment-99798501.

@nzakas @ilyavolodin What do you think? Is this logic is enough for determining working directory or it'd better to expose `Working directory` field in ESLint UI?

**Comment by nzakas** [comment]
From a quick look, it seems that would make sense. I don't use WebStorm so it's a little hard for me to know for sure.

**Comment by evilebottnawi** [comment]
@nzakas sorry for offtop, but what you use?

**Comment by segrey** [comment]
@nzakas Thanks. `Working directory` field will be added if there is a real use-case when working directory is guessed wrongly.

**Comment by nzakas** [comment]
I use Sublime Text 3.
