### ISSUE TITLE
no-implied-eval.js: Additional function names

### ISSUE THREAD

**Issue by mozfreddyb** [eslint/eslint#2873]
For completeness's sake, no-implied-eval could be enhanced to check for other functions that imply `eval`:

* <s>`setImmediate` (IE 10) [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate)</s> (doesn't accept strings)
* `new Function` (All browsers) ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function))
* `execScript` (IE) ([MSDN](https://msdn.microsoft.com/en-us/library/ms536420%28VS.85%29.aspx))
* `crypto.generateCRMFRequest` (Firefox) ([Bug in older Firefox versions](https://html5sec.org/#5))

I'd be willing to take this patch if you agree this makes sense in the *no-implied-eval* rule.
If not, I will likely create my own.

**Comment by nzakas** [comment]
setImmediate doesn't accept a string as an argument, so there's no need to warn on that.

new Function is actually not like eval because it doesn't execute anything by default and doesn't have access to the containing scope, so it's not dangerous.

execScript I could see an argument for, but might better be in no-eval?

The last one seems like it's very specific to outdated Firefox versions, so I'm not sure it makes sense to add.

What do others think?

**Comment by michaelficarra** [comment]
Agreed with your assessment, @nzakas.

**Comment by freddyb** [comment]
Please excuse the commit spam. It seems I messed up a bit :-)
Pull request #2882 points to adding `execScript` into the `no-eval` rule.

I think we can close this, if everyone agrees.

**Comment by brettz9** [comment]
While it is true that `new Function` does not execute anything by default and it doesn't have access to the immediate containing scope, it does have access to globals and could steal cookies or do other dangerous things, especially if, as with the other evalish methods, the string were constructed based on user input.
