### ISSUE TITLE
Create ESLint configuration to match 0.24 defaults

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#2966]
This is similar to #2730 and #2713.  

The creation of the "eslint:recommended" config in #2713 will not exactly match the current defaults in `v0.24`, but will rather only include rules to catch potential errors.  In order to ease the transition to `v1.0` for those who wish to stay as close as possible their current ruleset, I propose adding a configuration which would replicate the defaults set in https://github.com/eslint/eslint/blob/0.x/conf/eslint.json.  

I'm not sure what the best name for this would be.  For the sake of discussion, I'll call it `eslint:legacy`.  So, if someone wants to upgrade to `v1.0` with the least breakage, they would add `extends: eslint:legacy` to their configuration.  I believe this would more closely align to what @pascalduez initially recommended in https://github.com/eslint/eslint/issues/2100#issuecomment-98059422.

In case I've not been clear enough, consider this use case.  A project is using ESLint currently and relying on the default to ensure that all quotes are double quotes.  They upgrade to `v1.0` and are told they need to now extend the `eslint:recommended` configuration, or else they won't have any rules enabled.  So, they do that, and then someone submits a PR with single quotes, which passes their linting.  Confusion and consternation ensues.

It's great to have a minimal set of recommendations, but I think it should be easy to get the old defaults back too if someone really wants them.

**Comment by nzakas** [comment]
I'm not sold on this - I'd rather force people to update their rule configuration for 1.0.0. We're already going to be forcing people to update their configs, might as well get them into a good config state instead of relying on old and somewhat arbitrary default values.

**Comment by IanVS** [comment]
I agree that it makes sense to recommend a reasonable, minimal config (`eslint:recommended`), but if someone is perfectly happy with the defaults in the current ESLint and wants to stick with it for whatever reason, that person will likely be annoyed/frustrated that they need to re-create those rules to update to the latest version of ESLint.  I was hoping the stigma associated with "legacy" would convey that these are not recommended rules, they are just available for helping projects transition slowly to the new system.

If my arguments aren't enough to change your opinion, then maybe this is a issue that sharable configs can solve?  In that way it will be possible for those who want to use the old defaults to do so, while not being officially condoned by the ESLint project.  It just won't be quite as simple as if it were in core.

**Comment by gyandeeps** [comment]
there is already config which has default support. https://github.com/walmartlabs/eslint-config-defaults

**Comment by IanVS** [comment]
@baer is the intent of this "default" config to stay locked at the `0.x` branch of ESLint?  

The naming is a little unfortunate IMHO, because soon it won't be the default, it will be the "old default".  Seeing "extends: default" in a `.eslintrc` file will be somewhat confusing to ESLint newcomers.

**Comment by baer** [comment]
**Does config-defaults tracking a specific version** - Yes. Currently it's [tracking 0.24.0](https://github.com/walmartlabs/eslint-config-defaults#usage) and I plan to update it to track eslint's changes so my repo as it is now will not be enough to close this issue. 

That said - I sympathize with both sides and I'm happy to begin versioning ESLint configs in that project. 

**extending defaults may be confusing** - The reason I decided to have an explicit extend of defaults there was that this is already happening behind the scenes and as a newcommer to eslint it took me a while to realize that.

What I wanted was an explicit config that I could look at and understand. From there I decided to painfully copy every rule from the docs and set the ones I thought were important. After that was over and I had been copy pasting my jumbo config through a few projects I discovered the awesome sharable config feature and I thought I would extract that work into a lib. 

Since the extend of defaults tracks eslint there should be no confusion come 1.x though maybe I missed the point of your comment. I'm happy to make changes to better track what eslint is doing up to and including changing the name of the whole project :). Feedback is welcome.

**Comment by IanVS** [comment]
Thanks for the detailed reply. My comment about the naming being confusing was assuming it would be used in a way which closes this issue (ie locked at 0.24). After you explained it, it makes much more sense.

**Comment by nzakas** [comment]
>  if someone is perfectly happy with the defaults in the current ESLint and wants to stick with it for whatever reason, that person will likely be annoyed/frustrated that they need to re-create those rules to update to the latest version of ESLint

I feel like this is trying to predict the future. Everyone is going to make some sort of update to the config they are using for 1.0.0. We don't know whether this burden is actually high or not.

I could be wrong, but I'd rather wait for feedback from the RC before committing to something like this. As I've said many times, it's a lot easier to add something later on than it is to remove something.

**Comment by IanVS** [comment]
OK fair enough.  Just wanted to talk it through, thanks.
