### ISSUE TITLE
no-shadow support for ignoring identifiers.

### ISSUE THREAD

**Issue by mirek** [eslint/eslint#3035]
`no-shadow` is great but there are times when exception from the rule is desirable.

Consider the following example where `done` argument is used throughout the codebase:

```
import async from 'async';

function foo(done) {
  async.map([1, 2], function (e, done) {
    done(null, e * 2)
  }, done);
}

foo(function (err, result) {
  console.log({ err, result });
});
```

Imagine multiple nested levels throughout the whole project (with identifiers like `resolve`, `reject`, `done` or `cb` being shadowed). It would be great to take advantage of `no-shadow` for all other identifiers except `done` (or others).

This PR #3031 solves this problem by introducing `ignore` option where a list of identifiers can be provided to be excluded from `no-shadow` test.

**Comment by nzakas** [comment]
@eslint/eslint-team thoughts on this?

**Comment by ilyavolodin** [comment]
I think in node it's very common practice to reuse variables. While I think this exception goes against the whole point of the rule, I can see how it would be helpful to a lot of people.

**Comment by btmills** [comment]
Apologies to all analogies abused hereafter: While I see this as a footgun, at least it's unloaded by default. If someone in their own codebase wants to load it and is prepared to be very careful when doing so, I suppose that's their prerogative. I'm not opposed.*

--

*Since it's [already available as a plugin](https://www.npmjs.com/package/eslint-plugin-shadow-exception), is this use case common enough to justify its inclusion in core? I'd be more convinced if multiple people came along asking for this.

**Comment by nzakas** [comment]
OK, let's do it.
