### ISSUE TITLE
Report parsing errors explicitly as parsing errors [$5]

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint#3555]
Currently, if Espree bombs out on a parsing error, the error message displayed to the user (at least with `stylish`) is very similar to the errors that are received from linting rules, with the only exception being that a rule name is not provided.  For example:

```js
"use strict";
/*eslint no-delete-var: 2*/

var x;
delete x;
```

Will give:
```js
5:10  error  Delete of an unqualified identifier in strict mode
```

This could cause confusion to new users, who may wonder where the error is coming from, or assume that it is caused by the no-delete-var rule, when in fact it is a parsing error.

I propose one (or both) of the following to add clarity:

* Update formatter(s) to display `parse error` or `fatal error` rather than simply `error` in cases of fatal/parsing errors (https://github.com/eslint/eslint/blob/9dbd9fccfe0473897b22d471eb72f6809eda1bfd/lib/formatters/stylish.js#L50)
* Report the `ruleId` of fatal errors as `parse-error` or `fatal-error`.

Thoughts?

**Comment by BYK** [comment]
:+1:

**Comment by ilyavolodin** [comment]
Agree

**Comment by nzakas** [comment]
Updating every formatter isn't a good solution due to third party formatters.

I'm not sure specifying a fake rule ID makes sense either, as it could confuse people if they then go to look up that ID in the docs and can't find it. Though maybe if we do "(parser)" that would be student enough to avoid problems?

**Comment by IanVS** [comment]
I'm not sure the approaches are either/or.  I think we could do both.

I like the idea of `parser` as the rule ID.  It gives a good indication where the message is coming from.

And, as for the formatters, I'd say it's up to each formatter what it displays.  What's to stop us from at least adding some value into the built in formatters if/where it makes sense?

**Comment by nzakas** [comment]
> And, as for the formatters, I'd say it's up to each formatter what it displays. What's to stop us from at least adding some value into the built in formatters if/where it makes sense?

In general, solutions in the form, "we update every ___________ with this new functionality" are not good solutions because they rely on duplication of functionality in multiple places. At work, I'd call this a scaling problem, because solutions like this are how teams prevent themselves from being able to scale effectively.

The best solution is always the one where you make a change in one spot and those changes for through to others.

**Comment by platinumazure** [comment]
What about doing solely `(parser)`, i.e., fake rule identifier for now, and then see where that lands us? Is that acceptable?

**Comment by nzakas** [comment]
I think we probably need to play it safe here. Maybe prepending the message with "Parsing error:" is best?

**Comment by platinumazure** [comment]
Works for me.

**Comment by platinumazure** [comment]
@IanVS Are you working on this?

**Comment by IanVS** [comment]
I got hit by a cold and have not started yet. Feel free to jump in, should be a very simple change.
