### ISSUE TITLE
Shrink wrap dependencies?

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#4515]
We just had an issue (#4481) where a dependency patch upgrade introduced a problem for some users. I'm wondering if it makes sense to shrink wrap our dependencies so this doesn't happen in the future?

The advantage of doing so is that we can know with 100% certainty which versions of which dependencies people are using. The disadvantage is that we will need to pay close attention to patch and minor releases of our dependencies. With each minor release, we would need to manually upgrade dependencies. 

Thoughts?

**Comment by platinumazure** [comment]
I think the current approach is fine, but it would be a good idea to bump a
dependency after a patch version comes out when there is a known issue. In
the example you gave, escope would be bumped above the problematic version
when it is known that the new patch version is good, and ESLint would do a
patch release for that.

Right now, it's possible to have someone directly consume the problematic
escope in their project, and then ESLint will get that copy because it fits
the version requirements outlined in our package.json. If we bump the
version in our package.json, then npm install should pull in a different
copy of the package in that scenario and ESLint should function.

For cases where our dependencies do not have regressions introduced in
minor or patch releases (hopefully the vast majority of the time), the
current strategy is fine and it's not worth the maintenance hassle to
shrink wrap. But after a problem is brought to us with dependency
compatibility, I think we should bump the dependency version once a fix is
available.

If I'm misunderstanding something about how npm works, please let me know.

**Comment by gyandeeps** [comment]
FWIW I think it puts a lot of burden on us to maintain and up our release frequency. So I am :-1: on this for now until we have a solid argument on doing this.

**Comment by BYK** [comment]
I also think this is sort of overkill, especially for a library. Unless this happens again, I think we don't need shrinkwrap. That said it is always a good idea to keep required version of dependencies up to date.

**Comment by nzakas** [comment]
Okay, not enough support.
