### ISSUE TITLE
Update eslint:recommended

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#4953]
We've added a bunch of new rules since 1.0.0, and we should update `eslint:recommended` so that it has all of the important, error-catching rules that have been added since.

These seem like a good idea to have on by default:

1. `no-unexpected-multiline`
1. `no-empty-pattern`

What others should be added? (Remember, these can't be stylistic rules, only rules that catch possible errors.)

**Comment by mysticatea** [comment]
:+1: 

`no-empty-pattern` is a rule for ES6, so I think:

- `no-class-assign` (`no-func-assign` is on by default already)
- `no-const-assign` (always error)
- `no-dupe-class-members` (`no-dupe-keys` is on by default already)
- `no-new-symbol` (always error)
- `no-this-before-super` (always error)
- `constructor-super` (always error)

And maybe the following rules are proper as well:

- `no-case-declarations` (prevents a cause of reference errors)
- `no-empty-label` (I think those labels are a mistake since ECMAScript has no goto statement)

**Comment by gyandeeps** [comment]
How about `[array-callback-return](https://github.com/eslint/eslint/blob/master/docs/rules/array-callback-return.md)` ?

**Comment by nzakas** [comment]
These all seem like good additions. Any others?

**Comment by michaelficarra** [comment]
`array-callback-return` is not safe because it doesn't know the target is actually an array, so it should not be recommended.

**Comment by btmills** [comment]
What about `no-arrow-condition`?

**Comment by nzakas** [comment]
`no-arrow-condition` is a good one.

@michaelficarra has a point, `array-callback-return` is probably not safe enough to have as part of this.

**Comment by mysticatea** [comment]
`no-arrow-condition` has been deprecated :)

**Comment by btmills** [comment]
Ah right, I was reading the published rules list. I don't think we could put either of its replacements on the recommended list.

**Comment by nzakas** [comment]
Oh duh. :) That's OK, I think we have a good list of additions here.

**Comment by alberto** [comment]
Should the new rules also be listed in the `migrating-to-2.0.0` doc?
