### ISSUE TITLE
Auto-config seems to skip some rules

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/eslint#5098]
I've used autoconfig branch and created 3 different configs using 3 folders in my repository. For the most part, process went pretty smoothly, however, I noticed that some rules were turned off in all 3 config files, and when I turned them on, there were no errors reported. Rules in question were `no-undefined` and `no-use-before-define`. I don't know if any other rules were off that could be on, it's a bit hard to say.

Let me know what other information I can provide (I can't post the code in question).

**Comment by IanVS** [comment]
Thanks.  Can you say what answers you chose for the questions?

**Comment by ilyavolodin** [comment]
Slightly different for all 3, but basically:
ES6 - yes,
CommonJS - yes,
Browser,
JSX - no,
Whatever the last question is (can't remember of the top of my head) - no

**Comment by IanVS** [comment]
@ilyavolodin, I haven't been able to reproduce this issue so far.  I've realized that I need some better logging to help troubleshoot these kinds of issues.  So, would you mind running `eslint --init --debug` while using the branch from https://github.com/eslint/eslint/pull/5120?  There will be two interesting pieces in there that would be great if you could copy in here:

1. One of the first lines should be ` eslint:source-code-util constructed options:` followed by the config that was used.  
2. The entire result registry should be displayed (starting with `eslint:config-initializer
Registry:`).  Could you copy out the values for the rules you're having problems with?

I'm not sure if this will be enough to figure out what's going on, but it should hopefully at least be a start.

**Comment by ilyavolodin** [comment]
I'll try it tomorrow at work and see what I can come up with.

**Comment by mysticatea** [comment]
Thanks for the Great Works, @IanVS !
`eslint --init` generated what I expected almost perfect.
But I also found some missing rules, so I report it here.

Repo: https://github.com/mysticatea/npm-run-all
Log and Result: https://gist.github.com/mysticatea/1bc768a22148a71e24a9

- `eqeqeq`, `max-statements`, and `valid-jsdoc` seem to be missing.
- Some rules are turned off. e.g. I expected `space-before-function-paren` to be turned on with `"never"` option.

**Comment by IanVS** [comment]
@mysticatea thanks for the report and logs!  Here are my answers:

- `eqeqeq` had failures with the default config (`2`) so that can't be used, and it found no errors if an option was set (either `[ 2, 'smart' ]` or `[ 2, 'allow-null' ]`).  The problem is, which option should the autoconfig choose?  I made the decision that if more than one option is valid not to arbitrarily choose a winner.

- `max-statements` is an interesting case.  The config that autoconfig generated (`[ 2, { ignoreTopLevelFunctions: true } ]`) was not valid.  The first option after the severity __must__ be an integer.  This is a bug in autoconfig.

- `valid-jsdoc` was not configurable for the same reason as `eqeqeq`.

- `no-use-before-define` and `space-before-function-paren` have a schema with a `oneOf`, which autoconfig does not yet handle (it's on my list of improvements to make).

My initial thoughts were to set rules to `0` if all of the configs attempted resulted in errors, and leave the rules out entirely if autoconfig simply wasn't able to make an intelligent choice among passing configs.  I'm seeing now that due to limitations of the configs that we can generate, this distinction may not make sense, and should be revisited.

**Comment by mysticatea** [comment]
@IanVS Thank you for the answer!

Fair enough, these rules are off :)

Just I felt that I'm glad if I can look at the list of off rules after `--init`.
For example, it collects off-rules to one chunk in the generated .eslintrc

**Comment by IanVS** [comment]
I'll see what I can do about sorting them.  I've also thought it would be nice to group by enabled/disabled rules, and then alphabetize within each group.

**Comment by nzakas** [comment]
@IanVS what are your plans for this issue? Should it be marked as accepted? Or are we not doing it?

**Comment by IanVS** [comment]
I'm waiting on a response from @ilyavolodin (https://github.com/eslint/eslint/issues/5098#issuecomment-177764174) to continue troubleshooting.

**Comment by ilyavolodin** [comment]
Bah, this completely slipped my mind, and I don't think I can reproduce this easily anymore:-( It was a real bug, but I think we might need to close this now.
