### ISSUE TITLE
What is the purpose of props:true in no-param-reassign?

### ISSUE THREAD

**Issue by EvanCarroll** [eslint/eslint#5306]
I'm just wondering how this is better than not having it. The only thing I can see it doing is causing code to go from..

```javascript
login: (options) => {
    options.url = // stuff
```

to

```javascript
login: (argsOptions) => {
    let options = argsOptions;
    options.url = // stuff
```

Which becomes something we can't check for... Not to mention, attaching methods on an object is frequently done, as in the case of reduce's accumulator (https://github.com/airbnb/javascript/issues/719). This is just part of Javascript. If you don't want your object being muddled with by the function you're sending it too, then you should look at 

* Object.freeze()
* Object.seal()

I believe this is just being [enabled by people who want things to be *more* strict](https://github.com/airbnb/javascript/issues/626).. I don't understand why you'd want this *ever* as a style rule. Can we look into answering *why this should be used?*, or *why this shouldn't be used?* in the docs if we're going to keep this around.

**Comment by ilyavolodin** [comment]
I believe this is the reason for `props` argument: https://github.com/eslint/eslint/issues/1600#issuecomment-113007156

**Comment by ljharb** [comment]
It is a common (albeit not the only) coding style that mutation should be avoided in all its forms. JavaScript makes this very difficult. This particular rule causes a programmer who is mutating a passed-in object to have it brought to their attention - clearly there's a number of patterns that they can use to work around it, but that's not the point. The concern for me is that this linter warning will likely suggest them to copy the object (avoiding mutation), or, ask why it's bad (creating the discussion).

As to your second example, I don't see any reason why the linter can't check for that too, but again the purpose is not to *prevent* programmers from doing bad things, it's to prevent them from *unknowingly* doing bad things.

**Comment by EvanCarroll** [comment]
I *fully* agree mutation should be avoided, ideally. But, there is no "copy object" operator in JavaScript. It's simply [call by sharing](https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_sharing). You're going to be fighting this every step of the way. If you want to make the object frozen, your only option is to `Object.freeze()` from the caller. If you want to fundamentally change the way JavaScript works, you'd have to wrap every variable assignment through a deep copy. Shy of that, you have to use a library with [`_.cloneDeep()`](https://lodash.com/docs#cloneDeep) or roll you own version (which sounds horrendous).

> As to your second example, I don't see any reason why the linter can't check for that too, but again the purpose is not to prevent programmers from doing bad things, it's to prevent them from unknowingly doing bad things.

I'm not going to defend call by sharing. But, if the language is call by sharing, or call by reference you just have to learn it and accept the drawbacks. You can't enforce call by value, and it seems pointless to warn people that they're using JavaScript.

I'd be all for,

> Warning, you're using a loosely-typed dynamic multi-paradigm language with global state.

But, there is no reasonable way to fix that.

**Comment by ljharb** [comment]
The warning here isn't to fix it - it's to prevent you from not knowing that what you're doing is dangerous. If you know what you're doing, that's what override comments are for, but the default should be for the linter to assume you don't realize you're doing it.

**Comment by ilyavolodin** [comment]
@EvanCarroll ESLint's job is not to prevent errors, it's to notify you when there's a potential for an error. We have other rules that go against JavaScript syntax. Like `no-use-before-define`. In JavaScript due to hoisting, this is not a problem, but a lot of developers come to JavaScript from other languages, and might not be aware of the potential problems that could occur due to JS syntax, so we warn them about it. You always have an option of turning off rule completely if you don't agree with those warning, or don't find them helpful (or even harmful/limiting in some cases).

**Comment by EvanCarroll** [comment]
Sure, it's the job to *notify you of errors* seems to be an excuse here.. Though it's not really an error, it's just JavaScript: namely that the language itself is not call-by-value, but instead call-by-sharing. We're assuming I don't know that, and that's why it's notifying me. But, we don't assume that the user knows `=` is assign by reference and not by value. So the end result is that the user, in trying to work around the linter, makes the code more obtuse and solves no problems. So long as we agree that the behavior likely to arise out of from

    error    Assignment to function parameter 'options'       no-param-reassign

in

```javascript
login: (options) => {
    options.url = // stuff
```

is a modification like this

```javascript
login: (argsOptions) => {
    let options = argsOptions;
    options.url = // stuff
```

Because again, you have to know that `a = b` is not `a = _.deepCopy(b)`..

**Comment by ljharb** [comment]
I would never expect (nor have I ever seen) someone bypass this linter rule with your second example, unless they are explicitly trying to sneak past the spirit of the linter rule.

At any rate, this is a rule that some of us find helpful. Thus, objectively, it is a useful rule to have. If you do not find it helpful, there's tons of easy ways to disable it! However, even if you are not convinced of its usefulness, the simple fact that others merely *say* it is useful to them makes it objectively so ¯\_(ツ)_/¯ 

It seems like the purpose of this rule has been explained, and I don't see `eslint` removing a rule many find useful simply because it can't convince somebody of its usefulness.

**Comment by ilyavolodin** [comment]
Agree with @ljharb this is a useful rule for some people. If you do not find it useful, just turn it off in the config completely, and you will never have to worry about it's errors. Not every rule in ESLint apply to everyone, nor should they. We have a lot of users, and they do not have the same needs.
