### ISSUE TITLE
The --fix option is not available for piped-in code.

### ISSUE THREAD

**Issue by bugeats** [eslint/eslint#5393]
Trying to format some piped-in code:

```bash
echo "var foo = { one: 'one' };" | eslint --stdin --fix
```
Results in:

    The --fix option is not available for piped-in code.

It would be great to use all of my carefully crafted eslint rules as formatter rules for my editor.

**Comment by nzakas** [comment]
We decided not to do this because there was no clearly consistent way that this should behave. Piped-in code without `--fix` outputs the linting problems, the same as running ESLint on a file without `--fix`. When `--fix` is run on a file, we also print out the linting problems that weren't fixed. We could do that for piped-in code, but then you wouldn't be able to get the fixed code. If we output the fixed code, then you wouldn't get the remaining lint problems and it would be inconsistent with how ESLint works in general. So, we don't have a good solution for this.

This could change pending the results of https://github.com/eslint/eslint/issues/5329, so stay tuned there.

**Comment by bugeats** [comment]
>  it would be inconsistent with how ESLint works in general

I was following you until this statement. The expectation that not all lint problems are fixable is already set. I would just assume that `--fix` simply does the best it can when in std i/o mode. It's ok for this mode's output to be different because it's a different use case entirely.

**Comment by ilyavolodin** [comment]
@bugeats I think that statement was pointed at the different part of the sentence. Autofixing doesn't try to fix everything as it is now. However, we notify the user that we were able to fix some of the problems and give them the list of problems that we were unable to fix. With --stdin we can pipe back fixed code, but we will not be able to report issues that were not fix, which might create an impression that everything was fixed, and there are no errors left. Which would be inconsistent with the way ESLint works.

**Comment by bugeats** [comment]
Gotcha. I'm happy to take the bullet of inconsistency. I scratched my own itch here:

https://github.com/bugeats/eslint-pretty

It does just what I proposed: fix the code the best it can and fail open.  I'm using it with my editor now and I'm really happy with the results.

**Comment by theanimal666** [comment]
I just implemented a linter for vim-autoformat bypassing the behaviour using a tmp file, which is imho an ugly solution (https://github.com/Chiel92/vim-autoformat/pull/178).   
What about to output the fixed code to ```stdout``` and if errors the report to ```stderr```? 
This still feels a bit strange but would solves the issue for most of us (i guess)

**Comment by Chiel92** [comment]
Another solution would be to suppress the unfixed problems with a flag (so that the user is aware of problems not being reported), or optionally write those to a given log file. When you want to prettify/fix the code in an editor, you are not interested in unfixed problems. You can use the normal linter mode for that.
