### ISSUE TITLE
List of rules that can be auto-fixed (--fix)

### ISSUE THREAD

**Issue by Elijen** [eslint/eslint#5434]
I think life is too short to fix linting errors manually. Is there a list of rules that can be fixed using `--fix` right now, that are planned to be implemented soon and rules that are never going to be implemented because it would be too dangerous to auto-fix (if any)?

I would potentially like to contribute by implementing auto-fixing for more rules and such a list would be very helpful.

**Comment by ilyavolodin** [comment]
Yes, you can find a list of rules that are currently auto-fixable here: http://eslint.org/docs/rules/ anything that is marked with wranch icon supports auto-fixing. We currently only accept auto-fixing for whitespace rules (semi being the only exception out of this rule), due to a very good chance that fixes will conflict with other rules. We are planning to re-address auto-fixing as part of 3.0.0 milestone and empower more rules to use this feature, while mitigating possible collisions.
If you are planning on contributing auto-fixing to rules, please make sure to open an issue first, so we could discuss potential collisions with other rules.

**Comment by Elijen** [comment]
@ilyavolodin Makes sense, thanks.
