### ISSUE TITLE
(Docs) Getting Started "Next Steps" improvement

### ISSUE THREAD

**Issue by raould** [eslint/eslint#5530]
```
Next Steps
    Learn about advanced configuration of ESLint.
    Explore ESLint integrations into other tools like editors, build systems, and more.
    Can’t find just the right rule? Make your own custom rule.
    Make ESLint even better by contributing.
```

errrrr... why doesn't it say anything about *using* eslint?! Please include (as the first thing in the list) a link to something like http://eslint.org/docs/user-guide/command-line-interface

**Comment by nzakas** [comment]
Using ESLint is mentioned quite early in the page:
http://eslint.org/docs/user-guide/getting-started#usage

We can definitely add a link to the command line options if you think that's useful, I'm just not sure that's the logical next thing people should read. Most of our questions tend to be about configuration, which is why that's the top recommended link.

**Comment by raould** [comment]
fwiw, it would make sense to me at least for the link to be at the end (as well at least) so that a newbie can "flow" along getting setup and trying it out on some code. but of course i might just be an outlier in my use case.

**Comment by nzakas** [comment]
This file exists on the website, so I'll make the change there.
