### ISSUE TITLE
Rule Proposal: no-constant-expression

### ISSUE THREAD

**Issue by captbaritone** [eslint/eslint#5640]
__When the rules will warn.__

Using a literal/constant as the first value in a logical expression results in a statement that can be simplified. The follow would warn:

    var greeting = false || 'Hello';

    var greeting = 'hello' && 'goodbye';

Since they could be simplified to:

    var greeting = 'Hello';

    var greeting = 'goodbye';

__Whether the rule prevents an error or is stylistic.__

This rule would prevent errors.

__Why the rule should be in the core instead of creating a custom rule.__

This rule would fill a similar role as http://eslint.org/docs/rules/no-constant-condition

__Are you willing to create the rule yourself?__

Yes.

**Comment by platinumazure** [comment]
I would go for `no-constant-logical-expression` or `no-useless-logical-expression`, myself, even though they're a bit longer. (`true` is also a constant expression and this is really about the short-circuit behavior of LogicalExpressions)

What about ternary statements? Have you thought about those at all? (Might want to dig into `no-unneeded-ternary` to see if those are covered, but I *think* those focus on ternary expressions with booleans as their consequent/alternate parts, rather than examining the condition.)

**Comment by captbaritone** [comment]
@platinumazure `no-constant-logical-expression` does sound better, however it may not be general enough if we also want to include ternary operators.

I looked at the source of `no-unneded-ternary` and it does not currently support this type of warning. Perhaps the ternary version of this error would be better as an option of `no-unneded-ternary` rather than of this rule?

**Comment by platinumazure** [comment]
Hmm... ternary does open a can of worms indeed. I'd be okay with having this focus on LogicalExpressions only, at first, and then we can evaluate ternaries later.

@eslint/eslint-team Thoughts?

**Comment by nzakas** [comment]
Hmm, not sure how useful this rule is in the core at the moment. At this point, we really need to be looking at only adding rules where we think, "oh wow, we MUST have this," and I'm just not feeling that from this rule.

**Comment by captbaritone** [comment]
Makes sense.
