### ISSUE TITLE
npm shrinkwrap fails >= 2.5.0

### ISSUE THREAD

**Issue by akoskm** [eslint/eslint#5687]
I'm encountering the following error when trying to do `npm shrinkwrap` on a `package.json` which contains eslint 2.5.0 or 2.5.1:

```
$ npm shrinkwrap
npm ERR! Linux 3.13.0-83-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "shrinkwrap"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: through@^2.3.6, required by inquirer@0.12.0
npm ERR! missing: esprima@^2.6.0, required by js-yaml@3.5.5
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/akoskm/Projects/project/npm-debug.log
```

Reverting eslint to `2.4.0` made the error disappear.

**Comment by platinumazure** [comment]
Probably related to our other bundledDependencies issues.

**Comment by akoskm** [comment]
Yeah, I looked at the history of `package.json` and was wondering if that's causing it.

**Comment by platinumazure** [comment]
@akoskm Any chance you can try with npm@3? I'm just curious to see if that makes a difference. (We still intend to fix this issue regardless, but sometimes npm@3's deduping can mask the issue and maybe that would generate your shrinkwrap successfully.)

**Comment by akoskm** [comment]
Sure, I'll let you know once I tested (probably tomorrow).

**Comment by ilyavolodin** [comment]
We were running into shrinkwrap issues yesterday. Haven't had the time to investigate yet.

**Comment by kaicataldo** [comment]
Fair warning, this is my first time working with some of this stuff, so please correct me if I'm wrong :)

This only seems to affect npm@2 (I am able to replicate the original poster's error with npm@2, but npm@3 seems to be working as expected), so it seems like @platinumazure's comment above is probably what's going on. 

@ilyavolodin shared this https://github.com/npm/npm/issues/8396, which seems to be the relevant workaround. Testing locally it looks to me like adding `through` and `esprima` to our bundled dependencies fixes the issue. I can make a PR if that seems like the way forward.

**Comment by ilyavolodin** [comment]
@kaicataldo I'm not sure that's the right path forward. I'm not very familiar with all of the npm stuff, but adding dependencies just to satisfy npm seems wrong to me.

**Comment by kaicataldo** [comment]
@ilyavolodin That's fair. I'll keep digging to see if I can find the underlying cause.

**Comment by kaicataldo** [comment]
Unfortunately, seems like a known bug: https://github.com/npm/npm/issues/10634.

**Comment by kaicataldo** [comment]
The link in my comment above explains what's going on, but the issue seems to be that dev dependencies are not bundled even if they are required by a non-dev dependency in npm@2. This is only a problem in npm@2 because npm@3 fills in the missing dependencies.

Specifically to this case, `through` and `esprima` are listed as dev dependencies for ESLint while also being sub-dependencies of `inquirer` and `js-yaml`.  Any better ideas than explicitly including `through` and `esprima` in our bundledDependencies? I don't like the idea of moving them out of the dev dependencies list in the regular dependencies list because that's not how ESLint consumes them.

**Comment by ilyavolodin** [comment]
Including them in bundledDependencies might be a reasonable way to go, I think. But not in regular dependencies.

**Comment by kaicataldo** [comment]
Aware this probably needs more input and discussion, but made a preliminary PR

**Comment by alberto** [comment]
Good catch identifying the origin of issue @kaicataldo!

Wouldn't budledDependencies get overwritten in every release?

**Comment by alberto** [comment]
Also, this doesn't fix the underlying issue, so we should discuss additional measures to avoid this from happening again.

**Comment by kaicataldo** [comment]
@alberto From my understanding, the packages in bundledDependencies are bundled when `npm publish` (or `npm pack`) is run. Looking at `eslint-reslease`, it looks like we use a 3rd party package to actually create the bundledDependencies list, and in looking over that package's source, it doesn't look like it accounts for this bug in npm@2.

Realizing this, it seems like my PR actually isn't the right solution, since I think we dynamically generate this list with the build script. Can you confirm, @nzakas? If so, I'll close my PR.

Unless I'm missing something, it seems like the underlying issue is the aforementioned bug. If we want to continue using bundledDependencies in an npm@2 compatible way we could update the build script to account for this bug (i.e. reach out to the 3rd party package author and notify them of the bug and see if they can fix it or just write our script that does something similar).

**Comment by ljharb** [comment]
This is a breaking change in a minor version, so it'd be awesome if this could be fixed soon - I'd love to use the new rules :-/

**Comment by nzakas** [comment]
This only occurred because npm was flakey when the package was created. I already updated the release script in #5688, so there shouldn't be any other change necessary besides doing a new release, which I'll do sometime today.

@ljharb this is just a bug, not a breaking change. It's akin to forgetting to include a dependency in package.json. We are doing the best we can to resolve this as quickly as possible, si a bit of patience would be greatly appreciated.

**Comment by alberto** [comment]
@nzakas are you sure? It looks exactly like the issue mentioned above. I hope you are right :)

**Comment by nzakas** [comment]
@alberto not I'm not sure. :) I had done a quick test on Saturday that seemed to indicate I was right, but doing another test right now, it's broken again.

We'll just revert to not using bundled dependencies for now and revisit at some later point.

**Comment by ljharb** [comment]
@nzakas fair enough, thank you for fixing it!
