### ISSUE TITLE
CLI Request: Support ":write" as well as ":true" for writeable globals

### ISSUE THREAD

**Issue by bdkjones** [eslint/eslint#5765]
Currently, to pass a writeable global to the ESLint CLI, you must use: `globalName:true`. I propose that the CLI also accept `globalName:write`.
### Why?
1. It makes the intent much clearer. For newcomers, "true" doesn't make much sense; it's not immediately clear what that means.
2. `:write` is the standard used by JSHint and JSLint, which makes migration easier.
3. Supporting both `:true` and `:write` is the best of both worlds. It does not break any existing ESLint configurations and improves the syntax for the future.
4. Implementing this is trivial.

**Comment by platinumazure** [comment]
I'm pretty sure the original reason we did `:true` was because it was based off of JSHint, so if JSHint now supports `:write`, then we don't have much of a reason not to. I would champion this.

What about `:false`, is there a `:read` or similar?

**Comment by bdkjones** [comment]
Well hell, I just checked JSHint's docs and they do show `:true`. I don't know when that changed, but I could swear it used to be `:write`. I've been using `:write` for years, at any rate. I still think the proposal makes sense regardless though—`:write` is a lot more intuitive than `:true`. And as long as we support both, there's no cost.

**Comment by platinumazure** [comment]
@bdkjones Well, in any case, as long as we support both I have no objections.

I guess the only problem I could see is, "if we support write, what else are people going to ask us to support"? But I'll let the rest of the team weigh in here.

**Comment by bdkjones** [comment]
Not sure anything else needs to be supported if `:write` or (optionally, instead) `:writeable` is implemented. It would be tough to get any clearer than that!

**Comment by platinumazure** [comment]
> Not sure anything else needs to be supported if :write or (optionally, instead) :writeable is implemented. It would be tough to get any clearer than that!

Perhaps those who don't have English as a first language might disagree. :smiling_imp:

**Comment by bdkjones** [comment]
Ha. Touché. But :true is English!

**Comment by nzakas** [comment]
This would introduce a fair amount of complexity for only a minimal benefit, so I don't see us doing this.

**Comment by bdkjones** [comment]
No offense, @nzakas, but that's a pretty dismissive reply. What is the "fair amount of complexity" that gets added? Why is the much greater clarity a "minimal benefit"? 

Responses like this are the worst part of the open source community. I understand that not every feature can or should be implemented (and perhaps this one does rightly fall into that category). But it would be far better to address the idea on its merits rather than simply saying, "I don't see us doing this".  

Brief, dismissive replies like yours discourage participation and ideas. I think we can do better.

**Comment by michaelficarra** [comment]
I am very much in favour of this feature. True and false mean nothing and are arbitrary in this context, in the same way 0, 1, and 2 were arbitrary and obtuse in severity context.

**Comment by BYK** [comment]
I also support this change. People (including me) are still getting confused about true and false. I guess we could do `globalName:'write'`, extend the rule schema and map these to old values. That is some added complexity but worth the clarity IMO.

**Comment by michaelficarra** [comment]
@nzakas Please reopen this.

**Comment by nzakas** [comment]
@bdkjones I'm sorry, I triage a ton of issues every day and generally just close issues that are too far out of scope or our current work. Unfortunately, I just don't have the time to provide all the technical details or write extended replies to each issue. I feel like my response gave enough information as to why the issue was closed. I apologize if you felt differently.

@byk @michaelficarra since you two feel strongly about this, I'll leave this for you to follow up on. Please remember that we are reliant on the `globals` package, so we need to keep supporting true and false regardless.

**Comment by bdkjones** [comment]
@nzakas no worries; I understand completely. Thanks for reconsidering!

**Comment by BYK** [comment]
@michaelficarra you wanna champion this or should I assign this to myself? Not sure how much work this involves.

**Comment by michaelficarra** [comment]
@BYK It should be a very simple change to [this code right here](https://github.com/eslint/eslint/blob/a2c15ccf3f2bedb43513f61f7030bbe24de3516f/lib/config.js#L183-L189). I'd rather not make the change myself, as I am very busy right now, but I will do it if nobody else is willing.

**Comment by nzakas** [comment]
I'd like to see a full proposal before anyone starts coding. 

Also note that this would be a breaking change because anything other than "true" was considered "false", so we couldn't really consider this until we are ready for 3.0.

And one last thing: I'd really rather have people focusing on the JSCS issues right now.

**Comment by michaelficarra** [comment]
@nzakas It'd only be a breaking change if you could show evidence of someone using `write` but intending for it to mean `read`/`false`, which I think is *very* unlikely.

**Comment by BYK** [comment]
@nzakas I'm with @michaelficarra for this one. Also okay for deferring this until I work on a few more JSCS issues.

@michaelficarra I'll try to get to this after a few other bugs for the code changes. I'm hoping you can at least review my code?

**Comment by michaelficarra** [comment]
@BYK: will do.

**Comment by boneskull** [comment]
:+1: to this.  I was just remarking how silly the whole "writable == `true`" and "not-writable == `false`" thing is.  Gonna guess that was adopted from JSHint, which was probably inherited from JSLint.  In other words: I blame Crockford.

**Comment by kaicataldo** [comment]
I'm closing this issues because it looks like consensus couldn't be reached. While we wish we could accommodate all requests, we have limited resources and do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never reach consensus, and as a team have decided to close such issues. This doesn't mean the idea isn't interesting or valuable, only that it's not something the team can commit to at the moment.
