### ISSUE TITLE
Show if rule is enabled by eslint:recommended on rule page

### ISSUE THREAD

**Issue by rik** [eslint/eslint#5774]
Website change so I skipped the eslint version questions.

**What did you do? Please include the actual source code causing the issue.**
Land on a rule page from a search engine.

**What did you expect to happen?**
See if the rule is enabled in "eslint:recommended".

**What actually happened? Please include the actual, raw output from ESLint.**
No indication of the rule being enabled.

The indication is already on http://eslint.org/docs/rules/ so it would be nice to also have it on rule pages.

It would also be useful to see if `eslint --fix` can fix this. I can open another issue for this though.

**Comment by alberto** [comment]
There is already a notice for fixable rules

**Comment by pedrottimark** [comment]
Stay tuned to critique some pictures of a possible design on Monday.

**Comment by pedrottimark** [comment]
Expanding the scope a bit, here are sentences which could appear after the main heading in rule docs.

The following pictures are 768px width simulated iPad in portrait orientation. What do you think?

recommended
![5774 768 recommended comma-dangle](https://cloud.githubusercontent.com/assets/11862657/14431928/ecb80098-ffd5-11e5-85c1-d9fdda8cc8dc.png)

recommended and fixable
![5774 768 recommended fixable no-extra-semi](https://cloud.githubusercontent.com/assets/11862657/14431938/f30506da-ffd5-11e5-9195-b82374842ed0.png)

fixable
![5774 768 fixable no-multi-spaces](https://cloud.githubusercontent.com/assets/11862657/14431946/fd2b722a-ffd5-11e5-9172-64fe2a286104.png)

removed
![5774 768 removed generator-star](https://cloud.githubusercontent.com/assets/11862657/14431959/031f65ba-ffd6-11e5-9ccc-fcdce390584b.png)

removed and (was) fixable: I am guessing the audience to know that a removed rule was fixable is people using an older version of ESLint, especially soon after it was removed? If you think it is relevant and not confusing, is it worthwhile for me to see if any removed rules had been recommended?
![5774 768 removed fixable space-after-keywords](https://cloud.githubusercontent.com/assets/11862657/14431965/0a3fb08e-ffd6-11e5-96ee-77a89b756642.png)

**Comment by pedrottimark** [comment]
The following pictures are 600px width simulated Nexus 7 in portrait orientation. What do you think?
* Right now, a media query omits the icons because the margin is too narrow, but we could display then inline instead.
* If we go in that direction, it probably implies moving the thumb-down and thumbs-up from the code well to the preceding example sentence. See no-extra-semi in this and the next comment.

recommended
<img width="196" alt="5774 600 recommended comma-dangle" src="https://cloud.githubusercontent.com/assets/11862657/14432253/549dc962-ffd7-11e5-87f0-ed76db900c34.png">

recommended and fixable
<img width="196" alt="5774 600 recommended fixable no-extra_semi" src="https://cloud.githubusercontent.com/assets/11862657/14432218/251b4e1c-ffd7-11e5-8c7d-e0d43037cffc.png">

fixable
<img width="196" alt="5774 600 fixable no-multi-spaces" src="https://cloud.githubusercontent.com/assets/11862657/14432224/2b259ba0-ffd7-11e5-926b-3b7d5582a668.png">

removed
<img width="196" alt="5774 600 removed generator-star" src="https://cloud.githubusercontent.com/assets/11862657/14432231/3134eeba-ffd7-11e5-8d20-5cf0d583564f.png">

removed and (was) fixable
<img width="196" alt="5774 600 removed fixable space-after-keywords" src="https://cloud.githubusercontent.com/assets/11862657/14432238/3d1489d4-ffd7-11e5-9181-d171118fd644.png">

**Comment by pedrottimark** [comment]
Here is possible change to position of icons for incorrect and correct code at 768px width. Only a small minority of rule docs will have separate adjacent code fences (for example, vars-on-top).

![5774 768 incorrect correct no-extra-semi](https://cloud.githubusercontent.com/assets/11862657/14432436/294ced82-ffd8-11e5-9f61-5948c474dba5.png)

**Comment by rik** [comment]
Sorry for the delay answering. I like this a lot.

In light of https://github.com/eslint/eslint/issues/5858, let me propose an alternate sentence:
```markdown
✔︎ This rule can be enabled by adding one of the following properties in a [configuration file](link):
   - `"extends": "eslint:recommended"`
```

**Comment by pedrottimark** [comment]
@rik Your comment shines some light on a vague thought that was lurking in the back of my mind. For many people, ESLint plugins or JSCS presets seem more relevant than `eslint:recommended` but those are maintained by third parties, true?

In contrast, a change to *which rules* are recommended by ESLint is considered breaking, can only happen at major versions. therefore that information is realistic to include in the rules index page (and therefore in rule doc pages).

How to balance displaying information that is *most relevant* to a particular person with information that is “stable” enough for eslint.org is stretching my mind at this moment.

Could you look at #5417 and tell me what you think about this way forward:
* we add the simple limited sentence to rule docs on eslint.org
* because the community can use `meta` properties in rules to display dynamic relevant lists or tables of rules enabled in plugins or presents (and which can link to rule docs the Web site)

**Comment by pedrottimark** [comment]
@nzakas Am glad to receive your guidance about strategic goal and tactical plans to move forward.

Proposed **goals** are if you click a link from search results or error results to a rule page:

* Be able to see at a glance whether or not a rule is fixable, removed, **or eslint:recommended** (page currently displays fixable and removed).
* Be able to ignore the info if you already know or don’t care (support intentional banner blindness).

See pictures in https://github.com/eslint/eslint/issues/5774#issuecomment-208396092

Proposed **plan** is 3 stages. Suggest stage 1 in one update version of ESLint, 2 in the next version. 3 might or might not be in the same version as 2 (see below).

1. 18 removed rules are the warm-up exercise:
    * Make the sentences consistent in wording (they are already similar).
    * Display the **X** glyphicon for visual similarity with wrench icon at left of sentence in fixable rules.
    * Update the description in the main heading and move the rule identifier to the beginning (for similarity with the rules index). Depends on a change in **Makefile.js** to match identifier + “: “ at the beginning in addition to identifier enclosed in parentheses at the end of the heading.
    * Reorganize the **Removed** section in the rules index page as a two-column table of Removed and Replaced by. Just the rule identifiers: no rule description, nor wrench icon for fixable rules.

2. 212 active rules (of which 43 are recommended) in about 5 batches:
    * Update the description in the main heading and move the rule identifier to the beginning (for similarity with the rules index).
    * Add the recommended sentence which has the **check mark** glyphicon for visual similarity with the rules index page and wrench icon at left of sentence in fixable rules.
    * Update or delete the few remaining links from active rules to removed rules.
    * When there are no open pull requests for new rules whose docs have headings in the original format, remove from **Makefile.js** the regexp to match identifier enclosed in parentheses at the end.

3. rules index page:
    * Reorganize the active sections as three-column tables of recommended icon, fixable icon, rule identifier link + “: “ + rule description. [Am glad for advice from @ilyavolodin whether to do an initial reorganization, and then automate the index generation later; or wait until it is time to automate it]

**Comment by nzakas** [comment]
@pedrottimark all sounds great to me!

What I'd like to get to eventually is to have the rule documentation title, fixable sentence, recommended sentence, and removed sentence automatically added at build time (so people don't have to manually copy those everywhere). We can get the data from the `meta` info for each rule and just insert it when we do a build.

That's not really a blocker for your suggestions, just wanted to give you a peak into what I'm thinking.

In any event, I trust your instincts the plan looks good to me.

**Comment by pedrottimark** [comment]
@nzakas Agree with the goal to automate. I will start with manual changes for stage 1 and brain storm with @ilyavolodin and @vitorbal about stages 2 and 3.

**Comment by ilyavolodin** [comment]
@pedrottimark Metadata updates have been completed, I think we should automate index page first and then restructure the presentation (or do both at the same time).

**Comment by pedrottimark** [comment]
@ilyavolodin Yes good, let’s automate the rules index first as lists, and then restructure as tables later as simple change.

Exception to that is I will submit a pull request tonight to restructure the **Removed** section which we cannot build from rule meta data as pictured in https://github.com/eslint/eslint.github.io/pull/234#issuecomment-207544703

**Comment by ilyavolodin** [comment]
:+1: Totally forgot about removed rules. Thanks for the reminder. But that will just be added to a template that we use to generate index.

**Comment by pedrottimark** [comment]
Yes, just submitted #6091 so you will have stable content for the template.

**Comment by pedrottimark** [comment]
Comment to remind us of another exception for removed rules to our automation goal: probably not able to prepend to their doc the main heading, removed paragraph, nor fixable paragraph.

Just as well that we plan not to remove any more for a year or more.

**Comment by nzakas** [comment]
We can probably do that by just leaving the removed rule docs. In general, I think the various paragraphs should be in the template and triggered by page front matter, like;

```
---
title: Rule
fixable: true
recommended: false
removed: true
---

Rule docs here
```

So for existing rules, we can create that front matter, and for removed rules we can just define it manually (maybe just store a data file with that info?).

**Comment by pedrottimark** [comment]
👍  So the eslint/eslint/docs/rule/*.md files will have consistent structure whether active or removed!

**Comment by pedrottimark** [comment]
The suggestion in https://github.com/eslint/eslint/issues/5774#issuecomment-217180683 has at least two benefits, if the metadata file for removed rules has a subset of the `meta` object in `module.exports` of rule files:

* Minimize differences between active and removed rules in future build code to prepend front matter to the doc files.

* Simplify the procedure to remove a rule (but not any time soon). One step would be copy-and-paste `meta.docs` and `meta.fixable` from the rule file to the metadata file.

**Comment by vitorbal** [comment]
This looks super interesting! I actually started a branch a while ago where I was playing around with how to generate the rules list using an `.md.ejs` template. A bit on hold while I work on the jscodeshift transform, but I'm willing to help out wherever needed once I'm done with that :)

**Comment by pedrottimark** [comment]
Discovered while prototyping: rule descriptions can contain backticks and removed / recommended / fixable paragraphs contain links, so **gensite** function in Makefile.js is where to use the metadata in markdown notation before processing by kramdown. It also keeps the new logic in JavaScript 😀

To avoid conflict with pull requests in progress, it can ignore obsolete manually edited lines.

@nzakas Because a markdown file without a main heading looks like an error, what do you think of a future guideline for rule doc files in eslint repo that main heading has **just rule id** as a placeholder?

@ilyavolodin @vitorbal What do you think about keeping **README.md** as the template for the rules index? Ignore any existing list items now, delete them later, and insert the items or rows in gensite.

If possible, I will make a pull request with a proof of concept for your critique next week. The processing in gensite will become more **line-by-line** than whole-text-replacement. And it will not hurt my feelings if the way to move forward is for someone else to take it over, or even start from fresh.

**Comment by nzakas** [comment]
@pedrottimark a heading with the rule ID should be okay. I wouldn't want to make it more complicated than that because it would further complicate the build process.

**Comment by pedrottimark** [comment]
@ilyavolodin @vitorbal What do you think about this example property in a file containing metadata for removed rules to automatically generate:
* Removed section at the end of the rules index
* main heading and iconized sentences in rule docs (removed) / was (recommended) / was (fixable)

```js
module.exports = {
    "no-wrap-func": {
        docs: {
            description: "disallow unnecessary parentheses around function expressions",
            removedSupplementaryInfo: "The `"\functions\"` option in the new rule is equivalent to the removed rule.",
            category: "Stylistic Issues",
            recommended: true
        },

        schema: []
    }
};
```

* The main idea is when a rule is removed (if ever again ;) to copy-and-paste the meta object.
* What do you think about JavaScript vs JSON. JSON means paste, and then quote props.
* Where would you put this file in the file structure of the eslint repo? For example, replacements.json is in the conf directory
* What do you think about the optional `removedSupplementaryInfo` prop in the `docs` object for the extra sentence in global-strict, no-wrap-func, and space-before-function-parentheses?

**Comment by ilyavolodin** [comment]
I think I would make it a lot more verbose:
```
docs: {
  deprecated: 'Wed May 18 2016 16:16:01 GMT-0400 (EDT)`,
  replacedBy: ['no-confusing-arrow', 'no-constant-condition'],
  deprecationInfo: "Some text describing why the rule was removed"
}
```

**Comment by vitorbal** [comment]
@pedrottimark I think keeping the **README.md** as the template sounds okay. I was actually trying to achieve this by having it renamed to *README.md.ejs* and passing it through EJS, like we do for `templates/blogpost.md.ejs` at the moment.

with regards to the new `docs` fields, I like @ilyavolodin suggestion, in that case `deprecationInfo` would also cover the extra sentence needed for `global-strict`, `no-wrap-func` and `space-before-function-parentheses`, like you mentioned.

with regards to where to put the file, maybe `conf/deprecated.json` would be nice, to keep it in the same directory as `replacements.json`?

Let me know if you need help with anything!

**Comment by nzakas** [comment]
Can't we simplify this info?

```
docs: {
  replacedBy: ['no-confusing-arrow', 'no-constant-condition'],
  deprecated: "Some text describing why the rule was removed"
}
```

I don't think the date is useful or practical for this purpose (manually including dates is notoriously inaccurate). Since no further changes so be made to the file, you can just look at the last commit with a change to this file to get the date when necessary.

**Comment by pedrottimark** [comment]
In https://github.com/eslint/eslint/issues/5774#issuecomment-220136972, I omitted the following information because it is already available:

* ./conf/replacements.json has the **Replaced by** rules
* ./versions.json has ESLint version in which rule was added and removed

**Comment by nzakas** [comment]
I think `replacements.json` is only updated when a rule is removed, so the info is best kept in a deprecated rule until that point.

**Comment by platinumazure** [comment]
@nzakas The reason I suggested a datetime is because we could actually handle expirations in that way. (I don't think we need a deprecation datetime, but rather an expiration datetime.) That way, we could note in the documentation when we plan on removing a rule. (Presumably that would be a year out from deprecation, per the other discussion on rule deprecation/removal.) But perhaps that's not as useful in your mind as I think it might be?

**Comment by pedrottimark** [comment]
Any thoughts whether it communicates or confuses in the doc for a removed rule:
* To display recommended icon if the rule was recommended at the time it was removed. If yes, I will verify that the 3 I think might have been really were.
* To display recommended (if yes to above) and fixable icons in gray to reinforce past tense “enabled” and “fixed” in the sentences.

<img width="1024" alt="5774 removed rule gray icons" src="https://cloud.githubusercontent.com/assets/11862657/15483930/6aa04588-2105-11e6-99ff-1c7287ef7b7e.png">

**Comment by nzakas** [comment]
@platinumazure as I mentioned, we can get the date time from the git log whenever we want. I'd prefer not relying on human-provided dates, which can easily be mistyped or otherwise incorrect. 

@pedrottimark if a rule was removed, then i think we shouldn't show anything about it being recommended.

**Comment by wkurniawan07** [comment]
Hello! I'm a newbie and would like to work on this issue, is it still open? 🙂

**Comment by platinumazure** [comment]
@wkurniawan07 I see that we don't show any "recommended" info on individual rule pages, but we do show "fixable" info on individual rule pages. I think this is probably valid, unless the team decides we don't want it.

@eslint/eslint-team Do we want to augment the single-rule documentation template to show "recommended" similar to how we show "fixable" (with an icon and a small paragraph of text)? If not, should we close this issue?

**Comment by wkurniawan07** [comment]
Thanks for the amazingly quick response!

The plan I have in mind is not to manually add the said line to each of the recommended rule, but rather to read the rule metadata and determine if the rule is recommended or not, and automatically append the said line during the docs generation process if the rule is indeed recommended. If the team decides that "recommended" may not be necessary, at least "fixable" will benefit the same from the proposed enhancement.

I have scanned through the docs generation process and have high confidence that it is possible. 🙂

**Comment by platinumazure** [comment]
@wkurniawan07 Ah, now I see what you mean. Yes, it would be nice to be able to autogenerate that if possible.

Maybe you could open a PR against eslint.github.io with your thoughts on how it could be done? (If it won't take a lot of time, I mean.)

**Comment by wkurniawan07** [comment]
@platinumazure the change to be done will involve [this file](https://github.com/eslint/eslint/blob/master/Makefile.js), so I believe this repository is the right place to put my work on. I will explore and report back either with a PR or a white flag 🏳️ by this weekend. 🙂

**Comment by ilyavolodin** [comment]
@wkurniawan07 That's correct. The change should be done in this repository. I'm 👍 for adding both fixable and recommended to docs generation if that can be done easily. I think it should be possible since we always add "fixable" to the third line in the file.

**Comment by wkurniawan07** [comment]
@platinumazure @ilyavolodin sorry for an update later than promised! Everything's going well, a PR can be expected within one hour or two. 🙂

**Comment by wkurniawan07** [comment]
Hmmm I hit something. There are rules that are marked as "The `--fix` option on the [command line](../user-guide/command-line-interface#fix) automatically fixes **some instances of** problems reported by this rule". How should I go about treating this class of rule?

**Comment by not-an-aardvark** [comment]
@wkurniawan07 I think it would be fine to just use the same text for all autofixable rules. Actually, a significant number of autofixable rules have edge-cases where they decline to fix a problem (not just the two rules that use the "some instances of problems" message).

**Comment by ilyavolodin** [comment]
Agree. We should use the same message everywhere. If we don't think that message is clear enough, we can always tweak it, since it's going to be a single line change.
