### ISSUE TITLE
Can't install eslint

### ISSUE THREAD

**Issue by mperham** [eslint/eslint#5833]
I followed the install instructions: `npm install -g eslint` and then this:

```
$ eslint --init
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Standard
? What format do you want your config file to be in? JavaScript
Installing eslint-plugin-standard, eslint-config-standard
@mperham/sidekiq@0.5.0 /Users/mike/src/sjs
├── UNMET PEER DEPENDENCY eslint@^2.0.0-rc.0
├── eslint-config-standard@5.1.0 
├── UNMET PEER DEPENDENCY eslint-plugin-promise@^1.0.8
├── eslint-plugin-standard@1.3.2 
└── sidekiq@1.1.1  extraneous

npm WARN eslint-config-standard@5.1.0 requires a peer of eslint@^2.0.0-rc.0 but none was installed.
npm WARN eslint-config-standard@5.1.0 requires a peer of eslint-plugin-promise@^1.0.8 but none was installed.
npm WARN @mperham/sidekiq@0.5.0 No repository field.
```

Running `eslint lib`  gives this:

```
$ eslint lib

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-standard". This can happen for a couple different reasons:
[snip]
```

I'm new to the JavaScript world - please let me know if you need more info.

**Comment by platinumazure** [comment]
Can you please include the generated `.eslintrc.js` file (or similar name), as well as the output of running `npm ls` on the shell in your project root directory? Thanks!

**Comment by mperham** [comment]
```
$ more .eslintrc.js 
module.exports = {
    "extends": "standard",
    "plugins": [
        "standard"
    ]
};

$ npm ls
@mperham/sidekiq@0.5.0 /Users/mike/src/sjs
├── UNMET PEER DEPENDENCY eslint@^2.0.0-rc.0
├── eslint-config-standard@5.1.0
├── UNMET PEER DEPENDENCY eslint-plugin-promise@^1.0.8
├── eslint-plugin-standard@1.3.2
├── generic-pool@2.4.1
├─┬ ioredis@1.15.1 invalid
│ ├── bluebird@2.10.2
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── double-ended-queue@2.1.0-0
│ ├── flexbuffer@0.0.6
│ └── lodash@3.10.1
├── minimist@1.2.0 invalid
└── sidekiq@1.1.1 extraneous

npm ERR! peer dep missing: eslint@^2.0.0-rc.0, required by eslint-config-standard@5.1.0
npm ERR! peer dep missing: eslint-plugin-promise@^1.0.8, required by eslint-config-standard@5.1.0
npm ERR! invalid: ioredis@1.15.1 /Users/mike/src/sjs/node_modules/ioredis
npm ERR! invalid: minimist@1.2.0 /Users/mike/src/sjs/node_modules/minimist
npm ERR! extraneous: sidekiq@1.1.1 /Users/mike/src/sjs/node_modules/sidekiq
```

**Comment by alberto** [comment]
I think you may need to install `eslint` locally.

**Comment by btmills** [comment]
@IanVS if ESLint is installed globally, should `--init` check and also install plugins globally and forego `--save-dev`? I can see reasons why it should always install locally, so the current behavior may be intentional. We also might be getting into an issue of transitive plugin dependencies with `eslint-plugin-promise`.

**Comment by IanVS** [comment]
Ergh, sometimes I wish we could disable global installs of eslint altogether, for all the confusion it causes.

I tend to think it would be a bad thing to install plugins globally during `--init`, as even more than ESLint itself they will vary from project to project.  But, I'm not sure the right way to approach this.  Maybe we can try to detect if `--init` was run from a global installation, and if so disable the `Use a popular style guide` option?  Or warn immediately and disable `--init` altogether?  I'm definitely open to ideas and discussion on this one.

**Comment by btmills** [comment]
> sometimes I wish we could disable global installs of eslint altogether, for all the confusion it causes.

Hear, hear!

> I tend to think it would be a bad thing to install plugins globally during --init, as even more than ESLint itself they will vary from project to project.

I agree. For example, running `eslint --init` in one project could potentially clobber another project's build. Can we encourage local installs and discourage global usage? I don't think we can warn and immediately disable since that would be a breaking change, but perhaps a "proceed at your own risk" warning? Something like

> Using --init from globally-installed ESLint is not recommended and could lead to unexpected behavior with plugins and shareable configs.

**Comment by nzakas** [comment]
Some editor plugins rely on global installation, so we can't really disable it. 

The problem here is that `--init` is installing `standard` locally, which has a peer dependency on ESLint. ESLint isn't installed locally, so npm is warning to install it. I think the only real action needed here is to make `--init` install ESLint locally if it's missing.

**Comment by IanVS** [comment]
Oooo, I like that idea. That will also mitigate the global usage of eslint
as well.

**Comment by ilyavolodin** [comment]
Hmm.. how would that help? If they used global instance of ESLint to run init, even if you install local copy, it's doubtful they will start using local version. They might not even be aware that it was installed. Although, I guess, since we change plugins to start resolving based on the location of the config file, it will fix immediate issue of not finding plugin.

**Comment by nzakas** [comment]
@ilyavolodin it helps complete the installation without error. It probably makes sense for us to also outputva message letting the user know that we installed ESLint locally for them and suggest that they use that instead of the globally installed version.

**Comment by kaicataldo** [comment]
I can try to find some time to look at this - interested in learning how `--init` works!

**Comment by kaicataldo** [comment]
Have a fix for this, but still have to figure out how to test it. How is the wording for the error messages?

**Comment by kaicataldo** [comment]
With the changes in my branch, the installation would remain unchanged if ESLint is installed locally, but will look like the following when it isn't:
Pre-installation:
<img width="564" alt="screen shot 2016-04-15 at 12 04 50 am" src="https://cloud.githubusercontent.com/assets/7041728/14551194/d628ad26-029d-11e6-8f51-32ee941acc7f.png">
Post-installation:
<img width="873" alt="screen shot 2016-04-15 at 12 05 03 am" src="https://cloud.githubusercontent.com/assets/7041728/14551196/d96763ce-029d-11e6-8dcb-2d9ee9abdb82.png">

**Comment by nzakas** [comment]
I think maybe, "ESLint was installed locally. We recommend using this local copy instead of your globally-installed copy."?

**Comment by zxqfox** [comment]
> Some editor plugins rely on global installation, so we can't really disable it.

Guess the best here to have an `eslint-cli` module as a tiny runner for `eslint` (with pwd changing, etc) and to disable global installation of `eslint`.

**Comment by nzakas** [comment]
@zxqfox that already exists: https://www.npmjs.com/package/eslint-cli. We don't really want to disable global installs due to some editors using it.

**Comment by kaicataldo** [comment]
PR opened

**Comment by alberto** [comment]
@nzakas do you think we should move that into our org and officially recommend it as the preferred install method?

Also, do we know which editors use global installs?

**Comment by kaicataldo** [comment]
The accepted change in this issue seems like a good start to me, but it would be nice to try to make the onboarding process/docs for getting started clearer (local vs global installations, using `eslint-cli`, et al). Ideas have been brought up in a few different places, so in an effort to streamline and consolidate the discussion I've made another issue here: https://github.com/eslint/eslint/issues/5874

**Comment by jasonxia23** [comment]
I find my problem is a incorrect version eslint package installed.
