### ISSUE TITLE
Naming convention: Visitors / event-handlers?

### ISSUE THREAD

**Issue by jfmengels** [eslint/eslint#5843]
This is not a bug report, just a discussion about documentation, or rather, naming. I was wondering what the name of the type of function associated with `Identifier` in the following example is.
```js
return {
  "Identifier": function(node) {}
};
```
I know that Babel uses the term [`Visitor`](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#toc-visitors), as related to the [visitor pattern](https://en.wikipedia.org/wiki/Visitor_pattern), but couldn't find a definitive, or explicit answer in the documentation.

I've been reminded that the term `visit` is used [at some point in the docs](http://eslint.org/docs/developer-guide/working-with-rules#rule-basics), and `events` [in some other place](http://eslint.org/docs/developer-guide/code-path-analysis/#events).

I personally like the term `visitor`, which is consistent with Babel (the use of visitors seems to have kind of the same purpose too). The term `event handler` speaks less to me.

I've asked the question in the Gitter chat, and been asked to create an issue, so that an explicit name could maybe get chosen, and reflected in the documentation.

(cc @pedrottimark @platinumazure)

Note: for context, I wanted to create a project that simplifies writing rules for some cases I encounter, and was therefore looking for an appropriate name.

**Comment by nzakas** [comment]
The instances you point to are two different things. `"Identifier"` is implementing the visitor pattern because it indicates a node type to visit in the tree. The code path analysis events are not the visitor pattern, they are event handlers that are triggered along the way. So even though it's a bit confusing, I think the terminology between these two is accurate as they are today.

**Comment by jfmengels** [comment]
Ah, yes, you're correct. So would it be right in your opinion to name `"Identifier"` a `Visitor`?

**Comment by nzakas** [comment]
Yup!

**Comment by jfmengels** [comment]
Thanks for the answer :)

**Comment by nzakas** [comment]
Didn't we just agree that the documentation is correct?

**Comment by jfmengels** [comment]
Right. I meant more like clarifying the documentation. I'll close this, someone can reopen it if needed.

**Comment by platinumazure** [comment]
Right now, we only inferred "Visitor" because there is one word `visit` buried in the middle of the third paragraph of that section. I don't think it would hurt to make it a bit more clear, but I have no concrete proposal at this time. Since documentation PRs don't require an issue, I think we can let this stay closed since @jfmengels has received an answer to the question raised.
