### ISSUE TITLE
Document transitioning from JSCS to ESLint

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#5859]
Once we have figured out all of the technical details to allow people to transition from JSCS to ESLint, we will need to document the process. My guess is that we'll need some documentation for transitioning both from JSCS 2.x and 3.x. The things we should cover:
1. How to convert `.jscsrc` into `.eslintrc`
2. The shareable configs that are the equivalent of JSCS presets
3. Any manual changes that need to be done in order to complete the conversion
4. An overview of how the user experience is different
5. Where to go for questions

This will clearly have to come last, just don't want to forget. :)

**Comment by Aladdin-ADD** [comment]
seems it can be closed -- #6942 was merged.

**Comment by platinumazure** [comment]
@Aladdin-ADD Looks like nzakas intentionally changed the commit to "ref" this issue instead of "fix" (close) it. So maybe nzakas thinks they're more to do. Unfortunately, with nzakas out of commission, we won't know for sure.

@eslint/eslint-tsc Any thoughts on whether we have anything to do here? Or should we close this?

**Comment by not-an-aardvark** [comment]
Based on https://github.com/eslint/eslint/pull/6942#issuecomment-242155764, my guess is that it was changed to "refs" because there is some more work to do with the guide. However, I'm unsure what that work is. If we're not sure about specific action items, I think we can close this and possibly improve the guide later.

**Comment by not-an-aardvark** [comment]
Closing this issue since no one has proposed any future work on it.
