### ISSUE TITLE
`/* eslint-warn */`

### ISSUE THREAD

**Issue by pillowfication** [eslint/eslint#5901]
I'm looking for functionality similar to

```javascript
/* eslint-disable */
{Code stuff goes here}
/* eslint-enable */
```

where instead of ignoring all linting errors that appear in the code block, ESLint will mark them all as warnings.

```javascript
/* eslint-warn */
{Code stuff goes here}
/* eslint-enable */
```

This way I can see exactly which errors I am ignoring.

**Comment by ilyavolodin** [comment]
You can sort of do this with `/* eslint rulename: 1 */`, however, this declaration is hoisted to the top of the file, and will make the rule warn on the whole file. Unfortunately, we wouldn't be able to add non-hoisted warn comment like that, due to the way rules are processed in the core.

Closing since this is not something we can do. Feel free to reopen if you have an idea on how to implement this.
