### ISSUE TITLE
Don't include whole lodash but require specific functions onle

### ISSUE THREAD

**Issue by pke** [eslint/eslint#5918]
Would be nice if not the whole `lodash` lib would be required whenever a small function out of it is used. The recommended way is to require only the functions `require('lodash/lib/func)`

**Comment by ilyavolodin** [comment]
We specifically converted from requiring specific functions to requiring the whole lodash. It was deemed to be faster, due to the fact that NPM caches packages, and it's much more likely that another package would require the whole lodash, rather then specific functions that we are using (and we are using good number of them).

**Comment by pke** [comment]
Ah ok. Don't know much about NPM caches. Just caring about runtime overhead.

**Comment by ilyavolodin** [comment]
When this change was introduced, we did performance testing on it, and there was no impact on run-time at all. We were also able to remove a bunch of other dependencies (including handlebars which is bigger then the whole lodash library).

**Comment by winniehell** [comment]
Pulling in 5MB for 14 functions is quite a lot—especially given that ESLint itself is half the size. :wink: 

I understand the reasoning though.
