### ISSUE TITLE
Chore: Use squash-merges instead of explicity merges for PRs

### ISSUE THREAD

**Issue by BYK** [eslint/eslint#5935]
GitHub now supports squash-merges instead of the traditional explicit merge model. This allows us to have a linear and easier to follow Git history at the expense of some lost information of how patches shaped when they were being developed on. That said this information is still captured in GitHub's pull requests so the proposal is to turn this feature on.

**Comment by alberto** [comment]
What information is lost?

One thing that could be problematic is that by allowing editing the commit message of the PR, it could cause invalid messages to get in.

**Comment by BYK** [comment]
@alberto actually, thinking again, since we require single commits in PRs there's no information being lost.

**Comment by nzakas** [comment]
I'm 👍 For this. The squash command also automatically appends the PR number to the message, which is nice. 

Some other things to consider:

1. We can fix minor commit message issues ourselves rather than waiting for people to update PRs
2. We could actually remove the commit number check from the bot since we can squash automatically. Something to consider.

**Comment by btmills** [comment]
:+1: from me as well. There's the theoretical possibility that someone with commit access could typo a new commit message when merging a PR and the invalid message wouldn't be flagged by the bot, but I can think of no real disadvantages. In addition to the advantages already listed:

1. Easier to see at a glance who authored a commit (we have this already) *and* who merged it (merge commits aren't always adjacent - sometimes it's easier to visit the PR).
2. Cleaner, easier to scan history.

**Comment by hzoo** [comment]
👍 from me, exactly the same points about merging instead of waiting on commit message fixes and including PR # automatically - so less merge commits.

**Comment by gyandeeps** [comment]
I am :+1: for this.

**Comment by alberto** [comment]
👍

**Comment by ilyavolodin** [comment]
👍

**Comment by zxqfox** [comment]
👍

**Comment by nzakas** [comment]
Okay, I think that's quorum. I've setup the repo to only allow squash commits going forward. As part of this, I think we should also:

1. Remove the commit count check from the bot
1. Remove the commit message format check from Travis (since the bot can check that)

I'd like to keep the bot checking the commit message format so we can give people feedback, but I don't think we need to hold up merging PRs if only the commit message format needs to change. Instead, we can manually fix the message.

Am I missing any other tasks?

**Comment by platinumazure** [comment]
Sounds good. It would be awesome to get the bot to rerun on commit add/remove/change, though.

**Comment by nzakas** [comment]
@platinumazure already on it. Let's keep this issue focused on changes directly related to squashing.

**Comment by alberto** [comment]
The only minor annoyance I've found is now git can't track merged local branches and you must force delete them.

**Comment by mysticatea** [comment]
I'm just aware of GitHub's "squash and merge" removes GPG sign.

Before: https://github.com/eslint/eslint/pull/6083/commits/b4b93b3da63296931ead1022275288e4fe2afa97
After: https://github.com/eslint/eslint/commit/388d6f812d46f8ea255020d466d57c3c59b32cf2

**Comment by platinumazure** [comment]
@mysticatea I guess the squash is done by someone else, not using the original commits, so is that even something GitHub could fix?

**Comment by mysticatea** [comment]
Yeah, this is by squash's design. I don't oppose a use of "squash and merge" button.

**Comment by mysticatea** [comment]
`git branch --merged` command don't show me squash-merged branches.
Does anyone know a way to show squash-merged branches for local branches?
