### ISSUE TITLE
Implement auto fix for `no-unused-labels`

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#5954]
Working on this.

**Comment by platinumazure** [comment]
(Cross-posted from PR since this is the better discussion venue)

I wonder... Do we really want to auto-fix this? What if a label is "unused" because the associated break/continue statement has a typographical error? Really the better "fix" would be to modify the incorrect break/continue statement, but trying to guess the correct label could be painful. But at any rate, I'm not sure this actually helps the user- this strikes me as one step forward, two steps back, in terms of user experience.

**Comment by alberto** [comment]
Closing since it could cause issues.
