### ISSUE TITLE
curly: Allow to filter affected keywords and pass keywords-exceptions

### ISSUE THREAD

**Issue by zxqfox** [eslint/eslint#5975]
JSCS has rules `disallowCurlyBraces` and `requireCurlyBraces` that allows to pass keywords: `["if", "else", "for", "while", "do", "try", "catch", "default"]`.

More over `requireCurlyBraces` has `allExcept` option that works like exception for passed keywords:

```
    - `'allExcept'`
        - Array of keywords inside of the block that would allow curly braces
        - Ex: ["return" , "continue", "break"]
```

E.g. for:

``` js
"allExcept": ["return", "continue", "break"]
```

it works like:

``` js
// Here we need curlies
if (true) {
  // Dummy
} else {
  // Another one
}

// And here we don't
if (true) return false;
else if (false) break;
else continue;
```

The current `curly` options and the first suggestion:

```
"curly": [2, "all"]
"curly": [2, "multi"]
"curly": [2, "multi-line"]
"curly": [2, "multi-or-nest"]
"curly": [2, "multi", "consistent"]
```

I suggest to pass an `Object` with keywords and exceptions as the last parameter:

```
"curly": [2, { "keywords": ["if", "else"], "except": ["return", "break"] }]
"curly": [2, "multi", { "keywords": … }]
// or even:
"curly": [2, { "schema": "multi", "consistent": true, "keywords": … }]
```

Related: https://github.com/eslint/eslint/issues/4007

**Comment by mysticatea** [comment]
Some ESLint's rules have `overrides` option: [keyword-spacing], [space-unary-ops], and [operator-linebreak].
So, how about the `overrides` option for consistency?

For example:

```js
{
    "curly": [2, {
        "type": "all",
        "overrides": {
            "if": {"type": "multi"}
        }
    }]
}
```

[keyword-spacing]: http://eslint.org/docs/rules/keyword-spacing
[space-unary-ops]: http://eslint.org/docs/rules/space-unary-ops
[operator-linebreak]: http://eslint.org/docs/rules/operator-linebreak

**Comment by kaicataldo** [comment]
I'm fine with `overrides` :+1:

**Comment by Moeriki** [comment]
I love the idea as brought by @zxqfox.

The override proposition by @mysticatea however doesn't exactly match the suggestion. The overrides take care of exempting the if-statement, and not the potentially nested `return`, `break`, or `continue` statement.

The main issue as I see it that this is very common code.

```js
function fileReader(filepath, callback) {
  fs.readFile('file', (err, result) => {
    if (err) return callback(err);
    result = someLogic(result);
    callback(null, result);
  });
}
```

I'd love to be able to disallow same-line ifs, while exempting return statements.

**Comment by cbargren** [comment]
I'd like to take a stab at implementing this!

I tend to agree with @Moeriki's point about missing out on some important cases with @mysticatea's suggestion, but it would be nice to be able to specify the behavior of overrides in any case. I'd suggest combining the two proposals to some extent into something like this:
```javascript
"curly": [2, {
  "type": "multi",
  "overrides": {
    "type": "all",
    "keywords": ["if", "else"],
    "except": ["return", "continue", "break"]
  }
}],
```

```javascript
function foo() {
  // We don't need curlies here because `while` is not an overridden keyword
  while (a < 5) a++;

  // We need it here because `if` is overridden and not excepted
  if (a === 5) {
    a++;
  }
  // We don't need it here because `else` is overridden, but `return` is excepted
  else return true;
}
```

One thing to note is that I can't really think of a time when you'd want to have an exception in place for `return`s, but not `continue`s, etc. With that in mind, it might make sense to simplify that setting into just a boolean property that applies to all three control keywords (something like `exceptControlKeywords`, maybe?). If anyone has a counterexample on that, I'd be happy to backpedal on that suggestion, though.

Let me know if anyone can think of any edge cases I'd be missing with this implementation. Otherwise, I'll probably get started on this tonight or tomorrow.

**Comment by not-an-aardvark** [comment]
I don't think we should use a list of keywords for `except`, because it seems limiting to do that -- a user could have a preference relating to the body that isn't specific to `return`, `break`, or `continue`.

Now that we support [selectors](http://eslint.org/docs/developer-guide/selectors) in core, I think it would be better to configure the rule by letting the user specify selectors that match the body, rather than having a hardcoded list of allowed keywords. That way we could make the configuration very powerful, and we wouldn't have to worry about supporting any other preferences the user might have.

```js
curly: ['error', {
  type: 'multi',
  overrides: [
    {
      selector: 'IfStatement > ReturnStatement.consequent',
      type: 'multi'
    }
  ]
}]
```

**Comment by kaicataldo** [comment]
@eslint/eslint-team Thoughts on the proposal to use selectors? I'm :+1: as it makes the rule very flexible.

**Comment by platinumazure** [comment]
:+1: from me, assuming we come up with a user-friendly design in that regard.

**Comment by kaicataldo** [comment]
@platinumazure Are you imagining something different than what @not-an-aardvark proposed?

**Comment by platinumazure** [comment]
Sorry, I missed the actual proposal. No, what he has seems fine- I would love some good examples in the rule docs when we implement though!

:+1: Let's do this!

**Comment by Aladdin-ADD** [comment]
I'm willing to implement this.

**Comment by nzakas** [comment]
@Aladdin-ADD do you still intend to implement this?

**Comment by Aladdin-ADD** [comment]
oops, I missed it, will do it in the following days.

**Comment by aladdin-add** [comment]
closing, as it has been inactivity for a while.
