### ISSUE TITLE
Multipass exits prematurely

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#5995]
There are a couple of situations which cause multipass fix to exit, leaving potentially autofixable errors unfixed:

```
* There are no more linting errors reported.
```
If we fix the last error, but doing that uncovers a new one, we won't try to autofix it, but just lint and report it.

```
* The number of linting errors is no different between two passes.
```
One simple example is when fixing a file with one error on the first pass the number of linting errors is 0, which is the same as in the previous passes. 
There are more contrived examples: during one pass we report 2 remaining errors, but there is a hidden one. A new pass will detect the 3 errors and fix one, and so the number of errors will remain the same.

Here is an example that satisfies both conditions for `space-infix-ops`:
```
true?"yes":"no";
```

Since we have limited the number of passes to 10, I think those guards are not really needed and we can remove them.

I have a PR ready if this is accepted.

**Comment by alberto** [comment]
@eslint/eslint-team opinions?

**Comment by mikesherov** [comment]
I think it's fair to say that there are always going to be situations where we won't be able to predict if we're approaching zero remaining autofixes or not. There are cases where number of remaining fixes actually increases instead of decreases.

I haven't looked deeply enough, but what seemed to be good enough for JSCS was counting the actual number of *fixable* issues that are left, rather than the total number of *unfixed* issues remaining. That is to say, that as long as the number of fixable is greater than zero, we should go to 10 passes.

But there's more to consider here, we can be even a bit smarter than that if we really wanted to have a good shot at limiting trashing and simultaneously fixing as much as possible. I'm not sure that it's worth the complexity, but here's a rough outline to poke holes in:

1. Perform all autofixes on the code in a single pass.
2. Note the number of autofixes made and the "source locations" of those fixes, which spans the token to the left of the fix and the right of the fix.
3. Perform another pass if 10 total passes hasn't been made, make autofixes.
4. Ensure at least one of the fixes occurred within the "source locations" of the previous pass. If so, goto 3, else stop.

This still might terminate early so maybe not worth it if we don't care about speed that much. Just thought I'd sketch a possible algo.

**Comment by nzakas** [comment]
> Since we have limited the number of passes to 10, I think those guards are not really needed and we can remove them.

I'm not sure I agree. Doing this would mean we always do 10 passes per file, which is pretty inefficient when most won't need that.

We can probably eliminate the check for the same number of messages -- that's fuzzy enough that it has questionable value. 

Beyond that, I'm not sure it makes sense to tweak this too much. There's no guarantee that we will fix everything that needs to be fixed, any cutoff at all introduces this possibility. 

I'd rather hold off on significant changes until we do a deeper look at auto-fixing as a whole.

**Comment by alberto** [comment]
> I'm not sure I agree. Doing this would mean we always do 10 passes per file, which is pretty inefficient when most won't need that.
Not really, it would exit after it has completed a pass with no fixes

**Comment by nzakas** [comment]
Oh I see, you're right. In that case, 👍

**Comment by mikesherov** [comment]
:+1:
