### ISSUE TITLE
Whether set value to 'false' in 'globals' is proper ?

### ISSUE THREAD

**Issue by yedaodao** [eslint/eslint#6002]
I'm using latest eslint with default parser.

If I develop a custom lib, and use an global variable, But I want to make the variable that it can only set once. If I set the variable to 'true', it can be written. If I set it to 'false', my custom lib can't be run. What can I do for this?

**Comment by ilyavolodin** [comment]
@yedaodao In JavaScript pretty much everything is writable (unless you use `Object.freeze`, etc.), so `false` doesn't really map to readable, it basically says that if you write to the variable, there is no guarantee that your value is going to be saved, so you shouldn't every write to it.
In your case, since what you are describing sounds like a singleton, you should still mark it as `true`, otherwise the code that writes to it once, is going to be marked as an error.
