### ISSUE TITLE
please don't release any new rules without an automatic fix if one is possible

### ISSUE THREAD

**Issue by jedwards1211** [eslint/eslint#6103]
Fighting with ESLint rules in projects that use strict configuration, like `eslint-config-airbnb`, especially stylistic rules, is becoming a big time-waster for developers contributing to open-source projects.  It's inhumane to force developers to fix ESLint errors like `quote-props` when `--fix` could hypothetically make the necessary changes itself.

*Life is short*.  We have better things to do than waste our time being extremely OCD about code formatting.

**Comment by alberto** [comment]
You are free to help us make eslint autofix better. Keep in mind we are also somewhat strict about contributions though ;)

**Comment by jedwards1211** [comment]
I didn't want these OCD stylistic rules.  I wouldn't have this problem if ESLint hadn't created them or released them without autofix.  I want everyone in this project to realize, you are affecting developers' quality of life with these kinds of decisions.

**Comment by jimbolla** [comment]
ESLint isn't forcing every project to use every rule. If you don't like a rule in your project, don't use it. If it's not your project, discuss the pros/cons of those rules with the project owners.

**Comment by jedwards1211** [comment]
The problem is that people come to prefer certain rulesets just because they've been popularized by organizations like Airbnb, and they don't listen when you try to discuss it with them.  It would be better for all of us in open source in the long run if ESLint would just fix these kinds of things automatically.

**Comment by jedwards1211** [comment]
At least please consider not releasing any more stylistic rules without autofixes?

**Comment by platinumazure** [comment]
@jedwards1211 Please note that even if you use a configuration popularized by a group, you can still override the rule config in your project in order to (for example) turn certain rules off.

For example:

```json
{
    "extends": "airbnb",
    "rules": {
        "object-curly-spacing": "off"
    }
}
```

The above config will use AirBNB's config, but also turn off `object-curly-spacing` if you don't agree with their settings. You can also override individual rules to leave them on but use different settings. Ultimately, your project's configuration is *your* responsibility :smile:

It sounds like you are frustrated about a few different things-- not only that some rules aren't auto-fixable, but also that some people have made decisions about rule configurations in popular plugins and shareable configs that you don't agree with. Please be more conscious about that fact and please don't throw everything at our feet.

Please bear in mind that we are all volunteers working on this project in our limited free time, and that there are only so many of us on the team and that we get a lot of issues. Right now, the highest priority of the project is JSCS compatibility, but that doesn't mean we don't welcome contributions in other areas. If you would like to help us get auto-fix into more stylistic rules, we would greatly appreciate your help.

**Comment by jedwards1211** [comment]
This usually comes up when I'm making PRs to *someone else's project*, and have to contend with their strict rules.

I am bringing this up here because ESLint maintainers could decide that enforcing purely stylistic rules without an autofix is inhumane, and avoid releasing such rules into the wild until they do have an autofix, and if they did, we would all have fewer hassles when working on other people's open-source projects.

**Comment by jedwards1211** [comment]
@platinumazure on the other hand, please consider ESLint's impact on programming culture.  Programmers already tend to be a bit OCD, but ESLint is turning into the greatest OCD-enabler of any programming tool I've ever seen.
