### ISSUE TITLE
compareFn for sorting fixes is buggy

### ISSUE THREAD

**Issue by kunalspathak** [eslint/eslint#6124]
**What version of ESLint are you using?**
v2.9.0

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**
NA

**What did you do? Please include the actual source code causing the issue.**
[compareFn](https://github.com/eslint/eslint/blob/master/lib/util/source-code-fixer.js#L87) that sorts the fixes to be applied is buggy for overlapping range. For input `[[4,10] 5,10]]` it sorts and returns `[[4,10],[5,10]]`, while for input `[[5,10],[4,10]]` it returns `[[5,10],[4,10]]` . [ES6 spec](https://tc39.github.io/ecma262/#sec-array.prototype.sort) says `Calling comparefn(a, b) always returns the same value v when given a specific pair of values a and b as its two arguments.`

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**
This breaks [source-code-fixer](https://github.com/eslint/eslint/blob/master/tests/lib/util/source-code-fixer.js#L273) unit test for `node+chakracore`.

**Comment by platinumazure** [comment]
Hmm. Since we're trying to apply fixes in reverse order of occurrence, I would say we should probably expand the logic to compare the range ends, then the range starts.

Something like

```js
var compareFn = function (a, b) {
    return (b[1] - a[1]) || (b[0] - a[0]);
});
```

@nzakas, do you have any thoughts on this? You probably know the logic surrounding the auto-fix implementation the best.

**Comment by kunalspathak** [comment]
Just FYI, I had gitter chat about this issue sometime back with @ilyavolodin and he is aware of this issue.

**Comment by ilyavolodin** [comment]
I think the problem is that we are comparing begging of range b with the end of range a. I get why we are doing it, but it doesn't seem to take into account overlapping ranges. In any case, sort function shouldn't care what's passed in first, and should always return the same result for same input independent of order it was in originally.
