### ISSUE TITLE
for (;;) should count as a constant condition

### ISSUE THREAD

**Issue by slikts** [eslint/eslint#6282]
`for (;;)` is functionally equivalent to a constant condition so it should be caught by the constant conditon rule.

eslint version: 2.8.0

**Comment by platinumazure** [comment]
Originally it was decided that since there was no actual explicit condition, it would not count as a constant condition. Additionally, until 2.11.0 (latest release), there was no other way to potentially allow infinite loops (such as in generators), so `for (;;)` was the only way it could be done. So I don't think we can consider this a bug.

I think we could certainly consider an enhancement request for this, perhaps a new option which warns on an empty ForStatement. Would that work for you?

**Comment by platinumazure** [comment]
One other possibility I could see is to remove the `for (;;)` exception by default, making it a flagged constant condition, now that we have the loop exception option. However, that would be a breaking change.

**Comment by slikts** [comment]
Sorry, which option is that? I wasn't able to find it.

`while (true)` is preferable to `for (;;)` because it's more explicit, but the latter is not completely implicit either, so it's kind of inconsistent that it's allowed and using it for generators just because of that is hacky. It'd be nice if there was a way to allow just infinite loops in generators.

**Comment by platinumazure** [comment]
@slikts The option is called [checkLoops](http://eslint.org/docs/rules/no-constant-condition#checkloops) and it was just added with our latest release :smile: It's all or nothing, though- any loop, whether in a generator or not.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
