### ISSUE TITLE
`no-control-regex` has unnecessary code

### ISSUE THREAD

**Issue by ljharb** [eslint/eslint#6438]
While investigating a fix for #6293, I discovered that the test in 141b778 continues to pass even without some of the rule code.

I'm filing this per https://github.com/eslint/eslint/pull/6437#issuecomment-226546798 so there's an issue matching the PR.

**Comment by ljharb** [comment]
Tagging @efegurkan just in case :-)

**Comment by ljharb** [comment]
@efegurkan ping - any update on this one?

**Comment by efegurkan** [comment]
@ljharb I didn't had enough time to work on it yet. But I'm guessing there is something wrong with test execution. I'll add details on here when I have time.

**Comment by efegurkan** [comment]
@ljharb I just sent a pull request to fix this. Sorry for blocking so long :disappointed: .

The problem was the tests as we guessed before. I was not checking literal's on tests instead I was checking literals on a string. Basically /\x01/.toString() is not equal to "/\x01".toString() .

As soon as 8ffb1f0 gets aprroved you will be safe to work on the fix for #6293. Sorry for delaying again.

**Comment by ljharb** [comment]
Linking to https://github.com/eslint/eslint/pull/6839
