### ISSUE TITLE
Include documentation for all rules in published tarball

### ISSUE THREAD

**Issue by SimenB** [eslint/eslint#6481]
**What version of ESLint are you using?**
2.13

**The problem**
When working offline, I would like to have access to the documentation for all rules

**The solution**
Include the docs for rules in the published tarball

**Comment by vitorbal** [comment]
I think this is a fair request. Did we choose to not include the docs folder in the published package for any reason other than saving file size?

**Comment by SimenB** [comment]
PR link for reference: #6480

**Comment by nzakas** [comment]
The reason we left it out is to minimize the download size. 

@SimenB can you provide the file size of our generated tarball right now and compare it to the size of the generated tarball if the docs are included? (You can run `npm pack` locally to generate the tarball.) 

If the difference isn't too big, we can consider this IMHO.

**Comment by SimenB** [comment]
Before: 319833, or 312K
After: 458276, or 448K

Bigger difference than I'd have thought! I personally don't see any problem with the size of the tarball as longs as the contents are useful (i.e., not tests and dotfiles), but I understand if you don't want to increase the size by over 40%

**Comment by TheSavior** [comment]
Another approach would be to provide the documentation in a format for Dash which is made for that purpose. https://kapeli.com/dash.

That is at least what I use for offline documentation for Node, React, Sinon, Chai, etc. It might make more sense than to add over 40% to every install of eslint for documentation a subset of the population would want a subset of the time.

**Comment by nzakas** [comment]
Wow, 100kb difference is pretty significant, so I don't think we can do this. We had complaints about the download size before, so I'm reluctant to add that much back to the package.

**Comment by platinumazure** [comment]
Is there a way to make it optional? For example, if npm differentiated between included files and included docs and npm install had an `--include-docs` flag? (They probably don't, but I'm just trying to think outside the box a little...)

**Comment by SimenB** [comment]
An option might be to add a package.json to `docs/rules` called e.g. `eslint-docs`, and publish it along with the base package as an `afterpublish` or something?

**Comment by puzrin** [comment]
I'd say, tarball compare does not count dependencies. And if you count all, then 100kb difference will not make sence.

Another alternative is adding proper manifest to eslint.org to make it as offline html5 app

**Comment by ilyavolodin** [comment]
While we do have a lot of dependencies, 100Kb is still a lot. I think making eslint.org work offline might be a good solution (although, not everything will work that way. Search, for example, will not).

**Comment by puzrin** [comment]
After thinking a bit... why not just clone repo for docs? What are reasons to consider docs from npm as more convenient way?

**Comment by SimenB** [comment]
Offline access, mostly. No need to do something extra if I wanna access it, as long as I have eslint installed, I have access to it

**Comment by puzrin** [comment]
I'd say, if/after adding docs to npm package, eslint will receive requests to remove it, because that's a bad practice and because that reduce size :) . So, possible solution IMHO are:

- clone repo (no changes needed)
- allow eslint.org to work offline (that worth to do anyway)

**Comment by nzakas** [comment]
@SimenB if you need to install a different package to get the docs, why not just clone the repo? It's still two steps.

**Comment by SimenB** [comment]
Fair point! Mostly to have in in package.json, but I suppose just doing `"eslint": "eslint/eslint#v2.13.1"` would achieve the same thing

**Comment by platinumazure** [comment]
I think having docs is a fair middle ground request in between a lean
code-only package and a heavy repo with docs and also tests. I don't know
how feasible a code + docs bundle (or docs-only bundle) might be, but I
don't think it would be fair to equate a request for doc inclusion and the
ability to clone the repository.
On Jun 21, 2016 3:01 PM, "Simen Bekkhus" <notifications@github.com> wrote:

Fair point! Mostly to have in in package.json, but I suppose just
doing "eslint":
"eslint/eslint#v2.13.1" would achieve the same thing

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/eslint/eslint/issues/6481#issuecomment-227554304>, or mute
the thread
<https://github.com/notifications/unsubscribe/AARWegynL_yXFT9gld12NWgxv53SotReks5qOEL8gaJpZM4I5iEJ>
.

**Comment by nzakas** [comment]
Here's where we are: I don't think we are going to add the docs into the package because it bloats the download size. So the desire to install ESLint and have docs just be there can't be fulfilled. The only other options available require at least two steps. 

The only remaining question is what makes sense as a second step? Cloning the repo is one you can do now without us changing anything. Adding a docs-only package is another, but that seems like a bunch of added complexity for little gain. Is there another option I'm not seeing?

**Comment by aubergine10** [comment]
sounds like lots of work for little gain, especially when github provides this:

![just use this](https://cloud.githubusercontent.com/assets/1386719/16278365/9ac96cb0-38ae-11e6-9772-6a1f36c902d2.png)

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like consensus couldn't be reached on this issue and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend never to reach consensus, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
