### ISSUE TITLE
Unambiguous ES module rule

### ISSUE THREAD

**Issue by jdalton** [eslint/eslint#6496]
Currently, Script and Module goals have a grammatical ambiguity where some code can run in both goals, having the exact same source text, but produce different results. Unlike `"use strict"`, the signal to have a specific behavior is not in the code, thus the code has a multitude of possible effects which are not controlled by the programmer.

Because of this I think a new rule for unambiguous ES modules would be nice.
It could even be enabled by default when `"parserOptions": { "sourceType": "module" }`. The rule would enforce that an ES module should have at least one `import` or `export` declaration.

\cc @mikesherov @ilyavolodin

**Comment by platinumazure** [comment]
Hi @jdalton, thanks for the issue.

Per our [philosophy](http://eslint.org/docs/about/#philosophy), I don't think we can consider a rule that would be "on by default". We can certainly consider providing a rule which users could turn on, which would do nothing if sourceType is script and which would otherwise warn on the Program node if there is no import or export.

I'd be more interested in having the parser support unambiguous modules, but historically we tend to favor established standards (or at least Stage 4 proposals) in espree and so I'm not sure that is going to fly either.

I don't have much sway in the project, though, so by all means feel free to convince bigger wigs when they join the conversation.

**Comment by jdalton** [comment]
Cool! The reason I suggested enabled-by-default is `sourceType` as `module` currently enables a handful of rules by default (`no-invalid-this`, `no-redeclare`, etc.) and the inherent benefits of unambiguous modules makes it a good default is all.

**Comment by platinumazure** [comment]
@jdalton That's news to me. If we have precedent, then that's all the better for you :smile:

**Comment by jdalton** [comment]
If that's not the case it's cool too. Having it "recommended" and "fixable" would rock :metal:

**Comment by platinumazure** [comment]
@jdalton How would you auto-fix a module file that lacks imports/exports?

**Comment by jdalton** [comment]
If it didn't have at least an `import` or `export` declaration I'd simply add `export {}` which is the ES2015 way to explicitly specify exporting nothing.

**Comment by nzakas** [comment]
I'm personally 👎 as a core rule. Even though Node might one day use such syntax to figure out what mode to run in, there's not much value to enforcing this right now. I'd suggest just making the rule yourself in a plugin.

**Comment by jdalton** [comment]
This rule has benefits outside of Node (JSCS, TypeScript, Esprima, etc.), enforces a best practice, and is easily fixable, which makes it nice addition. I know @mikesherov can talk to some of the pros of it.

**Comment by platinumazure** [comment]
@jdalton Even if the final word is "no" on core, ESLint is super extensible and you can definitely implement this as a plugin and spam it to all of those projects. :smile: If you need help implementing the rule, stop by our [Gitter chat](https://gitter.im/eslint/eslint) and we'll definitely help out.

**Comment by nzakas** [comment]
@jdalton I'm sorry, you haven't made a good case for this rule, either explaining what it would do or why it should be in the core. Please review our [guidelines](http://eslint.org/docs/developer-guide/contributing/new-rules) and update this proposal accordingly. If you're claiming that this is already a best practice, then it would be great to see some evidence backing that up. So far, the only thing I can find is [your Node.js proposal](https://github.com/bmeck/UnambiguousJavaScriptGrammar).

And to reiterate: I feel like it is too soon to do something like this. I understand that you're excited about your proposal, but ESLint doesn't take positions on things that are still being debated. That's why I think the best way for you to support your proposal is to make your own plugin with the rule. If/when we reach a point where there is some general agreement in the community on the path forward, we can always look at incorporating such a rule. (To me, this feels very much like asking ESLint to automatically grep for `*.mjs` even though that's still in proposal form.)

**Comment by jdalton** [comment]
Thanks for the feedback @nzakas!

>  I'm sorry, you haven't made a good case for this rule, either explaining what it would do or why it should be in the core. 

The rule is simple. It would require that at source text has at least one `import` or `export` declaration. The fixable option could have it simply add `export {}` when no `import` or `export` declarations are detected. This rule would fit well with the `sourceType` of `module`. As outlined in [my first comment](https://github.com/eslint/eslint/issues/6496#issue-161486093) having ambiguous source can lead to unintentional behavior / side effects.

>  If you're claiming that this is already a best practice, then it would be great to see some evidence backing that up. 

It's a best practice in that it's a way to avoid executing code outside the context it was intended for. I see it as a companion to `strict` rules.

> And to reiterate: I feel like it is too soon to do something like this. I understand that you're excited about your proposal, but ESLint doesn't take positions on things that are still being debated.

As mentioned this holds value outside of any proposal.

Plugins are great, and of course I'll pursue that, but I think this rule hold enough merit on its own to be included in core. Which is why I've opened this issue.

**Comment by mikesherov** [comment]
I do think this could become a core rule but I'd like to see the results of the TC39 meeting coming up where UJG will be discussed.

I echo @nzakas's concern of ESLint not being in the business of trying to be king maker. TC39 comes soon, will be glad to rediscus after that.

**Comment by nzakas** [comment]
I'm happy to leave this open until after the TC39 meeting and revisit then. My concern is that the rule doesn't bestow much benefit on its own without some sort of standardization (ESLint users already say "this is a module", so we don't need to guess, and it's unlikely that we'd ever change that).

In either case, @jdalton, we ask people who submit rule proposals to also implement them if accepted. So the best path forward for you is to start working on the rule. If the approach becomes standardized, we can talk about it as a core rule, and if not, you'll be able to release it as a plugin.

**Comment by jdalton** [comment]
Word. I expect at the very least a stance on Node's approach to come out of the TC39 meeting.

**Comment by alberto** [comment]
What's the status of this? Has the meeting already taken place?

**Comment by jdalton** [comment]
The proposal progressed to the [node-eps](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#51-determining-if-source-is-an-es-module) in early July. We decided to hold off bringing it up to the TC39 in July to give us time to get our feet wet (get a feel for the TC39, since it was Bradley's first time representing Node).

Out of the meeting it looks like there is no compat path available to Node for ES modules. Due to complications with top level async await. This means introducing an async module loader API, like `import`. While unambiguous grammar is still desirable it would no longer be a hard requirement as ES modules would be loaded with the `import` method. Things are still cooking.

**Comment by mysticatea** [comment]
As far as I know, that is a stage 0 proposal now.

**Comment by nzakas** [comment]
Okay, this reinforces my belief that it's too soon to consider this for the core. It's now past our 21-day period to accept issues, so I'm closing. If the unambiguous module syntax reaches standardization and/or implementation, please open another issue and we can consider it again. In the meantime, a custom rule would be your best approach.

**Comment by jdalton** [comment]
Thanks @nzakas. For those interested the `unambiguous` rule has been added to v2 of [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/tree/v2).
