### ISSUE TITLE
Data URI is not included in ignoreUrls option of max-len

### ISSUE THREAD

**Issue by vsemozhetbyt** [eslint/eslint#6638]
**What version of ESLint are you using?**

3.0.1

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

`max-len: [2, 100, 2, { ignoreUrls: true, ignoreComments: false }]`

**What did you do? Please include the actual source code causing the issue.**
```js
const throbber = 'data:image/gif;base64,R0lGODlhEAAQAOMIAAAAABoaGjMzM0xMTGZmZoCAgJmZmbKysv///////////////////////////////yH/C05FVFNDQVBFMi4wAwEAAAAh+QQBCgAIACwAAAAAEAAQAAAESBDJiQCgmFqbZwjVhhwH9n3hSJbeSa1sm5GUIHSTYSC2jeu63q0D3PlwCB1lMMgUChgmk/J8LqUIAgFRhV6z2q0VF94iJ9pOBAAh+QQBCgAPACwAAAAAEAAQAAAESPDJ+UKgmFqbpxDV9gAA9n3hSJbeSa1sm5HUMHTTcTy2jeu63q0D3PlwDx2FQMgYDBgmk/J8LqWPQuFRhV6z2q0VF94iJ9pOBAAh+QQBCgAPACwAAAAAEAAQAAAESPDJ+YSgmFqb5xjV9gQB9n3hSJbeSa1sm5EUQXQTADy2jeu63q0D3PlwDx2lUMgcDhgmk/J8LqUPg+FRhV6z2q0VF94iJ9pOBAAh+QQBCgAPACwAAAAAEAAQAAAESPDJ+cagmFqbJyHV9ggC9n3hSJbeSa1sm5FUUXRTEDy2jeu63q0D3PlwDx3FYMgAABgmk/J8LqWPw+FRhV6z2q0VF94iJ9pOBAAh+QQBCgAPACwAAAAAEAAQAAAESPDJ+QihmFqbZynV9gwD9n3hSJbeSa1sm5GUYXSTIDy2jeu63q0D3PlwDx3lcMgEAhgmk/J8LqUPAOBRhV6z2q0VF94iJ9pOBAAh+QQBCgAPACwAAAAAEAAQAAAESPDJ+UqhmFqbpzHV9hAE9n3hSJbeSa1sm5HUcXTTMDy2jeu63q0D3PlwDx0FAMgIBBgmk/J8LqWPQOBRhV6z2q0VF94iJ9pOBAAh+QQBCgAPACwAAAAAEAAQAAAESPDJ+YyhmFqb5znV9hQF9n3hSJbeSa1sm5EUAHQTQTy2jeu63q0D3PlwDx0lEMgMBhgmk/J8LqUPgeBRhV6z2q0VF94iJ9pOBAAh+QQBCgAPACwAAAAAEAAQAAAESPDJ+c6hmFqbJwDV9hgG9n3hSJbeSa1sm5FUEHRTUTy2jeu63q0D3PlwDx1FIMgQCBgmk/J8LqWPweBRhV6z2q0VF94iJ9pOBAA7';
```
**What did you expect to happen?**

No warning for Data URI

**What actually happened? Please include the actual, raw output from ESLint.**

 `N:1 error Line N exceeds the maximum line length of 100 max-len`

**Comment by vitorbal** [comment]
hi @vsemozhetbyt, thanks for the issue!

It looks like according to [this section of the code](https://github.com/eslint/eslint/blob/master/lib/rules/max-len.js#L74-L82) the regex that matches URLs doesn't match all URIs on purpose to avoid false positives. I'm guessing we would need a separate regex that checks for data URIs specifically.

Also, since the name of the option is `ignoreUr*L*s` and not `ignoreUr*i*s` I don't think we should consider this a bug, but a rule enhancement. Maybe as a separate `ignoreDataUris` option?

I think you could also use the [ignorePattern](http://eslint.org/docs/rules/max-len#ignorepattern`) to achieve this, but in my opinion, this seems like a potentially worthwhile addition.

We can accept this issue once someone on the ESLint team champions it and three other people endorse the change (with no one voting against it).
Would you be willing to work on a PR for this if it gets accepted?

**Comment by vsemozhetbyt** [comment]
@vitorbal Thank you for the detailed answer. Unfortunately, I think I can't implement this in PR because of lack of experience. However, I would be glad about any enhancement Eslint team will add to the rule.

**Comment by nzakas** [comment]
@vsemozhetbyt in general, we ask the people reporting the issue to implement the change (see our [policy](http://eslint.org/docs/developer-guide/contributing/rule-changes)). We can guide you on how to make the change even if you've never worked on ESLint before. Otherwise, it's unlikely the change will be implemented. 

I agree that this is an enhancement request, and I'll give a 👍

**Comment by vsemozhetbyt** [comment]
@nzakas I see. I've tried to refuse because I am not a professional programmer (programming is just my hobby) and I am not a native English speaker (so I may make many mistakes in documenting). I did suppose it was a bug, I would not dare to suggest a new rule or addition to rule to implement it by myself. However, if alternative is "me or nobody", I may try. I'm just afraid that making a good regular expression for a large number of cases (protocol schema) may contain many challenges and unseen difficulties for such a newbie and may be I would make more mess than help.

**Comment by platinumazure** [comment]
I'm not sure I see the value in this enhancement given `ignorePattern`.

**Comment by alberto** [comment]
I'm with @platinumazure. Not sure this deserves its own special option

**Comment by vsemozhetbyt** [comment]
Well, it seems we have "against" votes, so I better close it.
