### ISSUE TITLE
Add fixer for strict

### ISSUE THREAD

**Issue by NickHeiner** [eslint/eslint#6668]
It may get tricky for some cases, but based on the config, it could be easy to apply a fix to insert `'use strict'` to solve a problem. I would be happy to send a PR for this if you'd accept it.

I'm using `eslint@3.0.1` and Node `v4.2.1`.

**Comment by platinumazure** [comment]
Presumably this could only be done in a small number of specific configurations. In order to help the discussion, can you please post some examples of when you think auto-fix could be applied and when you think it probably could not be applied? Thanks!

**Comment by mysticatea** [comment]
I think the fixing is:

- It should remove extra `"use strict"` directives (includes multiple). This is easy.
    - **Note:** if the next (or prev) statement is on the same line, it removes only the directive. Otherwise, it removes the whole line of the directive.
- It should insert a `"use strict"` directive for proper functions. This is easy.
    - **Note:** it uses double quotes since our `quotes` rule is enforcing double quotes by default. If people are using `quotes` rule with single quotes option, the 2nd iteration of the fixing will modify the inserted directives to single quotes.
    - **Note:** if a function has non-simple parameter list, it doesn't insert the directive.
- It should insert a `"use strict"` directive for globals.
    - **Note:** it uses double quotes
    - **Note:** if there is shebang (`#!/usr/bin/env node`), it inserts the directive below the shebang.
    - **Note:** if there is file header comment(s), it inserts the directive below the header comment(s). But I'm not sure this is feasible.

**Comment by NickHeiner** [comment]
I like those fixes.

> the 2nd iteration of the fixing will modify the inserted line ending.

Is this done automatically? Or do you mean that the user will manually run eslint with the fixer enabled multiple times?

**Comment by platinumazure** [comment]
Done automatically.

**Comment by nzakas** [comment]
Hmmm, we need to think about this. Previously we've said we wouldn't do fixes that changed logic because they can introduce runtime errors (and it's unexpected that a lint fix would cause a runtime error, that's why we don't fix `eqeqeq`). So I think the only thing we can safely fix is removing duplicate strict directives as that doesn't change runtime behavior. I don't think we should ever insert a strict directive.

**Comment by NickHeiner** [comment]
That makes sense. For my personal use case, I wouldn't mind a more aggressive approach, but I agree that in general, you don't want a fixer to possibly modify runtime behavior.

**Comment by nzakas** [comment]
I'll champion this for removing extra `"use strict"`, as I think that's helpful.

**Comment by nzakas** [comment]
@NickHeiner are you willing to submit a pull request for this?

**Comment by ilyavolodin** [comment]
👍

**Comment by NickHeiner** [comment]
Yep, I'll submit a PR. Out of curiosity, do you have a label other than "evaluating" you use if you've accepted the proposal?

**Comment by ilyavolodin** [comment]
@NickHeiner Yes, we have "accepted" label. We encourage people to wait until the issue is accepted, before submitting a PR, to avoid situation when we don't get consensus and have to close your PR. In order to mark an issue as accepted, we need a champion and 3 +1s from the core team. Right now we have champion (nazakas) and one +1, need to wait for 2 more before it's accepted.

**Comment by NickHeiner** [comment]
Ok, thanks for the clarification. So I will wait until I see that label before I start working on a PR.

**Comment by alberto** [comment]
👍

**Comment by mysticatea** [comment]
Hmmm, though I'm glad if it inserts `"use strict"` directive, I can understand that concern.

:+1:

**Comment by alberto** [comment]
@NickHeiner it's accepted now. Go for it! :)
