### ISSUE TITLE
Ignore files (`.eslintignore`) in parent folders _should_ be considered

### ISSUE THREAD

**Issue by moll** [eslint/eslint#6727]
Hey,

I know https://github.com/eslint/eslint/issues/5087 and other discussions have been about removing support for `.eslintignore` files in parent folders. I'd like to propose that be changed back. It's inconsistent with `.eslintrc`which _is_ "inherited", e.g. from the home folder, and inconsistent with how Git and other tools work. I often `cd` into folders to run commands and move files. Executing eslint there to see it recurse into nested folders' `node_modules` and `tmp`s or other folders I've explicitly ignored is annoying.

I use ESLint privately, that is, I don't wish to sprinkle more dot-files to each project's folder. Configuration files from the home folder are exactly for that.

**What version of ESLint are you using?**
v3.1.1

Thanks!

**Comment by vitorbal** [comment]
Hi @moll, thanks for reaching out. #5087 fixed a bug, `.eslintignore` was never supposed to have that behavior according to the docs and the discussion in that ticket. Because of that, I'll mark this as an `enhancement` suggestion.

I actually agree with you and think you have a valid point but I wonder if the decision for the current behavior was made due to performance reasons.
Hopefully we can get more feedback from the rest of the team when they see this issue, because I don't have enough experience in this area.

**Comment by moll** [comment]
Thanks.

An acceptable compromise would probably be to go upwards from the current directory during startup only. The common case, I presume, is people having either a project ignore file AND/OR one in the home directory. Merging them two would be a nice addition. Project-local, but nested ignores a rarer thing.

**Comment by alberto** [comment]
@moll doesn't `--config` solve your problem?

**Comment by moll** [comment]
As a workaround I _am_ using `--ignore-path ~/.eslintignore`, but I'm proposing the seek in parent directories were default behavior for reasons described above.

**Comment by platinumazure** [comment]
We can't allow for dynamic .eslintignores (i.e., multiple levels) because for performance reasons, we apply glob patterns and traverse directories once (linting as we go). So we can only work with one `.eslintignore` per lint run.

I do believe that we could hypothetically consider an option for looking in parent directories to *find* the one `.eslintignore` file that we could use, but with `--ignore-path` being a viable workaround option, it will be very hard to make a strong case for the necessity of looking in parent directories for `.eslintignore`.

**Comment by moll** [comment]
My argument was for consistency and user-friendliness. The arguments to and for should be identical to `.eslintrc`s in parent or home directories.

I don't understand the reasoning for performance, though. Mind clarifying? We're talking about a linear search up the tree from the current location (at minimum) and one extra comparison while doing directory listings for recursion. Compared to the thousand(s) of `stat` calls starting up ESLint causes, 4–5 for the ignore file parent search is negligible. To be honest, I can't imagine there being any measurable difference even in merging ignore files, unless the algorithm compiling/doing the path ignoring is exponentially poor. ;-)

**Comment by alberto** [comment]
Yes, sorry, I meant `--ignore-path`.

I am against this since:
- Ignore files are typically project specific, so I don't see this being benefitial to a lot of people.
- Making this the default option would be a breaking change, so I doubt we would do that. We would have to use some custom comment inside the file or add command-line flag.
- Parent lookup is not known to many people and catches them by surprise when eslint uses a file they didn't expect, so I don't agree with your user-friendliness point of view.
- If we ever wanted to do lookup inside the directory it could be problematic, since paths there would be relative to the directory they are in (like .gitignore), unlike this.
- There is a way to do what you want with `--ignore-path`.

**Comment by nzakas** [comment]
The decision was made because of the complexity involved with calculating ignore paths from multiple locations. The multiple`.eslintignire` support was actually a bug that wasn't even working correctly (so, there's nothing to "restore"). The ignore process is already complicated and we've had to completely rewrite it already. It's finally stable after a long time of instability, so I'm not in favor of a major change at this point. 

👎

**Comment by ilyavolodin** [comment]
I agree. Cascading ignore files has been removed from ESLint before version 1.0 and this is the first time I've seen somebody asking for this feature. Which tells me it's not a priority for vast majority of users.

**Comment by nzakas** [comment]
It seems like we have a consensus against adding this feature, so closing.

**Comment by jrsearles** [comment]
I wouldn't argue for any type of cascading functionality, but it does seem like it should traverse up and find the nearest `.eslintignore` file. All other ignore files (git, npm, etc) work in this fashion. 

I'd like to be able to run eslint from any directory within the project and have those settings honored. I just spent some time trying to figure out why the tool was taking forever to analyze my project when i realized that it wasn't using the ignore file. Now i know i have to run the tool from the root, but now i also need to inform all my team members of this quirk.

**Comment by platinumazure** [comment]
@jrsearles I don't think we can safely do even that until we resolve the questions in this issue: https://github.com/eslint/eslint/issues/6759

My advice would be to follow that issue, and if the proposed change is implemented, then open a new issue about traversing up (because then it will be clear whether the `.eslintignore` patterns should be interprested relative to the location of the `.eslintignore`, or relative to CWD.
