### ISSUE TITLE
Remove Node v5 from travis

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#6743]
Node v5 is in EOL since July 1st, so we can stop supporting it.

**Comment by nzakas** [comment]
One second, are you saying stop supporting or just stop testing? (These are two very different things.)

We can stop testing, but we do say we support Node 4 and higher, and we can't change that without a major release.

**Comment by nzakas** [comment]
I'm reverting this change after discussion with @ilyavolodin (who merged it). Because dropping a Node version requires a breaking change, that means the TSC needs to decide as a group. 

Even though Node 5 is EOL, we need to continue supporting it until we formally remove support in a major release. As such, we should continue to test until that time. 

Reopening this issue for more discussion.

**Comment by alberto** [comment]
Sorry, I missed your previous comment. I meant not actively supporting it, yes. I understood that from the node 4 issue. It made sense to me not supporting it beyond upstream, but I understand your concern. I also agree that if we are going to support it we should keep testing it.

**Comment by alberto** [comment]
> we do say we support Node 4 and higher
Where do we say that? We could also say we support any maintained node version >= 4.

**Comment by ljharb** [comment]
In general, official EOL of a platform in no way means that other things can stop supporting it - IE 10 is EOL but most websites still have to support it and will for years, for example.

**Comment by nzakas** [comment]
@alberto we made a big deal about it in our 3.0.0 release: http://eslint.org/blog/2016/07/eslint-v3.0.0-released

(We should probably also add that to the README.)

We can look at changing the policy going forward, we just need to have the TSC decide as a group on such changes since any change requires a major release.
