### ISSUE TITLE
builtin globals is defined using globals.es5 instead of globals.buitin.

### ISSUE THREAD

**Issue by othomann** [eslint/eslint#6936]
**What version of ESLint are you using?**
3.0.1, but this is still the case in master.

I wonder why the builtin globals is now set as globals.es5 instead of globals.builtin. It was done like that in past versions. Any reason this has been changed?

This is inside the file conf/environments.js.

Thanks.

**Comment by mysticatea** [comment]
ESLint parses code as ES5 by default.
If a user wants ES6, they need config `env: {es6: true}`.

**Comment by platinumazure** [comment]
This was an intentional change made in 2.0.0: http://eslint.org/docs/user-guide/migrating-to-2.0.0#built-in-global-variables

The reason is that people were confused about ES6 globals being available even when trying to parse with ES5, and we don't have a good way of turning off environments. So instead, we encourage people to opt in to ES6 using the `es6` environment.

**Comment by platinumazure** [comment]
Closing as I believe the question has been answered. Please reopen if you feel differently.

**Comment by othomann** [comment]
Thanks for the explanation. Makes perfect sense.
