### ISSUE TITLE
Feature request: new error level for informative purpose

### ISSUE THREAD

**Issue by xylosper** [eslint/eslint#6972]
ESLint provides 3 error levels: off, warn, error. I'd like to see another error level for informations, for instance, 'info'.

In my team, we're using 'warn' for potential problem and 'error' for definite problem.
However, there are lots of other useful rules for information.

For instance, eslint-plugin-lodash provides more simple form of chained methods.
It's absolutely safe to ignore that rule, so I don't want to set the level to warn or error. However,  I think it would be good to know that there's a simpler method, so I want to see it as an information.

If 'info' level introduced, the log could show info in green(safe) message.

**Comment by platinumazure** [comment]
I'm :-1: to this because we intentionally define warning as a lint error that won't cause the lint process to exit with a failure status code. That is literally the only meaning the warning level has and any other meaning is projected by users and not intended by us.

You could achieve this by writing a tool which wraps ESLint. It would support an ESLint-like configuration with four warning levels, as well as an `.eslintrc.js` which collapses warn and info into warn while iterating over your rules. Then you could use a custom formatter (or pipe JSON into another CLI program) which looks up the true warning level for each error message using the rule name, and it could transform infos as needed.

**Comment by xylosper** [comment]
@platinumazure 

In fact, that's exactly what I'm doing wright now. I made another configuration file and generate eslintrc from it to run eslint.

I've open this issue because I thought this feature is useful, but if you think this is out of scope, please close it.

**Comment by kaicataldo** [comment]
@xylosper Thanks for contributing! Wanted to point you to this link for some context with a previous discussion: https://github.com/eslint/eslint/issues/6139

The above issue might be why this is not getting a lot of discussion right now. Just wanted to make sure you knew we're listening, but we have the context of having discussed this before :)

**Comment by nzakas** [comment]
Yeah, we have discussed this before and decided this wasn't a good addition for ESLint as there would be no functional difference between a warning and info message, which would just be confusing. Please see #6139 for more information.
