### ISSUE TITLE
Add a --fix option for no-tabs

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#6980]
I'm using Node v6.4.0 and ESLint v3.3.1.

I think it would be useful to have an autofix option for the `no-tabs` rule. The fixer would simply delete any tab characters that it finds, inserting a space if necessary to avoid modifying the AST. (For example, `var\tfoo` would be replaced with `var foo`, since replacing it with `varfoo` would change the semantics of the program)

This would also provide a workaround for https://github.com/eslint/eslint/issues/4274; if all tabs were removed from the file, then the `indent` autofix could clean up and produce correct output on the next pass.

I would be willing to add this if the issue is accepted.

**Comment by Alaneor** [comment]
The potential implementation of this autofix could also inspect the `indent` rule's setting for how wide a tab character should be, then replacing `\t` with as many spaces. It might improve performance a bit.

I like this, tabs are a pain to fix across multiple files.

**Comment by platinumazure** [comment]
@Alaneor Unfortunately, rules are designed not to be able to know anything about other rules in ESLint, so looking at `indent` configuration is a non-starter. (Consider that users might not even use `indent`, so there wouldn't be a configuration to inspect.) Luckily, for those who do care, multipass auto-fix allows the `indent` issues to be fixed on a later pass.

**Comment by Alaneor** [comment]
I know this is not marked as `accepted` yet, but I decided to give it a go anyway. See #6987.

**Comment by platinumazure** [comment]
I'm :+1: to having autofixing here.

**Comment by mysticatea** [comment]
:+1:

**Comment by mysticatea** [comment]
Oops, :+1: except inside of literals. (I have commented in @Alaneor 's PR)

If it removes tabs in strings or regexps or templates, it changes the meaning of the code.

**Comment by nzakas** [comment]
👎 I'm not sure we can logically say that the correct fix for this rule is to delete a tab or replace it with a space. I don't see this as something we should guess about.

**Comment by not-an-aardvark** [comment]
@nzakas I'm a bit confused by your reasoning that this "[isn't] something we should guess about". Could you clarify the cases where replacing tabs would be undesirable? To me, it seems like if a project explicitly has `no-tabs` in their config, getting rid of the tabs would be a welcome fix for that project.

**Comment by Alaneor** [comment]
Perhaps the rule needs to get a configuration option for a tab width replacement to avoid guessing?

**Comment by not-an-aardvark** [comment]
@Alaneor In general, I think fixable rules don't have configuration options that specifically relate to fixing. Instead, they make a best guess and then then allow fixes for other rules to clean up afterwards. For example, in this case `no-tabs` might always replace tabs with a single space, and then the `indent` rule would correct it if necessary on the next pass, by adding/removing the appropriate number of spaces.

**Comment by platinumazure** [comment]
I wouldn't say we discourage options around fixing per se- it's just never
come up before.

Let's keep this as simple as possible for now. What can be fixed easily and
safely?

**Comment by nzakas** [comment]
@not-an-aardvark 

> To me, it seems like if a project explicitly has no-tabs in their config, getting rid of the tabs would be a welcome fix for that project.

I'm not arguing this point. My point is that we don't know what people would prefer to have instead of tabs, and therefore, we can't safely "fix" warnings for this rule. Just because someone said "I don't want tabs", that doesn't mean "I want one space instead of tabs" or "I want no spaces instead of tabs." Your proposal is based on what you would prefer, but we can't assume that that's what everyone would prefer.

Our approach has always been that we only apply fixes if we are 100% sure of the fix, because there's no way to opt-out of fixing for just one rule if you don't like how it fixes your code. I don't see a way where we can rationalize this fix as being correct in all cases. We are manipulating someone's code, and we just can't do that unless we are 100% sure that it's what they want.

I wouldn't want to introduce options just for fixing, I think that's pretty confusing and a bad precedent to set.

One thing I think we should make clear: we explicitly *do not* guarantee that all rules can be fixed automatically. Some rules will be fixable, some won't, and some fall somewhere in the middle where only a subset of the warnings it creates can be fixed.

**Comment by not-an-aardvark** [comment]
Thanks for clarifying; that makes more sense now.

---

I think we can classify tabs into three different categories:

* Indentation (i.e. tabs on a line before anything else):

Ideally, this would be handled by the `indent` autofix, since that rule has access to the user's preferred indentation. In other words, the `indent` fixer would be able to delete/add indentation tabs as necessary to ensure that a line's indentation is correct. (This is also discussed in https://github.com/eslint/eslint/issues/4274.)

* Tabs in string/template/regex literals

I think it would be safe for ESLint to replace these tabs with `\t`. There are other ways to represent a tab character in JS (`\x09`, `\x0009`, `\011`), but I don't think this replacement would surprise developers.

* Tabs as whitespace in other places, e.g. `function\tfoo () {}`

Tabs in this context aren't fixed by any other rule. While it would be possible to remove these tabs and replace them with a space, the user might not expect this particular fix. I think this category of tabs is fairly rare (in fact, I've never actually seen anyone use tabs like this) so it's hard to say whether the user would be surprised by a fix to these tabs.

**Comment by nzakas** [comment]
@not-an-aardvark I appreciate the thought you've put into this. Unfortunately, I still don't believe this a good idea. Whenever we are saying things like, "I don't think this replacement would surprise people," that means we are guessing, and fixes shouldn't be guesses. 

You can always create your own version that does the fixes you want, I just don't see this as a good idea for the core.

**Comment by Alaneor** [comment]
@nzakas What about limiting the fixer to the scope where we can safely assume the fix is "correct" or expected? From the discussion above, I would guess this would mean fixing only tabs used for indentation. Then the `indent` rule can kick in and fix it to the developer's preference.

**Comment by nzakas** [comment]
@Alaneor there is no situation where it's correct for this rule to fix, that's my point. Indentation would already be handled by the indent rule.

**Comment by nzakas** [comment]
TSC Summary: There is a proposal to autofix the `no-tabs` rule. I believe there is no good way to do this because the rule doesn't know what the correct fix is in this case (it's only disallowing something). The proposal is to use a mixture of inserted spaces and/or removing tabs without replacement depending on location.

TSC Question: Should we do autofix for `no-tabs`?

**Comment by btmills** [comment]
After discussion in the 2016-09-15 TSC meeting, we decided not to add autofix to the `no-tabs` rule.
