### ISSUE TITLE
Use eslint-config-airbnb-base for project initialization

### ISSUE THREAD

**Issue by alberto** [eslint/eslint#6986]
When running `eslint --init` one of the options is to use airbnb style as a base. If chosen, we install [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) which requires `eslint-plugin-react` among others.

I think we should install [eslint-config-airbnb-base](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/package.json) instead.

**Comment by platinumazure** [comment]
Seems reasonable to me. I think @ljharb made a similar recommendation in the JSCS migration doc issue.

**Comment by ljharb** [comment]
Yes, please do this - that much more closely will match developer expectations.

Please note, the command in step 1 [here](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base#eslint-config-airbnb-base-1) should be used, instead of hardcoding anything, to dynamically install the correct peer dependencies at the right versions.

**Comment by nzakas** [comment]
Yeah, let's make that change.

**Comment by gyandeeps** [comment]
@jacobp100 I think you have done the work, do you want to open a PR of it?

**Comment by jacobp100** [comment]
I'll try and make time for it—I'll need to redo the work, but it's not a huge amount
