### ISSUE TITLE
no-unused-vars false trigger?

### ISSUE THREAD

**Issue by dfcreative** [eslint/eslint#7027]
Hi!

```js
var inputsCount = 0;

this.on('pipe', function () {
	inputsCount++;
}).on('unpipe', function () {
	inputsCount--;
});
```

Eslint triggers `inputsCount is defined but never used`. It does not seem right, is it?

**Comment by ilyavolodin** [comment]
The rule doesn't not recognize writes as "use" of a variable. I know what you posted is a small extract, however, it can be completely removed without any loss of functionality the way it's written right now, since nothing is ever reads the value of `inputsCount` variable. See [rule documentat](http://eslint.org/docs/rules/no-unused-vars) for more information.

Closing as the rule behaves correctly.
