### ISSUE TITLE
Exclude Emacs backup files from globs by default?

### ISSUE THREAD

**Issue by domenic** [eslint/eslint#7040]
**What version of ESLint are you using?** 3.2.2

**What parser (default, Babel-ESLint, etc.) are you using?** Default

**Please show your full configuration:** Seems unrelated to the issue at hand. The relevant line is in my npm scripts: `"lint": "eslint \"{lib,test}/**\""`

**What did you do? Please include the actual source code causing the issue.** Ran eslint on a computer that uses emacs

**What did you expect to happen?** Emacs backup files should not have been linted

**What actually happened? Please include the actual, raw output from ESLint.** They were linted

---

@tyoshino may be able to tell you more. I don't quite understand besides that in https://github.com/whatwg/streams/pull/514 he suggested changing the lint glob to `"lint": "eslint \"{lib,test}/**/*[!~]\""`, and I thought maybe this or something like it should be the default?

**Comment by platinumazure** [comment]
Have you tried using a more specific glob pattern, such as `eslint "{lib,test}/**/*.js"`?

**Comment by tyoshino** [comment]
`**/*.js` should also work as we don't have any file with non js extension. Also in the sense of preparing for possible addition of e.g. md files to the subdirectories in the future, just glob-ing .js files would be the best thing to do, yeah.

**Comment by platinumazure** [comment]
We also support directories (including multiple directories), at which point those get expanded to JS-only globs (unless you use `--ext` as well), such as `eslint lib test`.

Since there are a few ways around this, both in terms of specifying more precise globs and using directories to avoid globs, I don't think we want to make our default more magical by looking for different forms of backup files (Emacs has `*~`, but vim has `.*.swp`). We can't just add a bunch of exceptions without there being a compelling reason to do so (and no workaround).

**Comment by tyoshino** [comment]
> directories

Oh, that's nice. Got it. Please close this as WontFix. Thanks!

**Comment by kaicataldo** [comment]
Looks like this question has been resolved. Thanks!
