### ISSUE TITLE
prefer-reflect: Reflect.deleteProperty considered harmful

### ISSUE THREAD

**Issue by shvaikalesh** [eslint/eslint#7226]
The rule tells that:
> `Reflect.deleteProperty` effectively deprecates `delete` keyword

Putting conciseness of `delete` and "`Map` should be used instead" points aside, given strict mode enabled and considering only property references, `Reflect.deleteProperty` returns result of `[[Delete]]` call (boolean), but **does not throw** on `false`, unlike `delete` operator does.

Throwing if deletion fails (non-configurable property, `Proxy` trap) is what modern JavaScript does. Not throwing [causes confusion](https://github.com/mgol/check-dependencies/pull/24/files#r76153529).

Quoting @nzakas on `prefer-reflect`:
> This rule should warn only for direct replacements.

I think `Reflect.deleteProperty` should be removed from the rule.

EDIT: same goes for `preventExtensions` and `setPrototypeOf`.

**Comment by vitorbal** [comment]
I think that's a good point. Judging by the conversation in https://github.com/eslint/eslint/pull/7171#issuecomment-248073052, I'd say this makes sense. Let's see what the rest of the team thinks.

@shvaikalesh would you be willing to submit a PR for this once it gets accepted?

**Comment by shvaikalesh** [comment]
@vitorbal sure, with pleasure

**Comment by nzakas** [comment]
What is the suggested change here?

Each of the 'Reflect' methods behaves slightly differently than the corresponding syntax or 'Object' methods as it relates to error conditions and return values. If we are going to say that deleteProperty isn't close enough to prefer it over 'delete' for these reasons, then we need to re-evaluate this rule as a whole because the same arguments can be made for each method.

**Comment by shvaikalesh** [comment]
From my point of view, there are 3 concerns with `prefer-reflect`:
1. Methods that swallow errors (to support legacy loose mode or other reasons): `deleteProperty`, `preventExtensions`, and `setPrototypeOf`.
2. Methods that behave *almost* the same: `getOwnPropertyDescriptor`, `getPrototypeOf` (except for `ToObject` thing). I am not sure we should recommend using them because some `Object` metaprog statics deliberately have no `Reflect` alternative (like `Object.getOwnPropertyDescriptors` and `Object.defineProperties`) and mixing them brings inconsistency.
3. Preferring `Reflect.apply` is useful when doing polyfills and can't call `apply` method directly, but in most cases it requires extra array allocation and has hard to remember parameter order (IMO).

This issue is about 1 and suggested change for it is to remove recommendations to prefer `deleteProperty`, `preventExtensions`, and `setPrototypeOf`.

**Comment by nzakas** [comment]
That's why I'm saying maybe the whole rule should be removed. I don't think it makes sense to just remove a subset.

**Comment by kaicataldo** [comment]
@eslint/eslint-team Thoughts? This discussion is blocking progress on a currently open PR, so we should probably figure this out.

**Comment by not-an-aardvark** [comment]
I'm not sure I agree with removing the rule -- I don't think we're claiming that the Reflect methods are identical to their counterparts. They're just similar enough that one could prefer to use them rather than their counterparts. If this was a proposal for a new rule I would say that it wasn't notable enough to meet our standard, but at this point I think removing it would just cause unnecessary breakage.

**Comment by kaicataldo** [comment]
For some context, we would only deprecate this rule for now. It would not actually be removed for quite a while. Check out http://eslint.org/docs/user-guide/rule-deprecation for more info.

**Comment by mikesherov** [comment]
My vote would be to clarify this rule, educate users, and clean up the docs so they aren't false.

**Comment by nzakas** [comment]
A little bit more background:

I think we may have moved too fast in creating this rule, and I take responsibility for that. I don't think any of us fully understood the purpose of `Reflect` and why those methods exist as separate from their `Object` equivalents. Now that I do understand, I feel like this entire rule is misguided, as the `Reflect` methods are not actually intended to replace the `Object` counterparts, but rather as low-level primitives to be used with proxies in order to replicate the default behavior of various previously existing functionality.

So, while I'm not opposed to updating the documentation, I'm more of the mind that this rule is does more harm than good by implying a relationship between `Reflect` and `Object` that doesn't necessarily exist.

**Comment by mikesherov** [comment]
@nzakas, makes sense. I'll rescind my recommendation and vote removal from core.

**Comment by not-an-aardvark** [comment]
To clarify, when we say we're considering removing this rule from core, do we mean that it would actually be removed, or just deprecated? Based on https://github.com/eslint/eslint/issues/5845, I thought we weren't removing rules for the time being.

I'll also vote for deprecation, if that is the proposal.

**Comment by shvaikalesh** [comment]
It it possible to repurpose this rule? Passing `receiver` with `Reflect.set` or `Reflect.get` (or `newTarget` with `Reflect.construct`), returning `true` from `set`, `deleteProperty` traps etc and other stuff tend to cause undesired behavior, throws in loose mode and hitting various edge cases. It is indeed difficult to program such heuristics given AST only, but it will be quite beneficial for `Proxy` adopters.

**Comment by nzakas** [comment]
@not-an-aardvark yes, we would deprecate it and decide on removal at a later time. Sorry, I can see how my comments were confusing in that regard.

@shvaikalesh we can't really repurpose an existing rule as that's a breaking change and probably completely surprising to existing users of the rule.

**Comment by nzakas** [comment]
TSC Summary: We've been finding more problems with the `prefer-reflect` rule, as this issue is one of a handful that have popped up. Instead of continuing to tweak the rule, the current proposal is to deprecate `prefer-reflect`, as it seems like it's original purpose doesn't make much sense now that we all understand ES6 better.

TSC Question: shall we deprecate this rule? If yes, how do we handle the case where a rule is deprecated without a replacement?

**Comment by alberto** [comment]
**TSC Resolution**: Deprecate prefer-reflect rule and update documentation explanaining why this rule will not be replaced

**Comment by corbinu** [comment]
@nzakas @alberto Sorry to ring in late on this. However I am going back through my code base and switching away from Reflect per this issues' recommendation. However it does seem that the purpose of Reflect.apply was to "less verbose and easier to understand" compared to `Function.prototype.apply.call`. Rather than to be a companion to a Object method. Would you guys be open to a proposal of a new rule only to prefer-reflect-apply?

**Comment by corbinu** [comment]
Sorry to ring in on this late. I am going through my code base and removing Reflect per this discussion's recommendation. However it does appear that `Reflect.apply` is not a companion for an Object method but meant to be "[less verbose and easier to understand](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/apply)" than `Function.prototype.apply.call`. I was wondering if you would be open to the addition of a new rule that is just `prefer-reflect-apply`. I understand if not however.

**Comment by corbinu** [comment]
Sorry to ring in on this late. However I am going through my code base to remove Reflect usage per this discussion. However I have found that `Reflect.apply` is not a companion for a Object method and seems to have a very different purpose than the rest of reflect to instead be ["less verbose and easier to understand"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/apply) Would you be open to a new rule that is just `prefer-reflect-appy` If not I understand

**Comment by ilyavolodin** [comment]
@corbinu I think that would be too small of a scope for a rule to be added to the core. I think this would be a better fit for custom plugin.

**Comment by kaicataldo** [comment]
Agreed with @ilyavolodin. If you need any help making a custom plugin, please feel free to stop by the [ESLint Gitter](https://gitter.im/eslint/eslint)!

**Comment by corbinu** [comment]
No worries I have built then my before will release one wanted to check here first though.

Corbin
