### ISSUE TITLE
`indent` rule discussion

### ISSUE THREAD

**Issue by kaicataldo** [eslint/eslint#7274]
Opening this issue to give us a place to discuss how we would like to move forward with the `indent` rule, given the number of open issues we have and the complexity of the rule. I'm leaving all the currently open `indent` issues open (even if they have reached the time we've agreed upon to close old issues) so we can take stock, but am not opposed to closing them after we discuss. Might even be worth creating a GitHub Project or milestone to track this when we've decided how we want to proceed.

The following a list of all the currently open issues we have for the indent rule (as referenced in [this comment](https://github.com/eslint/eslint/issues/4081#issuecomment-242591220)).
#### Accepted

https://github.com/eslint/eslint/issues/3352
https://github.com/eslint/eslint/issues/3737
https://github.com/eslint/eslint/issues/4161
https://github.com/eslint/eslint/issues/6007
https://github.com/eslint/eslint/issues/7164
https://github.com/eslint/eslint/issues/7320
#### Evaluating

https://github.com/eslint/eslint/issues/4081
https://github.com/eslint/eslint/issues/5073
https://github.com/eslint/eslint/issues/5540
https://github.com/eslint/eslint/issues/6571
https://github.com/eslint/eslint/issues/6670
https://github.com/eslint/eslint/issues/6890
#### Accepted

https://github.com/eslint/eslint/issues/1801
https://github.com/eslint/eslint/issues/3638
https://github.com/eslint/eslint/issues/3845
#### Evaluating

https://github.com/eslint/eslint/issues/6296
https://github.com/eslint/eslint/issues/6671
https://github.com/eslint/eslint/issues/6690
https://github.com/eslint/eslint/issues/6813
https://github.com/eslint/eslint/issues/6911
https://github.com/eslint/eslint/issues/6990
### Question

https://github.com/eslint/eslint/issues/7233

**Comment by kaicataldo** [comment]
Getting the discussion going, @not-an-aardvark has been working on this rule recently - would love to hear your thoughts on this. Working on this has been pushed back while we have focused on JSCS compatibility, and hearing from someone with a fresh perspective could be really valuable!

It seems to me like we should focus on resolving known issues/accepted bugs (maybe even closing any enhancement issues that are too long lived so that we can really focus our efforts). I know there has been a lot of discussion around the rule since well before my time (including an attempted rewrite, I believe?), but I think it could be beneficial (particularly for us newer members of the team) to discuss and develop a plan for how we want to move forward.

**Comment by not-an-aardvark** [comment]
Thanks for putting these together. I've been working on a rewrite of the `indent` rule. [This](/not-an-aardvark/eslint/commit/06dd1f01a6a8d13cad80bfcf4d2338d93daad594) is what I have so far -- I would say it's roughly 90% done, but there are still a few edge cases that need to be fixed. Hopefully I'll have a PR up for that in the near future.

Here's my take on the issues:

https://github.com/eslint/eslint/issues/6571 is a bug in the existing implementation. It's fixed in the rewrite.

https://github.com/eslint/eslint/issues/6813 is a bug in the existing implementation. It's fixed in the rewrite.

https://github.com/eslint/eslint/issues/7233#issuecomment-249981835 appears to be a bug, but I'm not sure -- the current behavior is briefly referenced in the docs, but the behavior doesn't make much sense to me. It's fixed in the rewrite.

https://github.com/eslint/eslint/issues/7270 is an enhancement proposal -- I have no strong opinions either way on whether we should add it. It is not included in the rewrite.

https://github.com/eslint/eslint/issues/4081, https://github.com/eslint/eslint/issues/6890, and https://github.com/eslint/eslint/issues/6990 are all referring to a very similar thing -- it's debatable whether the current behavior is a bug, or if it's just unintuitive in some cases.

https://github.com/eslint/eslint/issues/5073 seems like indented behavior to me, but I wouldn't mind having an option for the other behavior.

https://github.com/eslint/eslint/issues/6671 and https://github.com/eslint/eslint/issues/6296 are enhancement proposals -- personally I don't think either of them would be a good enhancements, but I would be open to other peoples' ideas on them.

https://github.com/eslint/eslint/issues/6690 is another enhancement proposal, no strong opinions on whether it gets added.

https://github.com/eslint/eslint/issues/5540 is already fixed in the current version of the rule (now that the `MemberExpression` option exists and the rule checks for both types of indent characters). I think that issue can be closed.

**Comment by sstern6** [comment]
@kaicataldo have been working on a few indent bugs in the codebase.  I am unsure how to proceed.  I was wondering if I should continue working through the bugs or wait until @not-an-aardvark 's PR is merged for the indent rewrite!

What do you think?

**Comment by jez9999** [comment]
I suspect my #7270 proposal would be relatively easy to implement, as it's just turning off checking for indentation within switch blocks, rather than implementing some more advanced logic.

**Comment by nzakas** [comment]
@not-an-aardvark are you rewriting to have the same options as we currently have?

I think part of this discussion needs to be about the scope of the indent rule and whether or not we want/need to alter the way we specify options. For instance, there have been several discussions where it's been suggested that indentation level is not a good way to configure the rule, and rather, we should be specifying how things should be aligned relative to each other.

**Comment by platinumazure** [comment]
Just noting here since I was one of the people who originally suggested a need to change options: I think I'm okay with indent levels now, as long as there's also an "align" option for some things. For example, I loathe that there's no way to specify six-space indentation for const statements with a four-space default indent, because we have to use integral indentation levels. But an "align" option for that case would help a lot (IMO). Indentation level makes a ton of sense in lots of other places (e.g., function params vs function body).

**Comment by not-an-aardvark** [comment]
Yes, the rewrite is intended to be fully backwards-compatible, aside from the fact that a lot more errors are reported at the moment due to the checks being more strict. (This part might warrant a separate discussion.)

Personally, I think our current system of indent levels is fine. However, I would be interested to see the discussions about non-indent-level options.

**Comment by jrajav** [comment]
If this rule is being re-approached anyway can https://github.com/eslint/eslint/issues/6606 please be re-evaluated? I feel like it was unfairly closed without due consideration. It's a valid style, me and my team have used it for a year now and we simply have to disable the entire indent rule because it doesn't support it.

**Comment by not-an-aardvark** [comment]
I finished the rewrite (pending review, etc).

See https://github.com/eslint/eslint/pull/7618

**Comment by sstern6** [comment]
Thoughts on doing an analysis of all of the indent issues aggregated in this file after @not-an-aardvark PR is merged and then start tackling the left overs?

Or @not-an-aardvark does this PR solve all of the open indent issues?

Thanks

**Comment by not-an-aardvark** [comment]
I think #7618 solves all of the *bugs* in the rule, but there are still some issues on the list where the indented behavior is unclear or disputed.

**Comment by sstern6** [comment]
Ok sounds good, lets revisit those when the PR is merged? 

It looks like a lot of files to go through 😄

**Comment by platinumazure** [comment]
Most of the extra files in @not-an-aardvark's PR are fixing obvious indent problems in the ESLint codebase (the majority being comments that weren't indented correctly). Review time will definitely be concentrated on the rule file itself, for sure.
