### ISSUE TITLE
Report format: log number of fixable problems

### ISSUE THREAD

**Issue by willclarktech** [eslint/eslint#7364]
I'm using eslint v3.7.1.

One of my favourite eslint features is the ability to fix a lot of problems automatically. When my team considers adding a new eslint rule, we take into account how many times the rule is broken and whether those new problems can be fixed automatically. So sometimes we want to know how many problems can be automatically fixed without actually running eslint with the `--fix` option.

The current report ends with something like this:

```
✖ 103 problems (103 errors, 12 warnings)
```

It would be great if the number of fixable problems was also included. Maybe like this:

```
✖ 103 problems (103 errors, 12 warnings).
88 errors, 2 warnings can be fixed by running eslint with the --fix option.
```

**Comment by platinumazure** [comment]
This is a cool idea, for sure! It'd be cool to see this happen.

Just a few practical concerns:

1. We support a few different formatters in ESLint core, so we need to figure out which of those can/should be enhanced. (Some formatters, the ones more designed for computer readability rather then human readability, may or may not support changes, and of course any change must be backward compatible.)
1. Because some fixable problems may actually need to operate on the same chunk of code, it is generally not true that all fixes will be applied. Thus, we would have to say that X problems may be fixable, rather than definitely will be fixed.

Other than those caveats, I think this is feasible, we just need to figure those out.

**Comment by SimenB** [comment]
This would be great! Many people don't know about `--fix`, meaning they don't use it, and get annoyed at the linter. Having it print it at the bottom would be really awesome

**Comment by vitorbal** [comment]
As far as I can tell, the following formatters should be okay to modify:

- stylish
- compact
- html
- table
- unix
- visualstudio

Would like someone from the team to double-check that list if possible, though. I'm also not sure what our policy is on changes to formatters.

**Comment by nzakas** [comment]
Practical problem: we don't actually know how many problems can be fixed until we try to fix them. Even though we know what a fix is, we might not be able to apply it, so there's no good way to know the total number of fixable problems. Given that, the best we could hope for is a message that says, "Try running --fix," and I'm not entirely sure that's very useful.

In general, we've tried to avoid changing the output of formatters too much as we don't know who is relying on the specific format to be fed into another tool. Even those that are meant to be human-readable rather than specifically targeting a tool can be dangerous to change because we have no idea if someone is feeding it into a tool.

**Comment by willclarktech** [comment]
1) I can see that it's not possible to say definitively how many will be *successfully* fixed, but we would find it helpful even to know how many errors eslint would *attempt* to fix. In our experience these numbers are usually the same or very close to each other, so this weaker report would still provide us with a lot of value.

2) How about introducing a new flag (e.g. `--fixcount` which provided the extra output information, while still preserving backwards compatibility for eslint runs without this flag?

**Comment by kaicataldo** [comment]
@willclarktech There are many cases where fixable rules cannot fix errors they find, since ESLint can't always know what the intention is/if an error is safe to fix. So what @nzakas is saying is that we actually don't know what ESLint would attempt to fix until the fixer is run.

**Comment by nzakas** [comment]
I think this falls into the category of "nice to have, but not practical." We'll review at the TSC meeting.

**Comment by nzakas** [comment]
TSC Summary: The proposal is to somehow output the number of possible fixes ESLint could apply when run without the `--fix` option. There's a practical problem in that we don't actually know this information and it's not possible calculate without attempting to apply the fixes.

TSC Question: Is it worth pursuing an implementation for this feature given the restrictions?

**Comment by alberto** [comment]
TSC resolution: Issue has been accepted. See [meeting notes](https://github.com/eslint/tsc-meetings/blob/0d75733ef001385a7ff5ba6336e60f210d1b0d21/notes/2016/2016-11-17.md) for details

**Comment by kaicataldo** [comment]
Should this be part of v4.0.0? There hasn't been any movement on this since Nov 17, and looks like we still need to decide on an implementation.

**Comment by vitorbal** [comment]
I think i can find some time to implement this one if we can agree on an
approach!

**Comment by nzakas** [comment]
I'd rather not race to get things into 4.0. This has been sitting for a while without any progress, trying to quickly revive it seems like a bad idea, especially when there doesn't appear to be any implementation decision.
