### ISSUE TITLE
Wrong schema/code definition for "CallExpression" option of the "indent" rule.

### ISSUE THREAD

**Issue by the-spyke** [eslint/eslint#7612]
**Tell us about your environment**

Ubuntu 16.04.1 LTS x64

* **ESLint Version:** 3.7.1
* **Node Version:** 6.9.1
* **npm Version:** 3.10.9

**What parser (default, Babel-ESLint, etc.) are you using?**

Default parser.

**Please show your full configuration:**

```json
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true,
        "jasmine": true,
        "node": true,
        "shared-node-browser": true
    },
    "extends": "eslint:recommended",
    "globals": {
        "Promise": true
    },
    "installedESLint": true,
    "parserOptions": {
        "ecmaFeatures": {
            "experimentalObjectRestSpread": true,
            "jsx": true
        },
        "ecmaVersion": 6
    },
    "plugins": [
        "react"
    ],
    "rules": {
        "block-scoped-var": "error",
        "consistent-this": [
            "error",
            "me"
        ],
        "curly": "error",
        "indent": [
            "error",
            4,
            {
                "SwitchCase": 1,
                "MemberExpression": 1,
                "CallExpression": { "arguments": 1 }
            }
        ],
        "jsx-quotes": [
            "error",
            "prefer-double"
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "no-caller": "error",
        "no-empty-function": "error",
        "no-global-assign": "error",
        "no-trailing-spaces": "error",
        "quotes": [
            "error",
            "double"
        ],
        "radix": "error",
        "semi": [
            "error",
            "always"
        ],
        "space-before-function-paren": [
            "error",
            "never"
        ],
        "strict": [
            "error",
            "safe"
        ],
        "vars-on-top": "error"
    }
}
```

**What did you do? Please include the actual source code causing the issue.**

There is a discrepancy with "indent" rule's schema and the actual code.

JSON schema:
```
CallExpression: {
                        type: "object",
                        properties: {
                            parameters: {
                                oneOf: [
```

And there is the code:
```
if (options.CallExpression.arguments ===
```

The result is that I have an error in my console.

**What did you expect to happen?**

I've expected this option to work.

**What actually happened? Please include the actual, raw output from ESLint.**

[Error - 10:21:10 AM] /home/***/Projects/***/.eslintrc.json: 	Configuration for rule "indent" is invalid: 	Value "data["1"].CallExpression" has additional properties.

**Comment by not-an-aardvark** [comment]
Thanks for the report. There are several things going on here:

* The `CallExpression` option was introduced in ESLint v3.9.0, but you're using v3.7.1. If you upgrade to the latest version of ESLint, I think your config will work as expected.
* The `indent` rule's schema is incorrect; it specifies `CallExpression: parameters` instead of `CallExpression: arguments`. However, since the schema does not specify `additionalProperties: false`, the `arguments` option actually works correctly; the effect of the incorrect schema is that some validation for the `arguments` option is skipped. This is unfortunate and we should probably fix it, but I think doing so would be a breaking change (some configs would end up getting marked as invalid due to the upgrade).

**Comment by the-spyke** [comment]
I've updated to the 3.10.2. Everything works fine now. Thanks!
