### ISSUE TITLE
Scheduled Release for December 9, 2016

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#7659]
The scheduled release on Friday, December 9, 2016 is assigned to:

- @kaicataldo
- @btmills

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by kaicataldo** [comment]
v3.12.0 release was successful. We had an issue with Travis being unable to install Node versions with nvm, but it was resolved pretty quickly.

@eslint/eslint-team Reminder to please only merge documentation and bug fix PRs until we determine whether or not we need a patch release on Monday.

**Comment by kaicataldo** [comment]
v3.12.1 release was successful. We have one [outstanding bug](https://github.com/eslint/eslint/pull/7750) that we would like get a fix in for, but because it's for the `indent` rule (which is prone to regressions), we're going to wait until Wednesday and do a second patch release. 

@eslint/eslint-team Reminder to please continue only merging documentation and bug fix PRs until we do a second patch release on Wednesday, 12/14.

**Comment by kaicataldo** [comment]
v3.12.2 release was successful. This concludes this round of releases.

@eslint/eslint-team Please feel free to merge all PR's!
