### ISSUE TITLE
Make sort-keys rule fixable

### ISSUE THREAD

**Issue by gajus** [eslint/eslint#7714]
[sort-keys](http://eslint.org/docs/rules/sort-keys) is a laborious style requirement when applied on a large code base. Fixing these errors by hand is time consuming and error prone, esp. with nested objects.

**Comment by gajus** [comment]
https://github.com/eslint/eslint/pull/7715

**Comment by not-an-aardvark** [comment]
Thanks for the rule suggestion and the implementation. However, I am concerned that autofixing `sort-keys` isn't safe, because it changes the order of `Object.keys` and could break working code. So I'm :-1: on this proposal, unless we can figure out a way to guarantee that it won't break code.

**Comment by gajus** [comment]
> Thanks for the rule suggestion and the implementation. However, I am concerned that autofixing sort-keys isn't safe, because it changes the order of Object.keys and could break working code. So I'm 👎 on this proposal, unless we can figure out a way to guarantee that it won't break code.

You already have "sort-keys" rule. Using your logic, one mustn't use the rule in the first place.

**Comment by not-an-aardvark** [comment]
A lot of rules enforce a specific style, but it's not always obvious how to modify code to fit that style without breaking the code. For example, in order to fix a problem reported by `sort-keys`, one might have to take the following two steps:

1. Modify the object so that the keys are sorted
1. Update code elsewhere that depended on the old ordering of the keys

It's reasonable to expect a human to do both of these steps, so I disagree that "one mustn't use the rule in the first place". However, an autofix like the one you're proposing would only do step 1 and would skip step 2, which could cause problems. The `sort-keys` rule wouldn't report any more issues with the resulting code, but the resulting code might also be doing something completely different than the original code, so I don't think this could be considered a good fix.

**Comment by gajus** [comment]
> It's reasonable to expect a human to do both of these steps, so I disagree that "one mustn't use the rule in the first place". However, an autofix like the one you're proposing would only do step 1 and would skip step 2, which could cause problems. The sort-keys rule wouldn't report any more issues with the resulting code, but the resulting code might also be doing something completely different than the original code, so I don't think this could be considered a good fix.

I understand your concerns.

I have written this rule for my personal use and contributed it back to the community. Its entirely up to @eslint/eslint team whether to merge this or not.

**Comment by AlexTes** [comment]
I would say auto-fix! I also understand the concern but would say a warning added to this rule is more than enough.

If someone wishes to rely on the order of objects (perhaps already a debatable practice), then enforce the order of keys to be alphabetic, then asks the computer to enforce set rule and then get upset with it over things breaking something went wrong earlier on and a valuable lesson was learned.

This hooks into my thinking that it's highly unlikely for someone to rely on object key order, then enforce object key order, be aware of the fact that might break something, and then forget or not act on this knowledge when auto-fixing. In other words, I don't think auto-fixing has any effect on whether your (2.) gets done. Either the person knows or doesn't, will execute step two or won't, assisted by auto-fixing or no.

Does that sound reasonable?

**Comment by Joris-van-der-Wel** [comment]
Perhaps hide this behind a new flag? Something like `--unsafe-fix`. Other rules such as `no-trailing-spaces` could also benefit from this (by trimming within multi-line strings).

**Comment by not-an-aardvark** [comment]
@AlexTes 

It doesn't really matter whether relying on the ordering of object keys is a good practice (in fact, I agree with you that it's not). But the fact is that it is possible for code to rely on it, and ESLint should not break working code under any circumstances.

> Either the person knows or doesn't, will execute step two or won't, assisted by auto-fixing or no.

An example of a case where this wouldn't apply: A user clones an existing repo that has `sort-imports` enabled, and makes some changes. When they're about to commit, they run the linter and see a bunch of linting errors. Before looking at all of the linting errors in depth, they decide to run `--fix` to reduce the number of errors they have to deal with. The linter fixes all the errors, the build passes, and the user commits the code, without ever realizing that the linter broke it. In this scenario, the user didn't have a chance to read the `sort-imports` documentation (in fact, they might not have even noticed that the `sort-imports` rule was enabled).

We currently have a fairly strict policy that the linter should never, ever break a user's code, and we've decided against autofixing some rules when the chance of breakage was far more remote than this. (As an example, see the list of caveats mentioned [here](https://github.com/eslint/eslint/pull/7517) for the `operator-assignment` fixer.) A user should feel comfortable running `--fix` and immediately deploying to production, and the tediousness of having to manually fix an error is not worth the risk of ESLint silently creating bugs.

**Comment by not-an-aardvark** [comment]
@Joris-van-der-Wel We're certainly open to the idea of having a way for the user to opt-in to "unsafe" fixes. However, I don't think there was consensus on this the last time it was discussed; feel free to open a separate issue for it if you'd like. (For more context, see https://github.com/eslint/eslint/issues/5329.)

**Comment by AlexTes** [comment]
@not-an-aardvark you make a strong point. I did not consider the case where the user enforcing the rule and responsible for the use of object key order say a maintainer, is not the same as the user submitting the auto-fixed code. A tricky use-case I'd enjoy trying to solve.

Before I do, I couldn't find more than the core-rule-guidelines but if what you say is set in stone:

> ESLint should not break working code under any circumstances

There's really no point in discussing this further. It's anything but trivial to detect if a codebase is relying on object key order. So that option is out I believe. As this auto-fix will always entertain the possibility of breaking your code, it can then never be merged. You do mention:

> We're certainly open to the idea of having a way for the user to opt-in to "unsafe" fixes.

But I think it's fair to say that won't ever become a part of this PR, so this can safely be closed. I'm tempted to open an issue to get movement on unsafe-fixes. You linked #5329. No minor issue but still discouragingly stale. Are you saying until that gets solved its unlikely unsafe fixes get in?

**Comment by gajus** [comment]
> @not-an-aardvark you make a strong point. I did not consider the case where the user enforcing the rule and responsible for the use of object key order say a maintainer, is not the same as the user submitting the auto-fixed code.

If the order of properties is important, it must be covered in their test cases.

If user identifies a breaking change, he can always opt-in to revert a change and use `/* eslint-disable */` to disable transformation of a specific object declaration.

**Comment by not-an-aardvark** [comment]
@AlexTes

> You linked #5329. No minor issue but still discouragingly stale. Are you saying until that gets solved its unlikely unsafe fixes get in?

Sort of; I'm saying that unsafe fixes probably won't get in until a better way to opt-in to fixes is implemented. (It's worth noting that since #5329 was created, there have been several major improvements to autofixing. So while there hasn't been much discussion on that issue recently, it's not as if all autofixing progress has been completely stalled since February.)

**Comment by AlexTes** [comment]
I understand.
On the latter: that's great to hear! Unfortunately, I don't think I can currently help out with the herculean effort that is implementing auto-fixing the way #5329 envisions. I can wish you the best of luck with it. Good luck to you and all others @not-an-aardvark!

**Comment by claudiorodriguez** [comment]
Something like `--fix --fix-unsafe=sort-keys,another-rule` would be ideal. `--fix` would be current default behaviour (err on the safe side of breaking code), and `--fix-unsafe` would let you specifically opt into autofixing specific rules whose autofixes are considered unsafe. At that point it's up to the developer to make sure that the rule's autofix can be safely applied. Maybe each autofix can have a warning - for example, for `sort-keys` you could prompt `Are you sure your code does not rely on object key order?`, and then prompt for each unsafe rule you opted into.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.

Also if you want to suggest a proposal about `unsafe-fixes`, please open a new issue to discuss that in a detailed way.

**Comment by jedwards1211** [comment]
Just a random comment, I think there is actually a lot of code in the wild relying on property order for better or worse, because as far as I know pretty much all JS engines maintain property order.  However, such cases as I've seen (I'm thinking of the old React TransitionGroup) rely on the ordering of an object created procedurally, rather than an object literal, so they would not be broken by an autofix.
