### ISSUE TITLE
Uncaught exception when cache file is empty (i.e. invalid JSON)

### ISSUE THREAD

**Issue by feross** [eslint/eslint#7748]
**Tell us about your environment**

* **ESLint Version:** 3.10.2
* **Node Version:** 6.9.1

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

[`standard` 8.6.0](https://github.com/feross/standard/blob/2b9afb6e49fb72d7043916b66e310f802f29f6cf/package.json)

**What did you do? Please include the actual source code causing the issue.**

Reposting [this issue](https://github.com/feross/standard/issues/673):

> Suddenly standard started giving the attached below output. After spending some time searching through my code and reducing it to 0 files I was still getting the same error. Later I've found that there is no try/catch trying to parse back the JSON from the cache files found at .standard-cache, so when the file is empty it crashes. The problem seems to be at flat-cache package or its usage, but I thought you may know more about it. I'll try to take a deeper look, anyway.

> What do you think about trying to delete cache files when this kind of error occurs?

> Hope I can help in any manner :)

So, basically the cache file parsing probably needs a try-catch. In case it's relevant, here's the place where we set the cache options: https://github.com/Flet/standard-engine/blob/b579ea143c8e64254caebbd276c1d67b16793458/index.js#L35-L36

**What did you expect to happen?**

No uncaught exceptions.

**What actually happened? Please include the actual, raw output from ESLint.**

```
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Object.parseRecursion [as parse] (.../node_modules/circular-json/build/circular-json.node.js:182:15)
    at module.exports.readJSON (.../node_modules/flat-cache/utils.js:15:25)
    at Object.cache.load (.../node_modules/flat-cache/cache.js:25:23)
    at Object.module.exports.create (.../node_modules/flat-cache/cache.js:158:9)
    at Object.module.exports.load (.../node_modules/flat-cache/cache.js:144:17)
    at Object.module.exports.create (.../node_modules/file-entry-cache/cache.js:13:27)
    at new CLIEngine (.../node_modules/eslint/lib/cli-engine.js:463:38)
    at .../node_modules/standard-engine/index.js:107:16
    at .../node_modules/deglob/index.js:51:12
```

cc @alvaropinot @VzqzAc

**Comment by not-an-aardvark** [comment]
Is there a use case for linting with an invalid cache file? I can see the argument for invalidating the cache if it's invalid, but I'm wondering how this even happens.

**Comment by VzqzAc** [comment]
My related-to-this error comes with an empty file as it tries to parse it or something like that but as is a blank file it throws an exception

**Comment by not-an-aardvark** [comment]
Right, but why is there a blank cache file in the first place?

**Comment by VzqzAc** [comment]
Sorry, mine is not a cache file, but a file I will use just that is blank at the moment, it will contain some code, maybe it would be good an error like file created but is empty or something like, anyway, sorry again because I have a problem with the empty file but it's not really a cache file so my problem might be irrelevant

**Comment by feross** [comment]
> Is there a use case for linting with an invalid cache file?

I wouldn't call it a use case, but it can definitely happen. I've seen multiple issues opened on the `standard` repo about this issue.

> I can see the argument for invalidating the cache if it's invalid, but I'm wondering how this situation even happens.

I don't know for sure what the cause is, but this could easily happen if ESLint throws an uncaught exception or if the user kills the program with Ctrl+C in the middle of execution.

It's probably a good idea to be robust against invalid cache files.

**Comment by platinumazure** [comment]
@feross I'd love to hear some thoughts on what you think we should do in those cases. Should we blow away the cache on `uncaughtException` event?

**Comment by not-an-aardvark** [comment]
My preference would be to blow away the cache any time we attempt to load the cache and fail. If I'm understanding correctly, we currently just abort immediately when that happens (and the result is that the same error occurs the next time ESLint is run).

**Comment by feross** [comment]
Right now, an uncaught exception is thrown (and the node process terminates) when the cache file is invalid. As a result, the same error occurs the next time ESLint is run, as @not-an-aardvark correctly pointed out.

The issue is in `flat-cache` on [this line](https://github.com/royriojas/flat-cache/blob/1c2b1f7d101790eb75049afd02c6005bf7bfded4/cache.js#L25). They call a function that can throw exceptions but do not have a `try`-`catch` block to handle the case where the string is invalid JSON.

I opened an issue on `flat-cache` to get the author's thoughts: https://github.com/royriojas/flat-cache/issues/12

**Comment by royriojas** [comment]
Hi @feross, I think you're right, if the cache is unusable we should probably discard it. But I have some questions... should we inform to the end user that the cache is not being used? I see that as a very minor issue, as once we have a valid cache the issue will disappear. 

Do you have by chance a small repo that I can use to replicate the issue? I would like to do the fix and test it before publishing a new patch version, since this might affect Eslint.

**Comment by royriojas** [comment]
Hi @feross, I have a possible fix for this issue in this PR: https://github.com/royriojas/flat-cache/pull/13, if you have a repo where you can try this will be awesome.

**Comment by not-an-aardvark** [comment]
@royriojas Thanks for the fix (and for considering its potential effects on ESLint)!

I'm currently writing a few integration tests for ESLint's use of cache files, and I'll include a test for what happens when an invalid cache file is present. If we run the integration tests on the patched version of `flat-cache`, we can hopefully verify that the patch works and that it won't create any regressions downstream in ESLint.

**Comment by not-an-aardvark** [comment]
@royriojas I just pushed a commit to the [cache-integration-tests](https://github.com/eslint/eslint/tree/cache-integration-tests) branch on the ESLint repo. The commit has tests for a lot of ESLint's behavior with cache files. Two tests on that commit are currently failing due to this cache-parsing issue.

When I install the commit on your branch:

```
npm install git://github.com/royriojas/flat-cache/#eaec2239ca1aaf7efb46b95f1b3153f70df8c8d3
```

...the tests pass. So as far as I can tell, your fix seems to work. :+1:

**Comment by royriojas** [comment]
@not-an-aardvark Thanks!, so I guess it is safe to publish a new patch version right? Just to confirm. All the previous tests seemed to pass, so I guess it is safe to release a patch, right?

**Comment by not-an-aardvark** [comment]
Yes, as far as I can tell, it should be safe to publish https://github.com/royriojas/flat-cache/pull/13 in a new patch version.

**Comment by feross** [comment]
The `flat-cache` patch is published now, so I think this issue can be closed.
