### ISSUE TITLE
Unnecessarily quote property 'Allow' found

### ISSUE THREAD

**Issue by johnripke** [eslint/eslint#7888]
** OS X 10.12.2 **

* **ESLint Version:** 
v3.13.0
* **Node Version:**
 v7.4.0
* **npm Version:**
 v4.0.5

**What parser (default, Babel-ESLint, etc.) are you using?**
ESLint
**Please show your full configuration:**

Installed packages

  "devDependencies": {
    "babel-eslint": "6.1.2",
    "chai": "3.5.0",
    "chai-enzyme": "0.5.2",
    "deep-freeze": "0.0.1",
    "enzyme": "2.4.1",
    "esformatter": "0.7.3",
    "esformatter-braces": "1.2.1",
    "esformatter-collapse-objects-a8c": "0.1.0",
    "esformatter-dot-notation": "1.3.1",
    "esformatter-quotes": "1.0.3",
    "esformatter-semicolons": "1.1.1",
    "esformatter-special-bangs": "1.0.1",
    "eslint": "3.8.1",
    "eslint-config-wpcalypso": "0.6.0",
    "eslint-plugin-react": "6.4.1",
    "eslint-plugin-wpcalypso": "3.0.2",
    "glob": "7.0.3",
    "lodash-deep": "1.5.3",
    "md5-file": "3.1.0",
    "mixedindentlint": "1.1.1",
    "mocha": "3.1.0",
    "mocha-junit-reporter": "1.12.0",
    "mockery": "1.7.0",
    "nock": "8.0.0",
    "nodemon": "1.4.1",
    "react-addons-test-utils": "15.4.0",
    "react-hot-loader": "1.3.0",
    "react-test-env": "0.2.0",
    "sinon": "1.17.6",
    "sinon-chai": "2.8.0",
    "socket.io": "1.4.5",
    "stylelint": "^6.5.1",
    "supertest": "2.0.0",
    "webpack-dashboard": "0.2.0",
    "webpack-dev-server": "1.11.0"
  }
**What did you do? Please include the actual source code causing the issue.**
Development

	if ( req.method === 'OPTIONS' ) {
		res.send( 'myApi OPTIONS\n', {
			'Allow': 'GET, OPTIONS',
			'Content-Type': 'text/plain'
		}, 200 );
	}

**What did you expect to happen?**
No warning

**What actually happened? Please include the actual, raw output from ESLint.**
Unnecessarily quote property 'Allow' found message

**Comment by platinumazure** [comment]
Could you please include your ESLint rule configuration?

At a glance, it seems like you have the `quote-props` rule configured so that properties should only be quoted if absolutely necessary (which is the case for `'Content-Type'`, but not for `'Allow'`). So you should either remove the quotes around `'Allow'`, or change your rule configuration to allow for quotes to be applied consistently. (Take a look [here](http://eslint.org/docs/rules/quote-props#options)-- you'll want either "consistent" or "consistent-as-needed".)

**Comment by nzakas** [comment]
Closing, as this appears to be a rule configuration issue.
