### ISSUE TITLE
Configuring eslint using single-line comments

### ISSUE THREAD

**Issue by cowwoc** [eslint/eslint#7890]
ESLint supports configuring rules using multi-line comments: http://eslint.org/docs/user-guide/configuring.html#configuring-rules

I'd like to request doing the same with single-line comments: `// eslint eqeqeq: "off", curly: "error"`

**Comment by platinumazure** [comment]
Hi @cowwoc, thanks for the issue.

We've had discussions about similar issues before. We've decided we can't do single-line comments for `/* eslint-enable */` and `/* eslint-disable */` due to ambiguity over where they would begin to apply. (See [here](https://github.com/eslint/eslint/issues/6416#issuecomment-225983447) for more info.)

That particular worry doesn't really apply for `/* eslint */` comments, but for me that means the question really becomes: Is it worth adding the extra logic to support `// eslint`, in terms of maintenance vs user benefit? And I'm not sure there is much benefit (in the sense that `/* eslint */` comments are a perfectly functional workaround).

Could you maybe please go into more detail on why you want single-line `// eslint` comments?

**Comment by cowwoc** [comment]
@platinumazure Thank you for the reply. I was mostly interested in `eslint-enable` and `eslint-disable`. I read the linked discussion thread, and although it's too bad (I find JSHint treating the two kind of comments differently to be unintuitive) I understand and respect your decision.

Hopefully we can revisit this decision in a year from now (maybe once migration from JSHint slows down). Closing this issue for now.
