### ISSUE TITLE
no-multiple-empty-lines performance issue (hang?)

### ISSUE THREAD

**Issue by undeadcat** [eslint/eslint#7893]
**Tell us about your environment**

* **ESLint Version:**
3.13.1
* **Node Version:**
6.9.2
* **npm Version:**
3.10.9

**What parser (default, Babel-ESLint, etc.) are you using?**
default
**Please show your full configuration:**
```
{
  "rules": {
    "no-multiple-empty-lines": [2, { "max": 1 }]  
  }
}
```

**What did you do** 
Linted a large file: [app.txt](https://github.com/eslint/eslint/files/696032/app.txt)
(I have changed the extension to .txt in order to attach it to this issue. It is obviously a js file and you should change the extension to the original .js).

**What did you expect to happen?**
Expected ESLint to produce output in a reasonable amount of time.

**What actually happened? Please include the actual, raw output from ESLint.**
ESLint did not produce any output after 10 minutes while consuming 100% of 1 CPU core.

<br>
The file is a file generated by WebPack. I am aware that linting generated files makes no sense and have added the generated files dir to .eslintignore so that performance on large files per se is not a problem for me.

The reason I would like to see some fix (a timeout? if improving the performance is not possible?) is that I was using ESLint from inside an IDE that became unresponsive while waiting for linting to complete. It took me a while to figure out what file and combination of rules was causing the behavior and it would be great if others would not have to spend more time only to figure out that they forgot to exclude their build output folder.

**Comment by not-an-aardvark** [comment]
Thanks for the report. This is a bit confusing, because we just fixed an issue in 3.13.0 (https://github.com/eslint/eslint/issues/7803) where `no-multiple-empty-lines` would hang on large files. However, it seems like you're using 3.13.1, which would already have gotten that fix.

Just to make sure, could you run `eslint -v` to double-check that you have 3.13.1 installed? If you have 3.13.1 in your `package.json` file but haven't run `npm install` recently, it's possible that the installed version of ESLint doesn't match the version in your `package.json` file.

**Comment by undeadcat** [comment]
I've looked at the issue before reporting and specifically checked, and confirmed now that ```eslint-v``` returns v3.13.1. There is no eslint installed globally or anywhere else, so I can't think of other things that could be wrong with my install.

Have you tried reproducing it?

**Comment by not-an-aardvark** [comment]
Not yet, I'm planning to look at it a bit later today. Thanks for confirming the ESLint version.
