### ISSUE TITLE
Add support in ESLint for other languages

### ISSUE THREAD

**Issue by th317erd** [eslint/eslint#7907]
As far as I understand it, ESLint parses and AST tree as returned by the parser to do its dirty work. ESLint is only half a step away from being able to lint other programming languages. If I had an AST parser for C or Java for example, ESLint could technically lint C or Java... but it currently would need a little help... but I don't think too much. 

As far as I understand it, if ESLint were simply to separate the "rules" into separate plugins like so: eslint-plugin-default-js, eslint-plugin-default-c, eslint-plugin-default-java, etc... Then ESLint should be able to be used for any languages.

Another change that would be needed is to tell ESLint which files to parse, and how to handle them. This could be accomplished by specifying "rule sets", that can be applied by extension type, or matching file name pattern (possibly just something like .eslintrc-js, .eslintrc-java, etc...?)

Thoughts?

**Comment by nzakas** [comment]
It's an interesting idea that I have actually thought about previously. However, it would require a massive rewrite of most of the codebase in order to abstract away a lot of hard coded JS-specific logic (it's definitely not just half a step away). 

When I'm healthy again, I'd like to explore this, I just don't think it's something we can commit to at this point.

**Comment by th317erd** [comment]
Thanks nzakas. I don't currently have a lot of time on my hands but I wouldn't mind helping when and where I can. Do you have any code documentation I can look at, or can you point me towards some of the parts of ESLint that would need updating so I can further wrap my head around the changes that would be needed in my spare time? Thanks!

**Comment by nzakas** [comment]
This is a good place to start: http://eslint.org/docs/developer-guide/architecture. Otherwise, I'd say start looking at code in `lib/`.

Again, I don't see us working on this anytime soon. Such a drastic change would require a lot of time and effort on the part of the team, and that would necessarily take away from everything else we're working on. You are, of course, free to dig around and see what's going on in the codebase -- I just can't promise there's going to be any concerted effort to move towards such work.

**Comment by platinumazure** [comment]
This is a pretty imprecise, quick answer and I know @nzakas can certainly deliver a much more precise and detailed answer, but his time is limited and I can at least show how big the problem is.

I find it helpful to think of the basic steps an ESLint-style linter needs to do first:
1. Parse code into an abstract syntax tree (AST)
1. Prepare auxiliary information needed by rules
1. Traverse the AST and emit events for each node entered and left
1. Rules listen for node events and emit lint messages
1. Iterate through lint messages and attempt to apply fixes
1. Output results, including "fixed" file

Auxiliary information primarily includes three things in ESLint: comment events (between relevant nodes), scope analysis (used for getting variable definition and reference locations in rules), and code path analysis (used for understanding when a code path forks, joins, or shadows the previous one and is useful for checking that any or all possible code paths meet a condition in a rule).

Which of these are really, really stuck to JavaScript? Well...

* Traverser: We use estraverse for traversing the AST (our event emitting wrapper is pretty generic, though)
* Scope analysis: We use escope for analyzing scopes and variables

I'm fairly sure everything else is reasonably generic (our parser is replaceable in config, and I assume the output and message analysis post-linting is basically generic as long as the message objects are formatted correctly).

Again, this is very high-level and imprecise, but it might be a useful guide as you look around the codebase.

**Comment by alberto** [comment]
While this seems an interesting idea, it's way outside the current scope of the project. Even if we did this, I think it should be a different project that eslint would depend on. Everyone is encouraged to explore it, of course.
