### ISSUE TITLE
Node support policy

### ISSUE THREAD

**Issue by corbinu** [eslint/eslint#7921]
This is an issue for the TSC but was hoping to get it in the next meeting. Brought about in how to reformat eslint-scope https://github.com/eslint/eslint-scope/issues/7

Eslint should have an official Node support policy. 

I was thinking Maintenance and Current + 3 Months

https://github.com/nodejs/LTS

So at the moment 0.X and 5 are out of support. Node 4 would end 2018-04-01 and Node 7 would end 3 months after Node 8 drops

**Comment by not-an-aardvark** [comment]
We can only drop support for a Node version in a major release of ESLint, so having a schedule like this would also require us to have our major releases on a schedule. This isn't out of the question, but it seems a bit restrictive and I'm not sure I see a compelling reason to do it.

Could you clarify why you think having an official Node support policy would be useful?

**Comment by corbinu** [comment]
@not-an-aardvark I am not saying you would have to drop it right away ... just come in line whenever the next major does drop. Well the befit today for me would have been being able to look and see what Node features eslint-scope can and can't use. 

It also then just makes questions of when to drop simpler especially now that Node has a super consistent schedule.

**Comment by not-an-aardvark** [comment]
Thanks for clarifying.

I certainly agree that we should make our supported versions clear (for both eslint and eslint-scope). However, I personally don't think attaching node support to a fixed timeline is worth it at the moment. IMO, major Node releases happen rarely enough that we can just discuss whether to drop support for a version on a case-by-case basis (taking into account the Node usage statistics, the benefits of dropping support for that particular version, etc.) rather than setting it on a schedule.

**Comment by ljharb** [comment]
+1 - people are still using 0.10 (i'm aware eslint has already dropped pre-4), and dropping support for a node version should only be done when there's a pressing reason to do so.

**Comment by nzakas** [comment]
Yeah, I don't see a huge benefit to tying ESLint's Node support policy to an external timeline. We made the switch to Node 4 last year because we wanted to start getting ES6 syntax into the codebase so we could dogfood our ES6 rules and fix a few long-standing bugs where we had to fork logic for different Node versions. I don't anticipate dropping Node 4 support anytime soon. 

I'd much rather just say our minimum is the most recent Node 4 release (since Travis uses that) and not worry about when we will make a change.

**Comment by corbinu** [comment]
I am ok with whatever is set mostly wanted clarity. I will say I am still confused about v5 support and what will happen for v7 after v8 drops.

**Comment by not-an-aardvark** [comment]
* We still support Node 5 -- it was the current version of Node when we did our last major release. However, Node 5 has reached EOL and no longer receives any updates (including security fixes) from Node, so I would not recommend using it.
* It's likely that the same scenario will occur with Node 7 when Node 8 comes out.

Regardless of what happens with Node 5, we will probably still support Node 4 for awhile longer because it's an [LTS version](https://github.com/nodejs/lts). So we wouldn't have much to gain from dropping support for Node 5, because we would still only be able to use ES6 features supported by Node 4.

**Comment by corbinu** [comment]
Ok thats fine ... like I said just wanted clarity on the policy... what it is matters little to me. Yes my original proposal was to support node 4 until end of life

**Comment by nzakas** [comment]
To put this concisely: Node 4 is the minimum we support, so read it as Node >= 4. Node EOLing Node 5 has no effect on our support of it. We don't get into the differences between even and odd numbered Node versions. (Again, we aren't affected by external decisions about Node versions or support).
