### ISSUE TITLE
executeOnFiles docs refer to top-level source property

### ISSUE THREAD

**Issue by mightyiam** [eslint/eslint#7944]
There's a line in [the `executeOnFiles` API docs](http://eslint.org/docs/developer-guide/nodejs-api#executeonfiles):

> Please note: the source property will be removed from the linting messages returned in messages in an upcoming breaking release. If you depend on this property, you should now use the top-level source or output properties instead.

The part about the top-level source property is different than [the equivalent line for the `linter.verify`](http://eslint.org/docs/developer-guide/nodejs-api#linter) docs:

> Please note: the source property will be removed from the linting messages in an upcoming breaking release. If you depend on this property, you can still use the getSourceCode method described below to get the line of code for each message.

This makes me think that perhaps the line for `executeOnFiles` is out of date.

**Comment by platinumazure** [comment]
I'm not familiar enough with the core internals to know which of those documentation lines are accurate or not, so I'll have to leave it to another team member. Thanks for the report!

**Comment by vitorbal** [comment]
Thanks for the report. The difference in the docs is intentional because `executeOnFiles` returns an object with a top-level property `source` that contains the full source code, but `linter.verify` returns just the array of errors/warnings, so the top-level `source` prop is not available in this case (that's why the docs suggest using `getSourceCode` instead).
Hopefully that makes sense. Do you think there's anything we could do to make this more clear in the docs?

**Comment by vitorbal** [comment]
Thinking about this some more, it looks like perhaps the phrase "the source property will be removed from the linting messages [...]" could be the source of confusion.
That phrase is supposed to mean that *only* the inner `source` properties, the ones that are part of each error/warning in the array, are deprecated, not the top-level one.
Maube it can be rephrased for clarity.

**Comment by mightyiam** [comment]
I feel fine with closing this as not a bug.
