### ISSUE TITLE
no-else-return and no-useless-return autofixers cause incorrect code

### ISSUE THREAD

**Issue by alangpierce** [eslint/eslint#8026]
**Tell us about your environment**

* **ESLint Version:** 3.14.1
* **Node Version:** 6.9.1
* **npm Version:** 3.10.8

**What parser (default, Babel-ESLint, etc.) are you using?** default

**Please show your full configuration:**

```
module.exports = {
  rules: {
    "no-else-return": "error",
    "no-useless-return": "error"
  }
};
```

**What did you do? Please include the actual source code causing the issue.**

I ran `eslint --fix` on a file with this code:

```js
function f() {
  if (true) {
    return;
  } else {
    return 1;
  }
}
```

**What did you expect to happen?**

I expected the resulting code to have the same behavior. I don't care which of the two autofixes it applies, but it shouldn't apply both.

**What actually happened? Please include the actual, raw output from ESLint.**

eslint gave no output and changed the code to this:

```js
function f() {
  if (true) {
    
  } 
    return 1;
  
}
```

This code behaves differently because the function now always returns `1` instead of `undefined`.

The real-world case I ran into is that it's causing a test failure after running some automatic conversions, including `eslint --fix`, to convert the autoprefixer project from CoffeeScript to JavaScript: https://github.com/decaffeinate-examples/autoprefixer/blob/decaffeinate/lib/hacks/break-props.js#L51

Looks like this bug was introduced in eslint 3.14.0 when the new no-else-return autofixer was added.

**Comment by not-an-aardvark** [comment]
I can reproduce this, thanks for reporting.

This is similar to https://github.com/eslint/eslint/issues/7928 -- the fix is independently correct for both rules, but it breaks when both fixes are applied at the same time. To fix this we need to make the conflict detection more strict in [source-code-fixer](https://github.com/eslint/eslint/blob/8ea98f9cc0c8444fcd38b6871ceb320067a5dc4b/lib/util/source-code-fixer.js).

As a workaround for the moment, I suppose you could run `eslint --fix` with one of the rules disabled (e.g. `eslint foo.js --fix --rule 'no-else-return: 0'`) followed by a regular fix run (`eslint foo.js --fix`).

**Comment by alangpierce** [comment]
👍 thanks. I left a comment on that issue, since it seems like there's already some discussion on how to approach this type of thing.
