### ISSUE TITLE
[Feature Request] Specify "fix" from eslint config file

### ISSUE THREAD

**Issue by indexzero** [eslint/eslint#8041]
> 👋 Been reading through some code and based on what I've learned I do not think this feature exists currently. If I am wrong I apologize for the bother. 

1. In [`lib/cli.js`](https://github.com/eslint/eslint/blob/master/lib/cli.js#L169-L176) only CLI arguments are valid for `--fix`.
2. Config is not read until [`processText` in `lib/cli-engine.js`](https://github.com/eslint/eslint/blob/master/lib/cli-engine.js#L224).

This means that if one were to have an eslint config such as:

**`.eslintrc`**
``` js
module.exports = {
  extends: 'eslint:recommended',
  fix: true
};
```

Then `fix` will completely be ignored. Is this a feature that other folks using `eslint` find useful? A previous incantation of a code styleguide we enabled auto-fix via binaries, but since the `eslint` convention is to extend a base config this approach feels less natural. 

If there is interest I'd be happy to put together a PR for this.

**Comment by ilyavolodin** [comment]
Unfortunately, this would not really be possible, due to the fact that config files cascade. As in, you can have multiple config files in different sub-directories they can also extend from each other. What should happen if one of the files have `fix` in it, and others don't? This could lead to a lot of very strange and unpredictable behaviors. This is the reason why we avoided moving global CLI flags into configs.

**Comment by indexzero** [comment]
I can appreciate that from an ecosystem perspective. As an `eslint` user I would always expect the last mile to win. So if I depend on a config that turns on `fix` then I can turn it off. 

Our use-case is mainly for things like Standard, XO, or in our case [`godaddy/javascript`](https://github.com/godaddy/javascript) where the users are primarily consuming one config file as a single source or truth. We've worked around this with [a custom binary we ship](https://github.com/godaddy/javascript/blob/master/packages/eslint-config-godaddy/cli.js) that turns on auto-fix.

**Comment by nzakas** [comment]
The larger problem is that "fix" is a global mode for the entire CLI -- we don't have a way to fix just some files. This is different from things in the config file that are applied based on the folder structure and cascade. 

I'd also echo the concern about spreading configs that bring autofixing with them. We try to be very transparent about what configs will and won't do just by including them (we had to change the behavior of plugins early on due to some unexpected side effects when you referenced a plugin from a config).

I don't think this is a good fit for our approach.

**Comment by alberto** [comment]
Thanks for your interest in improving eslint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after 21 days tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
