### ISSUE TITLE
Merge configs with their ancestors

### ISSUE THREAD

**Issue by spadgos** [eslint/eslint#820]
Currently, if you have multiple eslintrc files in a directory hierarchy, whichever one is "closest" wins. This is good for simplicity, but does create problems if you want files in a certain directory to have only one or two different rules.

An example might be that you have a project-wide .eslintrc file in the root of your project which defines all the linting rules, globals, etc. In a "tests" directory however, you might want to have some extra globals (eg: ones defined by the test framework), but you have to _duplicate_ the base .eslintrc file and then make sure you keep the two in sync if the rules ever change. Same could apply if you have some front-end JS as well as NodeJS files in the same project, which might have slightly different conventions.

My suggestion is to step up through the directories, merging together all .eslintrc files.

Your thoughts?

**Comment by ljharb** [comment]
I'm running into trouble with the merging behavior - a module A has a newer version of eslint with a new rule. it's dep is module B, which has an older version, and an eslintrc that doesn't have the new rule. In module A, `npm explore B npm run eslint` (where `npm run eslint` eslints my files), errors, because B's `eslint` is walking upwards and grabbing the incompatible eslint file from project A.

Is there a way I can disable the merging behavior, so that the first one found wins?

**Comment by mzgol** [comment]
@ljharb why do you need to run ESLint on a dependent package? Shouldn't it be linted in its own repository?

**Comment by ljharb** [comment]
@mzgol es7-shim's `npm test` runs the tests of all its dependents, and those dependents include linting as part of their tests.

But, it seems nonsensical that simply moving a directory elsewhere would change the output of a command that should be deterministic :-/ Creating `/.eslintrc` shouldn't break eslint on every project on my computer.

**Comment by mzgol** [comment]
@ljharb It seems #2736 should resolve your problems?

**Comment by ljharb** [comment]
aha, thanks!

**Comment by zanona** [comment]
I am not sure if this belongs to this issue however when having the following structure:

```
~/.eslintrc.yaml
~/path/to/my/project/.eslintrc.yaml
```

where `~/.eslintrc`

```yaml
parser: babel-eslint
plugins: [ html ]
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures: { jsx: true }
env:
  es6: true
  node: true
  browser: true
...
```
and `~/path/to/my/project/.eslintrc.yaml`

```yaml
globals:
  WebC: false
```

Where the file inside my project is reseting the configuration set on my home directory rather than extending it? Is this the intended behaviour?

```
sh-3.2$ eslint -v
v2.3.0
sh-3.2$ node -v
v5.7.1
sh-3.2$ npm -v
3.6.0
```

**Comment by ilyavolodin** [comment]
@zanona Configuration in home directory will only be used if no other configuration is found. This is intended behavior.
