### ISSUE TITLE
Support ES6+ by default

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8290]
A discussion about changing the default parser options came up on Gitter today. Currently, we only parse ES5 by default, and we don't have ES6 globals enabled. ES6 usage is fairly widespread now, and based on an [unscientific twitter poll](https://twitter.com/gyandeeps/status/843277118654025729) it seems like the community is overwhelmingly in favor of turning on ES6 by default. There are a few questions to consider:

* A significant amount of people still use ES5. At what point would we decide that the percentage of people using ES5 is "low enough" to change the default to ES6? (Should we even care about usage statistics?)
* Should we just always default to the latest official version (and change the default in major releases)? Arguably, once a feature reaches stage 4 developers should start using it, and if they want to restrict the version for browser compatibility then they can pin to a version in their config.

One potential advantage of having these features off-by-default is that if someone wants to use ES6 while eslint defaults to ES5, they'll notice the misconfiguration very quickly (eslint will throw a parsing error) and so they'll know to fix their config. On the other hand, if they don't want to use ES6 and eslint defaults to supporting ES6, they might not notice anything is wrong until they try using an old browser.

That said, I don't think we should default to ES5 forever, so we should figure out what criteria we use to determine when to upgrade the default parser options.

**Comment by ljharb** [comment]
ES5 should stop being the default when the most common set of supported browsers support ES6 - since that list still includes IE 9-11 for many people, that might be awhile.

Until then, the default should be whatever is safest - and that is ES5. (technically ES3, but, that ship has sailed)

**Comment by not-an-aardvark** [comment]
Wouldn't it be "safest" to not run at all until the user specifies a version? At some point I think we have to set a reasonable default that makes some assumptions about the common case.

**Comment by ljharb** [comment]
@not-an-aardvark yes, that would be totally ideal! The problem is that most users won't *know* how to decide what version they use, so to be truly safe, `eslint` would have to ask them which browsers/engines they want to support, and then use compat-table or browserlist data or similar to figure out the lowest common denominator that eslint should target.

imo the common case is still ES5 - I severely doubt that the majority of applications use babel, because I suspect very few applications are keeping up to date on best and common practices.

**Comment by not-an-aardvark** [comment]
Ok, thanks for the feedback. (I'm still undecided on this -- just playing devil's advocate.)

**Comment by ljharb** [comment]
[np](https://xkcd.com/1432/) :-)

**Comment by platinumazure** [comment]
There are a lot of big companies whose users aren't typically close ESLint followers (or team members!) who will be stuck on ES5 for a long time, so I would be in favor of staying with ES5 by default. I also think that if ES6+ changes tend to be backward compatible, then I would prefer new users start with lowest common denominator and then work their way towards new language features. Better that they get early feedback right away than use ES6 for development and not realize until it's too late that they're using language features unsupported by their target environment.

**Comment by nzakas** [comment]
I also think ES5 is the best default for now. Not only is that the lowest common denominator, but making such a change could be a significant pain for people who are currently using the default (they'd all have to change their configs -- something we try to prevent whenever possible due to the pain).

I think a better intermediate solution is just to enhance `--init` to ask what version people want to use and then list out all the supported versions with the most recent as the default. There's no real pain for new users that way.

**Comment by kaicataldo** [comment]
I'm torn on this.

Ideally, I don't think ESLint should be making the call of when we think ES6, ES2017, ES2018, and so on are "widespread enough" to turn on by default. In other words, I think ESLint should track the finalized language spec rather than the implementation of it. Since ESLint is pretty strict about supporting stage 4 features (with a few exceptions), it would support all spec-finalized features by default and, since we have the `ecmaVersion` config option, a configuration could effectively be pinned and wouldn't be affected by future changes to the default.

That being said, those who are currently using ES5 also might not be really aware of new language features, transpilers, etc., and so having to make these decisions might be especially burdensome for them. I also don't know if it's worth the pain of forcing any current configs without an `ecmaVersion` specified to have to include one.

> The problem is that most users won't know how to decide what version they use, so to be truly safe, eslint would have to ask them which browsers/engines they want to support, and then use compat-table or browserlist data or similar to figure out the lowest common denominator that eslint should target.

We discussed this in the Gitter a bit too - could be a cool thing to explore!

**Comment by nzakas** [comment]
Just so we are clear on semantics, when we say "by default" we mean ecmaVersion is not specified in the config they are using. That is likely to occur in the following situations:

1. Someone who is new to ESLint and has copy-pasted a config without running `--init`. 
2. Someone who has inherited a project with an existing config. 
3. Someone who intentionally wants to use ES5.

If someone doesn't have a config, then they get an error and hopefully run `--init`, which can guide them through picking the correct setup (again, I think having an ecmaVersion selection defaulted to the latest would help here).

My larger point is the situation of a new user who would benefit from having ESLint default to the latest ecmaVersion doesn't seem like a very likely scenario. Those people who need ES > 5 tend to figure out what to do fairly quickly. 

For some context: we decided to default to ES5 because ES6 adds new globals (which we add via the es6 environment). We don't currently have a way to configure globals to be removed, so it made sense to start with the lowest version and then add on to that. 

I also don't think we need to keep ES5 the default forever, but I think it's premature to change at this point (and 4.0 is definitely too soon to consider it). We would need to figure out a better strategy for dealing with the addition/removal of globals first in any event.

**Comment by kaicataldo** [comment]
@nzakas Thanks for the context - makes sense to me. Maybe we should table this discussion for now and make a new issue for adding the version of ECMAScript the user wants to their config using `--init`?

**Comment by nzakas** [comment]
That would be my recommendation.

**Comment by not-an-aardvark** [comment]
Looks like the consensus is to not change the default for now, so I'll close this issue.
