### ISSUE TITLE
[documentation] config eslint to check typescript code

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#8388]

**Comment by not-an-aardvark** [comment]
Based on the description you've given, it's hard to tell what you're suggesting. However, feel free to make a pull request with suggested changes.

**Comment by Aladdin-ADD** [comment]
How to config eslint to check typescript code? I didn't see any guide about it, Can we add it?

**Comment by not-an-aardvark** [comment]
Thanks for clarifying. I would recommend taking a look at [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser).

**Comment by Aladdin-ADD** [comment]
Thanks for your patience. Many developers may not be aware of this. we can add it to eslint docs. you recon?

**Comment by platinumazure** [comment]
@Aladdin-ADD The typescript-eslint-parser is still experimental at this point, so I would rather defer to the developers there with regard to whether we should add an FAQ or documentation entry at this point.

@JamesHenry @soda0289 Any thoughts on this?

cc @nzakas

**Comment by soda0289** [comment]
I'm concerned about adding the typescript parser to the docs since there are several known issues. This includes recommended rules not working as expected and some plugins causing infinite loops. The more users the parser has the faster bugs can be found and fixed. If we did add it we would have to place a note warning of it's experimental/alpha state. As well we should keep of list of known issues on the typescript parser README to warn users of potential issues.

**Comment by ilyavolodin** [comment]
While typescript-eslint-parser is part of ESLint org, it's a stand-alone project, and I'm not sure it should be advertised in ESLint documentation. By default ESLint works only with stage 4+ features of EcmaScript. Everything else is customization. We can definitely add a link to the site to typescript parser, just like we have a link to babel-eslint, but creating documentation for it on the site is probably an overkill.

**Comment by not-an-aardvark** [comment]
Closing because this question has been answered.
