### ISSUE TITLE
eslint reports parse errors for file containing /* eslint-disable */

### ISSUE THREAD

**Issue by jedwards1211** [eslint/eslint#8419]
**Tell us about your environment**

* **ESLint Version:** `3.18.0`
* **Node Version:** `6.5.0`
* **npm Version:** `3.10.10`

**What parser (default, Babel-ESLint, etc.) are you using?**
`babel-eslint`

**Please show your full configuration:**

```
{
  "parser": "babel-eslint",
  "plugins": [
    "react", "flowtype"
  ],
  "extends": "eslint:recommended",
  "ecmaFeatures": {
    "jsx": true,
    "modules": true,
    "experimentalObjectRestSpread": true
  },
  "rules": {
    "comma-dangle": 0,
    "strict": 0,
    "no-unused-vars": [1, {"args": "none", "varsIgnorePattern": "React"}],
    "no-console": 1,
    "react/react-in-jsx-scope": 1,
    "no-extra-semi": "error",
    "semi": ["error", "never"],
    "flowtype/boolean-style": [
      2,
      "boolean"
    ],
    "flowtype/define-flow-type": 1,
    "flowtype/delimiter-dangle": [
      2,
      "always-multiline"
    ],
    "flowtype/generic-spacing": [
      2,
      "never"
    ],
    "flowtype/no-dupe-keys": 2,
    "flowtype/no-primitive-constructor-types": 2,
    "flowtype/semi": [
      2,
      "never"
    ],
    "flowtype/space-after-type-colon": [
      2,
      "always"
    ],
    "flowtype/space-before-generic-bracket": [
      2,
      "never"
    ],
    "flowtype/space-before-type-colon": [
      2,
      "never"
    ],
    "flowtype/union-intersection-spacing": [
      2,
      "always"
    ],
    "flowtype/use-flow-type": 1
  },
  "env": {
    "meteor": true,
    "browser": true,
    "node": true,
    "es6": true,
    "commonjs": true
  },
  "globals": {
    "ReactClass": false,
    "FunctionalComponent": false,
    "ReactTag": false,
    "Roles": false
  },
  "settings": {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": true
    }
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
/* eslint-disable */
// @flow

declare module 'test' {
  declare class Blah {
    @@iterator(): Iterator<any>;
  }
}
```

**What did you expect to happen?**
No  eslint errors on **any** file with `/* eslint-disable */`.  I'm sure the problem is that you have to wait for the parser output to look for `/* eslint-disable */` comments... but you could at least check if the file begins with it before parsing.

**What actually happened? Please include the actual, raw output from ESLint.**
```
temp.js
  6:5  error  Parsing error: Unexpected token

  4 | declare module 'test' {
  5 |   declare class Blah {
> 6 |     @@iterator(): Iterator<any>;
    |     ^
  7 |   }
  8 | }
  9 | 
```

**Comment by gyandeeps** [comment]
I think its working as design. If you want to ignore a file then just dont pass them to eslint for linting.
For ignoring you can use `.eslintignore` file or use glob.
I hope this helps.

**Comment by not-an-aardvark** [comment]
Hi, thanks for the report.

It's [documented](http://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments) that `eslint-disable` only disables rules and not parse errors, because as you said, the file needs to be parsed to find the comments. I don't think adding a special case for a comment at the top of a file is a good idea, for a few reasons:

- It would cause a confusing behavior switch if something in the file changes (e.g. if another line is added before the comment).
- It wouldn't work correctly if the comment contained an `/* eslint-enable */` comment later on. The comment wouldn't ever be noticed if eslint skipped parsing the file as soon as it saw `/* eslint-disable */`.

Instead of a disable comment in this case, I would recommend using an `.eslintignore` file instead.

**Comment by jedwards1211** [comment]
okay, sorry, I should have just read through those docs.
