### ISSUE TITLE
Autofix adds unnecessary spaces in template string expression

### ISSUE THREAD

**Issue by ndresx** [eslint/eslint#8520]
**Tell us about your environment**

* **ESLint Version:** 3.19.0
* **Node Version:** 6.10.2
* **npm Version:** 3.10.8

**What parser (default, Babel-ESLint, etc.) are you using?**
default

**Please show your full configuration:**

```
{
  "env": {
    "browser": true,
    "es6": true
  },
  "rules": {
    "prefer-template": "error"
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
const test = 'bar';
const templateStr = 'foo' + test;
```

**What did you expect to happen?**
```js
const test = 'bar';
const templateStr = `foo${test}`;
```

**What actually happened? Please include the actual, raw output from ESLint.**
`--fix` adds unnecessary spaces inside the expression.
```js
const test = 'bar';
const templateStr = `foo${  test}`;
```

**Comment by not-an-aardvark** [comment]
Thanks for the report. This is working as intended -- the rule preserves spacing there so that it doesn't end up removing any comments that might appear on either side of the operator. You can use [`template-curly-spacing`](http://eslint.org/docs/rules/template-curly-spacing) if you want the whitespace there to be automatically removed.

**Comment by ndresx** [comment]
@not-an-aardvark Thanks and sorry then. With the additional rule it's working fine!
