### ISSUE TITLE
no-undef: option to not error on guarded usages

### ISSUE THREAD

**Issue by ethanresnick** [eslint/eslint#8549]
Hi, I want to propose a new feature for the `no-undef` rule.

Some background on the problem: I'm writing code intended to run on both the browser and the server, so I've set up Eslint to warn me if I use a global that isn't defined in both environments, using the `no-undef` rule. This is lovely. Often, though, I find myself having to suppress errors from this rule that I know are non-problematic, which is annoying.

The most common case is when I want to write code just for the browser, and I guard that code with a `typeof` check that the browser global is present before I use it. Often, it's idiomatic to guard this code in the same expression as my use of that global. Therefore, I have many lines like:

```js
const userAgent = typeof navigator !== "undefined" && navigator.userAgent;

typeof someTrackingGlobal === "function" && someTrackingGlobal('trackX');

typeof window !== "undefined" && window.addEventListener('resize', ...);
//etc
```

All the lines above cause errors, though, because the no-undef rule sees the uses of `navigator` and `someTrackingGlobal` as uses of undefined variables.

My proposal, therefore, would be to extend the no-undef rule to look at the expression in which usage occurs (tracking usage beyond one expression is, I imagine, totally impractical). If the usage is guarded by a `typeof` check, it wouldn't be an error. For starters, the rule might look for the guard just by checking previous operands in an `&&`, as in the examples above, or in the conditional part of a ternary.

We'd have to spell out exactly which forms of `typeof` would satisfy the rule that the variable usage is guarded, but i'm imagining any `typeof` check with `!=` or `!==` to the literal string `"undefined"`, or with `==` or `===` to any literal string that isn't `"undefined"`.

**Comment by ilyavolodin** [comment]
Duplicate of https://github.com/eslint/eslint/issues/7636, https://github.com/eslint/eslint/issues/6209 and https://github.com/eslint/eslint/issues/3684

**Comment by ethanresnick** [comment]
@ilyavolodin Thanks for pointing out those prior issues. I missed them somehow. It looks like they were closed because what they proposed would've been too hard to implement. However, my proposed solution here is simpler, if admittedly more limited. Rather than doing a full code-path analysis, I'm proposing just checking the surrounding expression. Doing that won't eliminate all of the rules false positives, but I think it's better than nothing.

I've put together a PR in #8558 showing, I hope, that something like this is relatively doable. I'm not very familiar working with ASTs, or with ESLint's various AST helpers (escope, estraverse), so my code is probably not very good, but hopefully it suffices as a proof of concept.

**Comment by ethanresnick** [comment]
Any thoughts on this? (Not sure who to tag, so tagging eslint team folks who commented on the prior issues about this: @ilyavolodin @not-an-aardvark @nzakas @platinumazure.)

**Comment by platinumazure** [comment]
Yowzer, this has sat for a while. Sorry about this, @ethanresnick.

I'm worried that implementing this would result in requests to check if statements and otherwise do full code path analysis things. I'm not really opposed at this point, just on the fence.

@eslint/eslint-team Thoughts? Would anyone like to champion this?

**Comment by ethanresnick** [comment]
Anything I can do to move this forward? @platinumazure

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement it as a separate rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.
