### ISSUE TITLE
Can ESLint runtime dependencies be reduced?

### ISSUE THREAD

**Issue by freshp86** [eslint/eslint#8603]
Currently running `npm install eslint` downloads 24MB of dependencies. Are all those deps needed to run ESLint?

I am looking for potential ways to reduce the size of the downloaded dependencies (even if I have to do this locally after I call `npm install`). The reason is that I am trying to introduce ESLint to Chromium's JS codebase, and would like to minimize the overhead imposed on other Chromium developers as much as possible.

For example
* Can I remove  `js-yaml` dependency, if my config file is provided in JS?
* Can I remove  `strip-json-comments` dependency, if my config file is provided in JS?
* Can I remove `doctrine` dependency if I turn off  the [valid-jsdoc rule](https://github.com/eslint/eslint/blob/40b8c6906db24d2c3da3a587f9765e57542367f6/lib/rules/valid-jsdoc.js#L11)?
* Are there other similar cases where a big chunk of dependencies can be pruned if I don't use a specific feature?

Also one more dependency that seems unnecessary is 
[user-home](https://github.com/sindresorhus/user-home) since it can be replaced by a call to the NodeJS [os.homedir()](https://nodejs.org/api/os.html#os_os_homedir). Perhaps I should file a separate issue for the latter.

**Comment by freshp86** [comment]
cc @danbeam

**Comment by platinumazure** [comment]
@freshp86 Definitely please create a separate issue for `os.homedir()`. Seems to be available since Node 2.3 which is before our lowest supported version of Node 4, so I'd love for us to switch to that unless `os.homedir()` has bugs or odd behavior that the user-home package circumvents.

**Comment by not-an-aardvark** [comment]
> * Can I remove  `js-yaml` dependency, if my config file is provided in JS?
> * Can I remove  `strip-json-comments` dependency, if my config file is provided in JS?
> * Can I remove `doctrine` dependency if I turn off  the [valid-jsdoc rule](https://github.com/eslint/eslint/blob/40b8c6906db24d2c3da3a587f9765e57542367f6/lib/rules/valid-jsdoc.js#L11)?

I think all of those should *probably* work. However, our semver/backwards compatibility guarantees would not cover removing dependencies.

For example, if you remove the `doctrine` dependency and enable the `require-jsdoc` rule, everything should still work right now, because `require-jsdoc` does not depend on `doctrine`. However, it's plausible that we would update `require-jsdoc` to use `doctrine` in the future, even in a patch release. In that case, your build might break if you upgrade without modifying the dependencies.

Another thing to note is that all module files in ESLint typically get loaded, regardless of whether you use a particular rule. For example, [this line of code](https://github.com/eslint/eslint/blob/a93a2f951e6a463945c8c1f9673fa4cf31848d7a/lib/rules/valid-jsdoc.js#L11) will get executed even if you don't enable the `valid-jsdoc` rule. (However, everything inside [this function](https://github.com/eslint/eslint/blob/a93a2f951e6a463945c8c1f9673fa4cf31848d7a/lib/rules/valid-jsdoc.js#L62) will not get executed.) To prevent the `require` call from throwing errors, it might be necessary to stub out removed dependencies, e.g. by creating an empty `node_modules/doctrine/index.js` file.

> Are there other similar cases where a big chunk of dependencies can be pruned if I don't use a specific feature?

* I think `concat-stream` can be removed if you're not piping code from stdin.
* `babel-code-frame` can be removed if you're not using the `codeframe` formatter
* `table` and `pluralize` can be removed if you're not using the `table` formatter
* `text-table` can be removed if you're not using the `stylish` formatter (this is the default formatter)
* `json-stable-stringify`, `file-entry-cache`, and `imurmurhash` can be removed if you're not using cache files
* `inquirer` and `progress` can be removed if you're not using `eslint --init`
* `require-uncached` can be removed if you're using JSON or YAML config files

There might be others that I've missed.

Also, looking at the dependency list, I think there are some other dependencies that we can replace easily:

* `shelljs`
* `path-is-inside`
* `strip-bom`

**Comment by freshp86** [comment]
@platinumazure: Filed https://github.com/eslint/eslint/issues/8604 for user-home removal.

**Comment by freshp86** [comment]
@not-an-aardvark Thanks for the detailed response. I will try those reductions in the coming days.

**Comment by not-an-aardvark** [comment]
Closing because the question has been answered.
