### ISSUE TITLE
hyphenless (JS compatible) rule name

### ISSUE THREAD

**Issue by gulping** [eslint/eslint#8643]
I'm using ESLint 3.19.0.

Issue
-----

Many ESLint rule names and rule options include hyphen.
In JS(ES6), identifier cannot include hyphen.
cf: [Variables - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Variables)

Therefore, in JS format configuration file, rule names as object keys should be quoted.

It causes a bit of frustration.
(just a stylistic issue)

My take on it
-----
I think that ESLint might as well accept `snake_case` or/and `lowerCamelCase` alias rule name that don't need to be quoted.

**Comment by ilyavolodin** [comment]
We could try doing this going forward, but we wouldn't be able to change existing properties, since it would be a major breaking change that would affect more or less every user out there. And in that case, I value consistency over style. If we can't rename existing properties, we might as well try to stay consistent with them.

**Comment by platinumazure** [comment]
Devil's advocate argument: We could write a jscodeshift transform that would allow users to fix this automatically for core rules.

That said, I otherwise completely agree with @ilyavolodin and don't consider this to be worthwhile.

**Comment by not-an-aardvark** [comment]
If I'm understanding correctly, @gulping wasn't suggesting renaming all the rules (as this would be a major breaking change) -- instead, the suggestion was to automatically interpret names like `new_parens` in a config file as references to the `new-parens` rule.

**Comment by ilyavolodin** [comment]
Ah, I see, that would not be a breaking change. However, I think it will introduce a lot of confusion. Somebody who is going to look at aliased config file, might not find options in documentation. Right now I'm not convinced that this is something that's worth the risk. We usually try to avoid having multiple ways of doing the same thing.

**Comment by krvikash35** [comment]
i use js over other configuration file. Due to this, i am not able to use object dot notation. It would be welcoming feature if implemented.
`
Actual
eslint.rules['array-bracket-spacing'] = ["error", "never"]

Expected
eslint.rules.arrayBracketSpacing = ["error", "never"]
eslint.rules.array_bracket_spacing = ["error", "never"]
`

**Comment by not-an-aardvark** [comment]
Personally, I don't think it's worth introducing the complications of automatically converting camelcase rule names just for the benefit of making config files more concise.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get enough support from the team and so I'm closing it. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to reach consensus after a long time tend to never do it, and as such, we close those issues. This doesn't mean the idea isn't interesting, just that it's not something the team can commit to.
