### ISSUE TITLE
minor rephrasing in documentation: advanced configuration

### ISSUE THREAD

**Issue by sudarsangp** [eslint/eslint#8674]
Under [**Specifying Environment**](http://eslint.org/docs/user-guide/configuring#specifying-environments) section 

_existing_
If you want to use an **environment from a plugin**, be sure to specify the plugin name in the plugins array and then use the unprefixed plugin name, followed by a slash, followed by the environment name

_suggestion_
If you want to use a **plugin in an environment**, be sure to specify the plugin name in the plugins array and then use the unprefixed plugin name, followed by a slash, followed by the environment name

**Comment by platinumazure** [comment]
Hi @sudarsangp, thanks for the issue!

In that context, an "environment" is a set of globals and other options which are exported that are supposed to simulate an execution environment. For example, "browser" is an environment that exports the `window` global, everything related to the DOM that should be global, etc. So in this case, plugins can actually specify these "environments" and the phrasing is correct (if, perhaps, unclear).

I would be okay with using "environment configuration" (or similar) instead of "environment" in those cases, but that would basically require the team agreeing on changing canonical terminology and getting that updated across all of our docs.

**Comment by not-an-aardvark** [comment]
Closing because the documentation is correct, but feel free to make a PR if you think it could be clearer.
