### ISSUE TITLE
[proposal] merge eslint with babel

### ISSUE THREAD

**Issue by lx93uv** [eslint/eslint#8687]
`eslint` use `espree` parser, built on top of `acorn.js`.
`babel` use `babylon` parser, built on top of `acorn.js`.

I think, it's will be great if  `eslint` and `babel` become a single project - it will be perfect suite for `js` developing.

**Comment by not-an-aardvark** [comment]
Thanks, for the suggestion, but I don't think this makes sense to do. It's true that they both happen to use parsers, but eslint and babel do completely different things.

**Comment by Aladdin-ADD** [comment]
more detail: https://github.com/eslint/espree#why-another-parser

**Comment by lx93uv** [comment]
repost of my message from `https://github.com/babel/babylon/issues/564`:
>As I understand, technically both eslint and babel developers can unite efforts to contributing of acorn. IMHO, if several projects use the same piece of software, they should unify it's interface and contribute to it together together.
>
>From developer point of view, work can be represented as stream from
>compiling from es6/7/etc to es5 according to babel-env
>linting, static analysis (eslint)
>minifying (babili)
>so, all tasks can be implemented as acorn plugins, isn't it?

**Comment by not-an-aardvark** [comment]
> IMHO, if several projects use the same piece of software, they should unify it's interface and contribute to it together together.

`acorn` is already a separate dependency, so it seems like that has already happened.

> From developer point of view, work can be represented as stream from
compiling from es6/7/etc to es5 according to babel-env
linting, static analysis (eslint)
minifying (babili)

You're describing several unrelated steps in a very specific workflow. It makes sense for these to be different projects because they're doing different things and there's no reason to combine them. We currently have a few very flexible tools that can be used in many different ways, and I'm not interested in replacing them with a monolithic tool that does too much.

> so, all tasks can be implemented as acorn plugins, isn't it?

No, that's not really how acorn plugins work. An "acorn plugin" is a hook that can be used with acorn to generate a different AST, not just any project that uses acorn for something.

**Comment by Aladdin-ADD** [comment]
![image](https://user-images.githubusercontent.com/13050025/27444436-f4d286fa-57a8-11e7-878a-62e3524eedd4.png)
