### ISSUE TITLE
Indent option for JSX component props/attributes

### ISSUE THREAD

**Issue by caravinci** [eslint/eslint#8715]
As suggested in #8425, I'm opening a new issue in hopes to address an indent rule collision when writing JSX components, as its props/attributes are forced to be indented as if they were children, rather than with an option to align with the first one, not unlike functions, variables, arrays, etc.

It'd be great if we could format props like this, yet naturally, the regular indent does not like it.
```js
<RandomComponent className="stuff"
                 prop1={moreStuff} />
```

While I do realise the guidelines for requesting new rules specify avoiding requests for specific libraries or frameworks, the current implementation of indent conflicts with JSX, and ignoring JSX altogether --if I understand correctly-- implies disabling the regular indent rule, which would lead to missing out on other several other features.

This change I believe applies to most JSX environments, thought I'm currently using it with React. All modules in their current version as of this issue's creation.
- ESLint Version: 4.0.0
- Node Version: 8.1.0
- npm Version: 5.0.3
- Webpack + Babel-loader, extending eslint: recommended and react-plugin.

Thanks!

**Comment by not-an-aardvark** [comment]
For what it's worth, it will soon be possible to ignore only JSX without disabling the entire `indent` rule -- see https://github.com/eslint/eslint/issues/8594.

**Comment by hallaathrad** [comment]
That's great. but what exactly will be ignored in it? I'm afraid it would ignore more than just the indentation of the component's definition (or whatever this is called) and also ignore indentation for other pieces of JavaScript inlined therein.

Considering the relatively widespread usage of JSX wouldn't it be easier to add the same "first" option for these? (I honestly cannot possibly fathom the difficulty of such an addition). I can try to help contributing if someone can guide me.

**Comment by not-an-aardvark** [comment]
> That's great. but what exactly will be ignored in it? I'm afraid it would ignore more than just the indentation of the component's definition (or whatever this is called) and also ignore indentation for other pieces of JavaScript inlined therein.

It will ignore only the indentation of the properties, but it won't ignore inlined javascript (the indentation of inlined code will still be checked relative to itself).

> Considering the relatively widespread usage of JSX wouldn't it be easier to add the same "first" option for these? (I honestly cannot possibly fathom the difficulty of such an addition). I can try to help contributing if someone can guide me.

I'll copy a comment from https://github.com/eslint/eslint/issues/8709#issuecomment-307961485:

Maybe. The problem is that people have a wide variety of different indentation preferences, and the `indent` rule can't realistically support all of them. Instead, the rule has a limited set of options and will allow you to turn off checks for JSX. The idea is that you can use the rule even if you disagree with a particular part of what it enforces, and potentially use a custom rule to enforce your own preferences for JSX indentation.

This isn't to say that we're never accepting any more options, but there's a possibility that this won't be accepted, simply because we can't support everything.

---

As far as implementation is concerned, I *think* this would actually be pretty simple -- it would just require replacing the `1` in [this line](https://github.com/eslint/eslint/blob/c61194f9440981d6c858525273e5c469bdd98290/lib/rules/indent.js#L1298) with the user-provided option (e.g. a number or `"first"`).

**Comment by carlgieringer** [comment]
Is this what a rule using the new indent option to ignore indent for React attributes should look like?  (I'm guessing this requires eslint-plugin-react to know about the JSXAttribute node type.)

`{
  "rules": {
    "indent": [
      "warn",
      2,
      {
        "SwitchCase": 1,
        "ignoredNodes": [
          "JSXAttribute"
        ],
      }
    ],
  }
}`

**Comment by fnlctrl** [comment]
@carlgieringer It worked for me, thanks!

**Comment by ljharb** [comment]
Also note that forcing AST selectors means that users will have to "figure out" to add `JSXFragment` to that list once the syntax makes it into implementations; having a `jsx` option would prevent developers from having to know AST minutiae.

**Comment by klimashkin** [comment]
Option `first` for the [jsx-indent-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent-props.md) rule has been added to [eslint-plugin-react 7.9.0](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.9.0)
PR: https://github.com/yannickcr/eslint-plugin-react/pull/1729

**Comment by nzakas** [comment]
Unfortunately, it looks like there wasn't enough interest from the team or community to implement this change. While we wish we'd be able to accommodate everyone's requests, we do need to prioritize. We've found that issues failing to be implemented after 90 days tend to never be implemented, and as such, we [close those issues](https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue). This doesn't mean the idea isn't interesting or useful, just that it's not something the team can commit to.
