### ISSUE TITLE
Chore: add npm5 generated `package-lock.json` to git repo?

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#8742]
+ NPM 5 will automatically create a `package-lock.json` when installing packages unless there’s already npm-shrinkwrap.json in which case it will update it instead (if necessary).

+ The new `package-lock.json`  is never published and should be added to your version control system.

or if we do not add it to git repo, better add to `.gitignore`.

**Comment by soda0289** [comment]
I think we should just ignore it, but wouldn't mind either way. Also yarn.lock seems like a better solution since its easier to manage git conflicts with a plain file rather than a json file and they have plans to automate conflict handling.

We don't really update dependencies too much but I could see an advantage to locking in some dependency versions.

**Comment by not-an-aardvark** [comment]
I don't feel strongly about it either way, but I would lean towards adding it to gitignore. I think there's an advantage to using the same dependencies that our users will get (e.g. if we attempt to make a change that doesn't work on a newer version, the build will fail, which is good because it would break users.)

**Comment by gyandeeps** [comment]
Based on my experience at work, we should not add it to `.gitignore`.
When we do a release using `npm version <minor|patch|major` at that time it changes the version in `package.json` and `package-lock.json` and adds and commits them both using `git`. Then after that when we try to push git changes to origin, then git complains because `package-lock.json` has been added and committed but its also in your `.gitignore` file. I think it gives issue during add phase and not commit phase... can't remeber for sure... But then I started committing `package-lock.json`.

I also didn't like this.

**Comment by mysticatea** [comment]
I think we should not ignore `package-lock.json`. If `package-lock.json` exists, npm seems to ignore `package.json`. As a result, I guess local `package-lock.json` will cause confusing if `git pull` changes `package.json`.

I think our options are:

1. Add `package-lock.json` into our repo.
2. Add `.npmrc` which disables `package-lock.json` into our repo.

**Comment by gyandeeps** [comment]
> Add .npmrc which disables package-lock.json into our repo.

Just curious, what does this do?

**Comment by not-an-aardvark** [comment]
If we put `package-lock = false` in `.npmrc`, I think npm won't generate a `package-lock.json` file at all.

**Comment by gyandeeps** [comment]
nice... I did not know about that fact. Then I would do that.
