### ISSUE TITLE
Scheduled release for June 23, 2017

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8766]
The scheduled release on Friday, June 23, 2017 is assigned to:

* @ilyavolodin
* @not-an-aardvark

Please use this issue to document how the release went, any problems during the release, and anything the team might want to know about the release process. This issue should be closed after all patch releases have been completed (or there was no patch release needed).

**Comment by ilyavolodin** [comment]
Release did not go smoothly today. We ran into regression that wasn't covered by the unit tests (see #8791 for more info). We should try to fix it over the weekend and do a patch release as soon as it's fixed, since it has potential to break user configuration. Please only merge semver-patch PRs until the release cycle is complete.

**Comment by ilyavolodin** [comment]
4.1.1 released today. Please continue to merge only semver-patch fixes until we can determine if we will need another patch release.

**Comment by ilyavolodin** [comment]
We decided that we do not need another patch release. So this concludes release cycle and you can now merge semver-minor PRs.
