### ISSUE TITLE
4.1 breaks on extending multiple configs from a plugin

### ISSUE THREAD

**Issue by corbinu** [eslint/eslint#8792]
**Tell us about your environment**

* **ESLint Version:** 4.1.0
* **Node Version:** 8.0.3
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?**
default and typescript

**Please show your full configuration:**

```
{
  "plugins": [
    "@corbinu/corbinu"
  ],
  "extends": [
    "plugin:@corbinu/corbinu/base",
    "plugin:@corbinu/corbinu/node",
    "plugin:@corbinu/corbinu/lodash",
    "plugin:@corbinu/corbinu/relax"
  ],
  "rules": {
    "node/no-missing-require": "off"
  }
}
```

**What did you do? Please include the actual source code causing the issue.**
I upgraded to 4.1 and began seeing output as if "sourceType" was not set to module.

If I remove all the extends except for "plugin:@corbinu/corbinu/base" then things begin to resolve again or if I paste and merge the configs from each of those then everything reacts normally

Sorry know it makes it more complex to dig into my plugin the source is here: [https://gitlab.com/corbinu/eslint-plugin-corbinu](https://gitlab.com/corbinu/eslint-plugin-corbinu)

It is only a set of configs no rules of my own.

**Comment by not-an-aardvark** [comment]
The issue is that we're caching configs by file path [here](https://github.com/eslint/eslint/blob/7d9e3beeb58c1ee71d53dfcfd3e3b0721dd79b46/lib/config/config-file.js#L582), and we're not accounting for the fact that plugin-loaded configs all come from the same file path. As a result, if two configs from the same plugin are loaded simultaneously, only the one with higher precedence is getting used, and the other is getting pulled from the cache as the same object as the first config.

**Comment by corbinu** [comment]
@not-an-aardvark Thanks so much for looking into this I am just going to pin on 4.0.x for now :)
