### ISSUE TITLE
Discussion: eslint-recommended changes proposal

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#8865]
these rules can be candidate to added in next major release:

+ no-eval
+ no-implied-eval
+ no-with
+ no-new-func
+ no-array-constructor
+ no-new-wrappers
+ for-direction
+ getter-return (new added)
+ no-proto
+ require-await
+ no-return-await
+ no-useless-rename

**Comment by not-an-aardvark** [comment]
Thanks for the suggestions. I think rules in `eslint:recommended` are generally only supposed to catch programming errors, and they generally don't enforce other things (even best practices) because there are cases where they aren't applicable or would need to be disabled.

* `no-eval` / `no-implied-eval` / `no-new-func` -- In general it's not a good idea to use `eval`, but there are some cases where it's desirable if you know what you're doing (e.g. code generation algorithms)
* `no-with` -- I wouldn't mind adding this, but it also seems like more of a best practice rather than a possible error. That said, we also have `no-octal` in `eslint:recommended`, so maybe we could add this too.
* `no-array-constructor` -- Using the `Array` constructor is sort of strange, and I'm not sure why anyone would want to use it (for the multiple-argument case that the rule enforces), but I'm not sure if disallowing it actually helps to catch errors.
* `no-new-wrappers` -- :+1:
* `for-direction` -- :+1:
* `no-proto` -- Hmm, I'm not sure. Arguably, using `__proto__` should be avoided, but it might be the only option in ES5 for accessing the prototype of an object. I'm not sure this rule prevents errors.
* `require-await` -- :-1:. See https://github.com/eslint/eslint/issues/6820#issuecomment-257117990
* `no-return-await` -- I wouldn't mind adding this, although I think some people prefer using `return await` for consistency, and the extra tick usually isn't noticable.
* `no-useless-rename` -- Not sure, this seems like more of a stylistic concern to me.

**Comment by nzakas** [comment]
I think only for-direction is appropriate to add, as it catches an error. The rest are pretty subjective, so I'd vote :-1: on everything else.

**Comment by mysticatea** [comment]
I vote to only `for-direction` in the list, too.
Plus, I vote to `getter-return` what 4.2.0 released.

**Comment by Aladdin-ADD** [comment]
Maybe widely accepted best practice can even be added, is there a discussion on this?

**Comment by ilyavolodin** [comment]
@Aladdin-ADD eslint-recommended was designed to only contain possible errors and best practices rules, we specifically didn't include any stylistic rules, because those are based on the personal preferences, and there're a lot of different preferences out there.

**Comment by Aladdin-ADD** [comment]
I do understand. but rules in the list are mostly widely accepted best practice. 

no-eval, no-eval / no-implied-eval / no-new-func, no-with etc. these rules were included in almost every sharable config. so I'm thinking it is reasonable to add them.
