### ISSUE TITLE
editorconfig  + eslint  = automation formatting code

### ISSUE THREAD

**Issue by cybermerlin** [eslint/eslint#8941]
hi
i have use .editorconfig for configure eslint and formatting code.
how can i do it?

**Comment by not-an-aardvark** [comment]
ESLint can't be configured with an .editorconfig file -- see our [configuration docs](http://eslint.org/docs/user-guide/configuring) for more information on how to configure ESLint.

**Comment by platinumazure** [comment]
Hi @cybermerlin,

For what it's worth, I've been developing an [ESLint plugin](https://github.com/platinumazure/eslint-plugin-react) that would configure based on `.editorconfig`. However, I haven't published it because of the fact that plugin configurations are only loaded and read once, so nested `.editorconfig` files (in a project's subfolders) would not get picked up.

I've been meaning to open an issue here to try to figure out a way around that, but I've been busy and until now, I wasn't aware of any interest in the project.

Please follow that repository for updates. Thanks!
