### ISSUE TITLE
Make it more convenient to test rules with other parsers

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/eslint#8991]
Currently, to write a test for a rule that uses another parser, we do the following:

1. Run the parser on the source text externally
1. Copy-paste the AST into a file somewhere in `tests/fixtures`
1. Create a new "parser" which just returns that AST regardless of the source text
1. Use that new parser in the test

This is tedious and confusing (changing the source code in the test doesn't affect the AST). I think it would be better to include the parsers as `devDependencies` and use them directly in the tests.

**Comment by platinumazure** [comment]
Hmm... In order to avoid having every last parser as a devDependency (especially if it turns out that the only reason someone wants us to support a particular parser is because that particular parser spits out bad location information or a nonconforming AST), I wonder if we should have TSC institute a policy/process for approving when we want to add a new parser.

Maybe it's unnecessary (I expect that we'd at least ask questions during PR reviews), but it would be nice to have an official policy we can point to.

That said, I'm not opposed to the idea from a code maintenance perspective.

**Comment by not-an-aardvark** [comment]
> Hmm... In order to avoid having every last parser as a devDependency (especially if it turns out that the only reason someone wants us to support a particular parser is because that particular parser spits out bad location information or a nonconforming AST)

I'm not saying we should support every parser -- our policy for handling nonstandard or buggy parsers would remain the same. This would only affect the case where we were planning to add a test including the AST of a nonstandard parser anyway.

**Comment by nzakas** [comment]
@not-an-aardvark is this something you still want to address?

**Comment by not-an-aardvark** [comment]
It's not a high priority, I'll close this issue.
