### ISSUE TITLE
Other markup languages not supported

### ISSUE THREAD

**Issue by lil5** [eslint/eslint#9022]
**What version are you using?**
eslint -v
v4.3.0

**What did you do?**
```shell
eslint -c .eslint.hjson src/**
```

**What happened?**
Only checked issues based on default configuations.

**What did you expect to happen?**
Read the `.eslint.hjson`, parse and use the configuations in the file.

Please add support for other markup languages.
Like:
 - **HJSON** (Human JSON): `.hjson`
 - **JSON5** (ES5 JSON): `.json5`
 - **CSON** (CoffeeScript Object Notation): `.cson`
 - **YAML** (Yet Another Markup Language): `.yaml`
 - **TOML** (Tom's Obvious, Minimal Language): `.toml`
 - **INI** (Initialization File Format): `.ini`

Please consider using [NAML](https://www.npmjs.com/package/naml) npm package to support all

**Comment by not-an-aardvark** [comment]
Thanks for the proposal. Could you clarify what problem this proposal is trying to solve? What would be the benefit of supporting so many different config file formats?

My initial impression is that this isn't worthwhile, because it would increase fragmentation and make it more likely that a human is unfamiliar with the config file syntax when working on a project. However, I'm open to being convinced otherwise.

> **YAML** (Yet Another Markup Language): `.yaml`

We already support `.yaml` config files.

**Comment by lil5** [comment]
My main standpoint lies on the JSON variants

- HJSON
- JSON5
- CSON
- TOML

# Use-case

HJSON because unlike YAML does not look at tabs or spaces, yet is incredibly lose in terms of syntax
Like TOML

CSON will be welcoming under a coffeescript development environment
As JSON5 under es5, 6


# Markup language over saturation issue

I see it more as a choice the team leader or maintainer should have a choice in. Not a choice a linting tool has to make.

**Comment by not-an-aardvark** [comment]
I'm :-1: for this proposal because our current supported config file formats work fine, and adding these new formats doesn't seem useful enough to justify the additional complexity. If people really want to write their config files in other formats, they can do that and then use an `.eslintrc.js` file that parses the other file and exports the result.
