### ISSUE TITLE
RegExp: /[^\/]/ violates "no-useless-escape"

### ISSUE THREAD

**Issue by onlywei** [eslint/eslint#9092]
**Tell us about your environment**

* **ESLint Version:** Whatever is on the demo page
* **Node Version:** Whatever is on the demo page
* **npm Version:** Whatever is on the demo page

**What parser (default, Babel-ESLint, etc.) are you using?**
Whatever is on the demo page

**Please show your full configuration:**
Whatever the default is on the demo page

**What did you do? Please include the actual source code causing the issue.**
Go to [eslint.org/demo](http://eslint.org/demo). Leave all rules configurations as default, it should include the rule "no-useless-escape". Enter the following into the box: `/[^\/]/`.

**What did you expect to happen?**
I expect this to not have any lint warnings.

**What actually happened? Please include the actual, raw output from ESLint.**
Linter complains about "no-useless-escape". Then, when flipping over to the "fixed code" tab, the "fixed code" is identical to the original code.

**Comment by not-an-aardvark** [comment]
Thanks for the report, but this is working as intended. Your `/` character is uselessly escaped; `/` does not need to be escaped when inside a character class.

The "fixed code" tab is identical to the original code because the `no-useless-escape` rule does not support autofixing.

**Comment by lilydjwg** [comment]
I find this particular one very annoying because:

* there is nothing wrong to escape that `/`
* syntax highlighters may not get it right (vim-es7 doesn't and I can't come up a good way to fix it)
* it makes writing regexes harder. It's much simpler to remember to escape every `/` in a regex literal than noticing that you don't need to escape ones inside character groups.

**Comment by platinumazure** [comment]
> * syntax highlighters may not get it right (vim-es7 doesn't and I can't come up a good way to fix it)

I would suggest reporting a bug in vim-es7's issue tracker so that they might fix their bug.

> * you can't grab a simple (and compatible with the JS one) regex somewhere else and put it in a regex literal by escaping every `/`.

Hmm... If you want to create a new issue to propose a rule enhancement that would allow some escapes useless in JS but required in another common regular expression dialect such as PCRE, feel free to do so. I think it's worth considering/discussing, although ultimately I don't know if we'll want to take on the maintenance/knowledge burden for what might not seem like an obvious value-add. A simpler ask might be that no-useless-escape could be configurable for strings only or regular expressions only, so you would at least have the option to opt out for regular expressions in your case. In any case, though, we should discuss this on a new issue. Thanks!
