### ISSUE TITLE
split changelog

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#9114]
currently we keep the changelog in one file, and it is a bit hard to read. 🤕 

what about keeping every major version in its own file, inside changelogs/, or others actions we can do to improve readability?

**Comment by not-an-aardvark** [comment]
In your opinion, what makes the changelog hard to read? I'm confused because it seems like all the relevant information is at the top, so the length shouldn't be a big problem if you're just looking for the latest changes.

**Comment by Aladdin-ADD** [comment]
when looking for some earlier changes, it is a little inconvenient. I see it is minority, so I'm wondering ...

**Comment by Aladdin-ADD** [comment]
>To make the changelog easier to both use and manage, it has been split into multiple files organized according to significant major and minor Node.js release lines.

https://github.com/nodejs/node/blob/master/CHANGELOG.md

**Comment by not-an-aardvark** [comment]
I think that was originally done because the size of Node's changelog exceeded 1MB, so it would no longer be displayed in the GitHub UI. (https://github.com/nodejs/node/pull/6337)

I don't feel strongly about this either way, but I am mildly opposed to changing it because I think the current changelog works fine.

**Comment by Aladdin-ADD** [comment]
fine, I'm going to close it. 
we can open it if someday it is too long..
