### ISSUE TITLE
ignore files in `.gitignore` by default.

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/eslint#9329]
is there any discussion on this?

**Comment by platinumazure** [comment]
It should be really easy to use the .gitignore file for ESLint ignores using the CLI flag `--ignore-path` or the CLIEngine key `ignorePath`. I'm not sure we want to include `.gitignore` by default since not everyone will be working in a git repository (if we support `.gitignore` we'll be asked to also support equivalents in SVN, etc.).

So I'm slightly :-1: to making a change here.
