### ISSUE TITLE
Webstorm don't Fix eslint problems, because module 'eslint-config-airbnb' not include by default 

### ISSUE THREAD

**Issue by odykyi** [eslint/eslint#9346]
**Tell us about your environment**

* **ESLint Version: 4.7.2**
* **Node Version: v7.7.4**
* **npm Version: 5.4.2**

**What parser (default, Babel-ESLint, etc.) are you using? Use only default nodejs, without compilers**

**Please show your full configuration:**

<details>
<summary>Configuration .eslintrc.json</summary>

```js
{
    "extends": "airbnb-base",
    "plugins": [
        "import"
    ]
}


```

</details>

**What did you do? Please include the actual source code causing the issue.**

```js

After install eslint for new project 'project-hello'
 


$ eslint --init
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Airbnb
? Do you use React? No
? What format do you want your config file to be in? JSON
Successfully created .eslintrc.json file in /private/var/www/project-hello


Then click in Webstorm -> Project folder (Mouse Right click) -> Fix Eslint Problems
Have error

	Problem with ESLint reformatting:
	index.js: Error: Cannot find module 'eslint-config-airbnb/base'
	Referenced from: /private/var/www/project-hello/.eslintrc.json


 My package.json

 "devDependencies": {
    "eslint": "^4.7.2",
    "eslint-config-airbnb-base": "^12.0.0",
    "eslint-plugin-import": "^2.7.0"
  }

```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**

**Comment by odykyi** [comment]
For fix this manyally 
It need to add module 
  
    `"eslint-config-airbnb": "^15.1.0", `

to `package.json`

**Comment by platinumazure** [comment]
It looks like you might have installed ESLint globally in order to run `eslint --init`. Our README [notes](https://github.com/eslint/eslint/blob/master/README.md#global-installation-and-usage) that you need to install plugins in the same way you install ESLint: global plugins for global ESLint, or local plugins for local ESLint.

In your case, WebStorm seems to look for locally installed ESLint, so you needed to locally install the shareable config.

In future, if you install ESLint locally and want to install plugins locally, you should run `./node_modules/.bin/eslint --init` to ensure you are hitting the local ESLint package.
