### ISSUE TITLE
Add package.json format option for eslint --init

### ISSUE THREAD

**Issue by nickmccurdy** [eslint/eslint#9379]
`eslint --init` provides a handy way to create new JSON configs, but there isn't an option for writing JSON to `package.json` instead of `.eslintrc.json`.

## ESLint Version
4.8.0

## Solution
Provide another option called `package.json` which behaves like `JSON` except it modifies (or creates) `package.json` instead of creating a separate `.eslintrc.json` file.

**Comment by ilyavolodin** [comment]
Sounds like a reasonable enhancement, since it's one of the opinion we actively support, we should provide it in init.

**Comment by not-an-aardvark** [comment]
**TSC Summary**: This issue proposes adding an selection in `eslint --init` to make ESLint create an `eslintConfig` property in `package.json`.
**TSC Question**: Should we accept this issue?

**Comment by not-an-aardvark** [comment]
This issue was discussed in [today's TSC meeting](https://github.com/eslint/tsc-meetings/blob/216e2779058a2090a022edb3b0aa4e39de9e4a5c/notes/2017/2017-11-09.md#add-packagejson-format-option-for-eslint---init). We decided that it wasn't worth adding this feature because it would add some complexity with regard to preserving the `package.json` indentation, etc., and it doesn't seem like something that is needed by many users.
