### ISSUE TITLE
The Function constructor is not recognized as eval or implied-eval

### ISSUE THREAD

**Issue by bfred-it** [eslint/eslint#9406]
**Tell us about your environment**

* **ESLint Version:** 4.8.0

**What parser (default, Babel-ESLint, etc.) are you using?**

default

**Please show your full configuration:**

```sh
eslint --rule 'no-implied-eval: 2' --rule 'no-eval: 2' file.js
```

**What did you do? Please include the actual source code causing the issue.**

```js
eval(`console.log("${location.hash}")`)
setTimeout(`console.log("${location.hash}")`)
Function(`console.log("${location.hash}")`)()
```

**What did you expect to happen?**

`Function(str)` should be an error

```
  1:1  error  eval can be harmful                                            no-eval
  2:1  error  Implied eval. Consider passing a function instead of a string  no-implied-eval
  3:1  error  Implied eval. Consider passing a function instead of a string  no-implied-eval

✖ 3 problems (3 errors, 0 warnings)
```

**What actually happened? Please include the actual, raw output from ESLint.**

`Function(str)` is not an error

```
  1:1  error  eval can be harmful                                            no-eval
  2:1  error  Implied eval. Consider passing a function instead of a string  no-implied-eval

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by Aladdin-ADD** [comment]
Thanks for the report. This is working as intended -- we have a rule [no-new-func](https://eslint.org/docs/rules/no-new-func) checking this.

**Comment by bfred-it** [comment]
Isn't this also _implied eval_ though? Perhaps someone setting `no-implied-eval: 2` would expect this to be picked up.

**Comment by Slayer95** [comment]
Function() performs compilation, not evaluation. It's also safer given some environment constraints. That's the difference.

**Comment by bfred-it** [comment]
I suppose that the difference is that `setTimeout` executes the code right away and `Function` waits for a successive call. I don’t see much difference in term of XSS-ability; both turn client strings into runnable code. 

(But then again that’s my interpretation, I just don’t know if there’s an actual difference in safety and performance in code like in my example)

**Comment by not-an-aardvark** [comment]
It looks like these rules are currently separate just because they were separate in JSLint (a linting tool that existed before ESLint). See https://github.com/eslint/eslint/pull/85 and https://github.com/eslint/eslint/pull/92.

If we were redesigning the rules from scratch now it might make sense to make them part of the same rule, although I'm unsure if it's worthwhile to do that now given that the separation doesn't seem to be causing any problems.

**Comment by platinumazure** [comment]
Neither `no-new-func` nor `no-implied-eval` is in `eslint:recommended`. I think including them in that configuration in the next major release would make sense.

**Comment by Aladdin-ADD** [comment]
@platinumazure  seems we don't have a consensus to add them. #8865

**Comment by platinumazure** [comment]
Thanks for the issue link. I personally think eslint:recommended should
include rules that are solid practices in the vast, vast majority of
situations. Code generation is not a common use case, in my view. I'll
reply on that issue later.

**Comment by not-an-aardvark** [comment]
(Marking this issue as "works as intended" because the behavior described in the original issue is working as designed.)

I think we might want to reconsider our standards for adding rules to `eslint:recommended` in general. There was some discussion about `no-console` in https://github.com/eslint/eslint/issues/8544, and it seems like the consensus is to leave it in `eslint:recommended` because using `console` is undesirable in most applications. But it seems like we're holding other rules to a much stricter standard. For example, we rejected adding `no-template-curly-in-string` to `eslint:recommended` for 4.0 because a deprecated jQuery plugin uses similar template syntax. It seems like it's much more common to need to use `console` than to need to use that specific template syntax, so maybe we should reconsider the rules in `eslint:recommended` and try to apply a consistent standard to them.

**Comment by not-an-aardvark** [comment]
Closing because this is working as intended.
