### ISSUE TITLE
prefer-template autofix edge case

### ISSUE THREAD

**Issue by mockdeep** [eslint/eslint#9552]
**Tell us about your environment**

* **ESLint Version:** 4.9.0
* **Node Version:** 8.1.4
* **npm Version:** 5.0.3

**What parser (default, Babel-ESLint, etc.) are you using?** default

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

ran the `prefer-template` autofix on the following code:

```js
$ids.val($ids.val() + temp_id + ',');
```

```bash
eslint --fix
```

**What did you expect to happen?**

It should have produced:

```js
$ids.val(`${ids.val()}${temp_id},`);
```

**What actually happened? Please include the actual, raw output from ESLint.**

It produced the following result:

```js
$ids.val(`${$ids.val() + temp_id},`);
```

**Comment by not-an-aardvark** [comment]
This is working as intended because ESLint can't tell what types `$ids.val()` and `temp_id` will have at runtime. The fix you described would work if both values are strings since it essentially concatenates them together, but if they're both numbers then concatenating them together would be incorrect.

**Comment by mockdeep** [comment]
Ah, I see. Nevermind then.
