### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jrajav** [eslint/eslint#957]
I wanted to isolate this generic problem further before opening this up but I've been at it for about two days now and I just wanted to see if anyone else has seen this or has any ideas. With the latest version of eslint there seems to be a significant memory leak, enough to cause Node to run out of memory:

```
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
```

This happens when running eslint on Windows on a directory of 4,463 items totaling 118.6mb. The process memory approached 1.5gb shortly before this error. When run on the same directory on OS X the memory also seems to increase but not enough to be fatal.

I'm trying to profile it and narrow down the naughty code, but Node's memory profiling tools seem to be a little lacking. I'm fumbling around with memwatch heap diffs at the moment, but they're not granular enough to do much narrowing down.

**Comment by nzakas** [comment]
Pasting in some info from the mailing list:

I just set up an ignore file to bypass all libs.  Still getting this error, now on a different file:

```
  eslint:cli-engine Processing chooser-frontend_trunk/chooser-frontend/public/t8/min/no_NO/t8-chooser.min.js +12s
  eslint:cli-engine Linting /home/jgourgou/Documents/workspace/netrepo/chooser-frontend_trunk/chooser-frontend/public/t8/min/no_NO/t8-chooser.min.js +0ms
  eslint:cli-engine Processing chooser-frontend_trunk/chooser-frontend/public/t8/min/zh_TW/t8-dateFormatter.min.js +6s
  eslint:cli-engine Linting /home/jgourgou/Documents/workspace/netrepo/chooser-frontend_trunk/chooser-frontend/public/t8/min/zh_TW/t8-dateFormatter.min.js +0ms
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
```

Is there a way I can print out the size of the result object?

-Jim G



Looks like it's dying while trying to parse Highcharts.js:

```
  eslint:cli-engine Processing chooser-frontend_trunk/chooser-frontend/public/scmp/lib/highcharts/2.3.3/highcharts.js +3s
  eslint:cli-engine Linting /home/jgourgou/Documents/workspace/netrepo/chooser-frontend_trunk/chooser-frontend/public/scmp/lib/highcharts/2.3.3/highcharts.js +0ms
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
```

However, if I point it at that file specifically and singly:

```
eslint -c ~/.eslintrc -f compact  /home/jgourgou/Documents/workspace/netrepo/chooser-frontend_trunk/chooser-frontend/public/scmp/lib/highcharts/2.3.3/highcharts.js
```

...it executes normally, finding 2637 problems, so I'm leaning towards your first hypothesis (result object growing too large).

Thanks!


Oh wow, that's pretty big. :)

Can you try running ESLint with some debug flags?

```
$ DEBUG=eslint:cli-engine eslint .
```

(replace eslint . with whatever you use normally)

That should tell you the last file linted before the error occurs. Can you see if there's anything special about that file (size, mostly).

My two theories are:

1. It's the size of the result object growing too large.
2. It's the size of the AST for an overly large file.

So if you can get back with what the offending file looks like size-wise, we can go from there.


Apologies.  Forgot to use the -L option on my find command.

Number of (nested) subdirectories: 1063 (some of these are symlinks)
Number of files: 5809
No files over 685k

-Jim G


I don't think this is a node issue, because JSHint works fine over the same directories.

Number of (nested) subdirectories: 37  (some of these are symlinks)
Number of files: 229
No files over 250k

FWIW, I just updated to v0.13.0 and am still seeing this.

Thanks!
-Jim G



We don't have a known limit on number of files or file size, but Node.js itself does.

From what I've read, the most likely cause is a single large file. Do you have any files that are larger than a megabyte or two?

Are there any other statistics you can share about your project folder? Number of subdirectories or files?

It's this same issue.  https://github.com/eslint/eslint/issues/957  FWIW I'm running v0.12.0 on an 8 core Linux box with 64G of memory.

Thanks,
-Jim G



When I throw ESLint at a large project folder, I'm getting "FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory" errors.  Does ESLint have a maximum number of files/errors it can handle?

**Comment by nzakas** [comment]
My hunch is that the size of the result set is growing because of the AST node reference we keep on it.

**Comment by nzakas** [comment]
@Jimgskoop can you try the issue957 branch and see if that works for you? The tests are all exploding at the moment because I removed the AST node from results, but we can deal with that if it fixes the issue.

**Comment by btmills** [comment]
If the size of the result set turns out to be the issue, fixing #1098 could be an alternative solution.

**Comment by nzakas** [comment]
@btmills That doesn't actually solve the problem. It only changes how results are output, not how the results are stored.

**Comment by Jimgskoop** [comment]
@nzakas I've got the issue957 code and am running it right now.  Looks like it's working!

**Comment by nzakas** [comment]
Okay. So it looks like what was going on is that we were keeping the AST of each file in memory due to attaching a node to each message. We don't really need that node, so it's probably safe to remove it. We'll need to change how eslint-tester works since it relies on the node, but that's okay.

**Comment by nzakas** [comment]
The `node` is really only used by ESLintTester to verify the correct node was passed into `report()`. However, we really only check the node type, so I can just attach a new `nodeType` property to the result and use that instead.
