### ISSUE TITLE
v4.10.0 test suite failing on all versions of node

### ISSUE THREAD

**Issue by MylesBorins** [eslint/eslint#9586]
Oh hey!

The v4.10.0 test suite is broken on all versions of know and breaking CITGM. master appears to be fine though 🎉

Is there a plan for a new release soon in order to fix the test suit?

**Comment by not-an-aardvark** [comment]
Hi, sorry about the inconvenience. After ESLint v4.10.0 was released, there was an [upgrade to `acorn`](https://github.com/ternjs/acorn/blob/cd2f34653671f17a48ec759ed75e59d249861599/CHANGELOG.md#520-2017-10-30) which caused some tests to start failing, due to bugs in those tests. The buggy tests were fixed in https://github.com/eslint/eslint/commit/a9606a3e99738e988fa0de31ba15590275720324.

We have a [scheduled release](https://github.com/eslint/eslint/issues/9546) for this upcoming Friday. We generally don't do special releases for fixes to tests, since they don't have any user-facing impact.

Does CITGM need to run from a released version? I assume it's pulling code from GitHub rather than npm (since the package on npm doesn't contain the test folder), so it seems like CITGM could run on the master branch, where the tests are currently passing.

**Comment by MylesBorins** [comment]
We can set citgm to run off master instead of the latest release... But we
tend to prefer to test what is released rather than master.

We are planning a release on Tuesday and these failures we're showing up in
our CI. If you have a timeline on a release that is totally cool, just
wanted to avoid having to mark eslint as flaky... We'll hold off marking
awaiting the Friday release

**Comment by not-an-aardvark** [comment]
Closing because v4.11.0 has been released with the fixed tests.
