### ISSUE TITLE
migrate to `babylon` parser proposal

### ISSUE THREAD

**Issue by le93us** [eslint/eslint#9850]
Now it's impossible seamless integrate `eslint` in `babel` toolchain.

Have you, `eslint` developers, plans to migrate to `babylon` parser?

Yes, there is an [babel-eslint](https://github.com/babel/babel-eslint) - but it is a buggy crutch.

**Comment by not-an-aardvark** [comment]
At the moment, I don't think we have any plans to migrate to `babylon`. Could you elaborate on what problems this would solve?

> Now it's impossible seamless integrate `eslint` in `babel` toolchain.

Could you elaborate on how you're trying to integrate `eslint`, and what you're having trouble with?

> Yes, there is an babel-eslint - but it is a buggy crutch.

Could you elaborate on what bugs you're encountering?

**Comment by le93us** [comment]
> Could you elaborate on what bugs you're encountering?

Please, look at `babel-eslint` page "known issues" section.

I have simple idea:

```
code -> 
`babel` to AST (?) parsing ->
`flow` type checking -> 
`flow` types removing ->
`eslint` checking ->
`babel` to `es5` compilation
```
using `webpack` loaders.

`eslint` use it's own parser -> there is no simple way use it with `babel` in proper way.

**Comment by not-an-aardvark** [comment]
The "known issues" in the `babel-eslint` readme occurs because ESLint rules don't support the semantics of experimental syntax. This would be true if we used `babylon` .

Regarding the other use case that you described: I don't think this would be possible anyway even if we used babylon ASTs, because ESLint requires token and range information which generally isn't preserved by babel plugins. Of course, you could always emit code from babel and re-parse it with ESLint.

**Comment by le93us** [comment]
Thank you for reply, @not-an-aardvark.
