### ISSUE TITLE
Change Request: Resolve LGPL dependency issue w/ Inquirer.js by updating package.json version to =>4.0.1

### ISSUE THREAD

**Issue by kreig303** [eslint/eslint#9887]
**Tell us about your environment**

* **ESLint Version:4.16.0**

cf. https://github.com/SBoudrias/Inquirer.js/releases/tag/v4.0.1

1. Underlying `Inquirer.js` is an `external-editor` package which was using `jschardet` which has an LGPL license.  LGPL licenses are incompatible with the permissive MIT/Apache/BSD style licenses which most node modules utilizie.  I was able to get `external-editor` to change to an MIT package called `node-chardet` and to have the `Inquirer.js` maintainer to update the dependency.  Thanks to all involved; `eslint` is the final piece.

2. Update the version used by `eslint` to be at minimum >=4.0.1 (where the change was made).  The package is as of this writing up to v5+.

3. Simply awaiting feedback on this.  If needed I can certainly fork, upgrade and run tests to see if anything comes out of the change.  A showstopper however may be that v4 of Inquirer.js dropped support for Node 4 due to code refactoring to ES6 syntax.  Hence this may have to await the dropping of lts/argon support by the node foundation...  which of course is currently in three months (4/30/18).

**Comment by platinumazure** [comment]
Hi @kreig303, thanks for the issue! This sounds reasonable to me.

This seems reasonable to me; however, I've added a "breaking" tag for now due to Inquirer 4+ having dropped support for Node 4. I think we're likely to drop support for Node 4 with our next major release, so maybe we could accept this for our next major.

@eslint/eslint-tsc We have a license check in our `npm test`. Do we need to make changes there? Should we regard LGPL and MIT as incompatible, from our perspective, and change the license check accordingly?

**Comment by not-an-aardvark** [comment]
We determined in https://github.com/eslint/eslint/issues/8647 that LGPL is fine for our purposes, although I realize some of our users might have stricter requirements. I don't feel strongly either way about whether we should disallow LGPL in the future (ostensibly the users that have stronger legal requirements could use forks and fix the issue themselves), although in this case I agree that we might as well upgrade in our next major release.

**Comment by nzakas** [comment]
Reference to JSF's legal counsel's response: https://github.com/eslint/eslint/issues/8647#issuecomment-304033468

To summarize: I don't think this is a fix we need to rush to make. The LGPL is incompatible with MIT only in the case LGPL licensed code is re-released as MIT. Because we are not dealing with a re-release and only a link (two levels down) to an LGPL licensed package, we are adhering to the license terms. 

@kreig303 is this causing a specific problem for you or is this just an FYI for us?

**Comment by kreig303** [comment]
Apologies for going "dark" on this...

@nzakas this causes a specific problem because our legal team would like to avoid LGPL for our own purposes.  Obviously since `eslint` is the big fish in the linting pond it would be truly beneficial to us at a minimum — and undoubtedly many other silent users — and a minor change on your part if node 4 support goes (which of course will be dropped by the foundation in a short while regardless)... for the next major semver as @platinumazure states.

It is true we can fork for the time being with the hope that in future `eslint` itself will come up to spec but we obviously would like to avoid this sort of maintenance for a minor change!

As per @StevenAyr's comment in the above, this is a grey area best avoided and there is a resolution at hand with this minor dependency switch!

**Comment by realityking** [comment]
I think this has been resolved, ESLint 5 requires inquirer 5.2.

**Comment by not-an-aardvark** [comment]
Agreed, closing this issue.
