### ISSUE TITLE
Enhancement: Should we use json5 to parse .eslintrc?

### ISSUE THREAD

**Issue by caub** [eslint/eslint#9936]
- comments, trailing commas allowed
- single/quotes allowed (this one is both an advantage and a drawback, more an advantage because I guess  `.eslintrc` can be linted as well to force consistencies in quotes
- adopted by others libs, like Babel's `.babelrc`

PR #9935

**Comment by not-an-aardvark** [comment]
Could you use a `yaml` file if you want these features?

**Comment by ilyavolodin** [comment]
I'm not sure the advantages are enough to justify bringing in another dependency (even though it's pretty light one). We already allow comments in our `.eslintrc` file, since they are stripped before parsing. So that only leaves trailing commas and single quotes. Those two don't strike me as a required features for basically deprecated config file (we recommend .js, .yaml or .json config files instead now).

**Comment by platinumazure** [comment]
I'm not seeing the need either.

That said, @ilyavolodin, don't we use "strip-json-comments" already? We wouldn't be adding a dependency, but trading dependencies (unless we use "strip-json-comments" somewhere else in the code).

**Comment by not-an-aardvark** [comment]
I think there is some confusion here:

* `.eslintrc` files (deprecated) can be some strange combination of YAML syntax and JavaScript comments.
* `.eslintrc.json` files can only be valid JSON.

I think this issue is referring to the latter.

**Comment by platinumazure** [comment]
@not-an-aardvark Unfortunately, no, `.eslintrc.json` files can have comments in them, as we [use `strip-json-comments`](https://github.com/eslint/eslint/blob/master/lib/config/config-file.js#L114) before parsing the JSON. So this discussion is relevant for `.eslintrc.json` files as well.

**Comment by not-an-aardvark** [comment]
Huh, I didn't realize that. I sort of wish we weren't doing that -- I don't think people should call a file `.json` if it is not actually valid JSON. In that case, we should probably come up with a better fix for https://github.com/eslint/eslint/pull/9226, since it affects a non-deprecated config file format.

Along similar lines, I'm mildly opposed to making this change because people can use YAML if they want a more strict config file format.

**Comment by caub** [comment]
@ilyavolodin it's one dependency in, another out normally (I didn't remove the strip-comments dep, because it's used for yaml, but yaml already have comments `# ...` I think, ideally that dependency could be removed)

**Comment by stevenvachon** [comment]
A *.js file means having to prepend `module.exports = `, correct? This likely breaks compatibility with code/text editors. I think JSON5 makes more sense.

**Comment by platinumazure** [comment]
Closing as it doesn't look like the ESLint team is going to reach consensus on supporting this change. Thanks for the discussion regardless!
