### ISSUE TITLE
Propose --fix support resolution of some no-use-before-define issues.

### ISSUE THREAD

**Issue by ggb667** [eslint/eslint#9945]
For simple cases, it would be nice if the code could be re-ordered with the functions moved up before they are invoked ass part of --fix, together with any comments that are directly above the function.  In some circular cases, nothing can be done, but in the vast majority of cases it should be fairly simple to just pick a function, move it to the top, and repeat that action again and again, say 100 times.  If it gets fixed, great, if not too bad, move on.  There is a stack overflow question related to this one, but no one had a solution.  If anyone has a way to do this easly, please write back, otherwise I'm going to hack something together.

**Comment by platinumazure** [comment]
Hi @ggb667, thanks for the issue.

We generally prefer not to move around entire blocks of code when autofixing, so I'm :-1: for this enhancement at this point.

**Comment by ggb667** [comment]
What if it was say --fix-no-use-before-define?  A seperate flag?

**Comment by platinumazure** [comment]
I don't think we can add a CLI flag for a fixer option related to a particular rule. You can imagine how difficult it would be to read ESLint documentation if you had to skim through 200+ CLI flags. (Basically, adding one flag for a rule would set a bad precedent.)

I think this could probably be done in a custom tool. You could use [`CLIEngine`](https://eslint.org/docs/developer-guide/nodejs-api) to run ESLint (with just the no-use-before-define rule) on a file or set of files, and then use a library like [jscodeshift](https://github.com/facebook/jscodeshift) to shift around the code as needed. But in any case, I'm not sure we can make a change in ESLint for this use case without introducing pretty significant drawbacks.

I'm just one person and maybe the rest of the team will think differently. Let's wait and see. :smile:

**Comment by ggb667** [comment]
I'm looking at jscodeshift and eslint to see what would be involved.  I want a tool to do this, where the tool lives is less important than having one.  But I would ask you this: If it's flagged as an error in the .eslintrc file and it gets reported, and if you know '--fix' will fix issues so flagged. why wouldn't you want it fixed?  If you don't want it fixed, make it a warning or even remove it as a class of issues for eslint to deal with I should think.

**Comment by platinumazure** [comment]
@ggb667 ESLint makes no promises to fix all reported lint errors. Even if a rule is listed as fixable on our [rules list](https://eslint.org/docs/rules), specific errors might not be fixed.

Speaking in terms of ESLint design, it's *very* important to us that autofixing does not create new errors. For that reason, we keep autofixes very simple and small, as much as we can. Moving entire blocks of code, which might include variables that were not reported by `no-use-before-define`, could have major impact on how variables are scoped and could cause subtle bugs for our users. So in my view, there's no way we can add a fixer to this rule.

**Comment by not-an-aardvark** [comment]
Thanks for your interest in improving ESLint. Unfortunately, it looks like this issue didn't get consensus from the team, so I'm closing it. We define [consensus](http://eslint.org/docs/maintainer-guide/issues.html#consensus) as having three :+1:s from team members, as well as a team member willing to champion the proposal. This is a high bar by design -- we can't realistically accept and maintain every feature request in the long term, so we only accept feature requests which are useful enough that there is consensus among the team that they're worth adding.

Since ESLint is pluggable and can load custom rules at runtime, the lack of consensus among the ESLint team doesn't need to be a blocker for you using this in your project, if you'd find it useful. It just means that you would need to [implement the rule](http://eslint.org/docs/developer-guide/working-with-rules) yourself, rather than using a bundled rule that is packaged with ESLint.
