### ISSUE TITLE
Weird bug(no-use-before-define) with async/await and and function names

### ISSUE THREAD

**Issue by carlblock** [eslint/eslint#9958]
**Tell us about your environment**

* **ESLint Version: 4.17.0**
* **Node Version: 8.9.1**
* **Yarn Version: 1.3.2**

**What parser (default, Babel-ESLint, etc.) are you using?**
`babel-eslint`

`eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter src` 
**Please show your full configuration:**

<details>
<summary>Configuration</summary>

```js
module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module',
    ecmaVersion: 8
  },
  env: {
    browser: true,
    node: true,
    es6: true
  },
  extends: 'standard',
  globals: {
    __static: true
  },
  plugins: [
    'html'
  ],
  'rules': {
    // allow paren-less arrow functions
    'arrow-parens': 0,
    // allow async-await
    'generator-star-spacing': 0,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
  }
}

```

</details>

**What did you do? Please include the actual source code causing the issue, as well as the command that you used to run ESLint.**

```js
/**
 * Called from saveSettings
 * @return {Promise<any>}
 */
function findSettings () {
  return new Promise((resolve, reject) => {
    db.find({objectType: 'settings'}, (err, docs) => {
    if (err) {
      reject(err)
    }
    resolve(docs)
  })
})
}

/**
 * Problems here
 * @param settings
 * @return {Promise<any>}
 */
async function saveSettings (settings) {
  let data = Object.assign({objectType: 'settings', settings: settings})
  let findSettings = await findSettings() // <-- no-use-before-define
  // ...
}
// ------------------------------------------
/**
 * Just a test await which works well
 * @return {Promise<any>}
 */
function testAwait () {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(true), 1000)
})
}

/**
 * Just a test async function which works well
 * @return {Promise<any>}
 */
async function testAsync () {
  let testAwat = await testAwait()
  console.log(testAwat)
}
testAsync()
```

```bash
eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter src
```

**What did you expect to happen?**
Not warning about _no-use-before-define_ since the function is defined just before the calling function. 

### Weirdly enough if i rename the *findSettings()* function to *findSetting()* without the **s** it works well.

**What actually happened? Please include the actual, raw output from ESLint.**
Receiving errors of used before defined
```bash
✘  http://eslint.org/docs/rules/no-use-before-define  'findSettings' was used before it was defined  
  src/renderer/services/SettingService.js:30:28
    let findSettings = await findSettings()
```

**Comment by platinumazure** [comment]
I don't think this has to do with async/await specifically. I've created a [demo](https://eslint.org/demo/#eyJ0ZXh0IjoiLyogZXNsaW50IG5vLXVzZS1iZWZvcmUtZGVmaW5lOiBlcnJvciAqL1xyXG5mdW5jdGlvbiBmb28oKSB7XHJcbn1cclxuXHJcbmZ1bmN0aW9uIGJhcigpIHtcclxuICAgIGxldCBmb28gPSBmb28oKTtcclxufVxyXG5cclxubGV0IGEgPSBhOyIsIm9wdGlvbnMiOnsicGFyc2VyT3B0aW9ucyI6eyJlY21hVmVyc2lvbiI6OCwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6e30sImVudiI6e319fQ==) that I believe is a representative case (at least, before line 9)

I don't think this is a bug. When I execute line 9 in the Chrome console, I get a ReferenceError because `a` has not been fully defined yet. I'm not sure that `let findSettings = await findSettings()` is doing what you think it's doing-- I think it would try to call the variable `findSettings`, rather than the function in upper scope. My suggestion would be to rename either the variable or the function.

**Comment by carlblock** [comment]
@platinumazure Hey, you're absolutely right. I came to the realisation just now when I renamed let findSettings variable. I haven't drunk any coffee today.. this issue can be closed.
